# Locations table

The purpose of this notebook is to create a table where have all possible locations of the students who registered to EIE or NMT during 2016-2025 and the locations of the test centers. The information about location contains:
- the old KOATUU code used until 2021, 
- the new KATOTTG code used from 2021, 
- the category of the administrative-territorial unit, 
- the English name of the corresponding region.

The original location data is highly inconsistent year over year, owing to the significant decommunization and decentralization that took place in Ukraine between 2016-2025. The decommunization process included removing Soviet-era location names and replacing them with names that reflect Ukraine’s national heritage. For instance, in 2016, a total of twenty-two villages bearing the name ‘с.Комсомольське’, which is derived from the Communist Party,underwent the renaming process. Also, in the open data location names are sometimes written in Russian instead of in Ukrainian (for example: ‘с.Фастовци’ is in Russian, while ‘с.Фастiвцi’ is the Ukrainian pronunciation)

## Loading libraries

In [1]:
import numpy as np
import pandas as pd
import importlib

import src.renaming_dictionaries as renam

## Collecting all possible locations

In [2]:
# load datasets
datasets = {}
years = range(2016, 2022)
for year in years:
    print(f"EIE {year} Loading...")
    if int(year) >= 2019:
        file_name = f'Odata{year}File.csv'
    else:
        file_name = f'OpenData{year}.csv'
    try:           
        dataset = pd.read_csv(f"../../data_loader/{year}/{file_name}", sep=";", encoding='utf-8', dtype = str)
    except:
        dataset = pd.read_csv(f"../../data_loader/{year}/{file_name}", sep=";", encoding='Windows 1251', dtype = str)
    datasets.update({year:dataset})
    print("success")

EIE 2016 Loading...
success
EIE 2017 Loading...
success
EIE 2018 Loading...
success
EIE 2019 Loading...
success
EIE 2020 Loading...
success
EIE 2021 Loading...
success

In [3]:
for year, dataset in datasets.items():
    #lowercase all columns and add year as attribute
    dataset.columns = [col.lower() for col in dataset.columns]
    #add year before merging datasets
    dataset['year'] = year

In [4]:
for year, dataset in datasets.items():
    print(year, dataset.shape)

2016 (268003, 107)
2017 (240889, 120)
2018 (335687, 126)
2019 (353813, 127)
2020 (379299, 127)
2021 (389323, 148)

In [5]:
for year, dataset in datasets.items():
    print([col for col in dataset.columns if col.endswith('regname')])

['regname', 'eoregname', 'ukrptregname', 'histptregname', 'mathptregname', 'physptregname', 'chemptregname', 'bioptregname', 'geoptregname', 'engptregname', 'frptregname', 'deuptregname', 'spptregname', 'rusptregname']
['regname', 'eoregname', 'ukrptregname', 'histptregname', 'mathptregname', 'physptregname', 'chemptregname', 'bioptregname', 'geoptregname', 'engptregname', 'fraptregname', 'deuptregname', 'spaptregname', 'rusptregname']
['regname', 'eoregname', 'ukrptregname', 'histptregname', 'mathptregname', 'physptregname', 'chemptregname', 'bioptregname', 'geoptregname', 'engptregname', 'fraptregname', 'deuptregname', 'spaptregname']
['regname', 'eoregname', 'ukrptregname', 'histptregname', 'mathptregname', 'physptregname', 'chemptregname', 'bioptregname', 'geoptregname', 'engptregname', 'fraptregname', 'deuptregname', 'spaptregname']
['regname', 'eoregname', 'ukrptregname', 'histptregname', 'mathptregname', 'physptregname', 'chemptregname', 'bioptregname', 'geoptregname', 'engptregname', 'fraptregname', 'deuptregname', 'spaptregname']
['regname', 'eoregname', 'umlptregname', 'ukrptregname', 'histptregname', 'mathptregname', 'mathstptregname', 'physptregname', 'chemptregname', 'bioptregname', 'geoptregname', 'engptregname', 'fraptregname', 'deuptregname', 'spaptregname']

In [6]:
types = ['', 'eo', 'ukrpt', 'umlpt', 'mathpt', 'histpt', 'physpt', 'mathstptregname', 'chempt', 'biopt', 'geopt', 'engpt', 'frapt', 'frpt', 'deupt', 'spapt', 'sppt', 'ruspt']

In [7]:
locations = pd.DataFrame(columns=['regname', 'areaname', 'tername'])

In [8]:
dataframes_to_concat = []

for year, dataset in datasets.items():
    for typ in types:
        new_col = {typ+'regname': 'regname', typ+'areaname':'areaname', typ+'tername': 'tername'}
        if all(column in dataset.columns for column in new_col):
            temp_data = dataset.loc[:, new_col.keys()].copy()
            temp_data.rename(columns=new_col, inplace=True)
            # Drop rows where all columns are NaN before adding to list
            temp_data = temp_data.dropna(how='all')
            dataframes_to_concat.append(temp_data)

if dataframes_to_concat:
    locations = pd.concat(dataframes_to_concat, ignore_index=True)
    locations.drop_duplicates(inplace=True)
    locations.reset_index(drop=True, inplace=True)
else:
    locations = pd.DataFrame(columns=['regname', 'areaname', 'tername'])

locations

,regname,areaname,tername
0,Запорізька область,Мелітопольський район,с.Терпіння
1,Хмельницька область,Красилівський район,м.Красилів
2,Дніпропетровська область,Петропавлівський район,с.Дмитрівка
3,Чернівецька область,м.Чернівці,Шевченківський район міста
4,Миколаївська область,Врадіївський район,с.Кумарі
...,...,...,...
22587,Житомирська область,Любарський район,с.Великий Браталів
22588,Хмельницька область,Ізяславський район,с.Влашанівка
22589,Львівська область,Яворівський район,с.Коханівка
22590,Житомирська область,Ємільчинський район,с.Бастова Рудня
22591,Чернівецька область,м.Чернівці,м.Чернівці

# Codifier brush-up

In [9]:
code2020 = pd.read_excel('./location_data/KOATUU_26112020.xls',  dtype=str)
code2020

               TE   NP                                       NU
0      0100000000  NaN  АВТОНОМНА РЕСПУБЛІКА КРИМ/М.СІМФЕРОПОЛЬ
1      0110000000  NaN         МІСТА АВТОНОМНОЇ РЕСПУБЛІКИ КРИМ
2      0110100000  NaN                              СІМФЕРОПОЛЬ
3      0110130000  NaN                     РАЙОНИ М.СІМФЕРОПОЛЯ
4      0110136300    Р                              ЗАЛІЗНИЧНИЙ
...           ...  ...                                      ...
39415  8536990504    С                                  КАМИШЛИ
39416  8536990505    С                                ПИРОГОВКА
39417  8536990507    С                                ПОВОРОТНЕ
39418  8536990509    С                                 ФРОНТОВЕ
39419  8536990511    С                                 ФРУКТОВЕ

[39420 rows x 3 columns]

In [10]:
code2020['region_KOATUU'] = code2020['TE'].str[:2]
code2020['area_KOATUU'] = code2020['TE'].str[2:5]
code2020['local_KOATUU'] = code2020['TE'].str[5:]
code2020

,TE,NP,NU,region_KOATUU,area_KOATUU,local_KOATUU
0,0100000000,NaN,АВТОНОМНА РЕСПУБЛІКА КРИМ/М.СІМФЕРОПОЛЬ,01,000,00000
1,0110000000,NaN,МІСТА АВТОНОМНОЇ РЕСПУБЛІКИ КРИМ,01,100,00000
2,0110100000,NaN,СІМФЕРОПОЛЬ,01,101,00000
3,0110130000,NaN,РАЙОНИ М.СІМФЕРОПОЛЯ,01,101,30000
4,0110136300,Р,ЗАЛІЗНИЧНИЙ,01,101,36300
...,...,...,...,...,...,...
39415,8536990504,С,КАМИШЛИ,85,369,90504
39416,8536990505,С,ПИРОГОВКА,85,369,90505
39417,8536990507,С,ПОВОРОТНЕ,85,369,90507
39418,8536990509,С,ФРОНТОВЕ,85,369,90509
39419,8536990511,С,ФРУКТОВЕ,85,369,90511

In [11]:
code2020['name_KOATUU'] = code2020['NU'].str.split('/').str[0].str.lower().str.capitalize()
code2020[code2020.area_KOATUU == '000'][['NU', 'region_KOATUU', 'name_KOATUU']]

,NU,region_KOATUU,name_KOATUU
0,АВТОНОМНА РЕСПУБЛІКА КРИМ/М.СІМФЕРОПОЛЬ,01,Автономна республіка крим
1328,ВІННИЦЬКА ОБЛАСТЬ/М.ВІННИЦЯ,05,Вінницька область
3508,ВОЛИНСЬКА ОБЛАСТЬ/М.ЛУЦЬК,07,Волинська область
4870,ДНІПРОПЕТРОВСЬКА ОБЛАСТЬ/М.ДНІПРО,12,Дніпропетровська область
6645,ДОНЕЦЬКА ОБЛАСТЬ/М.ДОНЕЦЬК,14,Донецька область
8272,ЖИТОМИРСЬКА ОБЛАСТЬ/М.ЖИТОМИР,18,Житомирська область
10367,ЗАКАРПАТСЬКА ОБЛАСТЬ/М.УЖГОРОД,21,Закарпатська область
11303,ЗАПОРІЗЬКА ОБЛАСТЬ/М.ЗАПОРІЖЖЯ,23,Запорізька область
12483,ІВАНО-ФРАНКІВСЬКА ОБЛАСТЬ/М.ІВАНО-ФРАНКІВСЬК,26,Івано-франківська область
13716,КИЇВСЬКА ОБЛАСТЬ/М.КИЇВ,32,Київська область
15548,КІРОВОГРАДСЬКА ОБЛАСТЬ/М.КРОПИВНИЦЬКИЙ,35,Кіровоградська область
17013,ЛУГАНСЬКА ОБЛАСТЬ/М.ЛУГАНСЬК,44,Луганська область
18187,ЛЬВІВСЬКА ОБЛАСТЬ/М.ЛЬВІВ,46,Львівська область
20787,МИКОЛАЇВСЬКА ОБЛАСТЬ/М.МИКОЛАЇВ,48,Миколаївська область
21951,ОДЕСЬКА ОБЛАСТЬ/М.ОДЕСА,51,Одеська область
23588,ПОЛТАВСЬКА ОБЛАСТЬ/М.ПОЛТАВА,53,Полтавська область
25930,РІВНЕНСЬКА ОБЛАСТЬ/М.РІВНЕ,56,Рівненська область
27273,СУМСЬКА ОБЛАСТЬ/М.СУМИ,59,Сумська область
29114,ТЕРНОПІЛЬСЬКА ОБЛАСТЬ/М.ТЕРНОПІЛЬ,61,Тернопільська область
30650,ХАРКІВСЬКА ОБЛАСТЬ/М.ХАРКІВ,63,Харківська область
32823,ХЕРСОНСЬКА ОБЛАСТЬ/М.ХЕРСОН,65,Херсонська область
33798,ХМЕЛЬНИЦЬКА ОБЛАСТЬ/М.ХМЕЛЬНИЦЬКИЙ,68,Хмельницька область
35623,ЧЕРКАСЬКА ОБЛАСТЬ/М.ЧЕРКАСИ,71,Черкаська область
36952,ЧЕРНІВЕЦЬКА ОБЛАСТЬ/М.ЧЕРНІВЦІ,73,Чернівецька область
37569,ЧЕРНІГІВСЬКА ОБЛАСТЬ/М.ЧЕРНІГІВ,74,Чернігівська область
39363,М.КИЇВ,80,М.київ
39375,М.СЕВАСТОПОЛЬ,85,М.севастополь

In [12]:
code2020 = code2020[~code2020['region_KOATUU'].isin(['01', '85'])]

In [13]:
code2020 = code2020[~code2020['name_KOATUU'].str.lower().str.startswith('міста ')]
code2020 = code2020[~code2020['name_KOATUU'].str.lower().str.startswith('райони ')]
code2020 = code2020[~code2020['name_KOATUU'].str.lower().str.startswith('селища ')]
code2020 = code2020[~code2020['name_KOATUU'].str.lower().str.startswith('населенi ')]
code2020 = code2020[~code2020['name_KOATUU'].str.lower().str.startswith('селища, ')]
code2020 = code2020[~code2020['name_KOATUU'].str.lower().str.startswith('сільради ')]
code2020 = code2020.reset_index(drop=True)

In [14]:
code2020.NP.unique()

array([nan, 'М', 'Т', 'С', 'Щ', 'Р', 'C'], dtype=object)

In [15]:
code2020.NP = code2020.NP.str.replace('C', 'С')

In [16]:
code2020.loc[code2020['NP'] == 'М', 'name_KOATUU'] = 'м.' + code2020.loc[code2020['NP'] == 'М', 'name_KOATUU']
code2020.loc[code2020['NP'] == 'С', 'name_KOATUU'] = 'с.' + code2020.loc[code2020['NP'] == 'С', 'name_KOATUU']
code2020.loc[code2020['NP'] == 'Щ', 'name_KOATUU'] = 'с-ще ' + code2020.loc[code2020['NP'] == 'Щ', 'name_KOATUU']
code2020.loc[code2020['NP'] == 'Т', 'name_KOATUU'] = 'смт ' + code2020.loc[code2020['NP'] == 'Т', 'name_KOATUU']

In [17]:
set(code2020[code2020.area_KOATUU == '000'].name_KOATUU.str.lower())^set(locations.regname.str.lower())

set()

In [18]:
locations_region = locations.merge(code2020[['region_KOATUU']], left_on=locations['regname'].str.lower(), right_on=code2020['name_KOATUU'].str.lower(), how='left')
locations_region = locations_region.drop('key_0', axis=1)
locations_region.head()

,regname,areaname,tername,region_KOATUU
0,Запорізька область,Мелітопольський район,с.Терпіння,23
1,Хмельницька область,Красилівський район,м.Красилів,68
2,Дніпропетровська область,Петропавлівський район,с.Дмитрівка,12
3,Чернівецька область,м.Чернівці,Шевченківський район міста,73
4,Миколаївська область,Врадіївський район,с.Кумарі,48

In [19]:
locations_region[['regname', 'region_KOATUU']].value_counts()

regname                    region_KOATUU
Львівська область          46               1787
Вінницька область          05               1338
Житомирська область        18               1274
Полтавська область         53               1215
Хмельницька область        68               1207
Харківська область         63               1176
Дніпропетровська область   12               1120
Рівненська область         56               1102
Волинська область          07               1079
Тернопільська область      61               1039
Київська область           32               1027
Одеська область            51                935
Чернігівська область       74                884
Івано-Франківська область  26                823
Запорізька область         23                800
Донецька область           14                754
Сумська область            59                750
Черкаська область          71                734
Закарпатська область       21                689
Кіровоградська область     35                688
Миколаївська область       48                672
Херсонська область         65                634
Чернівецька область        73                445
Луганська область          44                390
м.Київ                     80                 30
Name: count, dtype: int64

# Matching areas

In [20]:
locations_region['areaname_new'] = locations_region['areaname']
locations_region.head(25)

,regname,areaname,tername,region_KOATUU,areaname_new
0,Запорізька область,Мелітопольський район,с.Терпіння,23,Мелітопольський район
1,Хмельницька область,Красилівський район,м.Красилів,68,Красилівський район
2,Дніпропетровська область,Петропавлівський район,с.Дмитрівка,12,Петропавлівський район
3,Чернівецька область,м.Чернівці,Шевченківський район міста,73,м.Чернівці
4,Миколаївська область,Врадіївський район,с.Кумарі,48,Врадіївський район
5,Донецька область,Донецька область,м.Дружківка,14,Донецька область
6,Тернопільська область,Тернопільська область,м.Тернопіль,61,Тернопільська область
7,Дніпропетровська область,Дніпропетровська область,м.Нікополь,12,Дніпропетровська область
8,Кіровоградська область,Новгородківський район,с.Тарасівка,35,Новгородківський район
9,Дніпропетровська область,м.Дніпропетровськ,Жовтневий район міста,12,м.Дніпропетровськ
10,Одеська область,м.Одеса,Суворовський район міста,51,м.Одеса
11,Дніпропетровська область,Дніпропетровська область,м.Павлоград,12,Дніпропетровська область
12,Львівська область,Яворівський район,смт Івано-Франкове,46,Яворівський район
13,Івано-Франківська область,Надвірнянський район,с.Лоєва (Лоївська сільрада),26,Надвірнянський район
14,Хмельницька область,Славутський район,с.Гута (Хоровецька сільрада),68,Славутський район
15,Одеська область,Кілійський район,м.Кілія,51,Кілійський район
16,Дніпропетровська область,м.Дніпропетровськ,Ленінський район міста,12,м.Дніпропетровськ
17,Харківська область,Вовчанський район,с.Пролетарське (Червоноармійська Перша сільрада),63,Вовчанський район
18,Черкаська область,Черкаська область,м.Умань,71,Черкаська область
19,Одеська область,м.Одеса,Малиновський район міста,51,м.Одеса
20,Хмельницька область,Білогірський район,смт Білогір'я,68,Білогірський район
21,Тернопільська область,Теребовлянський район,с.Бенева (Бенівська сільрада),61,Теребовлянський район
22,Тернопільська область,Теребовлянський район,м.Теребовля,61,Теребовлянський район
23,Дніпропетровська область,м.Дніпропетровськ,Красногвардійський район міста,12,м.Дніпропетровськ
24,Донецька область,Артемівський район,с.Парасковіївка,14,Артемівський район

Sometimes they wrongly put the name of regions in the second column. We fix it here

In [21]:
locations_region['areaname_new'] = locations_region.apply(lambda row: row['tername'] if ('область' in row['areaname_new'] or 'м.Київ' in row['areaname_new']) else row['areaname_new'], axis=1)

In [22]:
locations_region['areaname_new'] = locations_region.apply(lambda row: row['areaname_new'].split('. ')[0] if ('. ' in row['areaname_new']) else row['areaname_new'], axis=1)

In [23]:
dct = {}
for code in code2020.region_KOATUU.unique():
    troubles = set(locations_region[(locations_region.region_KOATUU == code)].areaname_new.str.lower())-set(code2020[(code2020.region_KOATUU == code)&(code2020.area_KOATUU != '000')&(code2020.local_KOATUU == '00000')].name_KOATUU.str.lower())
    if troubles:
        dct[code] = troubles
print(dct)

{'12': {'м.кривий ріг', 'дніпропетровський район', "м.кам'янське", 'м.орджонікідзе', 'м.дніпро', 'м.дніпродзержинськ', 'м.дніпропетровськ'}, '14': {'м.маріуполь', 'м.дзержинськ', 'м.димитров', 'володарський район', 'м.артемівськ', 'красноармійський район', 'м.красний лиман', 'артемівський район', 'м.красноармійськ', 'першотравневий район'}, '18': {'м.житомир', 'червоноармійський район', 'володарськ-волинський район'}, '21': {'м.мукачеве'}, '23': {'м.запоріжжя', 'куйбишевський район'}, '32': {'м.переяслав-хмельницький'}, '35': {'м.кропивницький', 'кіровоградський район', 'м.кіровоград', 'ульяновський район'}, '46': {'м.львів'}, '48': {'м.миколаїв', 'жовтневий район'}, '51': {'красноокнянський район', 'м.одеса', 'м.іллічівськ', 'фрунзівський район', 'котовський район', 'комінтернівський район', 'м.котовськ'}, '53': {'м.кременчук', 'м.полтава', 'м.комсомольськ'}, '56': {'м.кузнецовськ'}, '59': {'м.суми'}, '63': {'м.харків'}, '65': {'м.херсон', 'цюрупинський район'}, '71': {'м.черкаси'}, '74': {'щорський район', 'м.чернігів'}, '80': {'подільський район міста', 'деснянський район міста', 'шевченківський район міста', 'печерський район міста', 'голосіївський район міста', 'святошинський район міста', "солом'янський район міста", 'дарницький район міста', 'дніпровський район міста', 'оболонський район міста'}}

In [24]:
for code in renam.dct_rename_area:
    for name in renam.dct_rename_area[code]:
        locations_region.loc[(locations_region.region_KOATUU == code) & (locations_region['areaname_new'] == name), 'areaname_new'] = renam.dct_rename_area[code][name]

In [25]:
for city in renam.dct_cities:
    code2020.loc[(code2020['local_KOATUU'] == '00000') & (code2020['name_KOATUU'].str.lower() == city), 'name_KOATUU'] = renam.dct_cities[city]

In [26]:
for ray in renam.kyiv_dict:
    locations_region.loc[(locations_region.regname == 'м.Київ') & (locations_region.areaname_new.str.lower() == ray), 'areaname_new'] = renam.kyiv_dict[ray]

In [27]:
dct = {}
for code in code2020.region_KOATUU.unique():
    troubles = set(locations_region[(locations_region.region_KOATUU == code)].areaname_new.str.lower())-set(code2020[(code2020.region_KOATUU == code)&(code2020.area_KOATUU != '000')&(code2020.local_KOATUU == '00000')].name_KOATUU.str.lower())
    if troubles:
        dct[code] = troubles
print(dct)

{}

In [28]:
locations_area = locations_region.merge(code2020[['area_KOATUU']], left_on=[locations_region['region_KOATUU'], locations_region['areaname_new'].str.lower()], right_on=[code2020['region_KOATUU'], code2020['name_KOATUU'].str.lower()], how='left')
locations_area = locations_area.drop(columns = ['key_0', 'key_1'], axis=1)
locations_area.head()

,regname,areaname,tername,region_KOATUU,areaname_new,area_KOATUU
0,Запорізька область,Мелітопольський район,с.Терпіння,23,Мелітопольський район,230
1,Хмельницька область,Красилівський район,м.Красилів,68,Красилівський район,227
2,Дніпропетровська область,Петропавлівський район,с.Дмитрівка,12,Петропавлівський район,238
3,Чернівецька область,м.Чернівці,Шевченківський район міста,73,м.Чернівці,101
4,Миколаївська область,Врадіївський район,с.Кумарі,48,Врадіївський район,223

In [29]:
locations_area[(locations_area.area_KOATUU.isna())]

Empty DataFrame
Columns: [regname, areaname, tername, region_KOATUU, areaname_new, area_KOATUU]
Index: []

# Matching tername

In [30]:
locations_area['tername_new'] = locations_area['tername']
locations_area['tername_new'] = locations_area['tername_new'].str.replace(r'\(.*\)', '', regex = True).str.strip()
locations_area['tername_new'] = locations_area['tername_new'].str.replace(' район міста','')
locations_area['tername_new']

0                с.Терпіння
1                м.Красилів
2               с.Дмитрівка
3            Шевченківський
4                  с.Кумарі
                ...
22587    с.Великий Браталів
22588          с.Влашанівка
22589           с.Коханівка
22590       с.Бастова Рудня
22591            м.Чернівці
Name: tername_new, Length: 22592, dtype: object

In [31]:
locations_area['code'] = locations_area['region_KOATUU']+locations_area['area_KOATUU']
locations_area

,regname,areaname,tername,region_KOATUU,areaname_new,area_KOATUU,tername_new,code
0,Запорізька область,Мелітопольський район,с.Терпіння,23,Мелітопольський район,230,с.Терпіння,23230
1,Хмельницька область,Красилівський район,м.Красилів,68,Красилівський район,227,м.Красилів,68227
2,Дніпропетровська область,Петропавлівський район,с.Дмитрівка,12,Петропавлівський район,238,с.Дмитрівка,12238
3,Чернівецька область,м.Чернівці,Шевченківський район міста,73,м.Чернівці,101,Шевченківський,73101
4,Миколаївська область,Врадіївський район,с.Кумарі,48,Врадіївський район,223,с.Кумарі,48223
...,...,...,...,...,...,...,...,...
22587,Житомирська область,Любарський район,с.Великий Браталів,18,Любарський район,231,с.Великий Браталів,18231
22588,Хмельницька область,Ізяславський район,с.Влашанівка,68,Ізяславський район,221,с.Влашанівка,68221
22589,Львівська область,Яворівський район,с.Коханівка,46,Яворівський район,258,с.Коханівка,46258
22590,Житомирська область,Ємільчинський район,с.Бастова Рудня,18,Ємільчинський район,217,с.Бастова Рудня,18217
22591,Чернівецька область,м.Чернівці,м.Чернівці,73,м.Чернівці,101,м.Чернівці,73101

In [32]:
code2020['code'] = code2020['region_KOATUU']+code2020['area_KOATUU']
code2020

,TE,NP,NU,region_KOATUU,area_KOATUU,local_KOATUU,name_KOATUU,code
0,0500000000,NaN,ВІННИЦЬКА ОБЛАСТЬ/М.ВІННИЦЯ,05,000,00000,Вінницька область,05000
1,0510100000,М,ВІННИЦЯ,05,101,00000,м.Вінниця,05101
2,0510141000,Т,ДЕСНА,05,101,41000,смт Десна,05101
3,0510300000,М,ЖМЕРИНКА,05,103,00000,м.Жмеринка,05103
4,0510390001,С,ЖУКІВЦІ,05,103,90001,с.Жуківці,05103
...,...,...,...,...,...,...,...,...
36847,8038200000,Р,ПЕЧЕРСЬКИЙ,80,382,00000,Печерський,80382
36848,8038500000,Р,ПОДІЛЬСЬКИЙ,80,385,00000,Подільський,80385
36849,8038600000,Р,СВЯТОШИНСЬКИЙ,80,386,00000,Святошинський,80386
36850,8038900000,Р,СОЛОМ'ЯНСЬКИЙ,80,389,00000,Солом'янський,80389
36851,8039100000,Р,ШЕВЧЕНКІВСЬКИЙ,80,391,00000,Шевченківський,80391

In [33]:
renaming = pd.read_csv('./location_data/Renaming.csv')
renaming

,New,Old,areaname,regname,year
0,с.Азовське,с.Луначарське,Бердянський район,Запорізька область,2016
1,с.Армашівка,с.Орджонікідзе,Ширяївський район,Одеська область,2016
2,с.Високе,с.Артемівка,Кегичівський район,Харківська область,2016
3,с.Вишневе,с.Жовтневе,Калинівський район,Вінницька область,2016
4,с.Єрмішкове,с.Дзержинське,Великомихайлівський район,Одеська область,2016
...,...,...,...,...,...
1536,м.Яремче,м.Яремча,м.Яремче,Івано-Франківська область,2006
1537,с.Яромель,с.Йосипівка,Ківерцівський район,Волинська область,1989
1538,с.Ясинівка,с.Ясенівка,Дубенський район,Рівненська область,2013
1539,с.Ятвяги,с.Прибілля,Жидачівський район,Львівська область,2015
1540,с.Яшники,с.Ячники,Лохвицький район,Полтавська область,1995

In [34]:
set(code2020[code2020.area_KOATUU == '000'].name_KOATUU.str.lower())^set(renaming.regname.str.lower())

{'м.київ'}

In [35]:
renam_code = renaming.merge(code2020[['region_KOATUU']], left_on=renaming['regname'].str.lower(), right_on=code2020['name_KOATUU'].str.lower(), how='left')
renam_code = renam_code.drop('key_0', axis=1)
renam_code

,New,Old,areaname,regname,year,region_KOATUU
0,с.Азовське,с.Луначарське,Бердянський район,Запорізька область,2016,23
1,с.Армашівка,с.Орджонікідзе,Ширяївський район,Одеська область,2016,51
2,с.Високе,с.Артемівка,Кегичівський район,Харківська область,2016,63
3,с.Вишневе,с.Жовтневе,Калинівський район,Вінницька область,2016,05
4,с.Єрмішкове,с.Дзержинське,Великомихайлівський район,Одеська область,2016,51
...,...,...,...,...,...,...
1536,м.Яремче,м.Яремча,м.Яремче,Івано-Франківська область,2006,26
1537,с.Яромель,с.Йосипівка,Ківерцівський район,Волинська область,1989,07
1538,с.Ясинівка,с.Ясенівка,Дубенський район,Рівненська область,2013,56
1539,с.Ятвяги,с.Прибілля,Жидачівський район,Львівська область,2015,46
1540,с.Яшники,с.Ячники,Лохвицький район,Полтавська область,1995,53

In [36]:
dct = {}
for code in code2020.region_KOATUU.unique():
    troubles = set(renam_code[(renam_code.region_KOATUU == code)].areaname.str.lower())-set(code2020[(code2020.region_KOATUU == code)&(code2020.area_KOATUU != '000')&(code2020.local_KOATUU == '00000')].name_KOATUU.str.lower())
    if troubles:
        dct[code] = troubles
print(dct)

{}

In [37]:
renam_code = renam_code.merge(code2020[['area_KOATUU']], left_on=[renam_code['region_KOATUU'], renam_code['areaname'].str.lower()], right_on=[code2020['region_KOATUU'], code2020['name_KOATUU'].str.lower()], how='left')
renam_code = renam_code.drop(columns = ['key_0', 'key_1'], axis=1)
renam_code

,New,Old,areaname,regname,year,region_KOATUU,area_KOATUU
0,с.Азовське,с.Луначарське,Бердянський район,Запорізька область,2016,23,206
1,с.Армашівка,с.Орджонікідзе,Ширяївський район,Одеська область,2016,51,254
2,с.Високе,с.Артемівка,Кегичівський район,Харківська область,2016,63,231
3,с.Вишневе,с.Жовтневе,Калинівський район,Вінницька область,2016,05,216
4,с.Єрмішкове,с.Дзержинське,Великомихайлівський район,Одеська область,2016,51,216
...,...,...,...,...,...,...,...
1536,м.Яремче,м.Яремча,м.Яремче,Івано-Франківська область,2006,26,110
1537,с.Яромель,с.Йосипівка,Ківерцівський район,Волинська область,1989,07,218
1538,с.Ясинівка,с.Ясенівка,Дубенський район,Рівненська область,2013,56,216
1539,с.Ятвяги,с.Прибілля,Жидачівський район,Львівська область,2015,46,215
1540,с.Яшники,с.Ячники,Лохвицький район,Полтавська область,1995,53,226

In [38]:
renam_code['code'] = renam_code['region_KOATUU']+renam_code['area_KOATUU']
renam_code

,New,Old,areaname,regname,year,region_KOATUU,area_KOATUU,code
0,с.Азовське,с.Луначарське,Бердянський район,Запорізька область,2016,23,206,23206
1,с.Армашівка,с.Орджонікідзе,Ширяївський район,Одеська область,2016,51,254,51254
2,с.Високе,с.Артемівка,Кегичівський район,Харківська область,2016,63,231,63231
3,с.Вишневе,с.Жовтневе,Калинівський район,Вінницька область,2016,05,216,05216
4,с.Єрмішкове,с.Дзержинське,Великомихайлівський район,Одеська область,2016,51,216,51216
...,...,...,...,...,...,...,...,...
1536,м.Яремче,м.Яремча,м.Яремче,Івано-Франківська область,2006,26,110,26110
1537,с.Яромель,с.Йосипівка,Ківерцівський район,Волинська область,1989,07,218,07218
1538,с.Ясинівка,с.Ясенівка,Дубенський район,Рівненська область,2013,56,216,56216
1539,с.Ятвяги,с.Прибілля,Жидачівський район,Львівська область,2015,46,215,46215
1540,с.Яшники,с.Ячники,Лохвицький район,Полтавська область,1995,53,226,53226

In [39]:
renaming_dict = {(row['Old'], row['code']): row['New'] for _, row in renam_code.iterrows()}
locations_area['tername_new'] = locations_area.apply(lambda row: renaming_dict.get((row['tername_new'], row['code']), row['tername_new']), axis=1)

In [40]:
for cod in locations_area.code.unique():
    troubles = set(locations_area[(locations_area.code == cod)].tername_new.str.lower())-set(code2020[code2020.code == cod].name_KOATUU.str.lower())
    if troubles:
        print(f'{repr(cod)}:{troubles},')

'68227':{'с.дружнє'},
'73101':{'першотравневий', 'шевченківський', 'садгірський'},
'14117':{'смт олексіїво-дружківка'},
'12101':{'ленінський', 'красногвардійський', 'бабушкінський', 'жовтневий', 'кіровський'},
'46258':{'с.щеплати', 'с.руда краковецька'},
'26240':{'с.саджавка'},
'68239':{'с.старий кривин', "с.д'яків", 'с.голики'},
'51223':{'с.миколаівка'},
'63216':{'с-ще вірівка', 'с-ще новоолександрівка', 'с-ще профінтерн'},
'14209':{'с.зайцеве', 'с.переізне', 'с-ще опитне', 'с-ще зеленопілля', 'с.іванівське', 'с.відродження', 'с.покровське', 'с-ще хромове', 'с.іванград', 'с.кліщіївка', 'с-ще володимирівка', 'с.клинове'},
'46212':{'с.отриничі'},
'71234':{'с.летицівка'},
'63101':{'червонозаводський', 'дзержинський', 'комінтернівський', 'ленінський', 'орджонікідзевський', 'фрунзенський', 'жовтневий'},
'35222':{'с.золоми'},
'05101':{'староміський', 'ленінський', 'замостянський'},
'74241':{'с.билорічиця'},
'14141':{'м.миколаївка'},
'56212':{'с.угольці'},
'53232':{'с.декабристів'},
'65101':{'комсомольський'},
'51210':{'м.біляївка', 'с.майори', 'с-ще повстанське'},
'32214':{'с.вільшанська-новоселиця', 'с.степове'},
'05230':{'с.кірова', 'с.нові обіходи'},
'21244':{'с.вонігово'},
'48220':{'с.новогригорівка', 'с.ракове'},
'46215':{'с.демянка-надднистрянська'},
'63220':{'с-ще дворічний кут'},
'32212':{'с.кулажінци'},
'56242':{'с.розваж'},
'14233':{'с.степне', 'с-ще дачне', 'с-ще водяне', 'с-ще дальнє', 'с-ще солодке', 'с.павлівка', 'с-ще степне', 'с-ще янтарне', 'с-ще максимівка'},
'12110':{'дзержинський', 'жовтневий'},
'59101':{'с.верхне піщане'},
'23101':{'смт тепличне', 'жовтневий', 'ленінський', 'орджонікідзевський'},
'53101':{'ленінський', 'октябрський'},
'12220':{'с-ще вишневе', 'с-ще кудашівка'},
'48101':{'ленінський'},
'14239':{'с-ще портівське', 'с-ще приазовське', 'с.білосарайська', "с-ще дем'янівка", 'с-ще агробаза', 'с-ще азовське'},
'71231':{'с.паланочки'},
'61226':{'с.іванківці', 'с.курівці', 'с.кобзарівка', 'с.чернихів', 'с.глядки', 'с.плесківці', 'с.воробіівка', 'с.вертелка', 'с.малашівці'},
'53206':{'м.глобино'},
'46251':{'с.городивичі', 'с.велика-волосянка'},
'14129':{'смт молотаранівка'},
'61216':{'с.паівка', 'с.орішківці'},
'63217':{'с-ще водяне', 'с-ще роздольне', 'с-ще красна поляна', 'с-ще першотравневе'},
'51214':{'с-ще оксамитне', 'с-ще тополине'},
'23242':{'с.улянівка'},
'74220':{'с.калитянське'},
'14103':{'м.часів яр', 'м.соледар'},
'65223':{'с.білогрудове', 'м.гола пристань', "с.стара збур'ївка"},
'35101':{'кіровський', 'ленінський'},
'14123':{'іллічівський', 'орджонікідзевський', 'с.виноградне', 'с.піонерське', 'жовтневий'},
'61234':{'с.гаі', 'м.кременець', 'с.савчинці', 'с.старий почаів', 'с.дунаів'},
'18240':{'с.майстрів', 'с.майстрова воля', 'с.маковиці'},
'14203':{"с.запаро-мар'євка"},
'51227':{'с-ще гвардійське'},
'05210':{'с.межирів', 'с.коростівці', 'с.сідава', 'с.рів', 'с.жуківці'},
'61252':{'с.прощова', 'с.чистілів'},
'46209':{'с.тулиголови'},
'65107':{'м.тавріїськ'},
'18244':{'с.рудня озерянська', 'с.майдан копищенський'},
'63208':{'с.улянівка'},
'12104':{'баглійський'},
'46248':{'с.свитязі'},
'51254':{'с.новопетрівка друга', 'с.новопетрівка перша'},
'07218':{'с.сапогове', 'с.жабка', 'с.прилуцьке', 'с.дачне'},
'65229':{'с.новодмитрівка-друга'},
'46118':{'м.соснівка'},
'73245':{'с.зруб-комарівці', 'с.аршица'},
'32105':{'с.несторівка'},
'18217':{'с.рудня іванівська'},
'21253':{'с.бороняво', 'с.крайна'},
'14215':{'с-ще діанівка', 'с-ще хлібодарівка', 'с-ще кіровське', 'с-ще пільне', 'смт ольгінка', 'с-ще привільне', 'с-ще степне', 'с.октябрьське', 'с-ще ближнє'},
'59253':{'с.ображіївка', 'с.погребки', 'с.остроушки'},
'05206':{'смт десна'},
'05253':{'с.рахни лісові'},
'32224':{'с.княжічі'},
'32202':{'с-ще садове', 'с.паршиків'},
'46242':{'с.воля-бранецька'},
'21232':{"с.тур'я бистра"},
'21227':{'с.нижній коропець', 'с.нове давидково', 'с.лавки', 'с.шенборн', 'с.кендерешів', 'с.дерцен', 'с.павшино'},
'21204':{'с.бодалово'},
'26228':{'с.вістова', 'с.середній бабин', 'с.студінка', 'с.сівка-калуська', 'с.кропивник', 'с.мостище'},
'05104':{'с.одая', 'с.сонячне'},
'12259':{'с.новотимофієвське', 'с.сергієвка'},
'74203':{'смт батурин', 'с.крапивне', 'с.фастовци'},
'53204':{'с.біленченківка', 'м.гадяч'},
'53218':{'с.грицаівка'},
'12252':{'с.ганно-миколаєвка', 'с.андрієвка', 'с.олексієвка'},
'46230':{'с.крупсько', 'с.мала горожана'},
'56208':{'с.заболоття'},
'59212':{'с.заводське'},
'74233':{'с.кунашівка'},
'23215':{'с.багатирівка'},
'51231':{'с.малаівці'},
'18242':{'с-ще білокамінка'},
'71206':{'с.драбове-барятинське', 'смт шрамківка'},
'59247':{'с-ще сад'},
'32208':{'с.петрівське'},
'46221':{'с.тадан'},
'18228':{'с-ще станційне'},
'53240':{'с.терентіівка'},
'12229':{'с-ще східне', 'с.шолохове', 'с-ще західне', 'с-ще першотравневе'},
'53216':{'с.шевченка', 'с.солона балка', 'с.вакулиха', 'с.красне', 'с.голобородьківське', 'с.михайлівське', 'с.іванівка', 'с.тагамлицьке', 'с.халтурине'},
'51202':{'с.ананьїв другий', 'с.ананьїв перший'},
'44209':{'с.заіківка'},
'51206':{'с.борсуки', 'с.пасицели', 'с.бендзари', 'с.немирівське', 'с.перельоти', 'с.перейма', 'с.мирони', 'с.гольма', 'с.обжиле', 'с.коритне', 'с.оленівка', 'с.саражинка', 'с.акулинівка', 'с.кармалюківка', 'с.пасат', 'с.лісничівка', 'с.євтодія', 'м.балта', 'с.андріяшівка', 'с.козацьке', 'с.березівка', 'с.білине'},
'74247':{'с.іванпуть'},
'26220':{'с.слобода долинська', 'с.слобода болехівська'},
'51212':{'с-ще виноград', 'с-ще жовтнівка', 'с-ще семихатки'},
'26248':{'с.слобода рівнянська', 'с.слобода небилівська'},
'46203':{'с.гаї-смоленскі'},
'53236':{'с-ще куйбишеве', 'с-ще вишневе'},
'71215':{'с.пальміра', 'с.плешкани'},
'05204':{'с.велика кириївка'},
'05202':{'с-ще слобода-ходацька'},
'44240':{'с.преображене'},
'63202':{'с-ще раківка'},
'73240':{'с.ломачинці'},
'12235':{'с.межеріч'},
'46239':{'с.паздимир'},
'44231':{'с.новоахтирка'},
'32204':{'с.олійникова-слобода'},
'59203':{'с.кудрявоє', 'с.сосонка', 'с.підлозієвка', 'с.климентове'},
'12226':{'с.новопетрівське', 'с.малієвське'},
'23221':{'с.біленьке-перше'},
'51233':{'с.сергіівка'},
'63242':{'с-ще слобожанське', 'с-ще ватутіне', 'с-ще комінтерн'},
'63231':{'с.бесарабівка'},
'68212':{'с.мала яромірка', 'с.велика яромірка'},
'35203':{'с.новоселівка', 'с.комінтерн'},
'51245':{'с-ще розівка'},
'63237':{'с-ще орлянка', 'с-ще лісна стінка', 'с-ще ягідне'},
'53245':{'с.старий калкаів'},
'05216':{'с-ще голендри'},
'51239':{'с-ще степове'},
'61258':{'с.матвіівці', 'с.кудлаівка'},
'12214':{'с-ще новотаромське', 'с-ще орджонікідзе'},
'59209':{'с.нечаівка'},
'18254':{'с-ще ягодинка', 'с-ще молодіжне'},
'65250':{'с-ще цюрупинське'},
'65203':{'с-ще східне'},
'53210':{'с-ще діброва', 'с-ще чапаєвка'},
'26208':{'с.устерікі'},
'59206':{'с-ще тімірязівка'},
'71212':{'с.богачівка'},
'35249':{'с-ще рядове', 'с-ще володимирівка'},
'48257':{'с.поляна'},
'18203':{'с.бровки-перші'},
'12248':{'с.новоолексієвка'},
'63218':{'с-ще великий виселок', 'с.мануїлівка'},
'12254':{'с.новокиївка', 'с.добра надія', 'с.сергієвка', 'с.іллінка'},
'61242':{'с.красіів'},
'05248':{'с.соколова'},
'63206':{'с-ще садове'},
'71251':{'с.ставківка'},
'61246':{'с.гниличики'},
'12242':{'с.черненкове'},
'26232':{'с.воскресинці', 'с.шепарівці', 'с.товмачик', 'с.воскресінці', 'с.іванівці'},
'26212':{"с.загір'я кукільницьке"},
'61255':{'с.скородинці', 'с.біла', 'с.росохач', 'с.переходи', 'с.горішня вигнанка', 'с.пастуше', 'с.бичківці'},
'23218':{'с-ще червоне', 'с-ще комсомольське', 'с-ще гуляйпільське'},
'14212':{'с.георгієвка', 'с-ще октябрьське', 'с.розлив', 'с.андрієвка'},
'32242':{'с.васіліха'},
'46245':{'с.зимівка', 'смт славсько'},
'32246':{'с.бурковці', 'с.деніхівка'},
'05241':{'с.демківське'},
'18258':{'с-ще суслівка', 'смт чуднів', 'с-ще шевченка'},
'14227':{'с.червоний лиман', 'с-ще солоне', 'смт новоекономічна'},
'44216':{'с.діброва'},
'61204':{'м.бережани', 'с.рай', 'с.нараів'},
'44233':{'с.тевяшеве', 'с.пелагеївка'},
'48209':{'с.червона україна'},
'53228':{'с-ще новооріхівка'},
'59220':{'с-ще заводи'},
'65238':{'с-ще донцове', 'с-ще заповітне', 'с-ще дальне', 'с-ще вільне', 'с-ще братське', 'с-ще змагання'},
'14217':{'с.малоянісоль', 'с-ще малинівка', 'с-ще гранітне', 'с-ще катеринівка', 'с-ще зоря', 'с-ще ключове', 'с-ще труженка', 'с.октябрьське'},
'71237':{'с.чубівка'},
'63239':{'с.олексіївка', 'с.нова іванівка', 'с.мирне', 'с.катеринівка', 'с-ще лагідне', 'с.царедарівка', 'с.полтавське', 'с.степове', 'с-ще чернігівське', 'с.нестеліївка', 'с.вільне', 'с-ще миролюбівка', 'с.олександрівка', 'с.світловщина', 'с.копані', 'с-ще кінне'},
'65247':{'с.шевченка', 'с.миколаівка'},
'63228':{"с.кам'янка"},
'21248':{'с.ратовці', 'с.верхнє солотвино', 'с.холмці'},
'74258':{'с.гуто-студенецька'},
'53242':{'с.шкурупіівка', 'с.жовтневе', 'с.покровське', 'смт решетилівка'},
'61230':{'с.мала плавучка'},
'74236':{'м.новгород-сіверський'},
'63245':{'с-ще червоне'},
'48251':{'с-ще рівне'},
'51225':{'с.будеі', 'с.олексіівка'},
'44254':{'с-ще привілля', 'с.богачка'},
'23206':{'с.азовське'},
'51235':{'с.улянівка', 'с.настасіівка', 'с.уляновка'},
'74211':{'с.брагінці'},
'65218':{'с.мала шестерня'},
'51229':{'с.нестоіта', 'с.мардаровка'},
'14230':{'с.торське', 'с.яцьківка', 'с-ще нове', 'смт ярова', 'с.рубці', 'с.олександрівка', 'с.лозове', 'смт зарічне', 'с.рідкодуб', 'с.терни', 'с.озерне', 'с-ще соснове', 'с.коровій яр', 'смт дробишеве', 'с.липове', 'смт новоселівка', 'с.закітне', 'с.шандриголове', 'смт ямпіль'},

In [41]:
for code in renam.dct_replace:
    for place in renam.dct_replace[code]:
        locations_area.loc[(locations_area.code == code) & (locations_area['tername_new'] == place), 'tername_new'] = renam.dct_replace[code][place]

In [42]:
def change_area_KOATUU(old_code, place, code, dataset):
    dataset.loc[(dataset.code == old_code)&(dataset['tername_new'] == place), 'area_KOATUU'] = code[2:]
    dataset.loc[(dataset.code == old_code)&(dataset['tername_new'] == place), 'code'] = code
    values = code2020.loc[(code2020.code == code)&(code2020.local_KOATUU == '00000'), 'name_KOATUU'].unique()
    if len(values) == 1:
        dataset.loc[(dataset.code == code)&(dataset['tername_new'] == place), 'areaname_new'] = values[0]
    else:
        raise Exception(f'More than one value:{old_code}, {place}, {code}, {values}')

In [43]:
for item in renam.place_change:
    change_area_KOATUU(item[0], item[1], item[2], locations_area)

In [44]:
for code in renam.dct_replace:
    for place in renam.dct_replace[code]:
        locations_area.loc[(locations_area.code == code) & (locations_area['tername_new'] == place), 'tername_new'] = renam.dct_replace[code][place]

In [45]:
locations_KOATUU= locations_area.merge(code2020[['local_KOATUU']], left_on=[locations_area['region_KOATUU'], locations_area['area_KOATUU'], locations_area['tername_new'].str.lower()], right_on=[code2020['region_KOATUU'], code2020['area_KOATUU'], code2020['name_KOATUU'].str.lower()], how='left')
locations_KOATUU = locations_KOATUU.drop(columns = ['key_0', 'key_1', 'key_2'], axis=1)
locations_KOATUU.head()

,regname,areaname,tername,region_KOATUU,areaname_new,area_KOATUU,tername_new,code,local_KOATUU
0,Запорізька область,Мелітопольський район,с.Терпіння,23,Мелітопольський район,230,с.Терпіння,23230,85101
1,Хмельницька область,Красилівський район,м.Красилів,68,Красилівський район,227,м.Красилів,68227,10100
2,Дніпропетровська область,Петропавлівський район,с.Дмитрівка,12,Петропавлівський район,238,с.Дмитрівка,12238,81501
3,Чернівецька область,м.Чернівці,Шевченківський район міста,73,м.Чернівці,101,м.Чернівці,73101,00000
4,Миколаївська область,Врадіївський район,с.Кумарі,48,Врадіївський район,223,с.Кумарі,48223,83001

In [46]:
locations_KOATUU['KOATUU'] = locations_KOATUU['region_KOATUU']+locations_KOATUU['area_KOATUU']+locations_KOATUU['local_KOATUU']
locations_KOATUU.head()

,regname,areaname,tername,region_KOATUU,areaname_new,area_KOATUU,tername_new,code,local_KOATUU,KOATUU
0,Запорізька область,Мелітопольський район,с.Терпіння,23,Мелітопольський район,230,с.Терпіння,23230,85101,2323085101
1,Хмельницька область,Красилівський район,м.Красилів,68,Красилівський район,227,м.Красилів,68227,10100,6822710100
2,Дніпропетровська область,Петропавлівський район,с.Дмитрівка,12,Петропавлівський район,238,с.Дмитрівка,12238,81501,1223881501
3,Чернівецька область,м.Чернівці,Шевченківський район міста,73,м.Чернівці,101,м.Чернівці,73101,00000,7310100000
4,Миколаївська область,Врадіївський район,с.Кумарі,48,Врадіївський район,223,с.Кумарі,48223,83001,4822383001

# Match with the new system of code2020

In [47]:
comparison = pd.read_excel('./location_data/Comparison table.xlsx',  dtype=str, skiprows=2)
comparison

,Кодифікатор,Код об'єкта КОАТУУ,Категорія об’єкта,Назва об’єкта
0,UA01000000000013043,0100000000,О,Автономна Республіка Крим
1,UA01020000000022387,0120400000,Р,Бахчисарайський
2,UA01020010000048857,8536990200,Н,Андріївська
3,UA01020010010075540,8536990201,С,Андріївка
4,UA01020010020030666,8536990203,Х,Сонячний
...,...,...,...,...
31753,UA85000000000065278,8500000000,К,Севастополь
31754,UA85000000000155841,8536300000,В,Балаклавський
31755,UA85000000000259923,8536400000,В,Гагарінський
31756,UA85000000000334608,8536600000,В,Ленінський
31757,UA85000000000449437,8536900000,В,Нахімовський

In [48]:
comparison.rename(columns = {'Кодифікатор':'KATOTTG',"Код об'єкта КОАТУУ ":'KOATUU','Категорія об’єкта':'category', 'Назва об’єкта':'name'}, inplace=True)
comparison

                   KATOTTG      KOATUU category                       name
0      UA01000000000013043  0100000000        О  Автономна Республіка Крим
1      UA01020000000022387  0120400000        Р            Бахчисарайський
2      UA01020010000048857  8536990200        Н               Андріївська
3      UA01020010010075540  8536990201        С                  Андріївка
4      UA01020010020030666  8536990203        Х                   Сонячний
...                    ...         ...      ...                        ...
31753  UA85000000000065278  8500000000        К                Севастополь
31754  UA85000000000155841  8536300000        В              Балаклавський
31755  UA85000000000259923  8536400000        В               Гагарінський
31756  UA85000000000334608  8536600000        В                 Ленінський
31757  UA85000000000449437  8536900000        В               Нахімовський

[31758 rows x 4 columns]

In [49]:
comparison_loc = comparison[comparison.category.isin(['С', 'М', 'В', 'Т', 'Х'])]

In [50]:
locations_KOATUU.loc[(locations_KOATUU.KOATUU == '5120280501'), 'local_KOATUU'] = '80401'
locations_KOATUU.loc[(locations_KOATUU.KOATUU == '5120280501'), 'KOATUU'] = '5120280401'

In [51]:
# locations_KATOTTG = locations_KOATUU.merge(comparison_loc[['KATOTTG']], left_on=[locations_KOATUU['KOATUU_2020']], right_on=[comparison_loc['KOATUU_2020']], how='left')
locations_KATOTTG = locations_KOATUU.merge(comparison_loc[['KATOTTG', 'category', 'KOATUU']], on=['KOATUU'], how='left')
# locations_KATOTTG  = locations_KATOTTG.drop(columns = ['key_0'], axis=1)
locations_KATOTTG.head()

,regname,areaname,tername,region_KOATUU,areaname_new,area_KOATUU,tername_new,code,local_KOATUU,KOATUU,KATOTTG,category
0,Запорізька область,Мелітопольський район,с.Терпіння,23,Мелітопольський район,230,с.Терпіння,23230,85101,2323085101,UA23080270010078454,С
1,Хмельницька область,Красилівський район,м.Красилів,68,Красилівський район,227,м.Красилів,68227,10100,6822710100,UA68040210010032567,М
2,Дніпропетровська область,Петропавлівський район,с.Дмитрівка,12,Петропавлівський район,238,с.Дмитрівка,12238,81501,1223881501,UA12140170040016918,С
3,Чернівецька область,м.Чернівці,Шевченківський район міста,73,м.Чернівці,101,м.Чернівці,73101,00000,7310100000,UA73060610010033137,М
4,Миколаївська область,Врадіївський район,с.Кумарі,48,Врадіївський район,223,с.Кумарі,48223,83001,4822383001,UA48080050190079797,С

In [52]:
locations_KATOTTG.category.unique()

array(['С', 'М', 'В', 'Т', 'Х', nan], dtype=object)

check na

In [53]:
locations_KATOTTG[(locations_KATOTTG.KATOTTG.isna())]

,regname,areaname,tername,region_KOATUU,areaname_new,area_KOATUU,tername_new,code,local_KOATUU,KOATUU,KATOTTG,category
13686,Дніпропетровська область,Дніпропетровська область,Петропавлівський район,12,Петропавлівський район,238,Петропавлівський район,12238,00000,1223800000,NaN,NaN
16272,Львівська область,Львівська область,Сокальський район,46,Сокальський район,248,Сокальський район,46248,00000,4624800000,NaN,NaN

these two tuples are not valid, since the final location couldn't be area. So we drop them

In [54]:
locations_KATOTTG= locations_KATOTTG[(locations_KATOTTG.KATOTTG.notna())]
locations_KATOTTG.reset_index(drop=True, inplace=True)
locations_KATOTTG

,regname,areaname,tername,region_KOATUU,areaname_new,area_KOATUU,tername_new,code,local_KOATUU,KOATUU,KATOTTG,category
0,Запорізька область,Мелітопольський район,с.Терпіння,23,Мелітопольський район,230,с.Терпіння,23230,85101,2323085101,UA23080270010078454,С
1,Хмельницька область,Красилівський район,м.Красилів,68,Красилівський район,227,м.Красилів,68227,10100,6822710100,UA68040210010032567,М
2,Дніпропетровська область,Петропавлівський район,с.Дмитрівка,12,Петропавлівський район,238,с.Дмитрівка,12238,81501,1223881501,UA12140170040016918,С
3,Чернівецька область,м.Чернівці,Шевченківський район міста,73,м.Чернівці,101,м.Чернівці,73101,00000,7310100000,UA73060610010033137,М
4,Миколаївська область,Врадіївський район,с.Кумарі,48,Врадіївський район,223,с.Кумарі,48223,83001,4822383001,UA48080050190079797,С
...,...,...,...,...,...,...,...,...,...,...,...,...
22692,Житомирська область,Любарський район,с.Великий Браталів,18,Любарський район,231,с.Великий Браталів,18231,55106,1823155106,UA18040290070047586,С
22693,Хмельницька область,Ізяславський район,с.Влашанівка,68,Ізяславський район,221,с.Влашанівка,68221,86602,6822186602,UA68060250040099385,С
22694,Львівська область,Яворівський район,с.Коханівка,46,Яворівський район,258,с.Коханівка,46258,87803,4625887803,UA46140110360079694,С
22695,Житомирська область,Ємільчинський район,с.Бастова Рудня,18,Ємільчинський район,217,с.Бастова Рудня,18217,80403,1821780403,UA18080030040080438,С
22696,Чернівецька область,м.Чернівці,м.Чернівці,73,м.Чернівці,101,м.Чернівці,73101,00000,7310100000,UA73060610010033137,М

In [55]:
locations_KATOTTG.columns

Index(['regname', 'areaname', 'tername', 'region_KOATUU', 'areaname_new',
       'area_KOATUU', 'tername_new', 'code', 'local_KOATUU', 'KOATUU',
       'KATOTTG', 'category'],
      dtype='object')

# 2022

In [56]:
dataset_2022 = pd.read_csv(f"../../data_loader/2022/Odata2022File.csv", sep=";", encoding='utf-8')
dataset_2022

,OUTID,Birth,SexTypeName,RegName,AREANAME,TERNAME,RegTypeName,TerTypeName,EONAME,EOTypeName,...,Block1Ball,Block2,Block2Ball100,Block2Ball,Block3,Block3Ball100,Block3Ball,PTRegName,PTAreaName,PTTerName
0,d60381f3-8d71-441e-817e-49b9fa8b43dd,2005,чоловіча,Львівська область,Яворівський район,с.Гусаків,Випускник закладу загальної середньої освіти 2...,"селище, село","Гусаківський навчально-виховний комплекс ""Зага...",навчально-виховний комплекс,...,14.0,Історія України,"147,0",15.0,Математика,"128,0",5.0,Львівська область,"м.Львів, Залізничний район міста",Залізничний район міста
1,eb25a9fc-b757-4321-a2b4-ebb1b635397d,2005,чоловіча,Львівська область,Яворівський район,с.Гусаків,Випускник закладу загальної середньої освіти 2...,"селище, село","Гусаківський навчально-виховний комплекс ""Зага...",навчально-виховний комплекс,...,11.0,Історія України,"149,0",17.0,Математика,"136,0",8.0,Львівська область,"м.Львів, Залізничний район міста",Залізничний район міста
2,1cb161bd-51ed-4d24-b605-1d45db63cada,2005,жіноча,Львівська область,Яворівський район,с.Гусаків,Випускник закладу загальної середньої освіти 2...,"селище, село","Гусаківський навчально-виховний комплекс ""Зага...",навчально-виховний комплекс,...,25.0,Історія України,"158,0",24.0,Математика,"185,0",28.0,Львівська область,"м.Львів, Залізничний район міста",Залізничний район міста
3,0311b8d8-67bb-49a4-a0b9-f049b7ef4184,2005,жіноча,Львівська область,Яворівський район,с.Гусаків,Випускник закладу загальної середньої освіти 2...,"селище, село","Гусаківський навчально-виховний комплекс ""Зага...",навчально-виховний комплекс,...,20.0,Історія України,"146,0",14.0,Математика,"148,0",14.0,Львівська область,"м.Львів, Залізничний район міста",Залізничний район міста
4,a8b35a53-feac-4e42-aed8-8d6ffab7decf,2005,чоловіча,Львівська область,Яворівський район,с.Гусаків,Випускник закладу загальної середньої освіти 2...,"селище, село","Гусаківський навчально-виховний комплекс ""Зага...",навчально-виховний комплекс,...,24.0,Історія України,"144,0",13.0,Математика,"144,0",12.0,Львівська область,"м.Львів, Залізничний район міста",Залізничний район міста
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234099,6cbe3454-80f0-42b5-8d6d-c2ead687d804,2005,чоловіча,Волинська область,Володимирський район,с.Заболотці,Випускник закладу загальної середньої освіти 2...,"селище, село",Заболотцівський ліцей Литовезької сільської ра...,середня загальноосвітня школа,...,13.0,Історія України,"136,0",9.0,Математика,"148,0",14.0,Волинська область,м.Нововолинськ,м.Нововолинськ
234100,b897557b-c01b-49d4-8624-b351aaafe5ff,2005,жіноча,Волинська область,Володимирський район,с.Заболотці,Випускник закладу загальної середньої освіти 2...,"селище, село",Заболотцівський ліцей Литовезької сільської ра...,середня загальноосвітня школа,...,31.0,Історія України,"170,0",29.0,Математика,"162,0",22.0,Волинська область,м.Нововолинськ,м.Нововолинськ
234101,dcec644b-dcec-47ee-9971-6beebd1a929b,2005,чоловіча,Волинська область,Володимирський район,с.Заболотці,Випускник закладу загальної середньої освіти 2...,"селище, село",Заболотцівський ліцей Литовезької сільської ра...,середня загальноосвітня школа,...,21.0,Історія України,"152,0",20.0,Математика,"154,0",19.0,Волинська область,м.Нововолинськ,м.Нововолинськ
234102,cb4156bb-a624-4274-9d38-28be3096f6b9,2004,жіноча,Волинська область,Володимирський район,с.Заболотці,Випускник закладу загальної середньої освіти 2...,"селище, село",Заболотцівський ліцей Литовезької сільської ра...,середня загальноосвітня школа,...,12.0,Історія України,"131,0",7.0,Математика,"131,0",6.0,Волинська область,м.Нововолинськ,м.Нововолинськ
234103,7514327a-0831-4adc-8277-41d74e543884,2005,жіноча,Херсонська область,Каховський район,с.Павлівка (Присиваська),Випускник закладу загальної середньої освіти 2...,"селище, село",Павлівська загальноосвітня школа I-III ступені...,середня загальноосвітня школа,...,NaN,Історія України,NaN,NaN,Математика,NaN,NaN,Одеська область,"м.Одеса, Приморський район міста",Приморський район міста

In [57]:
dataset_2023 = pd.read_csv(f"../../data_loader//2023/Odata2023File.csv", sep=";", encoding='utf-8')
dataset_2023

,outid,Birth,SexTypeName,RegName,AreaName,TerName,RegTypeName,TerTypeName,EOName,EOTypeName,...,DeuBlockStatus,DeuBlockBall100,DeuBlockBall,SpaBlock,SpaBlockStatus,SpaBlockBall100,SpaBlockBall,PTRegName,PTAreaName,PTTerName
0,98e9d1c5-c3e3-41ed-b8ef-8e42f293b8e2,2006,жіноча,Запорізька область,м.Запоріжжя,Шевченківський район міста,Випускник закладу загальної середньої освіти 2...,місто,Запорізька гімназія №93 Запорізької міської ра...,гімназія,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Одеська область,"м.Одеса, Малиновський район міста",Малиновський район міста
1,98e9ff41-20ec-4cb0-823c-b44580578ec0,2006,жіноча,Херсонська область,м.Херсон,Корабельний район міста,Випускник закладу загальної середньої освіти 2...,місто,Херсонська гімназія №1 Херсонської міської ради,гімназія,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Данія,м.Орхус,м.Орхус
2,98e06b8f-a755-4101-9379-d0f9332f6a23,2006,жіноча,Дніпропетровська область,м.Дніпро,Центральний район міста,Випускник закладу загальної середньої освіти 2...,місто,"Комунальний заклад освіти ""Навчально-виховний ...",навчально-виховний комплекс,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Дніпропетровська область,"м.Дніпро, Соборний район міста",Соборний район міста
3,990e6cee-d60e-4d7f-a71f-6cba3101ed35,2003,жіноча,Запорізька область,м.Запоріжжя,Олександрівський район міста,Випускник минулих років,місто,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Запорізька область,"м.Запоріжжя, Олександрівський район міста",Олександрівський район міста
4,98e62f06-f6e4-4b8f-8086-10b55a9335b1,2006,чоловіча,м.Київ,м.Київ,Деснянський район міста,Випускник закладу загальної середньої освіти 2...,місто,"Навчально-виховний комплекс ""Дошкільний навчал...",навчально-виховний комплекс,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,м.Київ,"м.Київ, Голосіївський район міста",Голосіївський район міста
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288930,98e83726-5473-40e0-a7c3-30f29f2bb0ec,2006,чоловіча,Донецька область,Волноваський район,смт Велика Новосілка,Випускник закладу загальної середньої освіти 2...,селище міського типу,Великоновосілківський заклад загальної середнь...,середня загальноосвітня школа,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Тернопільська область,м.Тернопіль,м.Тернопіль
288931,98de6ea2-28f3-4951-990a-9a3ff45449de,2004,чоловіча,Волинська область,Ковельський район,м.Ковель,Випускник минулих років,місто,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Волинська область,м.Ковель,м.Ковель
288932,98e883cb-d2b7-4bc7-b86e-3ac16b36a0ff,2006,жіноча,Львівська область,м.Львів,Сихівський район міста,Випускник закладу загальної середньої освіти 2...,місто,Середня загальноосвітня школа №13,середня загальноосвітня школа,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Львівська область,"м.Львів, Сихівський район міста",Сихівський район міста
288933,9909aefa-b1e9-4eef-a911-25fae0b9f70d,2004,чоловіча,Харківська область,Лозівський район,м.Лозова,Випускник закладу загальної середньої освіти 2...,місто,Лозівський центр професійної освіти Харківсько...,заклад професійної (професійно-технічної) освіти,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Харківська область,м.Лозова,м.Лозова
288934,98f9d13e-9a8b-4443-aaa1-da2f9337af1f,2006,чоловіча,Київська область,Бучанський район,м.Ірпінь,Випускник закладу загальної середньої освіти 2...,місто,Ірпінський ліцей інноваційних технологій Ірпін...,ліцей,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Київська область,м.Ірпінь,м.Ірпінь

In [58]:
dataset_2024 = pd.read_csv(f"../../data_loader/2024/Odata2024File.csv", sep=";", encoding='utf-8')
dataset_2024

,outid,Birth,SexTypeName,RegName,AreaName,TerName,RegTypeName,TerTypeName,EOName,EOTypeName,...,SpaBlockStatus,SpaBlockBall100,SpaBlockBall,UkrLitBlock,UkrLitBlockStatus,UkrLitBlockBall100,UkrLitBlockBall,PTRegName,PTAreaName,PTTerName
0,9b995d13-de3d-47c2-9b4e-004025346a49,2006,жіноча,Черкаська область,Черкаський район,с.Ліпляве,Випускник загальноосвітнього навчального закла...,"селище, село","Комунальний заклад ""Ліплявський ліцей"" Ліплявс...",ліцей,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Черкаська область,м.Канів,м.Канів
1,9c0a5f77-73e4-475d-aff9-006da514737b,2007,чоловіча,Дніпропетровська область,Нікопольський район,м.Нікополь,Випускник загальноосвітнього навчального закла...,місто,"Відокремлений структурний підрозділ ""Нікопольс...",заклад фахової передвищої освіти,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Дніпропетровська область,м.Покров,м.Покров
2,9bb9c262-2188-475c-949a-000b1a194cbb,2006,жіноча,Івано-Франківська область,Івано-Франківський район,м.Івано-Франківськ,Випускник загальноосвітнього навчального закла...,місто,"Фаховий коледж Закладу вищої освіти ""Університ...",заклад фахової передвищої освіти,...,NaN,NaN,NaN,Українська література,Зараховано,"125,0",12.0,Польща,м.Домброва Горнича,м.Домброва Горнича
3,9b982071-10d6-4caa-b80a-004675647a31,2007,жіноча,Дніпропетровська область,м.Дніпро,Чечелівський район міста,Випускник загальноосвітнього навчального закла...,місто,"Комунальний заклад освіти ""Середня загальноосв...",середня загальноосвітня школа,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Латвія,м.Рига,м.Рига
4,9b9fc04c-570f-4cb9-903c-0007200fe870,2007,жіноча,Львівська область,Самбірський район,с.Вовче,Випускник загальноосвітнього навчального закла...,"селище, село",ВОВЧЕНСЬКИЙ ЗАКЛАД ЗАГАЛЬНОЇ СЕРЕДНЬОЇ ОСВІТИ ...,середня загальноосвітня школа,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Львівська область,Самбірський район,м.Старий Самбір
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312503,9b9de379-0d9c-4208-9ff3-ff9c53ad2db4,2006,жіноча,Житомирська область,Бердичівський район,м.Бердичів,Випускник загальноосвітнього навчального закла...,місто,Ліцей № 4 м. Бердичева Житомирської області,ліцей,...,NaN,NaN,NaN,Українська література,Зараховано,"170,0",36.0,Житомирська область,м.Бердичів,м.Бердичів
312504,9b9b7f43-0b1a-44ee-b0cc-ffa8215408cf,2007,чоловіча,Черкаська область,Уманський район,с.Христинівка,Випускник загальноосвітнього навчального закла...,"селище, село",Христинівський ліцей Христинівської міської ра...,ліцей,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Черкаська область,Уманський район,м.Христинівка
312505,9bc7e9fe-dc70-4cdc-bb3f-ffadc91dc9a2,1986,чоловіча,Полтавська область,м.Полтава,Київський район міста,Випускник минулих років,місто,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Полтавська область,"м.Полтава, Київський район міста",Київський район міста
312506,9b9d9e51-0a61-4b08-b4af-ffb99d790fe5,2000,жіноча,Житомирська область,м.Житомир,Корольовський район міста,Випускник минулих років,місто,NaN,NaN,...,NaN,NaN,NaN,Українська література,Зараховано,"131,0",13.0,Житомирська область,"м.Житомир, Корольовський район міста",Корольовський район міста
312507,9b92487f-ab7d-4bf9-a83f-ffc351d07d21,2007,чоловіча,Харківська область,м.Харків,Слобідський район міста,Випускник загальноосвітнього навчального закла...,місто,"комунальний заклад ""Харківський ліцей №90 Харк...",ліцей,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Польща,м.Варшава,м.Варшава

In [59]:
dataset_2025 = pd.read_csv(f"../../data_loader/2025/Odata2025File.csv", sep=";", encoding='utf-8')
dataset_2025

/var/folders/cz/wq9d8j_11fx3b8pjjbk7z8br0000gn/T/ipykernel_47754/4078391422.py:1: DtypeWarning: Columns (58) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset_2025 = pd.read_csv(f"../../data_loader/2025/Odata2025File.csv", sep=";", encoding='utf-8')

,outid,Birth,SexTypeName,RegName,AreaName,TerName,RegTypeName,TerTypeName,EOName,EOTypeName,...,SpaBlockStatus,SpaBlockBall100,SpaBlockBall,UkrLitBlock,UkrLitBlockStatus,UkrLitBlockBall100,UkrLitBlockBall,PTRegName,PTAreaName,PTTerName
0,9e78ac3d-e137-41a2-83df-000bc5e7abd8,2007,чоловіча,Київська область,Броварський район,м.Бровари,Випускник минулих років,місто,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Київська область,м.Бровари,м.Бровари
1,9e77fd9e-00f4-4399-b239-000d421551cc,2008,жіноча,Чернівецька область,Вижницький район,с.Нижні Станівці,Випускник поточного року,"селище, село",Нижньостанівецький заклад загальної середньої ...,середня загальноосвітня школа,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Чернівецька область,Вижницький район,м.Вижниця
2,9e75f45e-7262-4fb8-a347-003a0ea7f2ed,1987,чоловіча,Запорізька область,м.Запоріжжя,Комунарський район міста,Випускник минулих років,місто,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Запорізька область,"м.Запоріжжя, Комунарський район міста",Комунарський район міста
3,9e6812b6-6191-46d3-9048-003ad300b80c,2007,чоловіча,Харківська область,м.Харків,Основ'янський район міста,Випускник поточного року,місто,"ПРИВАТНИЙ ЛІЦЕЙ ""ОНЛАЙН-ШКОЛА ""АЛЬТЕРНАТИВА"" Х...",ліцей,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Чехія,м.Брно,м.Брно
4,9e66bc72-ff85-4864-8a16-002816ca7f73,2008,чоловіча,Харківська область,Куп'янський район,с-ще Шевченкове (Шевченківська),Випускник поточного року,"селище, село",Шевченківський ліцей Шевченківської селищної р...,ліцей,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Словаччина,м.Братислава,м.Братислава
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317086,9e703a35-81af-47bc-b4a9-ff5c468c3756,2008,жіноча,м.Київ,м.Київ,Голосіївський район міста,Випускник поточного року,місто,Ліцей № 59 міста Києва,ліцей,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,м.Київ,"м.Київ, Голосіївський район міста",Голосіївський район міста
317087,9e67ab46-0359-4ae7-9996-ff970ac16a6c,2007,чоловіча,Полтавська область,Кременчуцький район,м.Горішні Плавні,Випускник поточного року,місто,"Відокремлений структурний підрозділ ""Політехні...",заклад фахової передвищої освіти,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Полтавська область,м.Горішні Плавні,м.Горішні Плавні
317088,9e8606ee-f67b-4b37-b01a-ffa775e99884,2002,жіноча,Закарпатська область,Берегівський район,м.Берегове,Випускник минулих років,місто,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Закарпатська область,м.Берегове,м.Берегове
317089,9e77b512-e760-4796-9e7d-ffa8998f2e1a,2008,чоловіча,Одеська область,Березівський район,с-ще Радісне,Випускник поточного року,"селище, село",Радісненський ліцей Знам'янської сільської ради,середня загальноосвітня школа,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Одеська область,Березівський район,с-ще Іванівка (Іванівська)
317090,9e86d68a-a9f3-4932-a693-fff4bd2650f9,2008,чоловіча,Закарпатська область,Хустський район,с-ще Міжгір'я,Випускник поточного року,"селище, село","Комунальний заклад ""Міжгірський медичний фахов...",заклад фахової передвищої освіти,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Закарпатська область,м.Хуст,м.Хуст

In [60]:
dataset_2022.columns = [col.lower() for col in dataset_2022.columns]
dataset_2023.columns = [col.lower() for col in dataset_2023.columns]
dataset_2024.columns = [col.lower() for col in dataset_2024.columns]
dataset_2025.columns = [col.lower() for col in dataset_2025.columns]

In [61]:
print([col for col in dataset_2022.columns if col.startswith('pt')])
print([col for col in dataset_2023.columns if col.startswith('pt')])
print([col for col in dataset_2024.columns if col.startswith('pt')])
print([col for col in dataset_2025.columns if col.startswith('pt')])

['ptregname', 'ptareaname', 'pttername']
['ptregname', 'ptareaname', 'pttername']
['ptregname', 'ptareaname', 'pttername']
['ptregname', 'ptareaname', 'pttername']

In [62]:
types = ['', 'eo', 'pt']

In [63]:
locations_KATOTTG

,regname,areaname,tername,region_KOATUU,areaname_new,area_KOATUU,tername_new,code,local_KOATUU,KOATUU,KATOTTG,category
0,Запорізька область,Мелітопольський район,с.Терпіння,23,Мелітопольський район,230,с.Терпіння,23230,85101,2323085101,UA23080270010078454,С
1,Хмельницька область,Красилівський район,м.Красилів,68,Красилівський район,227,м.Красилів,68227,10100,6822710100,UA68040210010032567,М
2,Дніпропетровська область,Петропавлівський район,с.Дмитрівка,12,Петропавлівський район,238,с.Дмитрівка,12238,81501,1223881501,UA12140170040016918,С
3,Чернівецька область,м.Чернівці,Шевченківський район міста,73,м.Чернівці,101,м.Чернівці,73101,00000,7310100000,UA73060610010033137,М
4,Миколаївська область,Врадіївський район,с.Кумарі,48,Врадіївський район,223,с.Кумарі,48223,83001,4822383001,UA48080050190079797,С
...,...,...,...,...,...,...,...,...,...,...,...,...
22692,Житомирська область,Любарський район,с.Великий Браталів,18,Любарський район,231,с.Великий Браталів,18231,55106,1823155106,UA18040290070047586,С
22693,Хмельницька область,Ізяславський район,с.Влашанівка,68,Ізяславський район,221,с.Влашанівка,68221,86602,6822186602,UA68060250040099385,С
22694,Львівська область,Яворівський район,с.Коханівка,46,Яворівський район,258,с.Коханівка,46258,87803,4625887803,UA46140110360079694,С
22695,Житомирська область,Ємільчинський район,с.Бастова Рудня,18,Ємільчинський район,217,с.Бастова Рудня,18217,80403,1821780403,UA18080030040080438,С
22696,Чернівецька область,м.Чернівці,м.Чернівці,73,м.Чернівці,101,м.Чернівці,73101,00000,7310100000,UA73060610010033137,М

In [64]:
# OPTIMIZATION: Collect all dataframes first, then concat once
dataframes_to_concat = []

for typ in types:
    for dataset in [dataset_2022, dataset_2023, dataset_2024, dataset_2025]:
        new_col = {typ+'regname': 'regname', typ+'areaname':'areaname', typ+'tername': 'tername'}
        if all(column in dataset.columns for column in new_col.keys()):
            temp_data = dataset.loc[:, new_col.keys()].copy()
            temp_data.rename(columns=new_col, inplace=True)
            # Add NaN columns to match structure
            temp_data.loc[:, ['region_KOATUU', 'areaname_new',
                             'area_KOATUU', 'tername_new', 'code', 'local_KOATUU', 'KOATUU',
                             'KATOTTG', 'category']] = np.nan
            # Drop rows where all original columns are NaN before adding to list
            temp_data = temp_data.dropna(how='all')
            dataframes_to_concat.append(temp_data)

# Single concat operation instead of many
if dataframes_to_concat:
    locations_KATOTTG25 = pd.concat(dataframes_to_concat, ignore_index=True)
    locations_KATOTTG25.drop_duplicates(inplace=True)
    locations_KATOTTG25.reset_index(drop=True, inplace=True)
else:
    locations_KATOTTG25 = pd.DataFrame(columns=locations_KATOTTG.columns)

locations_KATOTTG25

,regname,areaname,tername,region_KOATUU,areaname_new,area_KOATUU,tername_new,code,local_KOATUU,KOATUU,KATOTTG,category
0,Львівська область,Яворівський район,с.Гусаків,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Львівська область,Яворівський район,с.Баличі,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Львівська область,Яворівський район,с.Шегині,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Львівська область,Яворівський район,с.Волиця,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Івано-Франківська область,Надвірнянський район,с.Гвізд,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
9754,Одеська область,м.Південне,м.Південне,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9755,Нідерланди,м.Гаага,м.Гаага,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9756,США,м.Воррен,м.Воррен,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9757,Польща,м.Домброва-Гурнича,м.Домброва-Гурнича,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9758,Туреччина,м.Стамбул,м.Стамбул,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [65]:
code2025 = pd.read_excel('./location_data/Codifiers2025.xlsx',  dtype=str, skiprows=3,skipfooter=3)
code2025

,Перший рівень,Другий рівень,Третій рівень,Четвертий рівень,Додатковий рівень,Категорія об’єкта,Назва об’єкта
0,UA01000000000013043,NaN,NaN,NaN,NaN,O,Автономна Республіка Крим
1,UA01000000000013043,UA01020000000022387,NaN,NaN,NaN,P,Бахчисарайський
2,UA01000000000013043,UA01020000000022387,UA01020010000048857,NaN,NaN,H,Андріївська
3,UA01000000000013043,UA01020000000022387,UA01020010000048857,UA01020010010075540,NaN,C,Андріївка
4,UA01000000000013043,UA01020000000022387,UA01020010000048857,UA01020010020030666,NaN,X,Сонячний
...,...,...,...,...,...,...,...
31739,UA80000000000093317,UA80000000000093317,UA80000000000093317,UA80000000000093317,UA80000000000875983,B,Святошинський
31740,UA80000000000093317,UA80000000000093317,UA80000000000093317,UA80000000000093317,UA80000000000980793,B,Солом’янський
31741,UA80000000000093317,UA80000000000093317,UA80000000000093317,UA80000000000093317,UA80000000001078669,B,Шевченківський
31742,UA85000000000065278,NaN,NaN,NaN,NaN,K,Севастополь
31743,UA85000000000065278,UA85000000000065278,UA85000000000065278,UA85000000000065278,UA85000000000155841,B,Балаклавський

In [66]:
code2025.rename(columns = {'Перший рівень':'first_level','Другий рівень':'second_level','Третій рівень':'third_level', 'Четвертий рівень':'fourth_level',
       'Додатковий рівень':'additional_level', 'Категорія об’єкта':'category','Назва об’єкта':'name'}, inplace=True)
code2025

,first_level,second_level,third_level,fourth_level,additional_level,category,name
0,UA01000000000013043,NaN,NaN,NaN,NaN,O,Автономна Республіка Крим
1,UA01000000000013043,UA01020000000022387,NaN,NaN,NaN,P,Бахчисарайський
2,UA01000000000013043,UA01020000000022387,UA01020010000048857,NaN,NaN,H,Андріївська
3,UA01000000000013043,UA01020000000022387,UA01020010000048857,UA01020010010075540,NaN,C,Андріївка
4,UA01000000000013043,UA01020000000022387,UA01020010000048857,UA01020010020030666,NaN,X,Сонячний
...,...,...,...,...,...,...,...
31739,UA80000000000093317,UA80000000000093317,UA80000000000093317,UA80000000000093317,UA80000000000875983,B,Святошинський
31740,UA80000000000093317,UA80000000000093317,UA80000000000093317,UA80000000000093317,UA80000000000980793,B,Солом’янський
31741,UA80000000000093317,UA80000000000093317,UA80000000000093317,UA80000000000093317,UA80000000001078669,B,Шевченківський
31742,UA85000000000065278,NaN,NaN,NaN,NaN,K,Севастополь
31743,UA85000000000065278,UA85000000000065278,UA85000000000065278,UA85000000000065278,UA85000000000155841,B,Балаклавський

In [67]:
code2025['name'] = code2025['name'].str.replace('’', "'")

In [68]:
code2025['name_KOATUU']= code2025['name'] 
code2025['name_KOATUU']= code2025['name_KOATUU'].str.strip()
code2025

,first_level,second_level,third_level,fourth_level,additional_level,category,name,name_KOATUU
0,UA01000000000013043,NaN,NaN,NaN,NaN,O,Автономна Республіка Крим,Автономна Республіка Крим
1,UA01000000000013043,UA01020000000022387,NaN,NaN,NaN,P,Бахчисарайський,Бахчисарайський
2,UA01000000000013043,UA01020000000022387,UA01020010000048857,NaN,NaN,H,Андріївська,Андріївська
3,UA01000000000013043,UA01020000000022387,UA01020010000048857,UA01020010010075540,NaN,C,Андріївка,Андріївка
4,UA01000000000013043,UA01020000000022387,UA01020010000048857,UA01020010020030666,NaN,X,Сонячний,Сонячний
...,...,...,...,...,...,...,...,...
31739,UA80000000000093317,UA80000000000093317,UA80000000000093317,UA80000000000093317,UA80000000000875983,B,Святошинський,Святошинський
31740,UA80000000000093317,UA80000000000093317,UA80000000000093317,UA80000000000093317,UA80000000000980793,B,Солом'янський,Солом'янський
31741,UA80000000000093317,UA80000000000093317,UA80000000000093317,UA80000000000093317,UA80000000001078669,B,Шевченківський,Шевченківський
31742,UA85000000000065278,NaN,NaN,NaN,NaN,K,Севастополь,Севастополь
31743,UA85000000000065278,UA85000000000065278,UA85000000000065278,UA85000000000065278,UA85000000000155841,B,Балаклавський,Балаклавський

In [69]:
code2025 = code2025[~code2025['first_level'].str.startswith(('UA01', 'UA85'))]

In [70]:
code2025.category.unique()

array(['O', 'P', 'H', 'C', 'M', 'X', 'B', 'K'], dtype=object)

In [71]:
code2025.loc[code2025['category'] == 'O', 'name_KOATUU'] = code2025.loc[code2025['category'] == 'O', 'name_KOATUU']+' область'
code2025.loc[code2025['category'] == 'P', 'name_KOATUU'] = code2025.loc[code2025['category'] =='P', 'name_KOATUU']+' район'
code2025.loc[code2025['category'] == 'Н', 'name_KOATUU'] = code2025.loc[code2025['category'] == 'Н', 'name_KOATUU']+' громада'
code2025.loc[code2025['category'] == 'C', 'name_KOATUU'] = 'с.' + code2025.loc[code2025['category'] == 'C', 'name_KOATUU']
code2025.loc[code2025['category'] == 'M', 'name_KOATUU'] = 'м.' + code2025.loc[code2025['category'] == 'M', 'name_KOATUU']
code2025.loc[code2025['category'] == 'X', 'name_KOATUU'] = 'с-ще ' + code2025.loc[code2025['category'] == 'X', 'name_KOATUU']
code2025.loc[code2025['category'] == 'В', 'name_KOATUU'] = code2025.loc[code2025['category'] =='В', 'name_KOATUU']+' район в місті'
code2025.loc[code2025['category'] == 'K', 'name_KOATUU'] = 'м.'  + code2025.loc[code2025['category'] == 'K', 'name_KOATUU']

In [72]:
diff = set(code2025[code2025.category.isin(['O','K'])].name_KOATUU.str.lower())^set(locations_KATOTTG25.regname.str.lower())
print(diff)

{'португалія', 'ірландія', 'німеччина', 'швеція', 'молдова', 'угорщина', 'велика британія', 'болгарія', 'швейцарія', 'люксембург', 'латвія', 'нідерланди', 'хорватія', 'словаччина', 'канада', 'фінляндія', 'румунія', 'азербайджан', 'інші країни', 'франція', 'сша', 'естонія', 'бельгія', 'словенія', 'іспанія', 'туреччина', 'польща', 'норвегія', 'данія', 'австрія', 'литва', 'італія', 'чехія', 'грузія'}

In [73]:
locations_KATOTTG25['region_KATOTTG'] = np.nan

In [74]:
for reg in code2025[code2025.category.isin(['O','K'])].name_KOATUU.str.lower().unique():
    values = code2025.loc[code2025.name_KOATUU.str.lower() == reg, 'first_level'].unique()
    if len(values) == 1:
        locations_KATOTTG25.loc[(locations_KATOTTG25.regname.str.lower()==reg), 'region_KATOTTG'] = values[0]
    else:
        raise Exception(f'More than one value:{reg}, {values}')

/var/folders/cz/wq9d8j_11fx3b8pjjbk7z8br0000gn/T/ipykernel_47754/59978042.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'UA05000000000010236' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  locations_KATOTTG25.loc[(locations_KATOTTG25.regname.str.lower()==reg), 'region_KATOTTG'] = values[0]

In [75]:
locations_KATOTTG25[~locations_KATOTTG25.regname.str.lower().isin(diff)].region_KATOTTG.unique()

array(['UA46000000000026241', 'UA26000000000069363',
       'UA07000000000024379', 'UA51000000000030770',
       'UA35000000000016081', 'UA56000000000066151',
       'UA48000000000039575', 'UA32000000000030281',
       'UA21000000000011690', 'UA05000000000010236',
       'UA80000000000093317', 'UA14000000000091971',
       'UA65000000000030969', 'UA18000000000041385',
       'UA23000000000064947', 'UA12000000000090473',
       'UA61000000000060328', 'UA73000000000044923',
       'UA74000000000025378', 'UA53000000000028050',
       'UA71000000000010357', 'UA63000000000041885',
       'UA44000000000018893', 'UA59000000000057109',
       'UA68000000000099709'], dtype=object)

In [76]:
locations_KATOTTG25.loc[(locations_KATOTTG25.regname.str.lower().isin(diff)), 'region_KATOTTG'] ='OC00000000000000000'
locations_KATOTTG25

,regname,areaname,tername,region_KOATUU,areaname_new,area_KOATUU,tername_new,code,local_KOATUU,KOATUU,KATOTTG,category,region_KATOTTG
0,Львівська область,Яворівський район,с.Гусаків,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UA46000000000026241
1,Львівська область,Яворівський район,с.Баличі,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UA46000000000026241
2,Львівська область,Яворівський район,с.Шегині,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UA46000000000026241
3,Львівська область,Яворівський район,с.Волиця,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UA46000000000026241
4,Івано-Франківська область,Надвірнянський район,с.Гвізд,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UA26000000000069363
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9754,Одеська область,м.Південне,м.Південне,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UA51000000000030770
9755,Нідерланди,м.Гаага,м.Гаага,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OC00000000000000000
9756,США,м.Воррен,м.Воррен,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OC00000000000000000
9757,Польща,м.Домброва-Гурнича,м.Домброва-Гурнича,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OC00000000000000000
9758,Туреччина,м.Стамбул,м.Стамбул,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OC00000000000000000

In [77]:
locations_KATOTTG25.loc[(locations_KATOTTG25.region_KATOTTG.str.startswith('OC')), 'region_new'] ='Інші країни'
locations_KATOTTG25.loc[(locations_KATOTTG25.region_KATOTTG.str.startswith('UA')), 'region_new'] = locations_KATOTTG25.regname
locations_KATOTTG25

,regname,areaname,tername,region_KOATUU,areaname_new,area_KOATUU,tername_new,code,local_KOATUU,KOATUU,KATOTTG,category,region_KATOTTG,region_new
0,Львівська область,Яворівський район,с.Гусаків,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UA46000000000026241,Львівська область
1,Львівська область,Яворівський район,с.Баличі,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UA46000000000026241,Львівська область
2,Львівська область,Яворівський район,с.Шегині,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UA46000000000026241,Львівська область
3,Львівська область,Яворівський район,с.Волиця,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UA46000000000026241,Львівська область
4,Івано-Франківська область,Надвірнянський район,с.Гвізд,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UA26000000000069363,Івано-Франківська область
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9754,Одеська область,м.Південне,м.Південне,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UA51000000000030770,Одеська область
9755,Нідерланди,м.Гаага,м.Гаага,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OC00000000000000000,Інші країни
9756,США,м.Воррен,м.Воррен,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OC00000000000000000,Інші країни
9757,Польща,м.Домброва-Гурнича,м.Домброва-Гурнича,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OC00000000000000000,Інші країни
9758,Туреччина,м.Стамбул,м.Стамбул,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OC00000000000000000,Інші країни

In [78]:
locations_KATOTTG25[locations_KATOTTG25.region_KATOTTG.isna()]

Empty DataFrame
Columns: [regname, areaname, tername, region_KOATUU, areaname_new, area_KOATUU, tername_new, code, local_KOATUU, KOATUU, KATOTTG, category, region_KATOTTG, region_new]
Index: []

# Areaname 2022

заповнити areaname_new аналогічно попереднього коду

In [79]:
locations_KATOTTG25['areaname_new'] = locations_KATOTTG25['areaname']

In [80]:
locations_KATOTTG25['areaname_new'].unique()

array(['Яворівський район', 'Надвірнянський район', 'Луцький район',
       'Івано-Франківський район', 'м.Одеса', 'м.Львів',
       'м.Кропивницький', 'Рівненський район', 'Первомайський район',
       'Бориспільський район', 'Берегівський район', 'Вінницький район',
       'Самбірський район', 'Ужгородський район', 'м.Київ',
       'Волноваський район', 'Скадовський район', 'Житомирський район',
       'Мелітопольський район', 'Львівський район', 'Гайсинський район',
       'Ізмаїльський район', 'Краматорський район', 'Криворізький район',
       'Чортківський район', 'Вижницький район', 'Прилуцький район',
       'Вишгородський район', 'Чернівецький район', 'Лубенський район',
       'Сарненський район', 'м.Черкаси', "Кам'янський район",
       'Дубенський район', 'Тернопільський район', 'Дніпровський район',
       'Пологівський район', 'Вознесенський район', 'Хмільницький район',
       'Уманський район', 'Каховський район', 'Володимирський район',
       'Мукачівський район', 'Коростенський район', 'Черкаський район',
       'Харківський район', 'Звенигородський район',
       'Старобільський район', 'Шосткинський район',
       'Білоцерківський район', 'Богодухівський район',
       'Березівський район', 'Фастівський район', "Куп'янський район",
       'Новоукраїнський район', 'Полтавський район', 'Ковельський район',
       'Шепетівський район', 'Дністровський район', 'Конотопський район',
       'Миколаївський район', 'Болградський район', 'Золотоніський район',
       'Ізюмський район', 'Бердичівський район', 'Бериславський район',
       'м.Харків', 'Голованівський район', 'Камінь-Каширський район',
       'Новоград-Волинський район', 'Синельниківський район', 'м.Житомир',
       'Кропивницький район', 'Могилів-Подільський район',
       'Олександрійський район', 'Бердянський район',
       'Сєвєродонецький район', 'Щастинський район', 'Хустський район',
       'Жмеринський район', 'Вараський район', 'Херсонський район',
       'Хмельницький район', 'м.Кривий Ріг', 'Броварський район',
       'Сумський район', 'Обухівський район', 'Бучанський район',
       'Баштанський район', 'Подільський район', 'Тульчинський район',
       'Стрийський район', 'Кременецький район',
       "Кам'янець-Подільський район", 'Корюківський район',
       'Одеський район', 'Павлоградський район', 'Василівський район',
       'Сватівський район', 'Покровський район',
       'Білгород-Дністровський район', 'Чернігівський район',
       'Ніжинський район', 'Лозівський район', 'м.Запоріжжя',
       'Новомосковський район', 'Миргородський район',
       'Чугуївський район', 'Запорізький район', 'Нікопольський район',
       'Калуський район', 'Охтирський район', 'м.Херсон', 'м.Полтава',
       'м.Суми', 'Бахмутський район', 'Красноградський район',
       'Рахівський район', 'м.Миколаїв', 'Коломийський район',
       'Золочівський район', 'Червоноградський район',
       'Роздільнянський район', 'Роменський район', 'Тячівський район',
       'Маріупольський район', 'Кременчуцький район', 'м.Кременчук',
       'Новгород-Сіверський район', 'Генічеський район', 'м.Дніпро',
       "м.Кам'янське", 'Дрогобицький район', 'м.Чернігів',
       'Косівський район', 'м.Маріуполь', 'Верховинський район', 'Польща',
       'Звягельський район', 'Франція', 'Німеччина', 'Естонія',
       'Норвегія', 'Словаччина', 'Австрія', 'Велика Британія', 'Ірландія',
       'Болгарія', 'Молдова', 'Португалія', 'Азербайджан', 'Угорщина',
       'Італія', 'Туреччина', 'Чехія', 'Бельгія', 'Іспанія', 'Канада',
       'Хорватія', 'Латвія', 'Румунія', 'Литва', 'Грузія', 'США',
       'Фінляндія', 'Швеція', 'Люксембург', 'Нідерланди', 'Данія',
       'Швейцарія', 'Шептицький район', 'Самарівський район',
       'Сіверськодонецький район', 'Словенія', 'Берестинський район',
       'м.Луцьк', 'м.Івано-Франківськ',
       'м.Одеса, Малиновський район міста',
       'м.Львів, Франківський район міста',
       'м.Кропивницький, Подільський район міста', 'м.Рівне',
       'м.Первомайськ', 'м.Берегове', 'м.Вінниця', 'м.Ужгород',
       'м.Київ, Дніпровський район міста',
       'м.Одеса, Приморський район міста',
       'м.Київ, Голосіївський район міста',
       "м.Київ, Солом'янський район міста", 'м.Лиман', 'м.Чернівці',
       'м.Черкаси, Придніпровський район міста',
       'м.Київ, Печерський район міста',
       'м.Київ, Деснянський район міста', 'м.Козятин',
       'м.Київ, Дарницький район міста', 'м.Токмак', 'м.Шостка',
       'м.Канів', 'м.Золотоноша', 'м.Острог', "м.Куп'янськ", 'м.Каховка',
       'м.Бердичів', 'м.Харків, Немишлянський район міста',
       'м.Житомир, Корольовський район міста', 'м.Могилів-Подільський',
       'м.Дубно', 'м.Ладижин', 'м.Лисичанськ', 'м.Новоград-Волинський',
       'м.Рубіжне', 'м.Сєвєродонецьк',
       'м.Житомир, Богунський район міста', 'м.Вараш',
       'м.Кривий Ріг, Покровський район міста', 'м.Березань',
       'м.Біла Церква', 'м.Подільськ', 'м.Малин', 'м.Бориспіль',
       'м.Ірпінь', 'м.Кременець', 'м.Славутич', 'м.Ржищів', 'м.Переяслав',
       "м.Слов'янськ", "м.Кам'янець-Подільський", 'м.Васильків',
       'м.Фастів', 'м.Буча', 'м.Хмільник', 'м.Жмеринка', 'м.Чортків',
       'м.Запоріжжя, Вознесенівський район міста', 'м.Мелітополь',
       'м.Новомосковськ', 'м.Мукачево', 'м.Бровари',
       'м.Запоріжжя, Дніпровський район міста',
       'м.Запоріжжя, Комунарський район міста', 'м.Енергодар', 'м.Чугуїв',
       'м.Нікополь', 'м.Запоріжжя, Олександрівський район міста',
       'м.Запоріжжя, Шевченківський район міста', 'м.Вознесенськ',
       'м.Херсон, Суворовський район міста',
       'м.Полтава, Шевченківський район міста',
       'м.Черкаси, Соснівський район міста',
       'м.Одеса, Київський район міста', 'м.Білгород-Дністровський',
       'м.Запоріжжя, Хортицький район міста',
       'м.Суми, Ковпаківський район міста', 'м.Тернопіль',
       'м.Львів, Шевченківський район міста', 'м.Балта',
       'м.Запоріжжя, Заводський район міста', 'м.Бердянськ',
       'м.Миколаїв, Інгульський район міста',
       'м.Харків, Індустріальний район міста',
       'м.Суми, Зарічний район міста', 'м.Шепетівка', 'м.Селидове',
       'м.Бурштин', 'м.Львів, Галицький район міста', 'м.Володимир',
       'м.Харків, Салтівський район міста',
       'м.Київ, Шевченківський район міста', 'м.Нетішин', 'м.Марганець',
       'м.Київ, Оболонський район міста', 'м.Новий Розділ', 'м.Глухів',
       'м.Олександрія', 'м.Львів, Залізничний район міста', 'м.Покров',
       'м.Полтава, Київський район міста', 'м.Вугледар', 'м.Миргород',
       'м.Горішні Плавні', 'м.Краматорськ',
       'м.Кременчук, Автозаводський район міста', 'м.Хмельницький',
       'м.Червоноград', 'м.Полтава, Подільський район міста', 'м.Гадяч',
       'м.Кременчук, Крюківський район міста', 'м.Ізмаїл',
       'м.Старокостянтинів', 'м.Южне',
       'м.Кривий Ріг, Центрально-Міський район міста', 'м.Славута',
       'м.Дніпро, Шевченківський район міста',
       'м.Кривий Ріг, Металургійний район міста',
       "м.Кам'янське, Заводський район міста", "м.Знам'янка",
       'м.Новогродівка', 'м.Борислав', 'м.Ізюм',
       "м.Харків, Основ'янський район міста",
       'м.Харків, Холодногірський район міста',
       'м.Чернігів, Деснянський район міста', 'м.Коломия',
       'м.Херсон, Дніпровський район міста', 'м.Умань', 'м.Самбір',
       'м.Костянтинівка', 'м.Калуш', 'м.Болехів', 'м.Бахмут', 'м.Хуст',
       'м.Маріуполь, Центральний район міста',
       'м.Маріуполь, Лівобережний район міста',
       'м.Київ, Святошинський район міста', 'м.Павлоград', 'м.Дружківка',
       'м.Кривий Ріг, Тернівський район міста', 'м.Торецьк',
       'м.Маріуполь, Приморський район міста', 'м.Жовті Води',
       'м.Маріуполь, Кальміуський район міста', 'м.Синельникове',
       "м.Кам'янське, Південний район міста",
       "м.Кам'янське, Дніпровський район міста",
       'м.Дніпро, Амур-Нижньодніпровський район міста',
       'м.Дніпро, Чечелівський район міста', 'м.Трускавець',
       'м.Вільногірськ', 'м.Кривий Ріг, Інгулецький район міста',
       'м.Київ, Подільський район міста', 'м.Покровськ', 'м.Авдіївка',
       'м.Дніпро, Новокодацький район міста', 'м.Мирноград',
       'м.Дніпро, Соборний район міста',
       'м.Кривий Ріг, Саксаганський район міста', 'м.Дрогобич',
       'м.Дніпро, Індустріальний район міста', 'м.Нововолинськ',
       'м.Новодністровськ', 'м.Новгород-Сіверський',
       'м.Львів, Личаківський район міста', 'м.Ковель',
       'м.Дніпро, Центральний район міста',
       'м.Кривий Ріг, Довгинцівський район міста',
       'м.Харків, Новобаварський район міста',
       'м.Львів, Сихівський район міста',
       'м.Чернігів, Новозаводський район міста', 'м.Ромни',
       'м.Харків, Слобідський район міста',
       'м.Харків, Київський район міста', 'м.Нова Каховка',
       'м.Одеса, Суворовський район міста', 'м.Очаків', 'м.Обухів',
       'м.Лубни', 'м.Бережани', 'м.Конотоп',
       'м.Харків, Шевченківський район міста', 'м.Біляївка',
       'м.Добропілля', 'м.Теплодар', 'м.Люботин', 'м.Лозова',
       'м.Чорноморськ', 'м.Миколаїв, Заводський район міста',
       'м.Первомайський', 'м.Сміла',
       'м.Миколаїв, Центральний район міста', 'м.Лебедин',
       'м.Южноукраїнськ', 'м.Кропивницький, Фортечний район міста',
       'м.Яремче', 'м.Херсон, Корабельний район міста',
       'м.Дніпро, Самарський район міста',
       'м.Миколаїв, Корабельний район міста', 'м.Коростень', 'м.Тернівка',
       'м.Першотравенськ', 'м.Охтирка', 'м.Прилуки', 'м.Гола Пристань',
       'м.Моршин', 'м.Стрий', 'м.Ніжин', 'м.Світловодськ', 'м.Чоп',
       'м.Ватутіне', 'м.Варшава', 'м.Стокгольм', 'м.Краків', 'м.Брно',
       'м.Кельн', 'м.Лондон', 'м.Гданськ', 'м.Дублін', 'м.Париж',
       'м.Лісабон', 'м.Лейпциг', 'м.Рим', 'м.Брюссель', 'м.Бидгощ',
       'м.Кишинів', 'м.Бухарест', 'м.Мюнхен', 'м.Дебрецен', 'м.Будапешт',
       'м.Копенгаген', 'м.Роттердам', 'м.Берн', 'м.Загреб', 'м.Гамбург',
       'м.Братислава', 'м.Прага', 'м.Мадрид', 'м.Мілан', 'м.Відень',
       'м.Каунас', 'м.Познань', 'м.Франкфурт-на-Майні', 'м.Вроцлав',
       'м.Варна', 'м.Гельсінкі', 'м.Рига', 'м.Клуж-Напока', 'м.Люблін',
       'м.Дьєр', 'м.Анкара', 'м.Таллінн', 'м.Афіни', 'м.Берлін',
       'м.Марсель', 'м.Нью-Йорк', 'м.Бордо', 'м.Тарту', 'м.Тбілісі',
       'м.Барі', 'м.Гетеборг', 'м.Софія', 'м.Банська Бистриця',
       'м.Торонто', 'м.Гронінген', 'м.Люксембург', 'м.Марібор',
       'м.Сакраменто', 'м.Едмонтон', 'м.Орхус', 'м.Звягель', 'м.Единбург',
       'м.Осло', 'м.Валенсія', 'м.Майнц', 'м.Баку', 'м.Бельдібі',
       'м.Мерш', 'м.Детройт', 'м.Абериствіт', "м.Х'юстон", 'м.Монктон',
       'м.Домброва Горнича', 'м.Єна',
       'м.Одеса, Хаджибейський район міста', 'м.Тралі', 'м.Амстердам',
       'м.Одеса, Пересипський район міста', 'м.Чикаго', 'м.Дюссельдорф',
       'м.Пассау', 'м.Нюрнберг', 'с-ще Гастінгс-он-Гадсон', 'м.Алкмар',
       'м.Магдебург', 'м.Самар', 'м.Катовіце', 'м.Златопіль',
       'м.Південноукраїнськ', 'м.Шахтарське', 'м.Південне', 'м.Гаага',
       'м.Воррен', 'м.Домброва-Гурнича', 'м.Стамбул'], dtype=object)

In [81]:
locations_KATOTTG25['areaname_new'] = locations_KATOTTG25.apply(lambda row: row['tername'].split()[0] if ('м.Київ' in row['areaname_new']) else row['areaname_new'], axis=1)

In [82]:
locations_KATOTTG25['areaname_new'] = locations_KATOTTG25.apply(lambda row: row['areaname_new'].split(', ')[0].replace(' район міста','') if (', ' in row['areaname_new']) else row['areaname_new'], axis=1)

In [83]:
diff.remove('інші країни')

In [84]:
diff

{'австрія',
 'азербайджан',
 'бельгія',
 'болгарія',
 'велика британія',
 'грузія',
 'данія',
 'естонія',
 'канада',
 'латвія',
 'литва',
 'люксембург',
 'молдова',
 'норвегія',
 'нідерланди',
 'німеччина',
 'польща',
 'португалія',
 'румунія',
 'словаччина',
 'словенія',
 'сша',
 'туреччина',
 'угорщина',
 'франція',
 'фінляндія',
 'хорватія',
 'чехія',
 'швейцарія',
 'швеція',
 'ірландія',
 'іспанія',
 'італія'}

In [85]:
locations_KATOTTG25

,regname,areaname,tername,region_KOATUU,areaname_new,area_KOATUU,tername_new,code,local_KOATUU,KOATUU,KATOTTG,category,region_KATOTTG,region_new
0,Львівська область,Яворівський район,с.Гусаків,NaN,Яворівський район,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UA46000000000026241,Львівська область
1,Львівська область,Яворівський район,с.Баличі,NaN,Яворівський район,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UA46000000000026241,Львівська область
2,Львівська область,Яворівський район,с.Шегині,NaN,Яворівський район,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UA46000000000026241,Львівська область
3,Львівська область,Яворівський район,с.Волиця,NaN,Яворівський район,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UA46000000000026241,Львівська область
4,Івано-Франківська область,Надвірнянський район,с.Гвізд,NaN,Надвірнянський район,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UA26000000000069363,Івано-Франківська область
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9754,Одеська область,м.Південне,м.Південне,NaN,м.Південне,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UA51000000000030770,Одеська область
9755,Нідерланди,м.Гаага,м.Гаага,NaN,м.Гаага,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OC00000000000000000,Інші країни
9756,США,м.Воррен,м.Воррен,NaN,м.Воррен,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OC00000000000000000,Інші країни
9757,Польща,м.Домброва-Гурнича,м.Домброва-Гурнича,NaN,м.Домброва-Гурнича,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OC00000000000000000,Інші країни
9758,Туреччина,м.Стамбул,м.Стамбул,NaN,м.Стамбул,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OC00000000000000000,Інші країни

In [86]:
locations_KATOTTG25[locations_KATOTTG25.regname.str.lower() == 'інші країни']

,regname,areaname,tername,region_KOATUU,areaname_new,area_KOATUU,tername_new,code,local_KOATUU,KOATUU,KATOTTG,category,region_KATOTTG,region_new
8161,Інші країни,Польща,м.Варшава,NaN,Польща,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OC00000000000000000,Інші країни
8163,Інші країни,Франція,м.Париж,NaN,Франція,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OC00000000000000000,Інші країни
8165,Інші країни,Німеччина,м.Берлін,NaN,Німеччина,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OC00000000000000000,Інші країни
8167,Інші країни,Німеччина,м.Мюнхен,NaN,Німеччина,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OC00000000000000000,Інші країни
8168,Інші країни,Польща,м.Люблін,NaN,Польща,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OC00000000000000000,Інші країни
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9673,Інші країни,м.Гронінген,м.Гронінген,NaN,м.Гронінген,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OC00000000000000000,Інші країни
9674,Інші країни,м.Люксембург,м.Люксембург,NaN,м.Люксембург,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OC00000000000000000,Інші країни
9675,Інші країни,м.Марібор,м.Марібор,NaN,м.Марібор,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OC00000000000000000,Інші країни
9676,Інші країни,м.Сакраменто,м.Сакраменто,NaN,м.Сакраменто,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OC00000000000000000,Інші країни
9677,Інші країни,м.Едмонтон,м.Едмонтон,NaN,м.Едмонтон,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OC00000000000000000,Інші країни

In [87]:
locations_KATOTTG25['areaname_new'] = locations_KATOTTG25.apply(lambda row: row['regname'] if (row['regname'].lower() in diff) else row['areaname_new'], axis=1)
locations_KATOTTG25.tail()

,regname,areaname,tername,region_KOATUU,areaname_new,area_KOATUU,tername_new,code,local_KOATUU,KOATUU,KATOTTG,category,region_KATOTTG,region_new
9754,Одеська область,м.Південне,м.Південне,NaN,м.Південне,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UA51000000000030770,Одеська область
9755,Нідерланди,м.Гаага,м.Гаага,NaN,Нідерланди,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OC00000000000000000,Інші країни
9756,США,м.Воррен,м.Воррен,NaN,США,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OC00000000000000000,Інші країни
9757,Польща,м.Домброва-Гурнича,м.Домброва-Гурнича,NaN,Польща,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OC00000000000000000,Інші країни
9758,Туреччина,м.Стамбул,м.Стамбул,NaN,Туреччина,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OC00000000000000000,Інші країни

In [88]:
code2025[(code2025.first_level == 'UA18000000000041385')&(code2025.category.isin(['P','B', 'M']))]

,first_level,second_level,third_level,fourth_level,additional_level,category,name,name_KOATUU
7092,UA18000000000041385,UA18020000000072859,NaN,NaN,NaN,P,Бердичівський,Бердичівський район
7094,UA18000000000041385,UA18020000000072859,UA18020010000059904,UA18020010010097402,NaN,M,Андрушівка,м.Андрушівка
7120,UA18000000000041385,UA18020000000072859,UA18020030000035625,UA18020030010047029,NaN,M,Бердичів,м.Бердичів
7265,UA18000000000041385,UA18040000000058965,NaN,NaN,NaN,P,Житомирський,Житомирський район
7383,UA18000000000041385,UA18040000000058965,UA18040190000029215,UA18040190010057814,NaN,M,Житомир,м.Житомир
7384,UA18000000000041385,UA18040000000058965,UA18040190000029215,UA18040190010057814,UA18040190010115253,B,Богунський,Богунський
7385,UA18000000000041385,UA18040000000058965,UA18040190000029215,UA18040190010057814,UA18040190010281147,B,Корольовський,Корольовський
7409,UA18000000000041385,UA18040000000058965,UA18040250000068141,UA18040250010085012,NaN,M,Коростишів,м.Коростишів
7681,UA18000000000041385,UA18040000000058965,UA18040450000079138,UA18040450010049683,NaN,M,Радомишль,м.Радомишль
7948,UA18000000000041385,UA18040000000058965,UA18040610000049084,UA18040610010066897,NaN,M,Чуднів,м.Чуднів
7983,UA18000000000041385,UA18060000000021754,NaN,NaN,NaN,P,Коростенський,Коростенський район
8027,UA18000000000041385,UA18060000000021754,UA18060090000061708,UA18060090010074365,NaN,M,Коростень,м.Коростень
8122,UA18000000000041385,UA18060000000021754,UA18060130000061781,UA18060130010010134,NaN,M,Малин,м.Малин
8266,UA18000000000041385,UA18060000000021754,UA18060170000069581,UA18060170010010060,NaN,M,Овруч,м.Овруч
8358,UA18000000000041385,UA18060000000021754,UA18060190000071101,UA18060190010064821,NaN,M,Олевськ,м.Олевськ
8526,UA18000000000041385,UA18080000000016657,NaN,NaN,NaN,P,Звягельський,Звягельський район
8528,UA18000000000041385,UA18080000000016657,UA18080010000090720,UA18080010010059187,NaN,M,Баранівка,м.Баранівка
8752,UA18000000000041385,UA18080000000016657,UA18080150000022496,UA18080150010017476,NaN,M,Звягель,м.Звягель

In [89]:
importlib.reload(renam)

In [90]:
for code in renam.dct_rename_area_2023:
    for name in renam.dct_rename_area_2023[code]:
        locations_KATOTTG25.loc[(locations_KATOTTG25.region_KATOTTG == code) & (locations_KATOTTG25['areaname_new'].str.lower() == name.lower()), 'areaname_new'] = renam.dct_rename_area_2023[code][name]

In [91]:
troubles = {}
for reg in locations_KATOTTG25.region_KATOTTG.unique():
    trouble = set(locations_KATOTTG25[(locations_KATOTTG25.region_KATOTTG == reg)].areaname_new.str.lower())-set(code2025[(code2025.first_level == reg)&(code2025.category.isin(['P','B', 'M']))].name_KOATUU.str.lower())
    if trouble:
        troubles[reg] = trouble
troubles

{'OC00000000000000000': {'австрія',
  'азербайджан',
  'бельгія',
  'болгарія',
  'велика британія',
  'греція',
  'грузія',
  'данія',
  'естонія',
  'канада',
  'латвія',
  'литва',
  'люксембург',
  'молдова',
  'норвегія',
  'нідерланди',
  'німеччина',
  'польща',
  'португалія',
  'румунія',
  'словаччина',
  'словенія',
  'сша',
  'туреччина',
  'угорщина',
  'франція',
  'фінляндія',
  'хорватія',
  'чехія',
  'швейцарія',
  'швеція',
  'ірландія',
  'іспанія',
  'італія'}}

In [92]:
locations_KATOTTG25['area_KATOTTG'] = np.nan
locations_KATOTTG25

,regname,areaname,tername,region_KOATUU,areaname_new,area_KOATUU,tername_new,code,local_KOATUU,KOATUU,KATOTTG,category,region_KATOTTG,region_new,area_KATOTTG
0,Львівська область,Яворівський район,с.Гусаків,NaN,Яворівський район,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UA46000000000026241,Львівська область,NaN
1,Львівська область,Яворівський район,с.Баличі,NaN,Яворівський район,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UA46000000000026241,Львівська область,NaN
2,Львівська область,Яворівський район,с.Шегині,NaN,Яворівський район,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UA46000000000026241,Львівська область,NaN
3,Львівська область,Яворівський район,с.Волиця,NaN,Яворівський район,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UA46000000000026241,Львівська область,NaN
4,Івано-Франківська область,Надвірнянський район,с.Гвізд,NaN,Надвірнянський район,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UA26000000000069363,Івано-Франківська область,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9754,Одеська область,м.Південне,м.Південне,NaN,м.Південне,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UA51000000000030770,Одеська область,NaN
9755,Нідерланди,м.Гаага,м.Гаага,NaN,Нідерланди,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OC00000000000000000,Інші країни,NaN
9756,США,м.Воррен,м.Воррен,NaN,США,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OC00000000000000000,Інші країни,NaN
9757,Польща,м.Домброва-Гурнича,м.Домброва-Гурнича,NaN,Польща,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OC00000000000000000,Інші країни,NaN
9758,Туреччина,м.Стамбул,м.Стамбул,NaN,Туреччина,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OC00000000000000000,Інші країни,NaN

In [93]:
for reg in locations_KATOTTG25['region_KATOTTG'].unique():
    reg_filtered_data = locations_KATOTTG25[locations_KATOTTG25['region_KATOTTG'] == reg]
    
    for area in reg_filtered_data['areaname_new'].str.lower().unique():
        values = code2025.loc[(code2025['first_level'] == reg) & (code2025['name_KOATUU'].str.lower() == area), 'category'].unique()
        if len(values) == 0:
            print(f'Not found for {reg}, {area}: {values}')
        elif len(values) == 1:
            if values[0] in ['P', 'M']:
                value2 = code2025.loc[(code2025['first_level'] == reg) & (code2025['name_KOATUU'].str.lower() == area), 'second_level'].unique()
                
                if len(value2) == 1:
                    locations_KATOTTG25.loc[(locations_KATOTTG25['region_KATOTTG'] == reg) & (locations_KATOTTG25['areaname_new'].str.lower() == area), 'area_KATOTTG'] = value2[0]
                else:
                    print(f"Warning: More than one value for {reg}, {area}, {value2}")
            elif values[0] == 'B':
                value_add = code2025.loc[(code2025['first_level'] == reg) & (code2025['name_KOATUU'].str.lower() == area), 'additional_level'].unique()
                
                if len(value_add) == 1:
                    locations_KATOTTG25.loc[(locations_KATOTTG25['region_KATOTTG'] == reg)  & (locations_KATOTTG25['areaname_new'].str.lower() == area), 'area_KATOTTG'] = value_add[0]
                else:
                    print(f"Warning: More than one value for {reg}, {area}, {value_add}")
        else:
            print(f"Warning: More than one value for {reg}, {area}, {values}")

/var/folders/cz/wq9d8j_11fx3b8pjjbk7z8br0000gn/T/ipykernel_47754/630345596.py:13: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'UA46140000000036328' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  locations_KATOTTG25.loc[(locations_KATOTTG25['region_KATOTTG'] == reg) & (locations_KATOTTG25['areaname_new'].str.lower() == area), 'area_KATOTTG'] = value2[0]

Not found for OC00000000000000000, польща: []
Not found for OC00000000000000000, франція: []
Not found for OC00000000000000000, німеччина: []
Not found for OC00000000000000000, естонія: []
Not found for OC00000000000000000, норвегія: []
Not found for OC00000000000000000, словаччина: []
Not found for OC00000000000000000, австрія: []
Not found for OC00000000000000000, велика британія: []
Not found for OC00000000000000000, ірландія: []
Not found for OC00000000000000000, болгарія: []
Not found for OC00000000000000000, молдова: []
Not found for OC00000000000000000, португалія: []
Not found for OC00000000000000000, азербайджан: []
Not found for OC00000000000000000, угорщина: []
Not found for OC00000000000000000, італія: []
Not found for OC00000000000000000, туреччина: []
Not found for OC00000000000000000, чехія: []
Not found for OC00000000000000000, бельгія: []
Not found for OC00000000000000000, іспанія: []
Not found for OC00000000000000000, канада: []
Not found for OC00000000000000000, хорватія: []
Not found for OC00000000000000000, латвія: []
Not found for OC00000000000000000, румунія: []
Not found for OC00000000000000000, литва: []
Not found for OC00000000000000000, грузія: []
Not found for OC00000000000000000, сша: []
Not found for OC00000000000000000, фінляндія: []
Not found for OC00000000000000000, швеція: []
Not found for OC00000000000000000, люксембург: []
Not found for OC00000000000000000, нідерланди: []
Not found for OC00000000000000000, данія: []
Not found for OC00000000000000000, швейцарія: []
Not found for OC00000000000000000, словенія: []
Not found for OC00000000000000000, греція: []

In [94]:
for name in renam.dct_code_area_2023:
    locations_KATOTTG25.loc[(locations_KATOTTG25.region_KATOTTG == 'OC00000000000000000') & (locations_KATOTTG25['areaname_new'].str.lower() == name.lower()), 'area_KATOTTG'] = renam.dct_code_area_2023[name]

In [95]:
locations_KATOTTG25[locations_KATOTTG25.area_KATOTTG.isna()]

Empty DataFrame
Columns: [regname, areaname, tername, region_KOATUU, areaname_new, area_KOATUU, tername_new, code, local_KOATUU, KOATUU, KATOTTG, category, region_KATOTTG, region_new, area_KATOTTG]
Index: []

# tername 2022

In [96]:
locations_KATOTTG25

,regname,areaname,tername,region_KOATUU,areaname_new,area_KOATUU,tername_new,code,local_KOATUU,KOATUU,KATOTTG,category,region_KATOTTG,region_new,area_KATOTTG
0,Львівська область,Яворівський район,с.Гусаків,NaN,Яворівський район,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UA46000000000026241,Львівська область,UA46140000000036328
1,Львівська область,Яворівський район,с.Баличі,NaN,Яворівський район,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UA46000000000026241,Львівська область,UA46140000000036328
2,Львівська область,Яворівський район,с.Шегині,NaN,Яворівський район,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UA46000000000026241,Львівська область,UA46140000000036328
3,Львівська область,Яворівський район,с.Волиця,NaN,Яворівський район,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UA46000000000026241,Львівська область,UA46140000000036328
4,Івано-Франківська область,Надвірнянський район,с.Гвізд,NaN,Надвірнянський район,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UA26000000000069363,Івано-Франківська область,UA26120000000036058
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9754,Одеська область,м.Південне,м.Південне,NaN,м.Південне,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UA51000000000030770,Одеська область,UA51100000000095786
9755,Нідерланди,м.Гаага,м.Гаага,NaN,Нідерланди,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OC00000000000000000,Інші країни,OC18000000000000000
9756,США,м.Воррен,м.Воррен,NaN,США,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OC00000000000000000,Інші країни,OC26000000000000000
9757,Польща,м.Домброва-Гурнича,м.Домброва-Гурнича,NaN,Польща,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OC00000000000000000,Інші країни,OC21000000000000000
9758,Туреччина,м.Стамбул,м.Стамбул,NaN,Туреччина,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OC00000000000000000,Інші країни,OC27000000000000000

In [97]:
locations_KATOTTG25['tername_new'] = locations_KATOTTG25['tername']
locations_KATOTTG25['tername_new'] = locations_KATOTTG25['tername_new'].str.replace(r'\(.*\)', '', regex = True).str.strip()
locations_KATOTTG25['tername_new'] = locations_KATOTTG25['tername_new'].str.replace(' район міста','')
locations_KATOTTG25['tername_new'] = locations_KATOTTG25['tername_new'].str.replace('смт','с-ще')

In [98]:
locations_KATOTTG25

,regname,areaname,tername,region_KOATUU,areaname_new,area_KOATUU,tername_new,code,local_KOATUU,KOATUU,KATOTTG,category,region_KATOTTG,region_new,area_KATOTTG
0,Львівська область,Яворівський район,с.Гусаків,NaN,Яворівський район,NaN,с.Гусаків,NaN,NaN,NaN,NaN,NaN,UA46000000000026241,Львівська область,UA46140000000036328
1,Львівська область,Яворівський район,с.Баличі,NaN,Яворівський район,NaN,с.Баличі,NaN,NaN,NaN,NaN,NaN,UA46000000000026241,Львівська область,UA46140000000036328
2,Львівська область,Яворівський район,с.Шегині,NaN,Яворівський район,NaN,с.Шегині,NaN,NaN,NaN,NaN,NaN,UA46000000000026241,Львівська область,UA46140000000036328
3,Львівська область,Яворівський район,с.Волиця,NaN,Яворівський район,NaN,с.Волиця,NaN,NaN,NaN,NaN,NaN,UA46000000000026241,Львівська область,UA46140000000036328
4,Івано-Франківська область,Надвірнянський район,с.Гвізд,NaN,Надвірнянський район,NaN,с.Гвізд,NaN,NaN,NaN,NaN,NaN,UA26000000000069363,Івано-Франківська область,UA26120000000036058
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9754,Одеська область,м.Південне,м.Південне,NaN,м.Південне,NaN,м.Південне,NaN,NaN,NaN,NaN,NaN,UA51000000000030770,Одеська область,UA51100000000095786
9755,Нідерланди,м.Гаага,м.Гаага,NaN,Нідерланди,NaN,м.Гаага,NaN,NaN,NaN,NaN,NaN,OC00000000000000000,Інші країни,OC18000000000000000
9756,США,м.Воррен,м.Воррен,NaN,США,NaN,м.Воррен,NaN,NaN,NaN,NaN,NaN,OC00000000000000000,Інші країни,OC26000000000000000
9757,Польща,м.Домброва-Гурнича,м.Домброва-Гурнича,NaN,Польща,NaN,м.Домброва-Гурнича,NaN,NaN,NaN,NaN,NaN,OC00000000000000000,Інші країни,OC21000000000000000
9758,Туреччина,м.Стамбул,м.Стамбул,NaN,Туреччина,NaN,м.Стамбул,NaN,NaN,NaN,NaN,NaN,OC00000000000000000,Інші країни,OC27000000000000000

In [99]:
importlib.reload(renam)

In [100]:
for reg in locations_KATOTTG25.region_KATOTTG.unique():
    troubles = {}
    for area in locations_KATOTTG25[(locations_KATOTTG25.region_KATOTTG == reg)].area_KATOTTG.unique():
        trouble = set(locations_KATOTTG25[(locations_KATOTTG25.region_KATOTTG == reg)&(locations_KATOTTG25.area_KATOTTG == area)].tername_new.str.lower())-set(code2025[(code2025.first_level == reg)&((code2025.second_level == area)|(code2025.additional_level == area))&(code2025.category.isin(['C', 'M', 'T', 'X', 'B']))].name_KOATUU.str.lower())
        if trouble:
            troubles[area] = trouble
    if troubles:
        print(f'{repr(reg)}:{troubles},')

'UA46000000000026241':{'UA46140000000036328': {'с.іорданівка'}, 'UA46060000000042587': {'с-ще рудне', 'с.милошевичі'}, 'UA46100000000023056': {'с-ще славське', 'с.кавське'}, 'UA46040000000069196': {'с.підгородне', 'с.червоне'}, 'UA46120000000057093': {'м.червоноград'}},
'UA26000000000069363':{'UA26080000000050130': {'с.воскресинці', 'с.троїця'}},
'UA07000000000024379':{'UA07080000000034745': {'с-ще олика'}, 'UA07020000000048211': {'с.петрове'}},
'UA51000000000030770':{'UA51100000000095786': {'м.южне', 'с.першотравневе', 'с.гвардійське', 'малиновський', 'суворовський'}, 'UA51080000000061776': {'с.першотравневе', 'с-ще суворове'}, 'UA51020000000097683': {'с.андрієво-іванівка', 'с-ще петрівка'}, 'UA51060000000057808': {'с-ще бородіно', 'с.надеждівка', 'с.малоярославець перший', 'с.холмське', 'с-ще березине', 'с.малоярославець другий', 'с-ще тарутине'}, 'UA51120000000021678': {'с.ткаченка'}, 'UA51040000000032911': {'с.надежда', 'с.миколаївка-новоросійська', 'с.зоря'}, 'UA51140000000094970': {'с.першотравневе', 'с.полезне', 'с.росіянівка'}},
'UA35000000000016081':{'UA35040000000034705': {'с-ще новгородка', 'с.першотравенка', 'с-ще єлизаветградка'}},
'UA48000000000039575':{'UA48080000000082320': {'с.синюхин брід'}, 'UA48040000000011780': {'с-ще токарівка', 'с.царедарівка', 'м.южноукраїнськ', 'с-ще тімірязєвка'}, 'UA48060000000094390': {'с-ще грейгове', 'с-ще первомайське', "с.гур'ївка"}, 'UA48020000000033544': {'с.першотравневе'}},
'UA32000000000030281':{'UA32120000000081110': {'с.красна слобідка', 'с.перше травня'}},
'UA21000000000011690':{'UA21100000000055073': {'с.чертеж', 'с.кибляри'}, 'UA21120000000022889': {'с.довге'}, 'UA21080000000048851': {'с.тисалово', 'с.лопухів'}},
'UA05000000000010236':{'UA05020000000026686': {'с.некрасове'}, 'UA05040000000050292': {'с-ще северинівка'}, 'UA05080000000040234': {'с.дзигівка'}, 'UA05100000000022396': {'с.суворовське'}},
'UA14000000000091971':{'UA14040000000098211': {'с.петрівське', 'с.красна поляна'}, 'UA14160000000061982': {'с.первомайське', 'с-ще желанне'}, 'UA14140000000070889': {'с-ще нікольське'}},
'UA65000000000030969':{'UA65080000000090947': {'с.максима горького'}, 'UA65060000000061947': {'с.князе-григорівка', 'с.первомаївка'}, 'UA65020000000032929': {'с.чкалове'}, 'UA65100000000029736': {'суворовський', 'с.надеждівка'}, 'UA65040000000088940': {'с.чкалове'}},
'UA18000000000041385':{'UA18060000000021754': {'с-ще першотравневе'}, 'UA18080000000016657': {'с-ще першотравенськ', 'м.новоград-волинський'}},
'UA23000000000064947':{'UA23080000000090746': {'с.плодородне', 'с.мордвинівка', 'с.чкалове', 'с-ще переможне'}, 'UA23020000000032289': {"с-ще подспор'є"}, 'UA23060000000070350': {'с.московка', 'комунарський', 'с-ще новотавричеське'}},
'UA12000000000090473':{'UA12060000000022633': {'с.перше травня', 'с.чкаловка', 'с.велика костромка', 'с.надеждівка'}, 'UA12040000000032213': {'с.богдано-надеждівка'}, 'UA12020000000052809': {'м.підгородне', 'с.олександропіль', 'с-ще горького', 'с.перше травня', 'с.партизанське'}, 'UA12140000000011720': {'с-ще іларіонове', 'м.першотравенськ', 'с-ще первомайське'}, 'UA12120000000089862': {"с-ще юр'ївка"}, 'UA12100000000039307': {'с-ще гвардійське', 'с.першотравенка', 'м.новомосковськ'}, 'UA12080000000023578': {"с-ще кам'янське", 'с.першотравневе', 'с-ще зоря', 'с.чкалове'}},
'UA74000000000025378':{'UA74080000000030554': {'с.южне'}, 'UA74040000000028062': {'с-ще світанок'}},
'UA53000000000028050':{'UA53080000000068029': {'с.ряське'}, 'UA53060000000045271': {'с-ще декабристів'}},
'UA71000000000010357':{'UA71080000000036344': {'с.червона слобода'}, 'UA71060000000030325': {'с.дзензелівка'}, 'UA71020000000057292': {'с.іскрене', 'м.ватутіне', 'с-ще катеринопіль'}, 'UA71040000000022553': {'с.кантакузівка'}},
'UA63000000000041885':{'UA63120000000091135': {'с.котляри'}, 'UA63020000000066931': {'с-ще дублянка'}, 'UA63040000000023521': {'с-ще першотравневе'}, 'UA63100000000059237': {'с.новонадеждине', 'м.первомайський', 'с-ще панютине'}, 'UA63140000000096278': {'с.коробочкине', 'с-ще чкаловське', 'с.першотравневе', 'с-ще слобожанське'}, 'UA63060000000053698': {'с-ще красне', 'м.красноград'}},
'UA44000000000018893':{'UA44140000000031142': {'с-ще новопсков', 'с.половинкине', 'с.новорозсош'}, 'UA44120000000092852': {'м.сєвєродонецьк'}},
'UA59000000000057109':{'UA59100000000036457': {'м.дружба'}, 'UA59020000000081905': {'с.лебедєве', "с.юр'єве"}, 'UA59080000000057897': {'с.московський бобрик'}, 'UA59060000000086008': {'с.житне'}},
'OC00000000000000000':{'OC21000000000000000': {'м.бидгощ', 'м.варшава', 'м.краків', 'м.домброва-гурнича', 'м.катовіце', 'м.люблін', 'м.вроцлав', 'м.гданськ', 'м.познань', 'м.домброва горнича'}, 'OC30000000000000000': {'м.бордо', 'м.париж', 'м.марсель'}, 'OC19000000000000000': {'м.мюнхен', 'м.франкфурт-на-майні', 'м.магдебург', 'м.гамбург', 'м.дюссельдорф', 'м.кельн', 'м.пассау', 'м.лейпциг', 'м.берлін', 'м.єна', 'м.нюрнберг', 'м.майнц'}, 'OC12000000000000000': {'м.таллінн', 'м.тарту'}, 'OC20000000000000000': {'м.осло'}, 'OC24000000000000000': {'м.братислава', 'м.банська бистриця'}, 'OC05000000000000000': {'м.відень'}, 'OC08000000000000000': {'м.лондон', 'м.единбург', 'м.абериствіт'}, 'OC01000000000000000': {'м.тралі', 'м.дублін'}, 'OC07000000000000000': {'м.варна', 'м.софія'}, 'OC17000000000000000': {'м.кишинів'}, 'OC22000000000000000': {'м.лісабон'}, 'OC04000000000000000': {'м.баку'}, 'OC28000000000000000': {'м.дьєр', 'м.будапешт', 'м.дебрецен'}, 'OC03000000000000000': {'м.мілан', 'м.барі', 'м.рим'}, 'OC27000000000000000': {'м.бельдібі', 'м.анкара', 'м.стамбул'}, 'OC32000000000000000': {'м.брно', 'м.прага'}, 'OC06000000000000000': {'м.брюссель'}, 'OC02000000000000000': {'м.мадрид', 'м.валенсія'}, 'OC13000000000000000': {'м.торонто', 'м.едмонтон', 'м.монктон'}, 'OC31000000000000000': {'м.загреб'}, 'OC14000000000000000': {'м.рига'}, 'OC23000000000000000': {'м.бухарест', 'м.клуж-напока'}, 'OC15000000000000000': {'м.каунас'}, 'OC10000000000000000': {'м.тбілісі'}, 'OC26000000000000000': {'м.детройт', 'м.чикаго', 'м.нью-йорк', 'с-ще гастінгс-он-гадсон', 'м.сакраменто', "м.х'юстон", 'м.воррен'}, 'OC29000000000000000': {'м.гельсінкі'}, 'OC34000000000000000': {'м.стокгольм', 'м.гетеборг'}, 'OC16000000000000000': {'м.мерш', 'м.люксембург'}, 'OC18000000000000000': {'м.амстердам', 'м.гаага', 'м.роттердам', 'м.алкмар', 'м.гронінген'}, 'OC11000000000000000': {'м.копенгаген', 'м.орхус'}, 'OC33000000000000000': {'м.берн'}, 'OC25000000000000000': {'м.марібор'}, 'OC09000000000000000': {'м.афіни'}},

In [101]:
for region, next_info in renam.dct_rename_tername_2025.items():
    for area, names in next_info.items():
        for old_name, new_name in names.items():
            locations_KATOTTG25.loc[(locations_KATOTTG25.region_KATOTTG == region) & (locations_KATOTTG25.area_KATOTTG== area) & (locations_KATOTTG25.tername_new.str.lower() == old_name), 'tername_new'] = new_name

In [102]:
for reg in locations_KATOTTG25.region_KATOTTG.unique():
    troubles = {}
    for area in locations_KATOTTG25[(locations_KATOTTG25.region_KATOTTG == reg)].area_KATOTTG.unique():
        trouble = set(locations_KATOTTG25[(locations_KATOTTG25.region_KATOTTG == reg)&(locations_KATOTTG25.area_KATOTTG == area)].tername_new.str.lower())-set(code2025[(code2025.first_level == reg)&((code2025.second_level == area)|(code2025.additional_level == area))&(code2025.category.isin(['C', 'M', 'T', 'X', 'B']))].name_KOATUU.str.lower())
        if trouble:
            troubles[area] = trouble
    if troubles:
        print(f'{repr(reg)}:{troubles},')

'OC00000000000000000':{'OC21000000000000000': {'м.бидгощ', 'м.варшава', 'м.краків', 'м.домброва-гурнича', 'м.катовіце', 'м.люблін', 'м.вроцлав', 'м.гданськ', 'м.познань', 'м.домброва горнича'}, 'OC30000000000000000': {'м.бордо', 'м.париж', 'м.марсель'}, 'OC19000000000000000': {'м.мюнхен', 'м.франкфурт-на-майні', 'м.магдебург', 'м.гамбург', 'м.дюссельдорф', 'м.кельн', 'м.пассау', 'м.лейпциг', 'м.берлін', 'м.єна', 'м.нюрнберг', 'м.майнц'}, 'OC12000000000000000': {'м.таллінн', 'м.тарту'}, 'OC20000000000000000': {'м.осло'}, 'OC24000000000000000': {'м.братислава', 'м.банська бистриця'}, 'OC05000000000000000': {'м.відень'}, 'OC08000000000000000': {'м.лондон', 'м.единбург', 'м.абериствіт'}, 'OC01000000000000000': {'м.тралі', 'м.дублін'}, 'OC07000000000000000': {'м.варна', 'м.софія'}, 'OC17000000000000000': {'м.кишинів'}, 'OC22000000000000000': {'м.лісабон'}, 'OC04000000000000000': {'м.баку'}, 'OC28000000000000000': {'м.дьєр', 'м.будапешт', 'м.дебрецен'}, 'OC03000000000000000': {'м.мілан', 'м.барі', 'м.рим'}, 'OC27000000000000000': {'м.бельдібі', 'м.анкара', 'м.стамбул'}, 'OC32000000000000000': {'м.брно', 'м.прага'}, 'OC06000000000000000': {'м.брюссель'}, 'OC02000000000000000': {'м.мадрид', 'м.валенсія'}, 'OC13000000000000000': {'м.торонто', 'м.едмонтон', 'м.монктон'}, 'OC31000000000000000': {'м.загреб'}, 'OC14000000000000000': {'м.рига'}, 'OC23000000000000000': {'м.бухарест', 'м.клуж-напока'}, 'OC15000000000000000': {'м.каунас'}, 'OC10000000000000000': {'м.тбілісі'}, 'OC26000000000000000': {'м.детройт', 'м.чикаго', 'м.нью-йорк', 'с-ще гастінгс-он-гадсон', 'м.сакраменто', "м.х'юстон", 'м.воррен'}, 'OC29000000000000000': {'м.гельсінкі'}, 'OC34000000000000000': {'м.стокгольм', 'м.гетеборг'}, 'OC16000000000000000': {'м.мерш', 'м.люксембург'}, 'OC18000000000000000': {'м.амстердам', 'м.гаага', 'м.роттердам', 'м.алкмар', 'м.гронінген'}, 'OC11000000000000000': {'м.копенгаген', 'м.орхус'}, 'OC33000000000000000': {'м.берн'}, 'OC25000000000000000': {'м.марібор'}, 'OC09000000000000000': {'м.афіни'}},

In [103]:
locations_KATOTTG25['third_level'] = locations_KATOTTG25.loc[:, 'tername'].str.extract(r'\((.*?)\)')
locations_KATOTTG25[locations_KATOTTG25.third_level.notna()]

,regname,areaname,tername,region_KOATUU,areaname_new,area_KOATUU,tername_new,code,local_KOATUU,KOATUU,KATOTTG,category,region_KATOTTG,region_new,area_KATOTTG,third_level
39,Запорізька область,Мелітопольський район,с.Розівка (Якимівська),NaN,Мелітопольський район,NaN,с.Розівка,NaN,NaN,NaN,NaN,NaN,UA23000000000064947,Запорізька область,UA23080000000090746,Якимівська
47,Донецька область,Краматорський район,с.Торське (Лиманська),NaN,Краматорський район,NaN,с.Торське,NaN,NaN,NaN,NaN,NaN,UA14000000000091971,Донецька область,UA14120000000070232,Лиманська
70,Вінницька область,Гайсинський район,с.Яланець (Бершадська),NaN,Гайсинський район,NaN,с.Яланець,NaN,NaN,NaN,NaN,NaN,UA05000000000010236,Вінницька область,UA05040000000050292,Бершадська
71,Вінницька область,Гайсинський район,с.Мар'янівка (Гайсинська),NaN,Гайсинський район,NaN,с.Мар'янівка,NaN,NaN,NaN,NaN,NaN,UA05000000000010236,Вінницька область,UA05040000000050292,Гайсинська
94,Тернопільська область,Чортківський район,с.Озеряни (Борщівська),NaN,Чортківський район,NaN,с.Озеряни,NaN,NaN,NaN,NaN,NaN,UA61000000000060328,Тернопільська область,UA61060000000068766,Борщівська
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9363,Харківська область,Берестинський район,с.Миколаївка (Старовірівська),NaN,Берестинський район,NaN,с.Миколаївка,NaN,NaN,NaN,NaN,NaN,UA63000000000041885,Харківська область,UA63060000000053698,Старовірівська
9378,Харківська область,Берестинський район,с.Шевченкове (Сахновщинська),NaN,Берестинський район,NaN,с.Шевченкове,NaN,NaN,NaN,NaN,NaN,UA63000000000041885,Харківська область,UA63060000000053698,Сахновщинська
9380,Чернігівська область,Ніжинський район,с.Григорівка (Бахмацька),NaN,Ніжинський район,NaN,с.Григорівка,NaN,NaN,NaN,NaN,NaN,UA74000000000025378,Чернігівська область,UA74040000000028062,Бахмацька
9385,Харківська область,Ізюмський район,с.Підвисоке (Борівська),NaN,Ізюмський район,NaN,с.Підвисоке,NaN,NaN,NaN,NaN,NaN,UA63000000000041885,Харківська область,UA63040000000023521,Борівська
9386,Запорізька область,Василівський район,с.Шевченка (Василівська),NaN,Василівський район,NaN,с.Шевченка,NaN,NaN,NaN,NaN,NaN,UA23000000000064947,Запорізька область,UA23040000000067730,Василівська

In [104]:
locations_KATOTTG25['third_level_code'] = locations_KATOTTG25['third_level']

In [105]:
for reg in locations_KATOTTG25['region_KATOTTG'].unique():
    reg_filtered_data = locations_KATOTTG25[(locations_KATOTTG25['region_KATOTTG'] == reg)]
    
    for area in reg_filtered_data['area_KATOTTG'].unique():
        area_filtered_data = reg_filtered_data[(reg_filtered_data['area_KATOTTG'] == area)]
        
        for name in area_filtered_data['third_level'].str.lower().unique():
            values = code2025.loc[
                (code2025['first_level'] == reg) &
                (code2025['second_level'] == area) &
                (code2025['name_KOATUU'].str.lower() == name) &
                (code2025['category'].isin(['H', 'B'])), 'third_level'].unique()
            
            if len(values) == 1:
                locations_KATOTTG25.loc[
                    (locations_KATOTTG25['region_KATOTTG'] == reg) &
                    (locations_KATOTTG25['area_KATOTTG'] == area) &
                    (locations_KATOTTG25['third_level'].str.lower() == name), 'third_level_code'] = values[0]
            elif len(values) > 1:
                codes = locations_KATOTTG25.loc[
                    (locations_KATOTTG25['region_KATOTTG'] == reg) &
                    (locations_KATOTTG25['area_KATOTTG'] == area) &
                    (locations_KATOTTG25['third_level'].str.lower() == name), 'third_level_code'].unique()
                if not all(code.startswith('UA') for code in codes):
                    print(f"Warning: More than one value for {reg}, {area}, {name}, {values}")
            elif len(values) == 0 and isinstance(name, str):
                print(f"No values found for {reg}, {area}, {name}, {values}")

No values found for UA46000000000026241, UA46120000000057093, червоноградська, []
Warning: More than one value for UA51000000000030770, UA51100000000095786, чорноморська, ['UA51100370000040590' 'UA51100390000087217']
No values found for UA51000000000030770, UA51020000000097683, новокальчевська, []
No values found for UA51000000000030770, UA51060000000057808, тарутинська, []
No values found for UA35000000000016081, UA35040000000034705, новгородківська, []
No values found for UA35000000000016081, UA35060000000086172, мар'янівська, []
No values found for UA48000000000039575, UA48040000000011780, южноукраїнська, []
No values found for UA48000000000039575, UA48060000000094390, радсадівська, []
No values found for UA23000000000064947, UA23080000000090746, чкаловська, []
No values found for UA23000000000064947, UA23020000000032289, коларівська, []
No values found for UA12000000000090473, UA12140000000011720, іларіонівська, []
No values found for UA12000000000090473, UA12140000000011720, брагинівська, []
No values found for UA63000000000041885, UA63140000000096278, чкаловська, []
No values found for UA44000000000018893, UA44140000000031142, новопсковська, []
Warning: More than one value for UA59000000000057109, UA59080000000057897, миколаївська, ['UA59080130000022249' 'UA59080150000013842']
No values found for UA68000000000099709, UA68040000000086061, вiйтовецька, []

In [106]:
for region, areas in renam.dct_third_level_fixes_2025.items():
    for area, fixes in areas.items():
        for old_name, payload in fixes.items():
            new_name = payload.get('new', old_name)
            mask = (
                (locations_KATOTTG25.region_KATOTTG == region) &
                (locations_KATOTTG25.area_KATOTTG == area) &
                (locations_KATOTTG25.third_level.str.lower() == old_name)
            )
            locations_KATOTTG25.loc[mask, 'third_level'] = new_name
            if 'code' in payload:
                locations_KATOTTG25.loc[mask, 'third_level_code'] = payload['code']

In [107]:
all(code.startswith('UA') for code in locations_KATOTTG25['third_level_code'].unique() if pd.notna(code))

True

In [149]:
locations_2025 =locations_KATOTTG25

In [151]:
locations_2025['third_level_code'].fillna(-1, inplace=True)

/var/folders/cz/wq9d8j_11fx3b8pjjbk7z8br0000gn/T/ipykernel_47754/2594264417.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  locations_2025['third_level_code'].fillna(-1, inplace=True)

In [152]:
locations_2025

,regname,areaname,tername,region_KOATUU,areaname_new,area_KOATUU,tername_new,code,local_KOATUU,KOATUU,KATOTTG,category,region_KATOTTG,region_new,area_KATOTTG,third_level,third_level_code
0,Львівська область,Яворівський район,с.Гусаків,NaN,Яворівський район,NaN,с.Гусаків,NaN,NaN,4622481601,UA46140090120020894,С,UA46000000000026241,Львівська область,UA46140000000036328,NaN,-1
1,Львівська область,Яворівський район,с.Баличі,NaN,Яворівський район,NaN,с.Баличі,NaN,NaN,4622480401,UA46140090020037836,С,UA46000000000026241,Львівська область,UA46140000000036328,NaN,-1
2,Львівська область,Яворівський район,с.Шегині,NaN,Яворівський район,NaN,с.Шегині,NaN,NaN,4622487901,UA46140090010034963,С,UA46000000000026241,Львівська область,UA46140000000036328,NaN,-1
3,Львівська область,Яворівський район,с.Волиця,NaN,Яворівський район,NaN,с.Волиця,NaN,NaN,4622480901,UA46140090090088787,С,UA46000000000026241,Львівська область,UA46140000000036328,NaN,-1
4,Івано-Франківська область,Надвірнянський район,с.Гвізд,NaN,Надвірнянський район,NaN,с.Гвізд,NaN,NaN,2624081501,UA26120070030065363,С,UA26000000000069363,Івано-Франківська область,UA26120000000036058,NaN,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9754,Одеська область,м.Південне,м.Південне,NaN,м.Південне,NaN,м.Південне,NaN,NaN,5111700000,UA51100410010044384,М,UA51000000000030770,Одеська область,UA51100000000095786,NaN,-1
9755,Нідерланди,м.Гаага,м.Гаага,NaN,Нідерланди,NaN,м.Гаага,NaN,NaN,NaN,OC18030000000000000,NaN,OC00000000000000000,Інші країни,OC18000000000000000,NaN,-1
9756,США,м.Воррен,м.Воррен,NaN,США,NaN,м.Воррен,NaN,NaN,NaN,OC26010000000000000,NaN,OC00000000000000000,Інші країни,OC26000000000000000,NaN,-1
9757,Польща,м.Домброва-Гурнича,м.Домброва-Гурнича,NaN,Польща,NaN,м.Домброва-Гурнича,NaN,NaN,NaN,OC21050000000000000,NaN,OC00000000000000000,Інші країни,OC21000000000000000,NaN,-1
9758,Туреччина,м.Стамбул,м.Стамбул,NaN,Туреччина,NaN,м.Стамбул,NaN,NaN,NaN,OC27030000000000000,NaN,OC00000000000000000,Інші країни,OC27000000000000000,NaN,-1

In [153]:
for name in renam.dct_code_cities_2025:
   locations_2025.loc[(locations_2025.region_KATOTTG == 'OC00000000000000000') & (locations_2025['tername_new'].str.lower() == name.lower()), 'KATOTTG'] = renam.dct_code_cities_2025[name]

In [154]:
locations_2025

,regname,areaname,tername,region_KOATUU,areaname_new,area_KOATUU,tername_new,code,local_KOATUU,KOATUU,KATOTTG,category,region_KATOTTG,region_new,area_KATOTTG,third_level,third_level_code
0,Львівська область,Яворівський район,с.Гусаків,NaN,Яворівський район,NaN,с.Гусаків,NaN,NaN,4622481601,UA46140090120020894,С,UA46000000000026241,Львівська область,UA46140000000036328,NaN,-1
1,Львівська область,Яворівський район,с.Баличі,NaN,Яворівський район,NaN,с.Баличі,NaN,NaN,4622480401,UA46140090020037836,С,UA46000000000026241,Львівська область,UA46140000000036328,NaN,-1
2,Львівська область,Яворівський район,с.Шегині,NaN,Яворівський район,NaN,с.Шегині,NaN,NaN,4622487901,UA46140090010034963,С,UA46000000000026241,Львівська область,UA46140000000036328,NaN,-1
3,Львівська область,Яворівський район,с.Волиця,NaN,Яворівський район,NaN,с.Волиця,NaN,NaN,4622480901,UA46140090090088787,С,UA46000000000026241,Львівська область,UA46140000000036328,NaN,-1
4,Івано-Франківська область,Надвірнянський район,с.Гвізд,NaN,Надвірнянський район,NaN,с.Гвізд,NaN,NaN,2624081501,UA26120070030065363,С,UA26000000000069363,Івано-Франківська область,UA26120000000036058,NaN,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9754,Одеська область,м.Південне,м.Південне,NaN,м.Південне,NaN,м.Південне,NaN,NaN,5111700000,UA51100410010044384,М,UA51000000000030770,Одеська область,UA51100000000095786,NaN,-1
9755,Нідерланди,м.Гаага,м.Гаага,NaN,Нідерланди,NaN,м.Гаага,NaN,NaN,NaN,OC18030000000000000,NaN,OC00000000000000000,Інші країни,OC18000000000000000,NaN,-1
9756,США,м.Воррен,м.Воррен,NaN,США,NaN,м.Воррен,NaN,NaN,NaN,OC26010000000000000,NaN,OC00000000000000000,Інші країни,OC26000000000000000,NaN,-1
9757,Польща,м.Домброва-Гурнича,м.Домброва-Гурнича,NaN,Польща,NaN,м.Домброва-Гурнича,NaN,NaN,NaN,OC21050000000000000,NaN,OC00000000000000000,Інші країни,OC21000000000000000,NaN,-1
9758,Туреччина,м.Стамбул,м.Стамбул,NaN,Туреччина,NaN,м.Стамбул,NaN,NaN,NaN,OC27030000000000000,NaN,OC00000000000000000,Інші країни,OC27000000000000000,NaN,-1

In [155]:
locations_2025[(locations_2025.KATOTTG.isna())&(locations_2025.region_KATOTTG.str.startswith('OC'))][['region_new', 'areaname_new', 'tername_new']].value_counts()

Series([], Name: count, dtype: int64)

In [156]:
# OPTIMIZATION 1: Pre-compute lowercase name_KOATUU once (not in every iteration)
if 'name_KOATUU_lower' not in code2025.columns:
    code2025.loc[:, 'name_KOATUU_lower'] = code2025['name_KOATUU'].str.lower()

# OPTIMIZATION 2: Create filtered subsets once (not in every iteration)
code2025_cmtx = code2025[code2025['category'].isin(['C', 'M', 'T', 'X'])].copy()
code2025_b = code2025[code2025['category'] == 'B'].copy()

# OPTIMIZATION 3: Pre-compute group info to avoid repeated .loc calls
grouped_eie = locations_2025.groupby(['region_KATOTTG', 'area_KATOTTG', 'third_level_code', 'tername_new'])

for (reg, area, third_lev, name), group in grouped_eie:
    # Skip if already has KATOTTG
    if locations_2025.loc[group.index, 'KATOTTG'].notna().any():
        continue
    
    lower_name = name.lower()
    
    if isinstance(third_lev, str):
        # Use pre-filtered dataframes
        mask = (
            (code2025_cmtx['first_level'] == reg) &
            (code2025_cmtx['second_level'] == area) &
            (code2025_cmtx['third_level'] == third_lev) &
            (code2025_cmtx['name_KOATUU_lower'] == lower_name)
        )
        values = code2025_cmtx.loc[mask, 'fourth_level'].unique()
        
        mask_add = (
            (code2025_b['first_level'] == reg) &
            (code2025_b['second_level'] == area) &
            (code2025_b['third_level'] == third_lev) &
            (code2025_b['name_KOATUU_lower'] == lower_name)
        )
        values_add = code2025_b.loc[mask_add, 'additional_level'].unique()
    
    else:
        mask = (
            (code2025_cmtx['first_level'] == reg) &
            (code2025_cmtx['second_level'] == area) &
            (code2025_cmtx['name_KOATUU_lower'] == lower_name)
        )
        values = code2025_cmtx.loc[mask, 'fourth_level'].unique()
        
        if reg != 'UA80000000000093317':
            mask_add = (
                (code2025_b['first_level'] == reg) &
                (code2025_b['second_level'] == area) &
                (code2025_b['name_KOATUU_lower'] == lower_name)
            )
            values_add = code2025_b.loc[mask_add, 'additional_level'].unique()
        else:
            mask_add = (
                (code2025_b['first_level'] == reg) &
                (code2025_b['additional_level'] == area) &
                (code2025_b['name_KOATUU_lower'] == lower_name)
            )
            values_add = code2025_b.loc[mask_add, 'additional_level'].unique()

    if len(values) == 1:
        locations_2025.loc[group.index, 'KATOTTG'] = values[0]
    elif len(values_add) == 1:
        locations_2025.loc[group.index, 'KATOTTG'] = values_add[0]
    else:
        print(reg, area, third_lev, name, values, values_add)

In [115]:
# locations_2025[
#     (locations_2025['region_KATOTTG'] == 'UA63000000000041885') &
#     (locations_2025['area_KATOTTG'] == 'UA63140000000096278') &
#     (locations_2025['tername_new'] == "с.Варварівка")&
#     (locations_2025['KATOTTG'].isna())]

In [157]:
# Manual fixes for tername_new and KATOTTG using dictionary
# якщо є два населених пункти з однаковими назвами, то встановлюємо з більшим населенням
import importlib
importlib.reload(renam)

for region, areas in renam.dct_tername_katottg_fixes_2025.items():
    for area, fixes in areas.items():
        for old_name, payload in fixes.items():
            # If 'new_tername' is present, match against original 'tername' and update both tername_new and KATOTTG
            if 'new_tername' in payload:
                mask = (
                    (locations_KATOTTG25.region_KATOTTG == region) &
                    (locations_KATOTTG25.area_KATOTTG == area) &
                    (locations_KATOTTG25.tername.str.lower() == old_name)
                )
                locations_KATOTTG25.loc[mask, 'tername_new'] = payload['new_tername']
                if 'katottg' in payload:
                    locations_KATOTTG25.loc[mask, 'KATOTTG'] = payload['katottg']
            else:
                # Otherwise, match against 'tername_new' and set KATOTTG
                mask = (
                    (locations_KATOTTG25.region_KATOTTG == region) &
                    (locations_KATOTTG25.area_KATOTTG == area) &
                    (locations_KATOTTG25.tername_new.str.lower() == old_name)
                )
                if 'katottg' in payload:
                    locations_KATOTTG25.loc[mask, 'KATOTTG'] = payload['katottg']

In [158]:
locations_2025

,regname,areaname,tername,region_KOATUU,areaname_new,area_KOATUU,tername_new,code,local_KOATUU,KOATUU,KATOTTG,category,region_KATOTTG,region_new,area_KATOTTG,third_level,third_level_code
0,Львівська область,Яворівський район,с.Гусаків,NaN,Яворівський район,NaN,с.Гусаків,NaN,NaN,4622481601,UA46140090120020894,С,UA46000000000026241,Львівська область,UA46140000000036328,NaN,-1
1,Львівська область,Яворівський район,с.Баличі,NaN,Яворівський район,NaN,с.Баличі,NaN,NaN,4622480401,UA46140090020037836,С,UA46000000000026241,Львівська область,UA46140000000036328,NaN,-1
2,Львівська область,Яворівський район,с.Шегині,NaN,Яворівський район,NaN,с.Шегині,NaN,NaN,4622487901,UA46140090010034963,С,UA46000000000026241,Львівська область,UA46140000000036328,NaN,-1
3,Львівська область,Яворівський район,с.Волиця,NaN,Яворівський район,NaN,с.Волиця,NaN,NaN,4622480901,UA46140090090088787,С,UA46000000000026241,Львівська область,UA46140000000036328,NaN,-1
4,Івано-Франківська область,Надвірнянський район,с.Гвізд,NaN,Надвірнянський район,NaN,с.Гвізд,NaN,NaN,2624081501,UA26120070030065363,С,UA26000000000069363,Івано-Франківська область,UA26120000000036058,NaN,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9754,Одеська область,м.Південне,м.Південне,NaN,м.Південне,NaN,м.Південне,NaN,NaN,5111700000,UA51100410010044384,М,UA51000000000030770,Одеська область,UA51100000000095786,NaN,-1
9755,Нідерланди,м.Гаага,м.Гаага,NaN,Нідерланди,NaN,м.Гаага,NaN,NaN,NaN,OC18030000000000000,NaN,OC00000000000000000,Інші країни,OC18000000000000000,NaN,-1
9756,США,м.Воррен,м.Воррен,NaN,США,NaN,м.Воррен,NaN,NaN,NaN,OC26010000000000000,NaN,OC00000000000000000,Інші країни,OC26000000000000000,NaN,-1
9757,Польща,м.Домброва-Гурнича,м.Домброва-Гурнича,NaN,Польща,NaN,м.Домброва-Гурнича,NaN,NaN,NaN,OC21050000000000000,NaN,OC00000000000000000,Інші країни,OC21000000000000000,NaN,-1
9758,Туреччина,м.Стамбул,м.Стамбул,NaN,Туреччина,NaN,м.Стамбул,NaN,NaN,NaN,OC27030000000000000,NaN,OC00000000000000000,Інші країни,OC27000000000000000,NaN,-1

In [159]:
locations_2025[(locations_2025.KATOTTG.isna())]

Empty DataFrame
Columns: [regname, areaname, tername, region_KOATUU, areaname_new, area_KOATUU, tername_new, code, local_KOATUU, KOATUU, KATOTTG, category, region_KATOTTG, region_new, area_KATOTTG, third_level, third_level_code]
Index: []

In [160]:
locations_2025

,regname,areaname,tername,region_KOATUU,areaname_new,area_KOATUU,tername_new,code,local_KOATUU,KOATUU,KATOTTG,category,region_KATOTTG,region_new,area_KATOTTG,third_level,third_level_code
0,Львівська область,Яворівський район,с.Гусаків,NaN,Яворівський район,NaN,с.Гусаків,NaN,NaN,4622481601,UA46140090120020894,С,UA46000000000026241,Львівська область,UA46140000000036328,NaN,-1
1,Львівська область,Яворівський район,с.Баличі,NaN,Яворівський район,NaN,с.Баличі,NaN,NaN,4622480401,UA46140090020037836,С,UA46000000000026241,Львівська область,UA46140000000036328,NaN,-1
2,Львівська область,Яворівський район,с.Шегині,NaN,Яворівський район,NaN,с.Шегині,NaN,NaN,4622487901,UA46140090010034963,С,UA46000000000026241,Львівська область,UA46140000000036328,NaN,-1
3,Львівська область,Яворівський район,с.Волиця,NaN,Яворівський район,NaN,с.Волиця,NaN,NaN,4622480901,UA46140090090088787,С,UA46000000000026241,Львівська область,UA46140000000036328,NaN,-1
4,Івано-Франківська область,Надвірнянський район,с.Гвізд,NaN,Надвірнянський район,NaN,с.Гвізд,NaN,NaN,2624081501,UA26120070030065363,С,UA26000000000069363,Івано-Франківська область,UA26120000000036058,NaN,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9754,Одеська область,м.Південне,м.Південне,NaN,м.Південне,NaN,м.Південне,NaN,NaN,5111700000,UA51100410010044384,М,UA51000000000030770,Одеська область,UA51100000000095786,NaN,-1
9755,Нідерланди,м.Гаага,м.Гаага,NaN,Нідерланди,NaN,м.Гаага,NaN,NaN,NaN,OC18030000000000000,NaN,OC00000000000000000,Інші країни,OC18000000000000000,NaN,-1
9756,США,м.Воррен,м.Воррен,NaN,США,NaN,м.Воррен,NaN,NaN,NaN,OC26010000000000000,NaN,OC00000000000000000,Інші країни,OC26000000000000000,NaN,-1
9757,Польща,м.Домброва-Гурнича,м.Домброва-Гурнича,NaN,Польща,NaN,м.Домброва-Гурнича,NaN,NaN,NaN,OC21050000000000000,NaN,OC00000000000000000,Інші країни,OC21000000000000000,NaN,-1
9758,Туреччина,м.Стамбул,м.Стамбул,NaN,Туреччина,NaN,м.Стамбул,NaN,NaN,NaN,OC27030000000000000,NaN,OC00000000000000000,Інші країни,OC27000000000000000,NaN,-1

In [161]:
locations_2025['KOATUU'] = locations_2025['KOATUU'].fillna(locations_2025['KATOTTG'].map(comparison.set_index('KATOTTG')['KOATUU']))

In [162]:
locations_2025['category'] = locations_2025['category'].fillna(locations_2025['KATOTTG'].map(comparison.set_index('KATOTTG')['category']))
locations_2025

,regname,areaname,tername,region_KOATUU,areaname_new,area_KOATUU,tername_new,code,local_KOATUU,KOATUU,KATOTTG,category,region_KATOTTG,region_new,area_KATOTTG,third_level,third_level_code
0,Львівська область,Яворівський район,с.Гусаків,NaN,Яворівський район,NaN,с.Гусаків,NaN,NaN,4622481601,UA46140090120020894,С,UA46000000000026241,Львівська область,UA46140000000036328,NaN,-1
1,Львівська область,Яворівський район,с.Баличі,NaN,Яворівський район,NaN,с.Баличі,NaN,NaN,4622480401,UA46140090020037836,С,UA46000000000026241,Львівська область,UA46140000000036328,NaN,-1
2,Львівська область,Яворівський район,с.Шегині,NaN,Яворівський район,NaN,с.Шегині,NaN,NaN,4622487901,UA46140090010034963,С,UA46000000000026241,Львівська область,UA46140000000036328,NaN,-1
3,Львівська область,Яворівський район,с.Волиця,NaN,Яворівський район,NaN,с.Волиця,NaN,NaN,4622480901,UA46140090090088787,С,UA46000000000026241,Львівська область,UA46140000000036328,NaN,-1
4,Івано-Франківська область,Надвірнянський район,с.Гвізд,NaN,Надвірнянський район,NaN,с.Гвізд,NaN,NaN,2624081501,UA26120070030065363,С,UA26000000000069363,Івано-Франківська область,UA26120000000036058,NaN,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9754,Одеська область,м.Південне,м.Південне,NaN,м.Південне,NaN,м.Південне,NaN,NaN,5111700000,UA51100410010044384,М,UA51000000000030770,Одеська область,UA51100000000095786,NaN,-1
9755,Нідерланди,м.Гаага,м.Гаага,NaN,Нідерланди,NaN,м.Гаага,NaN,NaN,NaN,OC18030000000000000,NaN,OC00000000000000000,Інші країни,OC18000000000000000,NaN,-1
9756,США,м.Воррен,м.Воррен,NaN,США,NaN,м.Воррен,NaN,NaN,NaN,OC26010000000000000,NaN,OC00000000000000000,Інші країни,OC26000000000000000,NaN,-1
9757,Польща,м.Домброва-Гурнича,м.Домброва-Гурнича,NaN,Польща,NaN,м.Домброва-Гурнича,NaN,NaN,NaN,OC21050000000000000,NaN,OC00000000000000000,Інші країни,OC21000000000000000,NaN,-1
9758,Туреччина,м.Стамбул,м.Стамбул,NaN,Туреччина,NaN,м.Стамбул,NaN,NaN,NaN,OC27030000000000000,NaN,OC00000000000000000,Інші країни,OC27000000000000000,NaN,-1

In [163]:
locations_2025.category.unique()

array(['С', 'М', 'В', 'Т', 'Х', nan], dtype=object)

In [164]:
all(el.startswith('OC') for el in locations_2025[locations_2025.KOATUU.isna()].KATOTTG.unique())

True

In [165]:
locations_2025 = locations_2025.drop(columns = ['third_level','third_level_code'], axis=1)
locations_2025

,regname,areaname,tername,region_KOATUU,areaname_new,area_KOATUU,tername_new,code,local_KOATUU,KOATUU,KATOTTG,category,region_KATOTTG,region_new,area_KATOTTG
0,Львівська область,Яворівський район,с.Гусаків,NaN,Яворівський район,NaN,с.Гусаків,NaN,NaN,4622481601,UA46140090120020894,С,UA46000000000026241,Львівська область,UA46140000000036328
1,Львівська область,Яворівський район,с.Баличі,NaN,Яворівський район,NaN,с.Баличі,NaN,NaN,4622480401,UA46140090020037836,С,UA46000000000026241,Львівська область,UA46140000000036328
2,Львівська область,Яворівський район,с.Шегині,NaN,Яворівський район,NaN,с.Шегині,NaN,NaN,4622487901,UA46140090010034963,С,UA46000000000026241,Львівська область,UA46140000000036328
3,Львівська область,Яворівський район,с.Волиця,NaN,Яворівський район,NaN,с.Волиця,NaN,NaN,4622480901,UA46140090090088787,С,UA46000000000026241,Львівська область,UA46140000000036328
4,Івано-Франківська область,Надвірнянський район,с.Гвізд,NaN,Надвірнянський район,NaN,с.Гвізд,NaN,NaN,2624081501,UA26120070030065363,С,UA26000000000069363,Івано-Франківська область,UA26120000000036058
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9754,Одеська область,м.Південне,м.Південне,NaN,м.Південне,NaN,м.Південне,NaN,NaN,5111700000,UA51100410010044384,М,UA51000000000030770,Одеська область,UA51100000000095786
9755,Нідерланди,м.Гаага,м.Гаага,NaN,Нідерланди,NaN,м.Гаага,NaN,NaN,NaN,OC18030000000000000,NaN,OC00000000000000000,Інші країни,OC18000000000000000
9756,США,м.Воррен,м.Воррен,NaN,США,NaN,м.Воррен,NaN,NaN,NaN,OC26010000000000000,NaN,OC00000000000000000,Інші країни,OC26000000000000000
9757,Польща,м.Домброва-Гурнича,м.Домброва-Гурнича,NaN,Польща,NaN,м.Домброва-Гурнича,NaN,NaN,NaN,OC21050000000000000,NaN,OC00000000000000000,Інші країни,OC21000000000000000
9758,Туреччина,м.Стамбул,м.Стамбул,NaN,Туреччина,NaN,м.Стамбул,NaN,NaN,NaN,OC27030000000000000,NaN,OC00000000000000000,Інші країни,OC27000000000000000

In [166]:
locations_2025['KOATUU'] = locations_2025.apply(lambda row: '00'+row['KATOTTG'][2:10] if isinstance(row['KOATUU'], float) else row['KOATUU'], axis=1)
locations_2025['region_KOATUU'] = locations_2025['region_KOATUU'].fillna((locations_2025['KOATUU'].str[:2]+'00000000'))
locations_2025['area_KOATUU'] = locations_2025['area_KOATUU'].fillna((locations_2025['KOATUU'].str[:5]+'00000'))
locations_2025['category'] = locations_2025['category'].fillna('abroad')
locations_2025

,regname,areaname,tername,region_KOATUU,areaname_new,area_KOATUU,tername_new,code,local_KOATUU,KOATUU,KATOTTG,category,region_KATOTTG,region_new,area_KATOTTG
0,Львівська область,Яворівський район,с.Гусаків,4600000000,Яворівський район,4622400000,с.Гусаків,NaN,NaN,4622481601,UA46140090120020894,С,UA46000000000026241,Львівська область,UA46140000000036328
1,Львівська область,Яворівський район,с.Баличі,4600000000,Яворівський район,4622400000,с.Баличі,NaN,NaN,4622480401,UA46140090020037836,С,UA46000000000026241,Львівська область,UA46140000000036328
2,Львівська область,Яворівський район,с.Шегині,4600000000,Яворівський район,4622400000,с.Шегині,NaN,NaN,4622487901,UA46140090010034963,С,UA46000000000026241,Львівська область,UA46140000000036328
3,Львівська область,Яворівський район,с.Волиця,4600000000,Яворівський район,4622400000,с.Волиця,NaN,NaN,4622480901,UA46140090090088787,С,UA46000000000026241,Львівська область,UA46140000000036328
4,Івано-Франківська область,Надвірнянський район,с.Гвізд,2600000000,Надвірнянський район,2624000000,с.Гвізд,NaN,NaN,2624081501,UA26120070030065363,С,UA26000000000069363,Івано-Франківська область,UA26120000000036058
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9754,Одеська область,м.Південне,м.Південне,5100000000,м.Південне,5111700000,м.Південне,NaN,NaN,5111700000,UA51100410010044384,М,UA51000000000030770,Одеська область,UA51100000000095786
9755,Нідерланди,м.Гаага,м.Гаага,0000000000,Нідерланди,0018000000,м.Гаага,NaN,NaN,0018030000,OC18030000000000000,abroad,OC00000000000000000,Інші країни,OC18000000000000000
9756,США,м.Воррен,м.Воррен,0000000000,США,0026000000,м.Воррен,NaN,NaN,0026010000,OC26010000000000000,abroad,OC00000000000000000,Інші країни,OC26000000000000000
9757,Польща,м.Домброва-Гурнича,м.Домброва-Гурнича,0000000000,Польща,0021000000,м.Домброва-Гурнича,NaN,NaN,0021050000,OC21050000000000000,abroad,OC00000000000000000,Інші країни,OC21000000000000000
9758,Туреччина,м.Стамбул,м.Стамбул,0000000000,Туреччина,0027000000,м.Стамбул,NaN,NaN,0027030000,OC27030000000000000,abroad,OC00000000000000000,Інші країни,OC27000000000000000

In [167]:
locations_KATOTTG['region_KATOTTG'] =np.nan
locations_KATOTTG['area_KATOTTG'] =np.nan
locations_KATOTTG

,regname,areaname,tername,region_KOATUU,areaname_new,area_KOATUU,tername_new,code,local_KOATUU,KOATUU,KATOTTG,category,region_KATOTTG,area_KATOTTG
0,Запорізька область,Мелітопольський район,с.Терпіння,23,Мелітопольський район,230,с.Терпіння,23230,85101,2323085101,UA23080270010078454,С,NaN,NaN
1,Хмельницька область,Красилівський район,м.Красилів,68,Красилівський район,227,м.Красилів,68227,10100,6822710100,UA68040210010032567,М,NaN,NaN
2,Дніпропетровська область,Петропавлівський район,с.Дмитрівка,12,Петропавлівський район,238,с.Дмитрівка,12238,81501,1223881501,UA12140170040016918,С,NaN,NaN
3,Чернівецька область,м.Чернівці,Шевченківський район міста,73,м.Чернівці,101,м.Чернівці,73101,00000,7310100000,UA73060610010033137,М,NaN,NaN
4,Миколаївська область,Врадіївський район,с.Кумарі,48,Врадіївський район,223,с.Кумарі,48223,83001,4822383001,UA48080050190079797,С,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22692,Житомирська область,Любарський район,с.Великий Браталів,18,Любарський район,231,с.Великий Браталів,18231,55106,1823155106,UA18040290070047586,С,NaN,NaN
22693,Хмельницька область,Ізяславський район,с.Влашанівка,68,Ізяславський район,221,с.Влашанівка,68221,86602,6822186602,UA68060250040099385,С,NaN,NaN
22694,Львівська область,Яворівський район,с.Коханівка,46,Яворівський район,258,с.Коханівка,46258,87803,4625887803,UA46140110360079694,С,NaN,NaN
22695,Житомирська область,Ємільчинський район,с.Бастова Рудня,18,Ємільчинський район,217,с.Бастова Рудня,18217,80403,1821780403,UA18080030040080438,С,NaN,NaN
22696,Чернівецька область,м.Чернівці,м.Чернівці,73,м.Чернівці,101,м.Чернівці,73101,00000,7310100000,UA73060610010033137,М,NaN,NaN

In [168]:
locations_KATOTTG['area_KATOTTG'] = locations_KATOTTG['area_KATOTTG'].fillna(locations_KATOTTG['KATOTTG'].map(code2025[code2025.additional_level.notna()].set_index('additional_level')['second_level']))

In [169]:
locations_KATOTTG['area_KATOTTG'] = locations_KATOTTG['area_KATOTTG'].fillna(locations_KATOTTG['KATOTTG'].map(code2025[(code2025.fourth_level.notna())&(code2025.additional_level.isna())].set_index('fourth_level')['second_level']))
locations_KATOTTG

,regname,areaname,tername,region_KOATUU,areaname_new,area_KOATUU,tername_new,code,local_KOATUU,KOATUU,KATOTTG,category,region_KATOTTG,area_KATOTTG
0,Запорізька область,Мелітопольський район,с.Терпіння,23,Мелітопольський район,230,с.Терпіння,23230,85101,2323085101,UA23080270010078454,С,NaN,UA23080000000090746
1,Хмельницька область,Красилівський район,м.Красилів,68,Красилівський район,227,м.Красилів,68227,10100,6822710100,UA68040210010032567,М,NaN,UA68040000000086061
2,Дніпропетровська область,Петропавлівський район,с.Дмитрівка,12,Петропавлівський район,238,с.Дмитрівка,12238,81501,1223881501,UA12140170040016918,С,NaN,UA12140000000011720
3,Чернівецька область,м.Чернівці,Шевченківський район міста,73,м.Чернівці,101,м.Чернівці,73101,00000,7310100000,UA73060610010033137,М,NaN,UA73060000000061247
4,Миколаївська область,Врадіївський район,с.Кумарі,48,Врадіївський район,223,с.Кумарі,48223,83001,4822383001,UA48080050190079797,С,NaN,UA48080000000082320
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22692,Житомирська область,Любарський район,с.Великий Браталів,18,Любарський район,231,с.Великий Браталів,18231,55106,1823155106,UA18040290070047586,С,NaN,UA18040000000058965
22693,Хмельницька область,Ізяславський район,с.Влашанівка,68,Ізяславський район,221,с.Влашанівка,68221,86602,6822186602,UA68060250040099385,С,NaN,UA68060000000040570
22694,Львівська область,Яворівський район,с.Коханівка,46,Яворівський район,258,с.Коханівка,46258,87803,4625887803,UA46140110360079694,С,NaN,UA46140000000036328
22695,Житомирська область,Ємільчинський район,с.Бастова Рудня,18,Ємільчинський район,217,с.Бастова Рудня,18217,80403,1821780403,UA18080030040080438,С,NaN,UA18080000000016657
22696,Чернівецька область,м.Чернівці,м.Чернівці,73,м.Чернівці,101,м.Чернівці,73101,00000,7310100000,UA73060610010033137,М,NaN,UA73060000000061247

In [170]:
locations_KATOTTG['region_KATOTTG'] = locations_KATOTTG['region_KATOTTG'].fillna(locations_KATOTTG['KATOTTG'].map(code2025[code2025.additional_level.notna()].set_index('additional_level')['first_level']))

In [171]:
locations_KATOTTG['region_KATOTTG'] = locations_KATOTTG['region_KATOTTG'].fillna(locations_KATOTTG['KATOTTG'].map(code2025[(code2025.fourth_level.notna())&(code2025.additional_level.isna())].set_index('fourth_level')['first_level']))
locations_KATOTTG

,regname,areaname,tername,region_KOATUU,areaname_new,area_KOATUU,tername_new,code,local_KOATUU,KOATUU,KATOTTG,category,region_KATOTTG,area_KATOTTG
0,Запорізька область,Мелітопольський район,с.Терпіння,23,Мелітопольський район,230,с.Терпіння,23230,85101,2323085101,UA23080270010078454,С,UA23000000000064947,UA23080000000090746
1,Хмельницька область,Красилівський район,м.Красилів,68,Красилівський район,227,м.Красилів,68227,10100,6822710100,UA68040210010032567,М,UA68000000000099709,UA68040000000086061
2,Дніпропетровська область,Петропавлівський район,с.Дмитрівка,12,Петропавлівський район,238,с.Дмитрівка,12238,81501,1223881501,UA12140170040016918,С,UA12000000000090473,UA12140000000011720
3,Чернівецька область,м.Чернівці,Шевченківський район міста,73,м.Чернівці,101,м.Чернівці,73101,00000,7310100000,UA73060610010033137,М,UA73000000000044923,UA73060000000061247
4,Миколаївська область,Врадіївський район,с.Кумарі,48,Врадіївський район,223,с.Кумарі,48223,83001,4822383001,UA48080050190079797,С,UA48000000000039575,UA48080000000082320
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22692,Житомирська область,Любарський район,с.Великий Браталів,18,Любарський район,231,с.Великий Браталів,18231,55106,1823155106,UA18040290070047586,С,UA18000000000041385,UA18040000000058965
22693,Хмельницька область,Ізяславський район,с.Влашанівка,68,Ізяславський район,221,с.Влашанівка,68221,86602,6822186602,UA68060250040099385,С,UA68000000000099709,UA68060000000040570
22694,Львівська область,Яворівський район,с.Коханівка,46,Яворівський район,258,с.Коханівка,46258,87803,4625887803,UA46140110360079694,С,UA46000000000026241,UA46140000000036328
22695,Житомирська область,Ємільчинський район,с.Бастова Рудня,18,Ємільчинський район,217,с.Бастова Рудня,18217,80403,1821780403,UA18080030040080438,С,UA18000000000041385,UA18080000000016657
22696,Чернівецька область,м.Чернівці,м.Чернівці,73,м.Чернівці,101,м.Чернівці,73101,00000,7310100000,UA73060610010033137,М,UA73000000000044923,UA73060000000061247

In [172]:
locations_KATOTTG['region_KOATUU'] = locations_KATOTTG.apply(lambda row: row['region_KOATUU']+'00000000' , axis=1)
locations_KATOTTG

,regname,areaname,tername,region_KOATUU,areaname_new,area_KOATUU,tername_new,code,local_KOATUU,KOATUU,KATOTTG,category,region_KATOTTG,area_KATOTTG
0,Запорізька область,Мелітопольський район,с.Терпіння,2300000000,Мелітопольський район,230,с.Терпіння,23230,85101,2323085101,UA23080270010078454,С,UA23000000000064947,UA23080000000090746
1,Хмельницька область,Красилівський район,м.Красилів,6800000000,Красилівський район,227,м.Красилів,68227,10100,6822710100,UA68040210010032567,М,UA68000000000099709,UA68040000000086061
2,Дніпропетровська область,Петропавлівський район,с.Дмитрівка,1200000000,Петропавлівський район,238,с.Дмитрівка,12238,81501,1223881501,UA12140170040016918,С,UA12000000000090473,UA12140000000011720
3,Чернівецька область,м.Чернівці,Шевченківський район міста,7300000000,м.Чернівці,101,м.Чернівці,73101,00000,7310100000,UA73060610010033137,М,UA73000000000044923,UA73060000000061247
4,Миколаївська область,Врадіївський район,с.Кумарі,4800000000,Врадіївський район,223,с.Кумарі,48223,83001,4822383001,UA48080050190079797,С,UA48000000000039575,UA48080000000082320
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22692,Житомирська область,Любарський район,с.Великий Браталів,1800000000,Любарський район,231,с.Великий Браталів,18231,55106,1823155106,UA18040290070047586,С,UA18000000000041385,UA18040000000058965
22693,Хмельницька область,Ізяславський район,с.Влашанівка,6800000000,Ізяславський район,221,с.Влашанівка,68221,86602,6822186602,UA68060250040099385,С,UA68000000000099709,UA68060000000040570
22694,Львівська область,Яворівський район,с.Коханівка,4600000000,Яворівський район,258,с.Коханівка,46258,87803,4625887803,UA46140110360079694,С,UA46000000000026241,UA46140000000036328
22695,Житомирська область,Ємільчинський район,с.Бастова Рудня,1800000000,Ємільчинський район,217,с.Бастова Рудня,18217,80403,1821780403,UA18080030040080438,С,UA18000000000041385,UA18080000000016657
22696,Чернівецька область,м.Чернівці,м.Чернівці,7300000000,м.Чернівці,101,м.Чернівці,73101,00000,7310100000,UA73060610010033137,М,UA73000000000044923,UA73060000000061247

In [173]:
locations_KATOTTG['area_KOATUU'] = locations_KATOTTG.apply(lambda row: row['code']+'00000' , axis=1)
locations_KATOTTG

,regname,areaname,tername,region_KOATUU,areaname_new,area_KOATUU,tername_new,code,local_KOATUU,KOATUU,KATOTTG,category,region_KATOTTG,area_KATOTTG
0,Запорізька область,Мелітопольський район,с.Терпіння,2300000000,Мелітопольський район,2323000000,с.Терпіння,23230,85101,2323085101,UA23080270010078454,С,UA23000000000064947,UA23080000000090746
1,Хмельницька область,Красилівський район,м.Красилів,6800000000,Красилівський район,6822700000,м.Красилів,68227,10100,6822710100,UA68040210010032567,М,UA68000000000099709,UA68040000000086061
2,Дніпропетровська область,Петропавлівський район,с.Дмитрівка,1200000000,Петропавлівський район,1223800000,с.Дмитрівка,12238,81501,1223881501,UA12140170040016918,С,UA12000000000090473,UA12140000000011720
3,Чернівецька область,м.Чернівці,Шевченківський район міста,7300000000,м.Чернівці,7310100000,м.Чернівці,73101,00000,7310100000,UA73060610010033137,М,UA73000000000044923,UA73060000000061247
4,Миколаївська область,Врадіївський район,с.Кумарі,4800000000,Врадіївський район,4822300000,с.Кумарі,48223,83001,4822383001,UA48080050190079797,С,UA48000000000039575,UA48080000000082320
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22692,Житомирська область,Любарський район,с.Великий Браталів,1800000000,Любарський район,1823100000,с.Великий Браталів,18231,55106,1823155106,UA18040290070047586,С,UA18000000000041385,UA18040000000058965
22693,Хмельницька область,Ізяславський район,с.Влашанівка,6800000000,Ізяславський район,6822100000,с.Влашанівка,68221,86602,6822186602,UA68060250040099385,С,UA68000000000099709,UA68060000000040570
22694,Львівська область,Яворівський район,с.Коханівка,4600000000,Яворівський район,4625800000,с.Коханівка,46258,87803,4625887803,UA46140110360079694,С,UA46000000000026241,UA46140000000036328
22695,Житомирська область,Ємільчинський район,с.Бастова Рудня,1800000000,Ємільчинський район,1821700000,с.Бастова Рудня,18217,80403,1821780403,UA18080030040080438,С,UA18000000000041385,UA18080000000016657
22696,Чернівецька область,м.Чернівці,м.Чернівці,7300000000,м.Чернівці,7310100000,м.Чернівці,73101,00000,7310100000,UA73060610010033137,М,UA73000000000044923,UA73060000000061247

In [174]:
locations_2025

,regname,areaname,tername,region_KOATUU,areaname_new,area_KOATUU,tername_new,code,local_KOATUU,KOATUU,KATOTTG,category,region_KATOTTG,region_new,area_KATOTTG
0,Львівська область,Яворівський район,с.Гусаків,4600000000,Яворівський район,4622400000,с.Гусаків,NaN,NaN,4622481601,UA46140090120020894,С,UA46000000000026241,Львівська область,UA46140000000036328
1,Львівська область,Яворівський район,с.Баличі,4600000000,Яворівський район,4622400000,с.Баличі,NaN,NaN,4622480401,UA46140090020037836,С,UA46000000000026241,Львівська область,UA46140000000036328
2,Львівська область,Яворівський район,с.Шегині,4600000000,Яворівський район,4622400000,с.Шегині,NaN,NaN,4622487901,UA46140090010034963,С,UA46000000000026241,Львівська область,UA46140000000036328
3,Львівська область,Яворівський район,с.Волиця,4600000000,Яворівський район,4622400000,с.Волиця,NaN,NaN,4622480901,UA46140090090088787,С,UA46000000000026241,Львівська область,UA46140000000036328
4,Івано-Франківська область,Надвірнянський район,с.Гвізд,2600000000,Надвірнянський район,2624000000,с.Гвізд,NaN,NaN,2624081501,UA26120070030065363,С,UA26000000000069363,Івано-Франківська область,UA26120000000036058
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9754,Одеська область,м.Південне,м.Південне,5100000000,м.Південне,5111700000,м.Південне,NaN,NaN,5111700000,UA51100410010044384,М,UA51000000000030770,Одеська область,UA51100000000095786
9755,Нідерланди,м.Гаага,м.Гаага,0000000000,Нідерланди,0018000000,м.Гаага,NaN,NaN,0018030000,OC18030000000000000,abroad,OC00000000000000000,Інші країни,OC18000000000000000
9756,США,м.Воррен,м.Воррен,0000000000,США,0026000000,м.Воррен,NaN,NaN,0026010000,OC26010000000000000,abroad,OC00000000000000000,Інші країни,OC26000000000000000
9757,Польща,м.Домброва-Гурнича,м.Домброва-Гурнича,0000000000,Польща,0021000000,м.Домброва-Гурнича,NaN,NaN,0021050000,OC21050000000000000,abroad,OC00000000000000000,Інші країни,OC21000000000000000
9758,Туреччина,м.Стамбул,м.Стамбул,0000000000,Туреччина,0027000000,м.Стамбул,NaN,NaN,0027030000,OC27030000000000000,abroad,OC00000000000000000,Інші країни,OC27000000000000000

In [175]:
locations_KATOTTG.columns

Index(['regname', 'areaname', 'tername', 'region_KOATUU', 'areaname_new',
       'area_KOATUU', 'tername_new', 'code', 'local_KOATUU', 'KOATUU',
       'KATOTTG', 'category', 'region_KATOTTG', 'area_KATOTTG'],
      dtype='object')

In [176]:
locations_2025 = locations_2025.drop(columns = ['code', 'local_KOATUU'], axis=1)
locations_KATOTTG = locations_KATOTTG.drop(columns = ['code', 'local_KOATUU'], axis=1)
locations_2025

,regname,areaname,tername,region_KOATUU,areaname_new,area_KOATUU,tername_new,KOATUU,KATOTTG,category,region_KATOTTG,region_new,area_KATOTTG
0,Львівська область,Яворівський район,с.Гусаків,4600000000,Яворівський район,4622400000,с.Гусаків,4622481601,UA46140090120020894,С,UA46000000000026241,Львівська область,UA46140000000036328
1,Львівська область,Яворівський район,с.Баличі,4600000000,Яворівський район,4622400000,с.Баличі,4622480401,UA46140090020037836,С,UA46000000000026241,Львівська область,UA46140000000036328
2,Львівська область,Яворівський район,с.Шегині,4600000000,Яворівський район,4622400000,с.Шегині,4622487901,UA46140090010034963,С,UA46000000000026241,Львівська область,UA46140000000036328
3,Львівська область,Яворівський район,с.Волиця,4600000000,Яворівський район,4622400000,с.Волиця,4622480901,UA46140090090088787,С,UA46000000000026241,Львівська область,UA46140000000036328
4,Івано-Франківська область,Надвірнянський район,с.Гвізд,2600000000,Надвірнянський район,2624000000,с.Гвізд,2624081501,UA26120070030065363,С,UA26000000000069363,Івано-Франківська область,UA26120000000036058
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9754,Одеська область,м.Південне,м.Південне,5100000000,м.Південне,5111700000,м.Південне,5111700000,UA51100410010044384,М,UA51000000000030770,Одеська область,UA51100000000095786
9755,Нідерланди,м.Гаага,м.Гаага,0000000000,Нідерланди,0018000000,м.Гаага,0018030000,OC18030000000000000,abroad,OC00000000000000000,Інші країни,OC18000000000000000
9756,США,м.Воррен,м.Воррен,0000000000,США,0026000000,м.Воррен,0026010000,OC26010000000000000,abroad,OC00000000000000000,Інші країни,OC26000000000000000
9757,Польща,м.Домброва-Гурнича,м.Домброва-Гурнича,0000000000,Польща,0021000000,м.Домброва-Гурнича,0021050000,OC21050000000000000,abroad,OC00000000000000000,Інші країни,OC21000000000000000
9758,Туреччина,м.Стамбул,м.Стамбул,0000000000,Туреччина,0027000000,м.Стамбул,0027030000,OC27030000000000000,abroad,OC00000000000000000,Інші країни,OC27000000000000000

In [177]:
locations_KATOTTG.columns

Index(['regname', 'areaname', 'tername', 'region_KOATUU', 'areaname_new',
       'area_KOATUU', 'tername_new', 'KOATUU', 'KATOTTG', 'category',
       'region_KATOTTG', 'area_KATOTTG'],
      dtype='object')

In [181]:
merged_df = pd.merge(locations_KATOTTG[['regname', 'areaname', 'tername', 'KOATUU', 'KATOTTG', 'category']], locations_2025[['regname', 'areaname', 'tername', 'KOATUU', 'KATOTTG', 'category']], on=['regname', 'areaname', 'tername', 'category'], suffixes=('_2021', '_2025'), how='inner')
merged_df

,regname,areaname,tername,KOATUU_2021,KATOTTG_2021,category,KOATUU_2025,KATOTTG_2025
0,Запорізька область,Мелітопольський район,с.Терпіння,2323085101,UA23080270010078454,С,2323085101,UA23080270010078454
1,Одеська область,м.Одеса,Суворовський район міста,5110137600,UA51100270010413116,В,5110137600,UA51100270010413116
2,Львівська область,Яворівський район,смт Івано-Франкове,4625855300,UA46140010010031231,Т,4625855300,UA46140010010031231
3,Одеська область,м.Одеса,Малиновський район міста,5110137300,UA51100270010275193,В,5110137300,UA51100270010275193
4,Львівська область,Дрогобицький район,с.Рихтичі,4621286301,UA46020030280042854,С,4621286301,UA46020030280042854
...,...,...,...,...,...,...,...,...
2310,Сумська область,Роменський район,с.Авраменкове,5924188503,UA59060110020098714,С,5924188503,UA59060110020098714
2311,Київська область,Білоцерківський район,с.Сорокотяги,3220486201,UA32020090130055138,С,3220486201,UA32020090130055138
2312,Рівненська область,Дубенський район,с.Нагоряни,5621688207,UA56040310140028483,С,5621688207,UA56040310140028483
2313,Житомирська область,Новоград-Волинський район,с.Кануни,1824085402,UA18080190040044862,С,1824085402,UA18080190040044862
2314,Чернівецька область,м.Чернівці,м.Чернівці,7310100000,UA73060610010033137,М,7310100000,UA73060610010033137

In [182]:
df1_cols = [col for col in merged_df.columns if col.endswith('_2021')][3:]
df2_cols = [col for col in merged_df.columns if col.endswith('_2025')][3:]


different_rows = merged_df[(merged_df[df1_cols].values != merged_df[df2_cols].values).any(axis=1)]

if not different_rows.empty:
    print("There are rows with equal values in the first 3 columns and different values in other columns.")
    display(different_rows)
else:
    print("No rows found that meet the condition.")

No rows found that meet the condition.

In [209]:
concatenated_df = pd.concat([locations_KATOTTG[['regname', 'areaname', 'tername', 'KOATUU', 'KATOTTG', 'category']], locations_2025[['regname', 'areaname', 'tername', 'KOATUU', 'KATOTTG','category']]], ignore_index=True)
concatenated_df.drop_duplicates(inplace=True)
concatenated_df.reset_index(drop=True, inplace=True)


concatenated_df
# TODO: urban-rural status
# TODO: translation regname ukr_regname, eng_regname,...
# TODO: update dependencies (new location of notebook)

,regname,areaname,tername,KOATUU,KATOTTG,category
0,Запорізька область,Мелітопольський район,с.Терпіння,2323085101,UA23080270010078454,С
1,Хмельницька область,Красилівський район,м.Красилів,6822710100,UA68040210010032567,М
2,Дніпропетровська область,Петропавлівський район,с.Дмитрівка,1223881501,UA12140170040016918,С
3,Чернівецька область,м.Чернівці,Шевченківський район міста,7310100000,UA73060610010033137,М
4,Миколаївська область,Врадіївський район,с.Кумарі,4822383001,UA48080050190079797,С
...,...,...,...,...,...,...
30135,Одеська область,м.Південне,м.Південне,5111700000,UA51100410010044384,М
30136,Нідерланди,м.Гаага,м.Гаага,0018030000,OC18030000000000000,abroad
30137,США,м.Воррен,м.Воррен,0026010000,OC26010000000000000,abroad
30138,Польща,м.Домброва-Гурнича,м.Домброва-Гурнича,0021050000,OC21050000000000000,abroad
30139,Туреччина,м.Стамбул,м.Стамбул,0027030000,OC27030000000000000,abroad

In [210]:
concatenated_df.category.unique()

array(['С', 'М', 'В', 'Т', 'Х', 'abroad'], dtype=object)

In [211]:
dict_category = {'С':'village', 'Х':'settlement', 'Т':'urban village', 'М':'town', 'В':'city'}

for abbr, name in dict_category.items():
    concatenated_df.loc[concatenated_df.category == abbr, 'category'] = name

In [212]:
concatenated_df.category.unique()

array(['village', 'town', 'city', 'urban village', 'settlement', 'abroad'],
      dtype=object)

In [213]:
concatenated_df[concatenated_df.KATOTTG.str.len() !=len('OC13020000000000000')]

Empty DataFrame
Columns: [regname, areaname, tername, KOATUU, KATOTTG, category]
Index: []

In [214]:
concatenated_df

,regname,areaname,tername,KOATUU,KATOTTG,category
0,Запорізька область,Мелітопольський район,с.Терпіння,2323085101,UA23080270010078454,village
1,Хмельницька область,Красилівський район,м.Красилів,6822710100,UA68040210010032567,town
2,Дніпропетровська область,Петропавлівський район,с.Дмитрівка,1223881501,UA12140170040016918,village
3,Чернівецька область,м.Чернівці,Шевченківський район міста,7310100000,UA73060610010033137,town
4,Миколаївська область,Врадіївський район,с.Кумарі,4822383001,UA48080050190079797,village
...,...,...,...,...,...,...
30135,Одеська область,м.Південне,м.Південне,5111700000,UA51100410010044384,town
30136,Нідерланди,м.Гаага,м.Гаага,0018030000,OC18030000000000000,abroad
30137,США,м.Воррен,м.Воррен,0026010000,OC26010000000000000,abroad
30138,Польща,м.Домброва-Гурнича,м.Домброва-Гурнича,0021050000,OC21050000000000000,abroad
30139,Туреччина,м.Стамбул,м.Стамбул,0027030000,OC27030000000000000,abroad

In [215]:
concatenated_df['region_code'] = concatenated_df['KATOTTG'].str[:4]
sorted(concatenated_df.region_code.unique())

['OC01',
 'OC02',
 'OC03',
 'OC04',
 'OC05',
 'OC06',
 'OC07',
 'OC08',
 'OC09',
 'OC10',
 'OC11',
 'OC12',
 'OC13',
 'OC14',
 'OC15',
 'OC16',
 'OC17',
 'OC18',
 'OC19',
 'OC20',
 'OC21',
 'OC22',
 'OC23',
 'OC24',
 'OC25',
 'OC26',
 'OC27',
 'OC28',
 'OC29',
 'OC30',
 'OC31',
 'OC32',
 'OC33',
 'OC34',
 'UA05',
 'UA07',
 'UA12',
 'UA14',
 'UA18',
 'UA21',
 'UA23',
 'UA26',
 'UA32',
 'UA35',
 'UA44',
 'UA46',
 'UA48',
 'UA51',
 'UA53',
 'UA56',
 'UA59',
 'UA61',
 'UA63',
 'UA65',
 'UA68',
 'UA71',
 'UA73',
 'UA74',
 'UA80']

In [216]:
concatenated_df['region_name'] = concatenated_df['region_code'].apply(lambda x: renam.dct_code_regions[x])
concatenated_df

,regname,areaname,tername,KOATUU,KATOTTG,category,region_code,region_name
0,Запорізька область,Мелітопольський район,с.Терпіння,2323085101,UA23080270010078454,village,UA23,Zaporizka
1,Хмельницька область,Красилівський район,м.Красилів,6822710100,UA68040210010032567,town,UA68,Khmelnytska
2,Дніпропетровська область,Петропавлівський район,с.Дмитрівка,1223881501,UA12140170040016918,village,UA12,Dnipropetrovska
3,Чернівецька область,м.Чернівці,Шевченківський район міста,7310100000,UA73060610010033137,town,UA73,Chernivetska
4,Миколаївська область,Врадіївський район,с.Кумарі,4822383001,UA48080050190079797,village,UA48,Mykolaivska
...,...,...,...,...,...,...,...,...
30135,Одеська область,м.Південне,м.Південне,5111700000,UA51100410010044384,town,UA51,Odeska
30136,Нідерланди,м.Гаага,м.Гаага,0018030000,OC18030000000000000,abroad,OC18,Netherlands
30137,США,м.Воррен,м.Воррен,0026010000,OC26010000000000000,abroad,OC26,United States of America
30138,Польща,м.Домброва-Гурнича,м.Домброва-Гурнича,0021050000,OC21050000000000000,abroad,OC21,Poland
30139,Туреччина,м.Стамбул,м.Стамбул,0027030000,OC27030000000000000,abroad,OC27,Turkey

In [217]:
concatenated_df = concatenated_df.drop(columns = ['region_code'], axis=1)
concatenated_df

,regname,areaname,tername,KOATUU,KATOTTG,category,region_name
0,Запорізька область,Мелітопольський район,с.Терпіння,2323085101,UA23080270010078454,village,Zaporizka
1,Хмельницька область,Красилівський район,м.Красилів,6822710100,UA68040210010032567,town,Khmelnytska
2,Дніпропетровська область,Петропавлівський район,с.Дмитрівка,1223881501,UA12140170040016918,village,Dnipropetrovska
3,Чернівецька область,м.Чернівці,Шевченківський район міста,7310100000,UA73060610010033137,town,Chernivetska
4,Миколаївська область,Врадіївський район,с.Кумарі,4822383001,UA48080050190079797,village,Mykolaivska
...,...,...,...,...,...,...,...
30135,Одеська область,м.Південне,м.Південне,5111700000,UA51100410010044384,town,Odeska
30136,Нідерланди,м.Гаага,м.Гаага,0018030000,OC18030000000000000,abroad,Netherlands
30137,США,м.Воррен,м.Воррен,0026010000,OC26010000000000000,abroad,United States of America
30138,Польща,м.Домброва-Гурнича,м.Домброва-Гурнича,0021050000,OC21050000000000000,abroad,Poland
30139,Туреччина,м.Стамбул,м.Стамбул,0027030000,OC27030000000000000,abroad,Turkey

In [220]:
dup_katottg = concatenated_df["KATOTTG"].value_counts()
dup_katottg = dup_katottg[dup_katottg > 1]
dup_katottg

KATOTTG
UA73060610010033137    9
UA23040050010097416    9
UA05020030010063857    9
UA35040210010145346    7
UA35040210010286392    7
                      ..
UA65080050030084440    2
UA14140030160031433    2
UA23040130020042658    2
UA56040090020088413    2
UA63120030020029600    2
Name: count, Length: 9300, dtype: int64

In [222]:
concatenated_df[concatenated_df["KATOTTG"] =='UA23040050010097416']

,regname,areaname,tername,KOATUU,KATOTTG,category,region_name
872,Запорізька область,Великобілозерський район,с.Велика Білозерка(Частина 4 Села) (Червона сі...,2321180101,UA23040050010097416,village,Zaporizka
5484,Запорізька область,Великобілозерський район,с.Велика Білозерка(Частина 1 Села),2321180101,UA23040050010097416,village,Zaporizka
10001,Запорізька область,Великобілозерський район,с.Велика Білозерка(Частина 2 Села) (Новопетрів...,2321180101,UA23040050010097416,village,Zaporizka
15565,Запорізька область,Великобілозерський район,с.Велика Білозерка(Частина 3 Села) (Трудова сі...,2321180101,UA23040050010097416,village,Zaporizka
17249,Запорізька область,Великобілозерський район,с.Велика Білозерка(Частина 4 Села),2321180101,UA23040050010097416,village,Zaporizka
17681,Запорізька область,Великобілозерський район,с.Велика Білозерка(Частина 3 Села),2321180101,UA23040050010097416,village,Zaporizka
18940,Запорізька область,Великобілозерський район,с.Велика Білозерка(Частина 2 Села),2321180101,UA23040050010097416,village,Zaporizka
21796,Запорізька область,Великобілозерський район,с.Велика Білозерка,2321180101,UA23040050010097416,village,Zaporizka
23196,Запорізька область,Василівський район,с.Велика Білозерка,2321180101,UA23040050010097416,village,Zaporizka

In [194]:
concatenated_df.region_name.unique()

array(['Zaporizka', 'Khmelnytska', 'Dnipropetrovska', 'Chernivetska',
       'Mykolaivska', 'Donetska', 'Ternopilska', 'Kirovohradska',
       'Odeska', 'Lvivska', 'Ivano-Frankivska', 'Kharkivska', 'Cherkaska',
       'Volynska', 'Poltavska', 'Rivnenska', 'Vinnytska', 'Chernihivska',
       'Kyivska', 'Khersonska', 'Zhytomyrska', 'Zakarpatska', 'Kyiv',
       'Sumska', 'Luhanska', 'Poland', 'France', 'Germany', 'Estonia',
       'Norway', 'Slovakia', 'Austia', 'United Kingdom', 'Ireland',
       'Bulgaria', 'Moldova', 'Portugal', 'Azerbaijan', 'Hungary',
       'Italy', 'Turkey', 'Czechia', 'Belgium', 'Spain', 'Canada',
       'Croatia', 'Latvia', 'Romania', 'Lithuania', 'Georgia',
       'United States of America', 'Finland', 'Sweden', 'Luxembourg',
       'Netherlands', 'Denmark', 'Switzerland', 'Slovenia', 'Greece'],
      dtype=object)

In [223]:
concatenated_df = concatenated_df.drop_duplicates(subset=['regname', 'areaname', 'tername'], keep='first')

In [224]:
concatenated_df.to_csv('./matching_data/locations.csv', index=False, encoding='utf-8')

In [225]:
concatenated_df_code = concatenated_df.drop(columns = ['regname', 'areaname','tername'], axis=1).drop_duplicates().reset_index(drop=True)
concatenated_df_code

           KOATUU              KATOTTG category      region_name
0      2323085101  UA23080270010078454  village        Zaporizka
1      6822710100  UA68040210010032567     town      Khmelnytska
2      1223881501  UA12140170040016918  village  Dnipropetrovska
3      7310100000  UA73060610010033137     town     Chernivetska
4      4822383001  UA48080050190079797  village      Mykolaivska
...           ...                  ...      ...              ...
18506  0003010000  OC03010000000000000   abroad            Italy
18507  0034010000  OC34010000000000000   abroad           Sweden
18508  0024020000  OC24020000000000000   abroad         Slovakia
18509  0018040000  OC18040000000000000   abroad      Netherlands
18510  0016010000  OC16010000000000000   abroad       Luxembourg

[18511 rows x 4 columns]

In [227]:
concatenated_df_code.to_csv('./final_tables/locations.csv', index=False, encoding='utf-8')