# Form initial table of schools

In [1]:
import pandas as pd
import importlib

from src.changing_koatuu_schools_dict import *
from src.merging_with_id import *
import src.missing_eoedrpou as missed

In [2]:
# load datasets
datasets = {}
for year in range(2016, 2026):
    print(f"EIE {year} Loading...")
    if int(year) >= 2019:
        file_name = f'Odata{year}File.csv'
    else:
        file_name = f'OpenData{year}.csv'
    try:           
        dataset = pd.read_csv(f"../../data_loader/{year}/{file_name}", sep=";", encoding='utf-8', dtype = str)
    except UnicodeDecodeError :
        dataset = pd.read_csv(f"../../data_loader/{year}/{file_name}", sep=";", encoding='Windows 1251', dtype = str)
    datasets.update({year: dataset})
    print("success")

EIE 2016 Loading...
success
EIE 2017 Loading...
success
EIE 2018 Loading...
success
EIE 2019 Loading...
success
EIE 2020 Loading...
success
EIE 2021 Loading...
success
EIE 2022 Loading...
success
EIE 2023 Loading...
success
EIE 2024 Loading...
success
EIE 2025 Loading...
success

In [3]:
for year, dataset in datasets.items():
    dataset.columns = [col.lower() for col in dataset.columns]
    dataset['year'] = year

In [4]:
for year, dataset in datasets.items():
    print(year,":",[col for col in dataset.columns if col.startswith('eo')])

2016 : ['eoname', 'eotypename', 'eoregname', 'eoareaname', 'eotername', 'eoparent']
2017 : ['eoname', 'eotypename', 'eoregname', 'eoareaname', 'eotername', 'eoparent']
2018 : ['eoname', 'eotypename', 'eoregname', 'eoareaname', 'eotername', 'eoparent']
2019 : ['eoname', 'eotypename', 'eoregname', 'eoareaname', 'eotername', 'eoparent']
2020 : ['eoname', 'eotypename', 'eoregname', 'eoareaname', 'eotername', 'eoparent']
2021 : ['eoname', 'eotypename', 'eoregname', 'eoareaname', 'eotername', 'eoparent']
2022 : ['eoname', 'eotypename', 'eoregname', 'eoareaname', 'eotername', 'eoparent']
2023 : ['eoname', 'eotypename', 'eoregname', 'eoareaname', 'eotername', 'eoparent']
2024 : ['eoname', 'eotypename', 'eoregname', 'eoareaname', 'eotername', 'eoparent']
2025 : ['eoname', 'eotypename', 'eoregname', 'eoareaname', 'eotername', 'eoparent', 'eoedrpou', 'eoedeboid']

In [5]:
schools_edrpou = pd.DataFrame()

desired_cols = ['eoname', 'eotypename', 'eoregname', 'eoareaname', 'eotername', 'eoedrpou', 'year']

for year, dataset in datasets.items():
    temp_df = dataset.reindex(columns=desired_cols)
    schools_edrpou = pd.concat([schools_edrpou, temp_df], ignore_index=True)

In [6]:
schools_edrpou

,eoname,eotypename,eoregname,eoareaname,eotername,eoedrpou,year
0,"Терпіннівський колегіум ""Джерело"" Мелітопольсь...",колегіум,Запорізька область,Мелітопольський район,с.Терпіння,NaN,2016
1,Красилівська загальноосвітня школа I-III ступе...,середня загальноосвітня школа,Хмельницька область,Красилівський район,м.Красилів,NaN,2016
2,NaN,NaN,NaN,NaN,NaN,NaN,2016
3,Чернівецька спеціалізована школа І-ІІІ ступені...,спеціалізована школа,Чернівецька область,м.Чернівці,Шевченківський район міста,NaN,2016
4,NaN,NaN,NaN,NaN,NaN,NaN,2016
...,...,...,...,...,...,...,...
3119647,Ліцей № 59 міста Києва,ліцей,м.Київ,м.Київ,Голосіївський район міста,22879323,2025
3119648,"Відокремлений структурний підрозділ ""Політехні...",заклад фахової передвищої освіти,Полтавська область,Кременчуцький район,м.Горішні Плавні,39248242,2025
3119649,NaN,NaN,NaN,NaN,NaN,NaN,2025
3119650,Радісненський ліцей Знам'янської сільської ради,середня загальноосвітня школа,Одеська область,Березівський район,с-ще Радісне,22502305,2025
3119651,"Комунальний заклад ""Міжгірський медичний фахов...",заклад фахової передвищої освіти,Закарпатська область,Хустський район,с-ще Міжгір'я,02010729,2025

In [7]:
schools_edrpou.drop_duplicates(inplace=True)
# When the paricipant graduated in the previous years 
# the corresponding information about school (everything with 'eo') is NaN.
# We drop these rows.
schools_edrpou.dropna(subset=schools_edrpou.columns.difference(['year']), 
                      how = 'all', inplace=True)
schools_edrpou.reset_index(drop=True, inplace=True)
schools_edrpou

,eoname,eotypename,eoregname,eoareaname,eotername,eoedrpou,year
0,"Терпіннівський колегіум ""Джерело"" Мелітопольсь...",колегіум,Запорізька область,Мелітопольський район,с.Терпіння,NaN,2016
1,Красилівська загальноосвітня школа I-III ступе...,середня загальноосвітня школа,Хмельницька область,Красилівський район,м.Красилів,NaN,2016
2,Чернівецька спеціалізована школа І-ІІІ ступені...,спеціалізована школа,Чернівецька область,м.Чернівці,Шевченківський район міста,NaN,2016
3,Загальноосвітня школа I-III ступенів № 6 Дружк...,середня загальноосвітня школа,Донецька область,Донецька область,м.Дружківка,NaN,2016
4,Тернопільська спеціалізована школа І-ІІІ ступе...,спеціалізована школа,Тернопільська область,Тернопільська область,м.Тернопіль,NaN,2016
...,...,...,...,...,...,...,...
99911,"Ходорівське відділення ВСП ""Технічний фаховий ...",заклад фахової передвищої освіти,Львівська область,Стрийський район,м.Ходорів,05393837,2025
99912,"ТОВАРИСТВО З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ ""ПРИВА...",гімназія,м.Київ,м.Київ,Дарницький район міста,42372041,2025
99913,"Гаївська філія ""Початкова школа-заклад дошкіль...",початкова школа,Одеська область,Роздільнянський район,с.Гаївка,25038104,2025
99914,Вільшанська філія Романівського ліцею №2 Роман...,гімназія,Житомирська область,Житомирський район,с.Вільха,45498834,2025
99915,Одеська державна академія будівництва та архіт...,вищий навчальний заклад III-IV рівнів акредитації,Одеська область,м.Одеса,Приморський район міста,02071033,2025

In [8]:
schools_edrpou.year.value_counts()

year
2018    11001
2019    10876
2020    10743
2016    10492
2021    10467
2017    10081
2022     9752
2023     9204
2024     8828
2025     8472
Name: count, dtype: int64

## Add locations identifiers

In [9]:
# load location dictionary for matching names and codes
locations = pd.read_csv('./matching_data/locations.csv', encoding='utf-8', dtype=str)
locations

,regname,areaname,tername,KOATUU,KATOTTG,category,region_name
0,Запорізька область,Мелітопольський район,с.Терпіння,2323085101,UA23080270010078454,village,Zaporizka
1,Хмельницька область,Красилівський район,м.Красилів,6822710100,UA68040210010032567,town,Khmelnytska
2,Дніпропетровська область,Петропавлівський район,с.Дмитрівка,1223881501,UA12140170040016918,village,Dnipropetrovska
3,Чернівецька область,м.Чернівці,Шевченківський район міста,7310100000,UA73060610010033137,town,Chernivetska
4,Миколаївська область,Врадіївський район,с.Кумарі,4822383001,UA48080050190079797,village,Mykolaivska
...,...,...,...,...,...,...,...
30028,Одеська область,м.Південне,м.Південне,5111700000,UA51100410010044384,town,Odeska
30029,Нідерланди,м.Гаага,м.Гаага,0018030000,OC18030000000000000,abroad,Netherlands
30030,США,м.Воррен,м.Воррен,0026010000,OC26010000000000000,abroad,United States of America
30031,Польща,м.Домброва-Гурнича,м.Домброва-Гурнича,0021050000,OC21050000000000000,abroad,Poland
30032,Туреччина,м.Стамбул,м.Стамбул,0027030000,OC27030000000000000,abroad,Turkey

In [10]:
locations.rename(columns={'regname':'eoregname', 'areaname':'eoareaname', 'tername':'eotername'}, inplace=True)
locations.columns

Index(['eoregname', 'eoareaname', 'eotername', 'KOATUU', 'KATOTTG', 'category',
       'region_name'],
      dtype='object')

In [11]:
# add location codifier KOATUU
schools_edrpou_loc = schools_edrpou.merge(locations[['eoregname', 'eoareaname', 'eotername', 'KATOTTG', 'KOATUU', 'category']], on=['eoregname', 'eoareaname', 'eotername'], how='left')
schools_edrpou_loc

,eoname,eotypename,eoregname,eoareaname,eotername,eoedrpou,year,KATOTTG,KOATUU,category
0,"Терпіннівський колегіум ""Джерело"" Мелітопольсь...",колегіум,Запорізька область,Мелітопольський район,с.Терпіння,NaN,2016,UA23080270010078454,2323085101,village
1,Красилівська загальноосвітня школа I-III ступе...,середня загальноосвітня школа,Хмельницька область,Красилівський район,м.Красилів,NaN,2016,UA68040210010032567,6822710100,town
2,Чернівецька спеціалізована школа І-ІІІ ступені...,спеціалізована школа,Чернівецька область,м.Чернівці,Шевченківський район міста,NaN,2016,UA73060610010033137,7310100000,town
3,Загальноосвітня школа I-III ступенів № 6 Дружк...,середня загальноосвітня школа,Донецька область,Донецька область,м.Дружківка,NaN,2016,UA14120030010055241,1411700000,town
4,Тернопільська спеціалізована школа І-ІІІ ступе...,спеціалізована школа,Тернопільська область,Тернопільська область,м.Тернопіль,NaN,2016,UA61040490010069060,6110100000,town
...,...,...,...,...,...,...,...,...,...,...
99911,"Ходорівське відділення ВСП ""Технічний фаховий ...",заклад фахової передвищої освіти,Львівська область,Стрийський район,м.Ходорів,05393837,2025,UA46100270010046817,4621510500,town
99912,"ТОВАРИСТВО З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ ""ПРИВА...",гімназія,м.Київ,м.Київ,Дарницький район міста,42372041,2025,UA80000000000210193,8036300000,city
99913,"Гаївська філія ""Початкова школа-заклад дошкіль...",початкова школа,Одеська область,Роздільнянський район,с.Гаївка,25038104,2025,UA51140150050060575,5123981101,village
99914,Вільшанська філія Романівського ліцею №2 Роман...,гімназія,Житомирська область,Житомирський район,с.Вільха,45498834,2025,UA18040470090069061,1821481001,village
99915,Одеська державна академія будівництва та архіт...,вищий навчальний заклад III-IV рівнів акредитації,Одеська область,м.Одеса,Приморський район міста,02071033,2025,UA51100270010320268,5110137500,city

In [12]:
# check whether there are NaN in KOATUU
schools_edrpou_loc[schools_edrpou_loc.KATOTTG.isna()]

,eoname,eotypename,eoregname,eoareaname,eotername,eoedrpou,year,KATOTTG,KOATUU,category
8484,"Лучицький навчально-виховний комплекс ""Загальн...",навчально-виховний комплекс,Львівська область,Львівська область,Сокальський район,NaN,2016,NaN,NaN,NaN

In [13]:
schools_edrpou_loc[schools_edrpou_loc.KATOTTG.isna()].eoname.unique()[0]

'Лучицький навчально-виховний комплекс "Загальноосвітня школа І-ІІІ ступенів - дитячий садок" Сокальської районної ради Львівської області\r\n'

In [14]:
to_set = schools_edrpou_loc[schools_edrpou_loc.KATOTTG.isna()].eoname.unique()[0]
schools_edrpou_loc.loc[schools_edrpou_loc.eoname == to_set, 'KATOTTG'] = 'UA46120110270041867'
schools_edrpou_loc.loc[schools_edrpou_loc.eoname == to_set, 'KOATUU'] = '4624883201'
schools_edrpou_loc.loc[schools_edrpou_loc.eoname == to_set, 'eoedrpou'] = '23947156'
schools_edrpou_loc.loc[schools_edrpou_loc.eoname == to_set, 'category'] = 'village'
schools_edrpou_loc[schools_edrpou_loc.eoname == to_set]

,eoname,eotypename,eoregname,eoareaname,eotername,eoedrpou,year,KATOTTG,KOATUU,category
8484,"Лучицький навчально-виховний комплекс ""Загальн...",навчально-виховний комплекс,Львівська область,Львівська область,Сокальський район,23947156,2016,UA46120110270041867,4624883201,village

In [15]:
# drop names of region, area and territory
schools_edrpou_loc = schools_edrpou_loc[['eoname', 'eotypename', 'eoedrpou', 'year', 'KATOTTG', 'KOATUU', 'category']]
schools_edrpou_loc.drop_duplicates(inplace=True)
schools_edrpou_loc

/var/folders/cz/wq9d8j_11fx3b8pjjbk7z8br0000gn/T/ipykernel_14298/4162456799.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  schools_edrpou_loc.drop_duplicates(inplace=True)

,eoname,eotypename,eoedrpou,year,KATOTTG,KOATUU,category
0,"Терпіннівський колегіум ""Джерело"" Мелітопольсь...",колегіум,NaN,2016,UA23080270010078454,2323085101,village
1,Красилівська загальноосвітня школа I-III ступе...,середня загальноосвітня школа,NaN,2016,UA68040210010032567,6822710100,town
2,Чернівецька спеціалізована школа І-ІІІ ступені...,спеціалізована школа,NaN,2016,UA73060610010033137,7310100000,town
3,Загальноосвітня школа I-III ступенів № 6 Дружк...,середня загальноосвітня школа,NaN,2016,UA14120030010055241,1411700000,town
4,Тернопільська спеціалізована школа І-ІІІ ступе...,спеціалізована школа,NaN,2016,UA61040490010069060,6110100000,town
...,...,...,...,...,...,...,...
99911,"Ходорівське відділення ВСП ""Технічний фаховий ...",заклад фахової передвищої освіти,05393837,2025,UA46100270010046817,4621510500,town
99912,"ТОВАРИСТВО З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ ""ПРИВА...",гімназія,42372041,2025,UA80000000000210193,8036300000,city
99913,"Гаївська філія ""Початкова школа-заклад дошкіль...",початкова школа,25038104,2025,UA51140150050060575,5123981101,village
99914,Вільшанська філія Романівського ліцею №2 Роман...,гімназія,45498834,2025,UA18040470090069061,1821481001,village
99915,Одеська державна академія будівництва та архіт...,вищий навчальний заклад III-IV рівнів акредитації,02071033,2025,UA51100270010320268,5110137500,city

In [16]:
# check whether there are duplicates by name and location
schools_edrpou_loc[schools_edrpou_loc.duplicated(subset=['eoname', 'year', 'KATOTTG'], keep=False)]

,eoname,eotypename,eoedrpou,year,KATOTTG,KOATUU,category
37720,ДОНЕЦЬКЕ ВИЩЕ УЧИЛИЩЕ ОЛІМПІЙСЬКОГО РЕЗЕРВУ ІМ...,заклад вищої освіти,NaN,2019,UA14020010010059145,1410300000,town
38984,ДОНЕЦЬКЕ ВИЩЕ УЧИЛИЩЕ ОЛІМПІЙСЬКОГО РЕЗЕРВУ ІМ...,спеціалізована школа-інтернат,NaN,2019,UA14020010010059145,1410300000,town
73682,"Відокремлений структурний підрозділ ""Олімпійсь...",середня загальноосвітня школа,NaN,2023,UA80000000000336424,8036400000,city
77615,"Відокремлений структурний підрозділ ""Олімпійсь...",заклад фахової передвищої освіти,NaN,2023,UA80000000000336424,8036400000,city
81213,Данилівський заклад загальної середньої освіти...,середня загальноосвітня школа,NaN,2023,UA21120250040023498,2125382601,village
81661,Данилівський заклад загальної середньої освіти...,навчально-виховний комплекс,NaN,2023,UA21120250040023498,2125382601,village
86412,"Комунальний заклад фахової передвищої освіти ""...",заклад фахової передвищої освіти,NaN,2024,UA48060150010139573,4810136300,city
88345,Ставищенський ліцей №1 Ставищенської селищної ...,ліцей,NaN,2024,UA32020170010055237,3224255100,urban village
88743,Ставищенський ліцей №1 Ставищенської селищної ...,заклад професійної (професійно-технічної) освіти,NaN,2024,UA32020170010055237,3224255100,urban village
89636,"Комунальний заклад фахової передвищої освіти ""...",навчально-виховний комплекс,NaN,2024,UA48060150010139573,4810136300,city
93418,Лохвицька гімназія №1 Лохвицької міської ради ...,середня загальноосвітня школа,23548522,2025,UA53060190010016735,5322610100,town
93523,"Комунальний заклад фахової передвищої освіти ""...",заклад фахової передвищої освіти,22440981,2025,UA48060150010139573,4810136300,city
93880,"Комунальний заклад фахової передвищої освіти ""...",навчально-виховний комплекс,22440981,2025,UA48060150010139573,4810136300,city
93891,Ставищенський ліцей №1 Ставищенської селищної ...,ліцей,25668012,2025,UA32020170010055237,3224255100,urban village
93950,Комунальний заклад вищої освіти Львівської обл...,заклад вищої освіти,01989036,2025,UA46060250010121390,4610136600,city
95511,Комунальний заклад вищої освіти Львівської обл...,вищий навчальний заклад III-IV рівнів акредитації,01989036,2025,UA46060250010121390,4610136600,city
95612,Ставищенський ліцей №1 Ставищенської селищної ...,заклад професійної (професійно-технічної) освіти,25668012,2025,UA32020170010055237,3224255100,urban village
99767,Лохвицька гімназія №1 Лохвицької міської ради ...,заклад професійної (професійно-технічної) освіти,23548522,2025,UA53060190010016735,5322610100,town

In [17]:
schools_edrpou_loc[schools_edrpou_loc.duplicated(subset=['eoname', 'year', 'KATOTTG'], keep=False)].eoname.unique()

array(['ДОНЕЦЬКЕ ВИЩЕ УЧИЛИЩЕ ОЛІМПІЙСЬКОГО РЕЗЕРВУ ІМ.С.БУБКИ',
       'Відокремлений структурний підрозділ "Олімпійський фаховий коледж імені Івана Піддубного Національного університету фізичного виховання і спорту України"',
       'Данилівський заклад загальної середньої освіти І-ІІІ ступенів Хустської міської ради Закарпатської області',
       'Комунальний заклад фахової передвищої освіти "Миколаївський фаховий коледж фізичної культури" Миколаївської обласної ради',
       'Ставищенський ліцей №1 Ставищенської селищної ради Білоцерківського району Київської області',
       'Лохвицька гімназія №1 Лохвицької міської ради Полтавської області',
       'Комунальний заклад вищої освіти Львівської обласної ради "Львівська медична академія імені Андрея Крупинського"'],
      dtype=object)

In [18]:
schools_edrpou_loc.loc[schools_edrpou_loc.eoname=='ДОНЕЦЬКЕ ВИЩЕ УЧИЛИЩЕ ОЛІМПІЙСЬКОГО РЕЗЕРВУ ІМ.С.БУБКИ', 'eotypename'] = 'заклад фахової передвищої освіти'
schools_edrpou_loc.loc[schools_edrpou_loc.eoname=='Відокремлений структурний підрозділ "Олімпійський фаховий коледж імені Івана Піддубного Національного університету фізичного виховання і спорту України"', 'eotypename'] = 'заклад фахової передвищої освіти'
schools_edrpou_loc.loc[schools_edrpou_loc.eoname=='Данилівський заклад загальної середньої освіти І-ІІІ ступенів Хустської міської ради Закарпатської області', 'eotypename'] = 'навчально-виховний комплекс'
schools_edrpou_loc.loc[schools_edrpou_loc.eoname=='Комунальний заклад фахової передвищої освіти "Миколаївський фаховий коледж фізичної культури" Миколаївської обласної ради', 'eotypename'] = 'заклад фахової передвищої освіти'
schools_edrpou_loc.loc[schools_edrpou_loc.eoname=='Ставищенський ліцей №1 Ставищенської селищної ради Білоцерківського району Київської області', 'eotypename'] = 'ліцей'
schools_edrpou_loc.loc[schools_edrpou_loc.eoname=='Лохвицька гімназія №1 Лохвицької міської ради Полтавської області', 'eotypename'] = 'гімназія'
schools_edrpou_loc.loc[schools_edrpou_loc.eoname=='Комунальний заклад вищої освіти Львівської обласної ради "Львівська медична академія імені Андрея Крупинського"', 'eotypename'] = 'заклад вищої освіти'

In [19]:
schools_edrpou_loc.drop_duplicates(inplace=True)

/var/folders/cz/wq9d8j_11fx3b8pjjbk7z8br0000gn/T/ipykernel_14298/55812111.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  schools_edrpou_loc.drop_duplicates(inplace=True)

In [20]:
schools_edrpou_loc.shape

(99907, 7)

In [21]:
# check whether there are duplicates by name and location
schools_edrpou_loc[schools_edrpou_loc.duplicated(subset=['eoname', 'year', 'KATOTTG'], keep=False)]

Empty DataFrame
Columns: [eoname, eotypename, eoedrpou, year, KATOTTG, KOATUU, category]
Index: []

In [22]:
# Скільки значень заповнилось
total = schools_edrpou_loc.shape[0]
filled = schools_edrpou_loc['eoedrpou'].notna().sum()
print(f"Filled: {filled} out of {total}  or {round(filled/total*100)}%")

Filled: 8468 out of 99907  or 8%

In [23]:
schools_edrpou_loc[schools_edrpou_loc['eoedrpou'].isna()].year.value_counts()

year
2018    11001
2019    10875
2020    10743
2016    10491
2021    10467
2017    10081
2022     9752
2023     9202
2024     8826
2025        1
Name: count, dtype: int64

In [24]:
schools_edrpou_loc[(schools_edrpou_loc['eoedrpou'].isna())&(schools_edrpou_loc['year'] == 2025)]

,eoname,eotypename,eoedrpou,year,KATOTTG,KOATUU,category
94273,Миколаївський юридичний фаховий коледж Націона...,заклад вищої освіти,NaN,2025,UA48060150010139573,4810136300,city

In [25]:
schools_edrpou_loc[(schools_edrpou_loc['eoedrpou'].isna())&(schools_edrpou_loc['year'] == 2025)].eoname.unique()

array(['Миколаївський юридичний фаховий коледж Національного університету "Одеська юридична академія"'],
      dtype=object)

In [26]:
schools_edrpou_loc.loc[(schools_edrpou_loc['eoedrpou'].isna())&(schools_edrpou_loc['year'] == 2025),'eoedrpou' ]='20933314_'

In [27]:
schools_edrpou_loc[schools_edrpou_loc.eoedrpou.str.len() < 8]

Empty DataFrame
Columns: [eoname, eotypename, eoedrpou, year, KATOTTG, KOATUU, category]
Index: []

## Fill from 2025 edrpou

In [28]:
create_id(schools_edrpou_loc, 'eoname', 'id')

/Users/scipyguru/Library/Mobile Documents/com~apple~CloudDocs/Documents_New/ZNO-Dataset/notebooks/tables_creation/src/merging_with_id.py:178: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset.loc[:,id_] = dataset[attr]
/Users/scipyguru/Library/Mobile Documents/com~apple~CloudDocs/Documents_New/ZNO-Dataset/notebooks/tables_creation/src/merging_with_id.py:193: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset[id_] = dataset[id_].apply(del_rayon)
/Users/scipyguru/Library/Mobile Documents/com~apple~CloudDocs/Documents_New/ZNO-Dataset/notebooks/tables_creation/src/merging_with_id.py:206: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset[id_] = dataset[id_].apply(lambda s: s if (len(s) and s[-1].isdigit()) else s[:-1])

,eoname,eotypename,eoedrpou,year,KATOTTG,KOATUU,category,id
0,"Терпіннівський колегіум ""Джерело"" Мелітопольсь...",колегіум,NaN,2016,UA23080270010078454,2323085101,village,терпнвськийколегумджереломелтопольська
1,Красилівська загальноосвітня школа I-III ступе...,середня загальноосвітня школа,NaN,2016,UA68040210010032567,6822710100,town,красилвськазагальноосвтняшкола3ступ3
2,Чернівецька спеціалізована школа І-ІІІ ступені...,спеціалізована школа,NaN,2016,UA73060610010033137,7310100000,town,чернвецькаспецалзованашкола3ступфзикоматематич...
3,Загальноосвітня школа I-III ступенів № 6 Дружк...,середня загальноосвітня школа,NaN,2016,UA14120030010055241,1411700000,town,загальноосвтняшкола3ступ6дружквська
4,Тернопільська спеціалізована школа І-ІІІ ступе...,спеціалізована школа,NaN,2016,UA61040490010069060,6110100000,town,тернопльськаспецалзованашкола3ступ3зпоглиблени...
...,...,...,...,...,...,...,...,...
99911,"Ходорівське відділення ВСП ""Технічний фаховий ...",заклад фахової передвищої освіти,05393837,2025,UA46100270010046817,4621510500,town,ходорвськевддленятехнчнийколеджнацональногоунв...
99912,"ТОВАРИСТВО З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ ""ПРИВА...",гімназія,42372041,2025,UA80000000000210193,8036300000,city,приватнийзакладосвтигмназякларсверб
99913,"Гаївська філія ""Початкова школа-заклад дошкіль...",початкова школа,25038104,2025,UA51140150050060575,5123981101,village,гавськафляпочатковашколазакладдошкльнаосвтияко...
99914,Вільшанська філія Романівського ліцею №2 Роман...,гімназія,45498834,2025,UA18040470090069061,1821481001,village,вльшанськафляроманвськоголцею2романвська
99915,Одеська державна академія будівництва та архіт...,вищий навчальний заклад III-IV рівнів акредитації,02071033,2025,UA51100270010320268,5110137500,city,одеськадержавнаакадемябудвництватаархтектур

In [29]:
assert (
    schools_edrpou_loc
    .dropna(subset=['eoedrpou'])
    .groupby(['id', 'KATOTTG'])['eoedrpou']
    .nunique()
    .le(1)
    .all()
)

In [30]:
schools_edrpou_loc['eoedrpou'] = schools_edrpou_loc.groupby(['id', 'KATOTTG'])['eoedrpou'].transform(
    lambda x: x.ffill().bfill()
)

/var/folders/cz/wq9d8j_11fx3b8pjjbk7z8br0000gn/T/ipykernel_14298/1122107747.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  lambda x: x.ffill().bfill()
/var/folders/cz/wq9d8j_11fx3b8pjjbk7z8br0000gn/T/ipykernel_14298/1122107747.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  schools_edrpou_loc['eoedrpou'] = schools_edrpou_loc.groupby(['id', 'KATOTTG'])['eoedrpou'].transform(

In [31]:
filled =schools_edrpou_loc['eoedrpou'].notna().sum()
print(f"Filled: {filled} out of {total}  or {round(filled/total*100)}%")

Filled: 35164 out of 99907  or 35%

In [32]:
schools_edrpou_loc[schools_edrpou_loc['eoedrpou'].isna()].year.value_counts()

year
2016    9902
2018    9858
2017    9407
2019    9369
2020    8920
2021    7833
2022    5420
2023    2682
2024    1352
Name: count, dtype: int64

In [33]:
schools_edrpou_loc[schools_edrpou_loc.eoedrpou.str.len() < 8]

Empty DataFrame
Columns: [eoname, eotypename, eoedrpou, year, KATOTTG, KOATUU, category, id]
Index: []

# Schools 2026

In [34]:
schools_2026 =  pd.read_excel('./school_data/schools_data_gov_ua_2026_02.xlsx', dtype='str')
schools_2026

,university_name,edrpou,university_type_name,education_type_name,university_level,location_type,university_financing_type_name,post_index,koatuu_id,language,...,university_address,post_index_u,koatuu_id_u,region_name_u,koatuu_name_u,university_address_u,university_phone,university_email,university_site,university_director_fio
0,Бердянська загальноосвітня школа І-ІІІ ступені...,26338802,заклад середньої освіти,загальносвітня школа,I-III,МІСТО,комунальна,71117,2310400000,! not applicable,...,"вул. Херсонська, 1/90,",71117,2310400000,Запорізька область,Бердянськ,"вул. Херсонська, 1/90,","(06153)77-270, (06153)78-270",brd-school7@ukr.net,http://brd-school7.ucoz.ua,! not applicable
1,"Первомайський навчально виховний комплекс ""Заг...",25992635,заклад середньої освіти,навчально-виховний комплекс (об'єднання),I-III,МІСТО,комунальна,55202,4810400000,! not applicable,...,"вул. Коротченко, 18-а",55202,4810400000,Миколаївська область,Первомайськ,"вул. Коротченко, 18-а",0516174548,NVK-15@i.ua,NaN,! not applicable
2,Загальноосвітня школа І-ІІІ ступенів №9 Мирног...,25689474,заклад середньої освіти,загальносвітня школа,I-III,МІСТО,комунальна,85321,1411300000,! not applicable,...,"мрн. Західниий, 4а",85321,1411300000,Донецька область,Мирноград,"мрн. Західниий, 4а",(06239)64352,osh9mirnograd@gmail.com,http://osh9.at.ua,! not applicable
3,Заклад загальної середньої освіти І-ІІ ступені...,32624238,заклад середньої освіти,ліцей,I-III,МІСТО,комунальна,85323,1411300000,! not applicable,...,"вул. Карбишева, 2",85323,1411300000,Донецька область,Мирноград,"вул. Карбишева, 2",(06239)64541,dimlicei04@ukr.net,http://lyceum0918.wixsite.com/harmony/,! not applicable
4,"Комунальний заклад ""Середня загальноосвітня шк...",23370351,заклад середньої освіти,загальносвітня школа,I-III,МІСТО,комунальна,51900,1210436900,! not applicable,...,"вул. Братська, 4",51900,1210436900,Дніпропетровська область,"Кам'янське, Заводський район","вул. Братська, 4",(05692)33148,school23drdn@ukr.net,http://shkola232016.ucoz.site/,! not applicable
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15256,Приватний заклад загальної середньої освіти ``...,42988398,заклад середньої освіти,загальносвітня школа,II-III,МІСТО,приватна,NaN,4610137500,! not applicable,...,"ал. Замарстинівська, 83а",NaN,4610137500,Львівська область,"Львів, Шевченківський район","ал. Замарстинівська, 83а",NaN,NaN,NaN,! not applicable
15257,"ТОВ приватний заклад освіти початкова школа ""Е...",42973250,заклад середньої освіти,загальносвітня школа,I,МІСТО,приватна,02152,8036600000,! not applicable,...,"вул. Регенаторна, 4",02152,8036600000,м.Київ,"Київ, Дніпровський район","вул. Регенаторна, 4",(097)4102208,bfine1867@ukr.net,NaN,! not applicable
15258,Львівська загальоосвітня школа ПП Стембрідж Скул,42998605,заклад середньої освіти,загальносвітня школа,I-III,МІСТО,приватна,NaN,4610137500,! not applicable,...,"вул. Клепарівська, 30",NaN,4610137500,Львівська область,"Львів, Шевченківський район","вул. Клепарівська, 30",(096)2751027,NaN,NaN,! not applicable
15259,"ПРИВАТНИЙ ЗАКЛАД ""ЗАКЛАД ЗАГАЛЬНОЇ СЕРЕДНЬОЇ О...",43128932,заклад середньої освіти,загальносвітня школа,I,МІСТО,приватна,08200,3210900000,! not applicable,...,"вул. Полтавська, 29 Д",08200,3210900000,Київська область,Ірпінь,"вул. Полтавська, 29 Д",(097)0059090,abetka123@email.ua,NaN,! not applicable
15260,"Товариство з обмеженою відповідальністю ""Ліцей...",43078080,заклад середньої освіти,ліцей,I-III,СЕЛО,приватна,08140,3222480401,! not applicable,...,"вул. Георгіївська, 28",08140,3222480401,Київська область,Білогородка,"вул. Георгіївська, 28",(98)8082288,NaN,NaN,! not applicable

In [35]:
schools_2026 = schools_2026[['university_name', 'edrpou', 'koatuu_id']]

In [36]:
schools_2026.rename(columns={'edrpou':'eoedrpou', 'koatuu_id':'KOATUU'}, inplace=True)

/var/folders/cz/wq9d8j_11fx3b8pjjbk7z8br0000gn/T/ipykernel_14298/558460108.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  schools_2026.rename(columns={'edrpou':'eoedrpou', 'koatuu_id':'KOATUU'}, inplace=True)

In [37]:
create_id(schools_2026, 'university_name', 'id')

/Users/scipyguru/Library/Mobile Documents/com~apple~CloudDocs/Documents_New/ZNO-Dataset/notebooks/tables_creation/src/merging_with_id.py:178: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset.loc[:,id_] = dataset[attr]
/Users/scipyguru/Library/Mobile Documents/com~apple~CloudDocs/Documents_New/ZNO-Dataset/notebooks/tables_creation/src/merging_with_id.py:193: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset[id_] = dataset[id_].apply(del_rayon)
/Users/scipyguru/Library/Mobile Documents/com~apple~CloudDocs/Documents_New/ZNO-Dataset/notebooks/tables_creation/src/merging_with_id.py:206: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset[id_] = dataset[id_].apply(lambda s: s if (len(s) and s[-1].isdigit()) else s[:-1])

,university_name,eoedrpou,KOATUU,id
0,Бердянська загальноосвітня школа І-ІІІ ступені...,26338802,2310400000,бердянськазагальноосвтняшкола3ступ7бердянська
1,"Первомайський навчально виховний комплекс ""Заг...",25992635,4810400000,первомайськийнавчальновиховнийкомплексзагально...
2,Загальноосвітня школа І-ІІІ ступенів №9 Мирног...,25689474,1411300000,загальноосвтняшкола3ступ9мирноградська
3,Заклад загальної середньої освіти І-ІІ ступені...,32624238,1411300000,2ступлцейгармонямирноградська
4,"Комунальний заклад ""Середня загальноосвітня шк...",23370351,1210436900,середнязагальноосвтняшкола23камянська
...,...,...,...,...
15256,Приватний заклад загальної середньої освіти ``...,42988398,4610137500,приватнийтстепску
15257,"ТОВ приватний заклад освіти початкова школа ""Е...",42973250,8036600000,приватнийзакладосвтипочатковашколаеврик
15258,Львівська загальоосвітня школа ПП Стембрідж Скул,42998605,4610137500,льввськазагальоосвтняшколаппстембрджску
15259,"ПРИВАТНИЙ ЗАКЛАД ""ЗАКЛАД ЗАГАЛЬНОЇ СЕРЕДНЬОЇ О...",43128932,3210900000,приватнийзакладабеткао
15260,"Товариство з обмеженою відповідальністю ""Ліцей...",43078080,3222480401,лцейсмарттехнолог

In [38]:
schools_2026 = schools_2026[schools_2026.eoedrpou.notna()]

In [39]:
schools_2026[schools_2026.duplicated(subset=['id', 'KOATUU'], keep=False)]

,university_name,eoedrpou,KOATUU,id
648,Рафалівська ЗОШ ІІ-ІІІ ступенів Володимирецько...,22567925,5620855400,рафалвськазагальноосвтняшкола3ступволодимирецька
683,Рафалівська загальноосвітня школа І-ІІІ ступен...,04590760,5620855400,рафалвськазагальноосвтняшкола3ступволодимирецька
12015,Червенівська загальноосвітня школа І ступеня М...,3491927,2122782805,червенвськазагальноосвтняшколаступмукачвська
12040,Червенівська загальноосвітня школа І-І ступені...,34855921,2122782805,червенвськазагальноосвтняшколаступмукачвська

In [40]:

schools_2026 = schools_2026[~schools_2026.eoedrpou.isin(['22567925', '04590760', '3491927', 
                                                                '34855921'])]

In [41]:
schools_2026 = schools_2026[schools_2026.eoedrpou.str.len() == 8]

In [42]:
schools_ed2026 = merging_edrpou(schools_edrpou_loc, schools_2026[['KOATUU', 'id', 'eoedrpou']], ['KOATUU', 'id'])
schools_ed2026

Filled: 67079 out of 99907  or 67%

,eoname,eotypename,eoedrpou,year,KATOTTG,KOATUU,category,id
0,"Терпіннівський колегіум ""Джерело"" Мелітопольсь...",колегіум,26373098,2016,UA23080270010078454,2323085101,village,терпнвськийколегумджереломелтопольська
1,Красилівська загальноосвітня школа I-III ступе...,середня загальноосвітня школа,25880114,2016,UA68040210010032567,6822710100,town,красилвськазагальноосвтняшкола3ступ3
2,Чернівецька спеціалізована школа І-ІІІ ступені...,спеціалізована школа,NaN,2016,UA73060610010033137,7310100000,town,чернвецькаспецалзованашкола3ступфзикоматематич...
3,Загальноосвітня школа I-III ступенів № 6 Дружк...,середня загальноосвітня школа,25705061,2016,UA14120030010055241,1411700000,town,загальноосвтняшкола3ступ6дружквська
4,Тернопільська спеціалізована школа І-ІІІ ступе...,спеціалізована школа,14040173,2016,UA61040490010069060,6110100000,town,тернопльськаспецалзованашкола3ступ3зпоглиблени...
...,...,...,...,...,...,...,...,...
99902,"Ходорівське відділення ВСП ""Технічний фаховий ...",заклад фахової передвищої освіти,05393837,2025,UA46100270010046817,4621510500,town,ходорвськевддленятехнчнийколеджнацональногоунв...
99903,"ТОВАРИСТВО З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ ""ПРИВА...",гімназія,42372041,2025,UA80000000000210193,8036300000,city,приватнийзакладосвтигмназякларсверб
99904,"Гаївська філія ""Початкова школа-заклад дошкіль...",початкова школа,25038104,2025,UA51140150050060575,5123981101,village,гавськафляпочатковашколазакладдошкльнаосвтияко...
99905,Вільшанська філія Романівського ліцею №2 Роман...,гімназія,45498834,2025,UA18040470090069061,1821481001,village,вльшанськафляроманвськоголцею2романвська
99906,Одеська державна академія будівництва та архіт...,вищий навчальний заклад III-IV рівнів акредитації,02071033,2025,UA51100270010320268,5110137500,city,одеськадержавнаакадемябудвництватаархтектур

In [43]:
schools_ed2026[schools_ed2026 ['eoedrpou'].isna()].year.value_counts()

year
2016    5926
2017    4767
2018    4762
2019    3818
2021    3755
2022    3432
2020    3357
2023    1892
2024    1119
Name: count, dtype: int64

In [44]:
schools_ed2026[schools_ed2026.eoedrpou.str.len() < 8]

Empty DataFrame
Columns: [eoname, eotypename, eoedrpou, year, KATOTTG, KOATUU, category, id]
Index: []

# Youcontrol

In [45]:
youcontrol =  pd.read_excel('./school_data/Youcontrol_historical_name.xlsx', dtype='str')
youcontrol

,Код ЄДРПОУ,Назва,Коротка назва
0,00121146,"ВІДКРИТЕ АКЦІОНЕРНЕ ТОВАРИСТВО ""ПІВДЕНТЕПЛОЕНЕ...",NaN
1,00121146,"ПУБЛІЧНЕ АКЦІОНЕРНЕ ТОВАРИСТВО ""ПІВДЕНТЕПЛОЕНЕ...","АТ ""ПТЕМ"""
2,00121146,"ПРИВАТНЕ АКЦІОНЕРНЕ ТОВАРИСТВО ""ПІВДЕНТЕПЛОЕНЕ...","АТ ""ПТЕМ"""
3,00131446,"КОЛЕКТИВНЕ ПІДПРИЄМСТВО ""БІЛГОРОД-ДНІСТРОВСЬКА...",NaN
4,00131446,ІНШІ ОРГАНІЗАЦІЙНО-ПРАВОВІ ФОРМИ КОЛЕКТИВНЕ ПІ...,NaN
...,...,...,...
80921,60043961,ДЕРЕБЧИНСЬКИЙ ОПОРНИЙ ЗАКЛАД ЗАГАЛЬНОЇ СЕРЕДНЬ...,ДОЗЗСО
80922,60043961,"ОПОРНИЙ ЗАКЛАД ""ДЕРЕБЧИНСЬКИЙ ЗАКЛАД ЗАГАЛЬНОЇ...","ОЗ ""ДЕРЕБЧИНСЬКИЙ ЗЗСО I-III СТУПЕНІВ"""
80923,60043961,"ОПОРНИЙ ЗАКЛАД ""ДЕРЕБЧИНСЬКИЙ ЗАКЛАД ЗАГАЛЬНОЇ...","ОЗ ""ДЕРЕБЧИНСЬКИЙ ЗЗСО I-III СТУПЕНІВ"""
80924,60043961,"ОПОРНИЙ ЗАКЛАД ""ДЕРЕБЧИНСЬКИЙ ЗАКЛАД ЗАГАЛЬНОЇ...","ОЗ ""ДЕРЕБЧИНСЬКИЙ ЗЗСО I-III СТУПЕНІВ"""
80925,60043961,ДЕРЕБЧИНСЬКИЙ ЛІЦЕЙ ДЖУРИНСЬКОЇ СІЛЬСЬКОЇ РАДИ...,ДЕРЕБЧИНСЬКИЙ ЛІЦЕЙ

In [46]:
youcontrol.columns

Index(['Код ЄДРПОУ', 'Назва', 'Коротка назва'], dtype='object')

In [47]:
youcontrol[youcontrol.duplicated(subset=['Назва', 'Код ЄДРПОУ'], keep=False)]

,Код ЄДРПОУ,Назва,Коротка назва
3,00131446,"КОЛЕКТИВНЕ ПІДПРИЄМСТВО ""БІЛГОРОД-ДНІСТРОВСЬКА...",NaN
5,00131446,"КОЛЕКТИВНЕ ПІДПРИЄМСТВО ""БІЛГОРОД-ДНІСТРОВСЬКА...",КП МК-26
119,00452713,"ДЕРЖАВНИЙ НАВЧАЛЬНИЙ ЗАКЛАД ""ЗВЕНИГОРОДСЬКИЙ Ц...","ДНЗ ""ЗВЕНИГОРОДСЬКИЙ ЦППРК"""
121,00452713,"ДЕРЖАВНИЙ НАВЧАЛЬНИЙ ЗАКЛАД ""ЗВЕНИГОРОДСЬКИЙ Ц...","ДНЗ ""ЗВЕНИГОРОДСЬКИЙ ЦППРК"""
144,00854423,"КООПЕРАТИВ ""НОВОКРОПИВНИЦЬКИЙ""",NaN
...,...,...,...
80918,60043961,ДЕРЕБЧИНСЬКИЙ ОПОРНИЙ ЗАКЛАД ЗАГАЛЬНОЇ СЕРЕДНЬ...,ДОЗЗСО
80919,60043961,ДЕРЕБЧИНСЬКА СЕРЕДНЯ ЗАГАЛЬНООСВІТНЯ ШКОЛА I-I...,ДЕРЕБЧИНСЬКА СЗШ I-III СТУПЕНІВ
80921,60043961,ДЕРЕБЧИНСЬКИЙ ОПОРНИЙ ЗАКЛАД ЗАГАЛЬНОЇ СЕРЕДНЬ...,ДОЗЗСО
80922,60043961,"ОПОРНИЙ ЗАКЛАД ""ДЕРЕБЧИНСЬКИЙ ЗАКЛАД ЗАГАЛЬНОЇ...","ОЗ ""ДЕРЕБЧИНСЬКИЙ ЗЗСО I-III СТУПЕНІВ"""
80924,60043961,"ОПОРНИЙ ЗАКЛАД ""ДЕРЕБЧИНСЬКИЙ ЗАКЛАД ЗАГАЛЬНОЇ...","ОЗ ""ДЕРЕБЧИНСЬКИЙ ЗЗСО I-III СТУПЕНІВ"""

In [48]:
youcontrol_long = youcontrol.drop_duplicates(subset=['Назва', 'Код ЄДРПОУ'], keep='first')

In [49]:
create_id(youcontrol_long, 'Назва', 'id')

/Users/scipyguru/Library/Mobile Documents/com~apple~CloudDocs/Documents_New/ZNO-Dataset/notebooks/tables_creation/src/merging_with_id.py:178: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset.loc[:,id_] = dataset[attr]
/Users/scipyguru/Library/Mobile Documents/com~apple~CloudDocs/Documents_New/ZNO-Dataset/notebooks/tables_creation/src/merging_with_id.py:193: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset[id_] = dataset[id_].apply(del_rayon)
/Users/scipyguru/Library/Mobile Documents/com~apple~CloudDocs/Documents_New/ZNO-Dataset/notebooks/tables_creation/src/merging_with_id.py:206: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset[id_] = dataset[id_].apply(lambda s: s if (len(s) and s[-1].isdigit()) else s[:-1])

,Код ЄДРПОУ,Назва,Коротка назва,id
0,00121146,"ВІДКРИТЕ АКЦІОНЕРНЕ ТОВАРИСТВО ""ПІВДЕНТЕПЛОЕНЕ...",NaN,вдкритеакцонернетовариствопвдентеплоенергомонта
1,00121146,"ПУБЛІЧНЕ АКЦІОНЕРНЕ ТОВАРИСТВО ""ПІВДЕНТЕПЛОЕНЕ...","АТ ""ПТЕМ""",публчнеакцонернетовариствопвдентеплоенергомонта
2,00121146,"ПРИВАТНЕ АКЦІОНЕРНЕ ТОВАРИСТВО ""ПІВДЕНТЕПЛОЕНЕ...","АТ ""ПТЕМ""",приватнеакцонернетовариствопвдентеплоенергомонта
3,00131446,"КОЛЕКТИВНЕ ПІДПРИЄМСТВО ""БІЛГОРОД-ДНІСТРОВСЬКА...",NaN,колективнепдпримствоблгородднстровськамеханзов...
4,00131446,ІНШІ ОРГАНІЗАЦІЙНО-ПРАВОВІ ФОРМИ КОЛЕКТИВНЕ ПІ...,NaN,колективнепдпримствоблгородднстровськамеханзов...
...,...,...,...,...
80918,60043961,ДЕРЕБЧИНСЬКИЙ ОПОРНИЙ ЗАКЛАД ЗАГАЛЬНОЇ СЕРЕДНЬ...,ДОЗЗСО,деребчинськийопорний3ступен
80920,60043961,ДЕРЕБЧИНСЬКИЙ ОПОРНИЙ ЗАКЛАД ЗАГАЛЬНОЇ СЕРЕДНЬ...,ДОЗЗСО,деребчинськийопорний3ступен
80922,60043961,"ОПОРНИЙ ЗАКЛАД ""ДЕРЕБЧИНСЬКИЙ ЗАКЛАД ЗАГАЛЬНОЇ...","ОЗ ""ДЕРЕБЧИНСЬКИЙ ЗЗСО I-III СТУПЕНІВ""",опорнийзакладдеребчинський3ступджуринська
80923,60043961,"ОПОРНИЙ ЗАКЛАД ""ДЕРЕБЧИНСЬКИЙ ЗАКЛАД ЗАГАЛЬНОЇ...","ОЗ ""ДЕРЕБЧИНСЬКИЙ ЗЗСО I-III СТУПЕНІВ""",опорнийзакладдеребчинський3ступджуринська
80925,60043961,ДЕРЕБЧИНСЬКИЙ ЛІЦЕЙ ДЖУРИНСЬКОЇ СІЛЬСЬКОЇ РАДИ...,ДЕРЕБЧИНСЬКИЙ ЛІЦЕЙ,деребчинськийлцейджуринська

In [50]:
youcontrol_long.rename(columns={'Код ЄДРПОУ':'eoedrpou'}, inplace=True)

/var/folders/cz/wq9d8j_11fx3b8pjjbk7z8br0000gn/T/ipykernel_14298/3977263988.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  youcontrol_long.rename(columns={'Код ЄДРПОУ':'eoedrpou'}, inplace=True)

In [51]:
youcontrol_long[(youcontrol_long.eoedrpou.str.len() < 8)]

Empty DataFrame
Columns: [eoedrpou, Назва, Коротка назва, id]
Index: []

In [52]:
youcontrol_long = youcontrol_long.drop_duplicates(subset=['id', 'eoedrpou'], keep='first')

In [53]:
youcontrol_long[youcontrol_long.duplicated(subset=['id'], keep=False)]

,eoedrpou,Назва,Коротка назва,id
221,01284979,МІЖШКІЛЬНИЙ НАВЧАЛЬНО-ВИРОБНИЧИЙ КОМБІНАТ,МНВК,мжшкльнийнавчальновиробничийкомбна
494,02218789,"КОМУНАЛЬНА ОРГАНІЗАЦІЯ (УСТАНОВА, ЗАКЛАД) МУЗИ...",NaN,музичнашкола2
498,02218884,"КОМУНАЛЬНА ОРГАНІЗАЦІЯ (УСТАНОВА, ЗАКЛАД) КОМУ...",NaN,музичнашкола3
503,02218921,"КОМУНАЛЬНА ОРГАНІЗАЦІЯ (УСТАНОВА, ЗАКЛАД) КОМУ...",NaN,музичнашкола2
719,02542129,МИКОЛАЇВСЬКИЙ ПРОФЕСІЙНИЙ ЛІЦЕЙ,NaN,миколавськийпрофесйнийлце
...,...,...,...,...
80889,45117367,"ФЕРМЕРСЬКЕ ГОСПОДАРСТВО ""ДОВІРА Б""","ФГ ""ДОВІРА Б""",фермерськегосподарстводовра
80903,45251511,Юріївська гімназія з початковою школою та дошк...,Юріївська гімназія,юрвськагмназязпочатковоюшколоютадошкльнимпдроз...
80905,45275530,Юріївська гімназія з початковою школою та дошк...,Юріївська гімназія,юрвськагмназязпочатковоюшколоютадошкльнимпдроз...
80907,45287518,Кобзарцівська початкова школа з дошкільним під...,Кобзарцівська початкова школа,кобзарцвськапочатковашколаздошкльнимпдроздломс...
80912,45383386,Кобзарцівська початкова школа з дошкільним під...,Кобзарцівська початкова школа,кобзарцвськапочатковашколаздошкльнимпдроздломс...

In [54]:
youcontrol_long.drop(youcontrol_long[youcontrol_long.duplicated(subset=['id'], keep=False)].index.values.tolist()  , inplace=True)

/var/folders/cz/wq9d8j_11fx3b8pjjbk7z8br0000gn/T/ipykernel_14298/2842222147.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  youcontrol_long.drop(youcontrol_long[youcontrol_long.duplicated(subset=['id'], keep=False)].index.values.tolist()  , inplace=True)

In [55]:
youcontrol_long[youcontrol_long.eoedrpou == '25708094'].id.unique()

array(['михайлвськазагальноосвтняшкола3ступкрасноармйська',
       'навчальновиховнийкомплексмихайлвськазагальноосвтняшкола3ступдошкльнийнавчальнийзакладкрасноармйська',
       'навчальновиховнийкомплексмихайлвськазагальноосвтняшкола3ступдошкльнийнавчальнийзакладпокровська',
       'навчальновиховнийкомплексмихайлвський3ступзакладдошкльнаосвтиновогродвська'],
      dtype=object)

In [56]:
schools_youcontrol_long = merging_edrpou(schools_ed2026, youcontrol_long[['id', 'eoedrpou']], ['id'])
schools_youcontrol_long

Filled: 89304 out of 99907  or 89%

,eoname,eotypename,eoedrpou,year,KATOTTG,KOATUU,category,id
0,"Терпіннівський колегіум ""Джерело"" Мелітопольсь...",колегіум,26373098,2016,UA23080270010078454,2323085101,village,терпнвськийколегумджереломелтопольська
1,Красилівська загальноосвітня школа I-III ступе...,середня загальноосвітня школа,25880114,2016,UA68040210010032567,6822710100,town,красилвськазагальноосвтняшкола3ступ3
2,Чернівецька спеціалізована школа І-ІІІ ступені...,спеціалізована школа,21431046,2016,UA73060610010033137,7310100000,town,чернвецькаспецалзованашкола3ступфзикоматематич...
3,Загальноосвітня школа I-III ступенів № 6 Дружк...,середня загальноосвітня школа,25705061,2016,UA14120030010055241,1411700000,town,загальноосвтняшкола3ступ6дружквська
4,Тернопільська спеціалізована школа І-ІІІ ступе...,спеціалізована школа,14040173,2016,UA61040490010069060,6110100000,town,тернопльськаспецалзованашкола3ступ3зпоглиблени...
...,...,...,...,...,...,...,...,...
99902,"Ходорівське відділення ВСП ""Технічний фаховий ...",заклад фахової передвищої освіти,05393837,2025,UA46100270010046817,4621510500,town,ходорвськевддленятехнчнийколеджнацональногоунв...
99903,"ТОВАРИСТВО З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ ""ПРИВА...",гімназія,42372041,2025,UA80000000000210193,8036300000,city,приватнийзакладосвтигмназякларсверб
99904,"Гаївська філія ""Початкова школа-заклад дошкіль...",початкова школа,25038104,2025,UA51140150050060575,5123981101,village,гавськафляпочатковашколазакладдошкльнаосвтияко...
99905,Вільшанська філія Романівського ліцею №2 Роман...,гімназія,45498834,2025,UA18040470090069061,1821481001,village,вльшанськафляроманвськоголцею2романвська
99906,Одеська державна академія будівництва та архіт...,вищий навчальний заклад III-IV рівнів акредитації,02071033,2025,UA51100270010320268,5110137500,city,одеськадержавнаакадемябудвництватаархтектур

In [57]:
schools_youcontrol_long[schools_youcontrol_long['eoedrpou'].isna()].year.value_counts()

year
2016    2006
2018    1732
2019    1452
2017    1391
2020    1260
2021    1102
2022     873
2023     469
2024     318
Name: count, dtype: int64

In [58]:
schools_youcontrol_long[schools_youcontrol_long.eoedrpou.str.len() < 8]

Empty DataFrame
Columns: [eoname, eotypename, eoedrpou, year, KATOTTG, KOATUU, category, id]
Index: []

# Gathered by hand

In [59]:
data_hand = pd.read_csv('./school_data/by_hand.csv',  dtype = str)
data_hand

,eoname,KOATUU_2020,KOATUU_2020_reg,year,id,EDRPOU
0,"Вiдокремлений структурний пiдроздiл ""Краматорс...",0510100000,05,[2023],краматорськийколеджпромисловостнформацйнихтехн...,04601943
1,"ВСП ""Технологічно-промисловий фаховий коледж В...",0510100000,05,[2022],технологчнопромисловийколеджвницькогонацональн...,00419667
2,Вище професійне училище №11 м. Вінниці,0510100000,05,"[2018, 2019, 2020, 2021, 2022, 2023]",вищепрофесйнеучилище11мвниц,03065891
3,Вище художнє професійно-технічне училище № 5 м...,0510100000,05,[2023],вищехудожнпрофесйнотехнчнеучилище5мвниц,02539890
4,Вище художнє професійно-технічне училище №5 м....,0510100000,05,"[2018, 2019, 2020, 2021, 2022]",вищехудожнпрофесйнотехнчнеучилище5мвниця,02539890
...,...,...,...,...,...,...
32052,Школа №25 І-ІІІ ступенів Шевченківського район...,8039100000,80,"[2016, 2017, 2018, 2019, 2020, 2021]",школа253ступмкива,22880786
32053,Школа №27 І-ІІІ ступенів Шевченківського район...,8039100000,80,[2016],школа273ступмкива,26125710
32054,Школа №70 І-ІІІ ступенів Шевченківського район...,8039100000,80,[2016],школа703ступмкива,22881828
32055,Школа №95 І-ІІІ ступенів Шевченківського район...,8039100000,80,[2017],школа953ступмкива,26125905
32056,школа І-ІІІ ступенів №175 ім.В Марченка Шевчен...,8039100000,80,"[2020, 2021, 2022, 2023]",школа3ступ175мвмарченкамкива,26125940

In [60]:
data_hand.columns

Index(['eoname', 'KOATUU_2020', 'KOATUU_2020_reg', 'year', 'id', 'EDRPOU'], dtype='object')

In [61]:
data_hand = data_hand[['eoname', 'KOATUU_2020', 'EDRPOU']]

In [62]:
data_hand['temp_eoname'] = data_hand['eoname'].str.replace(r'\r\n|\n', '', regex=True).str.strip()

/var/folders/cz/wq9d8j_11fx3b8pjjbk7z8br0000gn/T/ipykernel_14298/1678710856.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_hand['temp_eoname'] = data_hand['eoname'].str.replace(r'\r\n|\n', '', regex=True).str.strip()

In [63]:
data_hand.rename(columns={'EDRPOU':'eoedrpou', 'KOATUU_2020': 'KOATUU'}, inplace=True)
data_hand.columns

/var/folders/cz/wq9d8j_11fx3b8pjjbk7z8br0000gn/T/ipykernel_14298/1071490741.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_hand.rename(columns={'EDRPOU':'eoedrpou', 'KOATUU_2020': 'KOATUU'}, inplace=True)

Index(['eoname', 'KOATUU', 'eoedrpou', 'temp_eoname'], dtype='object')

In [64]:
data_hand[data_hand.duplicated(subset=['temp_eoname', 'eoedrpou', 'KOATUU'], keep=False)]

,eoname,KOATUU,eoedrpou,temp_eoname
483,Степенівський навчально - виховний комплекс: з...,0520687603,23562485,Степенівський навчально - виховний комплекс: з...
484,Степенівський навчально - виховний комплекс: з...,0520687603,23562485,Степенівський навчально - виховний комплекс: з...
619,"Комунальний заклад ""Сербинівський навчально-ви...",0521085403,39977763,"Комунальний заклад ""Сербинівський навчально-ви..."
620,"Комунальний заклад ""Сербинівський навчально-ви...",0521085403,39977763,"Комунальний заклад ""Сербинівський навчально-ви..."
1145,"Комунальний заклад ""Воловодівська загальноосві...",0523084004,25918745,"Комунальний заклад ""Воловодівська загальноосві..."
...,...,...,...,...
26594,Новосеменівська загальноосвітня школа I-III ст...,6522955112,24750102,Новосеменівська загальноосвітня школа I-III ст...
29182,Лип'янська загальноосвітня школа І-ІІІ ступені...,7125784001,24355707,Лип'янська загальноосвітня школа І-ІІІ ступені...
29184,Лип'янська загальноосвітня школа І-ІІІ ступені...,7125784001,24355707,Лип'янська загальноосвітня школа І-ІІІ ступені...
31260,Школа І-ІІІ ступенів №284 Дарницького району м...,8036300000,22875957,Школа І-ІІІ ступенів №284 Дарницького району м...
31261,Школа І-ІІІ ступенів №284 Дарницького району м...,8036300000,22875957,Школа І-ІІІ ступенів №284 Дарницького району м...

In [65]:
data_hand = data_hand.drop_duplicates(subset=['temp_eoname', 'eoedrpou', 'KOATUU'], keep='first')

In [66]:
data_hand[data_hand.duplicated(subset=['temp_eoname', 'KOATUU'], keep=False)]

,eoname,KOATUU,eoedrpou,temp_eoname
19465,Розівська загальноосвітня школа I-III ступенів...,5124585101,26506286,Розівська загальноосвітня школа I-III ступенів...
19466,Розівська загальноосвітня школа I-III ступенів...,5124585101,25814353,Розівська загальноосвітня школа I-III ступенів...

In [67]:
data_hand = data_hand.drop_duplicates(subset=['temp_eoname', 'KOATUU'], keep='first')

In [68]:
data_hand[data_hand.eoedrpou.str.len() < 8]

Empty DataFrame
Columns: [eoname, KOATUU, eoedrpou, temp_eoname]
Index: []

In [69]:
schools_youcontrol_long['temp_eoname'] = schools_youcontrol_long['eoname'].str.replace(r'\r\n|\n', '', regex=True).str.strip()
schools_youcontrol_long

,eoname,eotypename,eoedrpou,year,KATOTTG,KOATUU,category,id,temp_eoname
0,"Терпіннівський колегіум ""Джерело"" Мелітопольсь...",колегіум,26373098,2016,UA23080270010078454,2323085101,village,терпнвськийколегумджереломелтопольська,"Терпіннівський колегіум ""Джерело"" Мелітопольсь..."
1,Красилівська загальноосвітня школа I-III ступе...,середня загальноосвітня школа,25880114,2016,UA68040210010032567,6822710100,town,красилвськазагальноосвтняшкола3ступ3,Красилівська загальноосвітня школа I-III ступе...
2,Чернівецька спеціалізована школа І-ІІІ ступені...,спеціалізована школа,21431046,2016,UA73060610010033137,7310100000,town,чернвецькаспецалзованашкола3ступфзикоматематич...,Чернівецька спеціалізована школа І-ІІІ ступені...
3,Загальноосвітня школа I-III ступенів № 6 Дружк...,середня загальноосвітня школа,25705061,2016,UA14120030010055241,1411700000,town,загальноосвтняшкола3ступ6дружквська,Загальноосвітня школа I-III ступенів № 6 Дружк...
4,Тернопільська спеціалізована школа І-ІІІ ступе...,спеціалізована школа,14040173,2016,UA61040490010069060,6110100000,town,тернопльськаспецалзованашкола3ступ3зпоглиблени...,Тернопільська спеціалізована школа І-ІІІ ступе...
...,...,...,...,...,...,...,...,...,...
99902,"Ходорівське відділення ВСП ""Технічний фаховий ...",заклад фахової передвищої освіти,05393837,2025,UA46100270010046817,4621510500,town,ходорвськевддленятехнчнийколеджнацональногоунв...,"Ходорівське відділення ВСП ""Технічний фаховий ..."
99903,"ТОВАРИСТВО З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ ""ПРИВА...",гімназія,42372041,2025,UA80000000000210193,8036300000,city,приватнийзакладосвтигмназякларсверб,"ТОВАРИСТВО З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ ""ПРИВА..."
99904,"Гаївська філія ""Початкова школа-заклад дошкіль...",початкова школа,25038104,2025,UA51140150050060575,5123981101,village,гавськафляпочатковашколазакладдошкльнаосвтияко...,"Гаївська філія ""Початкова школа-заклад дошкіль..."
99905,Вільшанська філія Романівського ліцею №2 Роман...,гімназія,45498834,2025,UA18040470090069061,1821481001,village,вльшанськафляроманвськоголцею2романвська,Вільшанська філія Романівського ліцею №2 Роман...
99906,Одеська державна академія будівництва та архіт...,вищий навчальний заклад III-IV рівнів акредитації,02071033,2025,UA51100270010320268,5110137500,city,одеськадержавнаакадемябудвництватаархтектур,Одеська державна академія будівництва та архіт...

In [70]:
schools_final = merging_edrpou(schools_youcontrol_long, data_hand[['temp_eoname', 'eoedrpou', 'KOATUU']], ['temp_eoname', 'KOATUU'])
schools_final

Filled: 99674 out of 99907  or 100%

,eoname,eotypename,eoedrpou,year,KATOTTG,KOATUU,category,id,temp_eoname
0,"Терпіннівський колегіум ""Джерело"" Мелітопольсь...",колегіум,26373098,2016,UA23080270010078454,2323085101,village,терпнвськийколегумджереломелтопольська,"Терпіннівський колегіум ""Джерело"" Мелітопольсь..."
1,Красилівська загальноосвітня школа I-III ступе...,середня загальноосвітня школа,25880114,2016,UA68040210010032567,6822710100,town,красилвськазагальноосвтняшкола3ступ3,Красилівська загальноосвітня школа I-III ступе...
2,Чернівецька спеціалізована школа І-ІІІ ступені...,спеціалізована школа,21431046,2016,UA73060610010033137,7310100000,town,чернвецькаспецалзованашкола3ступфзикоматематич...,Чернівецька спеціалізована школа І-ІІІ ступені...
3,Загальноосвітня школа I-III ступенів № 6 Дружк...,середня загальноосвітня школа,25705061,2016,UA14120030010055241,1411700000,town,загальноосвтняшкола3ступ6дружквська,Загальноосвітня школа I-III ступенів № 6 Дружк...
4,Тернопільська спеціалізована школа І-ІІІ ступе...,спеціалізована школа,14040173,2016,UA61040490010069060,6110100000,town,тернопльськаспецалзованашкола3ступ3зпоглиблени...,Тернопільська спеціалізована школа І-ІІІ ступе...
...,...,...,...,...,...,...,...,...,...
99902,"Ходорівське відділення ВСП ""Технічний фаховий ...",заклад фахової передвищої освіти,05393837,2025,UA46100270010046817,4621510500,town,ходорвськевддленятехнчнийколеджнацональногоунв...,"Ходорівське відділення ВСП ""Технічний фаховий ..."
99903,"ТОВАРИСТВО З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ ""ПРИВА...",гімназія,42372041,2025,UA80000000000210193,8036300000,city,приватнийзакладосвтигмназякларсверб,"ТОВАРИСТВО З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ ""ПРИВА..."
99904,"Гаївська філія ""Початкова школа-заклад дошкіль...",початкова школа,25038104,2025,UA51140150050060575,5123981101,village,гавськафляпочатковашколазакладдошкльнаосвтияко...,"Гаївська філія ""Початкова школа-заклад дошкіль..."
99905,Вільшанська філія Романівського ліцею №2 Роман...,гімназія,45498834,2025,UA18040470090069061,1821481001,village,вльшанськафляроманвськоголцею2романвська,Вільшанська філія Романівського ліцею №2 Роман...
99906,Одеська державна академія будівництва та архіт...,вищий навчальний заклад III-IV рівнів акредитації,02071033,2025,UA51100270010320268,5110137500,city,одеськадержавнаакадемябудвництватаархтектур,Одеська державна академія будівництва та архіт...

In [71]:
schools_final.drop(columns=['temp_eoname'], inplace=True)

In [72]:
schools_final

,eoname,eotypename,eoedrpou,year,KATOTTG,KOATUU,category,id
0,"Терпіннівський колегіум ""Джерело"" Мелітопольсь...",колегіум,26373098,2016,UA23080270010078454,2323085101,village,терпнвськийколегумджереломелтопольська
1,Красилівська загальноосвітня школа I-III ступе...,середня загальноосвітня школа,25880114,2016,UA68040210010032567,6822710100,town,красилвськазагальноосвтняшкола3ступ3
2,Чернівецька спеціалізована школа І-ІІІ ступені...,спеціалізована школа,21431046,2016,UA73060610010033137,7310100000,town,чернвецькаспецалзованашкола3ступфзикоматематич...
3,Загальноосвітня школа I-III ступенів № 6 Дружк...,середня загальноосвітня школа,25705061,2016,UA14120030010055241,1411700000,town,загальноосвтняшкола3ступ6дружквська
4,Тернопільська спеціалізована школа І-ІІІ ступе...,спеціалізована школа,14040173,2016,UA61040490010069060,6110100000,town,тернопльськаспецалзованашкола3ступ3зпоглиблени...
...,...,...,...,...,...,...,...,...
99902,"Ходорівське відділення ВСП ""Технічний фаховий ...",заклад фахової передвищої освіти,05393837,2025,UA46100270010046817,4621510500,town,ходорвськевддленятехнчнийколеджнацональногоунв...
99903,"ТОВАРИСТВО З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ ""ПРИВА...",гімназія,42372041,2025,UA80000000000210193,8036300000,city,приватнийзакладосвтигмназякларсверб
99904,"Гаївська філія ""Початкова школа-заклад дошкіль...",початкова школа,25038104,2025,UA51140150050060575,5123981101,village,гавськафляпочатковашколазакладдошкльнаосвтияко...
99905,Вільшанська філія Романівського ліцею №2 Роман...,гімназія,45498834,2025,UA18040470090069061,1821481001,village,вльшанськафляроманвськоголцею2романвська
99906,Одеська державна академія будівництва та архіт...,вищий навчальний заклад III-IV рівнів акредитації,02071033,2025,UA51100270010320268,5110137500,city,одеськадержавнаакадемябудвництватаархтектур

In [73]:
schools_final[schools_final.eoedrpou.isna()].year.value_counts()

year
2024    200
2017      6
2018      6
2016      5
2019      5
2021      3
2022      3
2023      3
2020      2
Name: count, dtype: int64

In [74]:
importlib.reload(missed)

In [75]:
for katottg, school in missed.MISSING_EOEDRPOU.items():
    for school_id, eoedrpou in school.items():
        schools_final.loc[(schools_final.KATOTTG== katottg)&(schools_final.id==school_id)&schools_final.eoedrpou.isna(), 'eoedrpou']= eoedrpou

In [76]:
schools_final[schools_final.eoedrpou.isna()].year.value_counts()

Series([], Name: count, dtype: int64)

In [77]:
schools_final[schools_final.eoedrpou.str.len() < 8]

Empty DataFrame
Columns: [eoname, eotypename, eoedrpou, year, KATOTTG, KOATUU, category, id]
Index: []

In [78]:
schools_final.shape

(99907, 8)

# Issues

In [79]:
cols_no_year = [c for c in schools_final.columns if c != 'year']

schools_merged = (
    schools_final
    .groupby(cols_no_year, dropna=False)['year']
    .agg(lambda x: ', '.join(map(str, sorted(set(x)))))  # "2019, 2020, 2021"
    .reset_index(name='years')  # нова колонка years
)

schools_merged = (
    schools_merged
    .sort_values('eoedrpou')  # сортування по ЄДРПОУ
    .reset_index(drop=True) # оновити індекси, необов'язково
)

schools_merged.head()

,eoname,eotypename,eoedrpou,KATOTTG,KOATUU,category,id,years
0,Загальноосвітні школи Придністров'я,середня загальноосвітня школа,00000000,UA51100270010196805,5110136900,city,загальноосвтншколиприднстров,"2016, 2017"
1,Дніпровський технікум зварювання та електронік...,заклад вищої освіти,00129314,UA12020010010512802,1210136900,city,днпровськийтехнкумзварюванятаелектронкименопатон,2019
2,Дніпровський технікум зварювання та електронік...,вищий навчальний заклад I-II рівнів акредитації,00129314,UA12020010010512802,1210136900,city,днпровськийтехнкумзварюванятаелектронкименопатон,2018
3,Дніпровський технікум зварювання та електронік...,заклад фахової передвищої освіти,00129314,UA12020010010512802,1210136900,city,днпровськийтехнкумзварюванятаелектронкименопатон,2021
4,Дніпровський технікум зварювання та електронік...,заклад вищої освіти,00129314,UA12020010010512802,1210136900,city,днпровськийтехнкумзварюванятаелектронкименопатон,2020

In [80]:
# schools_merged.to_csv('./school_data/schools_merged.csv', index = False)

In [81]:
# schools_merged[schools_merged.KATOTTG == 'UA51120150160082202']

In [82]:
# schools_merged[schools_merged.eoedrpou == '20627959']

In [83]:
key_cols = ['eoedrpou']

def years_to_list(years_str: str) -> list[int]:
    return [int(y.strip()) for y in years_str.split(',') if y.strip()]

def has_duplicate_years(years_lists: list) -> bool:
    """Перевіряє, чи є дублювання років між різними рядками для одного eoedrpou"""
    # збираємо всі роки з усіх рядків
    all_years = []
    for years_list in years_lists:
        all_years.extend(years_list)
    
    # перевіряємо, чи є повторення років
    # якщо кількість унікальних років менша за загальну кількість, значить є дублікати
    return len(all_years) != len(set(all_years))

tmp = schools_merged.copy()
tmp['years_list'] = tmp['years'].apply(years_to_list)

# для кожної групи перевіряємо, чи є дублювання років
group_has_duplicates = (
    tmp
    .groupby(key_cols)['years_list']
    .agg(lambda lists: has_duplicate_years(lists.tolist()))
)

tmp = tmp.join(group_has_duplicates.rename('has_duplicate_years'), on=key_cols)

# залишаємо тільки ті групи, де є дублювання років
schools_with_duplicate_years = (
    tmp[tmp['has_duplicate_years'] == True]
    .drop(columns=['years_list', 'has_duplicate_years'])
)

print(f"Кількість шкіл з дублюванням років: {schools_with_duplicate_years.shape[0]}")
print(f"Унікальних eoedrpou з дублюванням: {schools_with_duplicate_years['eoedrpou'].nunique()}")
print("\nПриклади:")
schools_with_duplicate_years.head(20)

Кількість шкіл з дублюванням років: 1527
Унікальних eoedrpou з дублюванням: 310

Приклади:

,eoname,eotypename,eoedrpou,KATOTTG,KOATUU,category,id,years
770,Чернівецький медичний коледж Буковинського дер...,вищий навчальний заклад I-II рівнів акредитації,02010994,UA73060610010033137,7310100000,town,чернвецькиймедичнийколеджбуковинськогодержавно...,2018
771,Фаховий коледж Вищого державного навчального з...,заклад фахової передвищої освіти,02010994,UA73060610010033137,7310100000,town,коледжвищогодержавногонавчальногозакладуукрани...,2021
772,Коледж Вищого державного навчального закладу У...,вищий навчальний заклад I-II рівнів акредитації,02010994,UA73060610010033137,7310100000,town,коледжвищогодержавногонавчальногозакладуукрани...,2018
773,Коледж Вищого державного навчального закладу У...,заклад вищої освіти,02010994,UA73060610010033137,7310100000,town,коледжвищогодержавногонавчальногозакладуукрани...,"2019, 2020"
774,Чернівецький медичний коледж Буковинського дер...,заклад вищої освіти,02010994,UA73060610010033137,7310100000,town,чернвецькиймедичнийколеджбуковинськогодержавно...,"2019, 2020"
775,Чернівецький медичний фаховий коледж,заклад фахової передвищої освіти,02010994,UA73060610010033137,7310100000,town,чернвецькиймедичнийколед,"2021, 2022, 2023, 2024, 2025"
776,Вашковецький медичний фаховий коледж,заклад фахової передвищої освіти,02011002,UA73020070010063977,7320510400,town,вашковецькиймедичнийколед,"2021, 2022, 2023, 2024, 2025"
777,"Комунальний вищий навчальний заклад ""Вашковець...",вищий навчальний заклад I-II рівнів акредитації,02011002,UA73020070010063977,7320510400,town,комунальнийвищийнавчальнийзакладвашковецькийме...,2018
778,"Комунальний вищий навчальний заклад ""Вашковець...",заклад вищої освіти,02011002,UA73020070010063977,7320510400,town,комунальнийвищийнавчальнийзакладвашковецькийме...,"2019, 2020"
779,Фаховий коледж Буковинського державного медичн...,заклад фахової передвищої освіти,02011002,UA73060610010033137,7310100000,town,коледжбуковинськогодержавногомедичногоунверситет,"2022, 2023"
846,Івано-Франківський базовий медичний коледж,заклад вищої освіти,02011321,UA26040190010045761,2610100000,town,ванофранквськийбазовиймедичнийколед,"2019, 2020"
847,"Медичний коледж ДВНЗ ""Івано-Франківський націо...",вищий навчальний заклад I-II рівнів акредитації,02011321,UA26040190010045761,2610100000,town,медичнийколедждвнзванофранквськийнацональнийме...,2018
848,"Медичний коледж ДВНЗ ""Івано-Франківський націо...",заклад вищої освіти,02011321,UA26040190010045761,2610100000,town,медичнийколедждвнзванофранквськийнацональнийме...,2019
849,"Комунальний заклад фахової передвищої освіти ""...",заклад фахової передвищої освіти,02011321,UA26040190010045761,2610100000,town,фаховапередвищаосвтиванофранквськиймедичнийкол...,"2022, 2024, 2025"
850,Фаховий медичний коледж Івано-Франківського на...,заклад вищої освіти,02011321,UA26040190010045761,2610100000,town,медичнийколеджванофранквськогонацональногомеди...,"2021, 2022, 2023"
851,Івано-Франківський базовий медичний коледж,вищий навчальний заклад I-II рівнів акредитації,02011321,UA26040190010045761,2610100000,town,ванофранквськийбазовиймедичнийколед,2018
852,Медичний коледж Івано-Франківського національн...,заклад вищої освіти,02011321,UA26040190010045761,2610100000,town,медичнийколеджванофранквськогонацональногомеди...,2020
853,"Комунальний заклад фахової передвищої освіти ""...",заклад вищої освіти,02011321,UA26040190010045761,2610100000,town,фаховапередвищаосвтиванофранквськиймедичнийкол...,"2021, 2023"
924,"Комунальний заклад ""Бериславський медичний фах...",заклад фахової передвищої освіти,02011634,UA65020010010095508,6520610100,town,бериславськиймедичнийколеджхерсонськаобласно,"2021, 2022, 2023, 2024, 2025"
925,Ліцей природничо-математичного напрямку (біоло...,ліцей,02011634,UA65020010010095508,6520610100,town,лцейприродничоматематичногонапрямкубериславськ...,2021

In [117]:
fix_schools_with_duplicate_years = pd.read_csv(
    './school_data/EIE_NMT Answers - cleaned_duplicates.csv',
    dtype=str,
    keep_default_na=True
)
fix_schools_with_duplicate_years

,eoname,eotypename,eoedrpou,KATOTTG,KOATUU,category,id,years,status,correction
0,Чернівецький медичний коледж Буковинського дер...,вищий навчальний заклад I-II рівнів акредитації,02010994,UA73060610010033137,7310100000,town,чернвецькиймедичнийколеджбуковинськогодержавно...,2018,ok,NaN
1,Фаховий коледж Вищого державного навчального з...,заклад фахової передвищої освіти,02010994,UA73060610010033137,7310100000,town,коледжвищогодержавногонавчальногозакладуукрани...,2021,not,02010971
2,Коледж Вищого державного навчального закладу У...,вищий навчальний заклад I-II рівнів акредитації,02010994,UA73060610010033137,7310100000,town,коледжвищогодержавногонавчальногозакладуукрани...,2018,not,02010971
3,Коледж Вищого державного навчального закладу У...,заклад вищої освіти,02010994,UA73060610010033137,7310100000,town,коледжвищогодержавногонавчальногозакладуукрани...,"2019, 2020",not,02010971
4,Чернівецький медичний коледж Буковинського дер...,заклад вищої освіти,02010994,UA73060610010033137,7310100000,town,чернвецькиймедичнийколеджбуковинськогодержавно...,"2019, 2020",ok,NaN
...,...,...,...,...,...,...,...,...,...,...
1522,"Великосолтанівська гімназія - філія ОЗО ""Калин...",гімназія,43801651,UA32140090050048147,3221480901,village,великосолтанвськагмназяфляозокалинвськийакадем...,2025,not,43846053
1523,"Опорний заклад освіти ""Калинівський академічни...",ліцей,43801651,UA32140090010093169,3221455800,urban village,опорнийзакладосвтикалинвськийакадемчнийлцейосв...,"2023, 2024, 2025",ok,NaN
1524,"Відокремлений структурний підрозділ ""Донбаськи...",заклад фахової передвищої освіти,44843006,UA14120210010032554,1414100000,town,донбаськийаграрнийколеджсхдноукранськогонацона...,2023,ok,NaN
1525,"Відокремлений структурний підрозділ ""Донбаськи...",заклад фахової передвищої освіти,44843006,UA14120050010016211,1422482701,village,донбаськийаграрнийколеджсхдноукранськогонацона...,2023,not,44843006b
1526,"Відокремлений структурний підрозділ ""Донбаськи...",заклад фахової передвищої освіти,44843006,UA12020010010512802,1210136900,city,донбаськийаграрнийколеджсхдноукранськогонацона...,"2024, 2025",ok,NaN

In [118]:
# перевіряємо, чи є дублікати за трьома полями
dup_mask = fix_schools_with_duplicate_years.duplicated(
    subset=['eoname', 'eotypename', 'eoedrpou', 'KATOTTG'],
    keep=False
)

# подивитися самі дублікати (якщо вони є)
fix_schools_with_duplicate_years[dup_mask]

# якщо потрібно жорстко перевірити, що дублікатів немає:
assert not dup_mask.any(), "Є дублікати за eoname, eotypename, eoedrpou та KATOTTG"

In [119]:
# залишаємо лише ті рядки, де correction не NA
fix_non_na = fix_schools_with_duplicate_years[
    fix_schools_with_duplicate_years['correction'].notna()
][['eoname', 'eotypename', 'eoedrpou', 'KATOTTG', 'correction']]

# нормалізуємо текстові ключі (обрізаємо \r, \n, пробіли)
for df in (schools_final, fix_non_na):
    df['eoname'] = df['eoname'].astype(str).str.strip()
    df['eotypename'] = df['eotypename'].astype(str).str.strip()

# приєднуємо correction до schools_final за трьома полями
schools_final_fixed = schools_final.merge(
    fix_non_na,
    on=['eoname', 'eotypename', 'eoedrpou', 'KATOTTG'],
    how='left'
)

# замінюємо eoedrpou там, де є correction
mask_corr = schools_final_fixed['correction'].notna()
schools_final_fixed.loc[mask_corr, 'eoedrpou'] = schools_final_fixed.loc[mask_corr, 'correction']

# за бажанням можна видалити колонку correction
schools_final_fixed = schools_final_fixed.drop(columns=['correction'])
schools_final_fixed

,eoname,eotypename,eoedrpou,year,KATOTTG,KOATUU,category,id
0,"Терпіннівський колегіум ""Джерело"" Мелітопольсь...",колегіум,26373098,2016,UA23080270010078454,2323085101,village,терпнвськийколегумджереломелтопольська
1,Красилівська загальноосвітня школа I-III ступе...,середня загальноосвітня школа,25880114,2016,UA68040210010032567,6822710100,town,красилвськазагальноосвтняшкола3ступ3
2,Чернівецька спеціалізована школа І-ІІІ ступені...,спеціалізована школа,21431046,2016,UA73060610010033137,7310100000,town,чернвецькаспецалзованашкола3ступфзикоматематич...
3,Загальноосвітня школа I-III ступенів № 6 Дружк...,середня загальноосвітня школа,25705061,2016,UA14120030010055241,1411700000,town,загальноосвтняшкола3ступ6дружквська
4,Тернопільська спеціалізована школа І-ІІІ ступе...,спеціалізована школа,14040173,2016,UA61040490010069060,6110100000,town,тернопльськаспецалзованашкола3ступ3зпоглиблени...
...,...,...,...,...,...,...,...,...
99909,"Ходорівське відділення ВСП ""Технічний фаховий ...",заклад фахової передвищої освіти,05393837a,2025,UA46100270010046817,4621510500,town,ходорвськевддленятехнчнийколеджнацональногоунв...
99910,"ТОВАРИСТВО З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ ""ПРИВА...",гімназія,42372041,2025,UA80000000000210193,8036300000,city,приватнийзакладосвтигмназякларсверб
99911,"Гаївська філія ""Початкова школа-заклад дошкіль...",початкова школа,25038104б,2025,UA51140150050060575,5123981101,village,гавськафляпочатковашколазакладдошкльнаосвтияко...
99912,Вільшанська філія Романівського ліцею №2 Роман...,гімназія,45498834,2025,UA18040470090069061,1821481001,village,вльшанськафляроманвськоголцею2романвська
99913,Одеська державна академія будівництва та архіт...,вищий навчальний заклад III-IV рівнів акредитації,02071033,2025,UA51100270010320268,5110137500,city,одеськадержавнаакадемябудвництватаархтектур

In [120]:
# 1. Долинська ЗОШ №7
mask = (
    (schools_final_fixed['eoname'] == 'Долинська загальноосвітня школа I-III ступенів №7') &
    (schools_final_fixed['eotypename'] == 'середня загальноосвітня школа') &
    (schools_final_fixed['eoedrpou'] == '20565796') &
    (schools_final_fixed['KATOTTG'] == 'UA26060130010099427')
)
schools_final_fixed.loc[mask, 'eoedrpou'] = '20555674'

# 2. Комунальний заклад Любимівська ЗОШ
mask = (
    (schools_final_fixed['eoname'] == 'Комунальний заклад Любимівська  загальноосвітня школа') &
    (schools_final_fixed['eotypename'] == 'середня загальноосвітня школа') &
    (schools_final_fixed['eoedrpou'] == '22760881') &
    (schools_final_fixed['KATOTTG'] == 'UA12020050010036263')
)
schools_final_fixed.loc[mask, 'eoedrpou'] = '26462241'

# 3. Медичний коледж (2021–2022)
mask = (
    (schools_final_fixed['eoname'] == 'Фаховий медичний коледж КЗВО "Рівненська медична академія" Рівненської обласної ради') &
    (schools_final_fixed['eotypename'] == 'заклад фахової передвищої освіти') &
    (schools_final_fixed['eoedrpou'] == '25833244') &
    (schools_final_fixed['KATOTTG'] == 'UA56060470010041018')
)
schools_final_fixed.loc[mask, 'eoedrpou'] = '02011545a'

# 4. Медичний коледж (2023)
mask = (
    (schools_final_fixed['eoname'] == 'Фаховий медичний коледж комунального закладу вищої освіти "Рівненська медична академія" Рівненської обласної ради') &
    (schools_final_fixed['eotypename'] == 'заклад фахової передвищої освіти') &
    (schools_final_fixed['eoedrpou'] == '25833244') &
    (schools_final_fixed['KATOTTG'] == 'UA56060470010041018')
)
schools_final_fixed.loc[mask, 'eoedrpou'] = '02011545a'

# 5. Корсунь-Шевченківський ліцей
mask = (
    (schools_final_fixed['eoname'] == 'Корсунь-Шевченківський ліцей Корсунь-Шевченківської міської ради Черкаської області') &
    (schools_final_fixed['eotypename'] == 'ліцей') &
    (schools_final_fixed['eoedrpou'] == '33246632') &
    (schools_final_fixed['year'] == 2024) &
    (schools_final_fixed['KATOTTG'] == 'UA71080170010098381')
)
schools_final_fixed.loc[mask, 'eoedrpou'] = '25769782'

In [121]:
cols_no_year = [c for c in schools_final_fixed.columns if c != 'year']

schools_merged_fixed = (
    schools_final_fixed
    .groupby(cols_no_year, dropna=False)['year']
    .agg(lambda x: ', '.join(map(str, sorted(set(x)))))  # "2019, 2020, 2021"
    .reset_index(name='years')  # нова колонка years
)

schools_merged_fixed = (
    schools_merged_fixed
    .sort_values('eoedrpou')  # сортування по ЄДРПОУ
    .reset_index(drop=True) # оновити індекси, необов'язково
)

schools_merged_fixed.head()

,eoname,eotypename,eoedrpou,KATOTTG,KOATUU,category,id,years
0,Загальноосвітні школи Придністров'я,середня загальноосвітня школа,00000000,UA51100270010196805,5110136900,city,загальноосвтншколиприднстров,"2016, 2017"
1,Фаховий коледж зварювання та електроніки імені...,заклад фахової передвищої освіти,00129314,UA12020010010512802,1210136900,city,коледжзварюванятаелектронкименопатон,"2023, 2024, 2025"
2,Фаховий коледж зварювання та електроніки імені...,заклад фахової передвищої освіти,00129314,UA12020010010512802,1210136900,city,коледжзварюванятаелектронкименопатон,2022
3,Дніпровський технікум зварювання та електронік...,заклад вищої освіти,00129314,UA12020010010512802,1210136900,city,днпровськийтехнкумзварюванятаелектронкименопатон,2019
4,Дніпровський технікум зварювання та електронік...,вищий навчальний заклад I-II рівнів акредитації,00129314,UA12020010010512802,1210136900,city,днпровськийтехнкумзварюванятаелектронкименопатон,2018

In [122]:
key_cols = ['eoedrpou']

def years_to_list(years_str: str) -> list[int]:
    return [int(y.strip()) for y in years_str.split(',') if y.strip()]

def has_duplicate_years(years_lists: list) -> bool:
    """Перевіряє, чи є дублювання років між різними рядками для одного eoedrpou"""
    # збираємо всі роки з усіх рядків
    all_years = []
    for years_list in years_lists:
        all_years.extend(years_list)
    
    # перевіряємо, чи є повторення років
    # якщо кількість унікальних років менша за загальну кількість, значить є дублікати
    return len(all_years) != len(set(all_years))

tmp = schools_merged_fixed.copy()
tmp['years_list'] = tmp['years'].apply(years_to_list)

# для кожної групи перевіряємо, чи є дублювання років
group_has_duplicates = (
    tmp
    .groupby(key_cols)['years_list']
    .agg(lambda lists: has_duplicate_years(lists.tolist()))
)

tmp = tmp.join(group_has_duplicates.rename('has_duplicate_years'), on=key_cols)

# залишаємо тільки ті групи, де є дублювання років
schools_with_duplicate_years = (
    tmp[tmp['has_duplicate_years'] == True]
    .drop(columns=['years_list', 'has_duplicate_years'])
)

print(f"Кількість шкіл з дублюванням років: {schools_with_duplicate_years.shape[0]}")
print(f"Унікальних eoedrpou з дублюванням: {schools_with_duplicate_years['eoedrpou'].nunique()}")
print("\nПриклади:")
schools_with_duplicate_years.head(20)

Кількість шкіл з дублюванням років: 109
Унікальних eoedrpou з дублюванням: 24

Приклади:

,eoname,eotypename,eoedrpou,KATOTTG,KOATUU,category,id,years
942,Черкаська медична академія,вищий навчальний заклад III-IV рівнів акредитації,02011686,UA71080490010259590,7110136700,city,черкаськамедичнаакадем,"2023, 2025"
943,Черкаська медична академія,заклад вищої освіти,02011686,UA71080490010144486,7110136400,city,черкаськамедичнаакадем,"2019, 2020, 2021, 2022, 2023, 2024, 2025"
944,Черкаська медична академія,вищий навчальний заклад I-II рівнів акредитації,02011686,UA71080490010144486,7110136400,city,черкаськамедичнаакадем,2018
1083,"Комунальний заклад Львівської обласної ради ""Л...",заклад фахової передвищої освіти,02136962,UA46060250010515336,4610136900,city,льввськаобласнальввськийколеджспорт,"2023, 2024, 2025"
1084,"Комунальний заклад Львівської обласної ради ""Л...",середня загальноосвітня школа,02136962,UA46060250010515336,4610136900,city,льввськаобласнальввськийколеджспорт,"2021, 2022, 2023"
1085,"Комунальний заклад Львівської обласної ради ""Л...",середня загальноосвітня школа-інтернат,02136962,UA46060250010515336,4610136900,city,льввськаобласнальввськеучилищефзичнакультур,"2016, 2017, 2018, 2019, 2020"
1543,Державний професійно-технічний навчальний закл...,центр професійно-технічної освіти,02541409,UA12020010010512802,1210136900,city,державнийпрофесйнотехнчнийнавчальнийзакладднпр...,"2019, 2020"
1544,Державний професійно-технічний навчальний закл...,заклад професійної (професійно-технічної) освіти,02541409,UA12020010010512802,1210136900,city,державнийпрофесйнотехнчнийнавчальнийзакладднпр...,2021
1545,Державний професійно-технічний навчальний закл...,центр професійно-технічної освіти,02541409,UA12020010010350200,1210138100,city,державнийпрофесйнотехнчнийнавчальнийзакладднпр...,"2019, 2020"
1546,Державний професійно-технічний навчальний закл...,центр професійно-технічної освіти,02541409,UA12020010010757287,1210137800,city,державнийпрофесйнотехнчнийнавчальнийзакладднпр...,2019
1547,Державний професійно-технічний навчальний закл...,заклад професійної (професійно-технічної) освіти,02541409,UA12020010010757287,1210137800,city,державнийпрофесйнотехнчнийнавчальнийзакладднпр...,"2022, 2023, 2024, 2025"
1556,Деожавний професійно-технічний навчальний закл...,центр підготовки і перепідготовки робітничих к...,02541527,UA12040050030016744,1221055800,urban village,деожавнийпрофесйнотехнчнийнавчальнийзакладкамя...,"2019, 2020"
1557,Державний професійно-технічний навчальний закл...,центр підготовки і перепідготовки робітничих к...,02541527,UA12040150010395824,1210436300,city,державнийпрофесйнотехнчнийнавчальнийзакладкамя...,"2019, 2020"
1558,Державний професійно-технічний навчальний закл...,професійно-технічне училище відповідного профілю,02541527,UA12040150010395824,1210436300,city,державнийпрофесйнотехнчнийнавчальнийзакладкамя...,2018
1559,Державний професійно-технічний навчальний закл...,заклад професійної (професійно-технічної) освіти,02541527,UA12040050030016744,1221055800,urban village,державнийпрофесйнотехнчнийнавчальнийзакладкамя...,2021
1560,Державний професійно-технічний навчальний закл...,заклад професійної (професійно-технічної) освіти,02541527,UA12040150010395824,1210436300,city,державнийпрофесйнотехнчнийнавчальнийзакладкамя...,"2023, 2024, 2025"
1561,Державний професійно-технічний навчальний закл...,заклад професійної (професійно-технічної) освіти,02541527,UA12040150010395824,1210436300,city,державнийпрофесйнотехнчнийнавчальнийзакладкамя...,2021
2701,КОМУНАЛЬНИЙ ЗАКЛАД “ДНІПРОПЕТРОВСЬКИЙ ФАХОВИЙ ...,заклад фахової передвищої освіти,04544524,UA12020010010816623,1210136600,city,днпропетровськийколеджспорту”днпропетровськаоб...,"2023, 2024, 2025"
2702,"Комунальний заклад ""Дніпропетровський фаховий ...",середня загальноосвітня школа-інтернат,04544524,UA12020010010816623,1210136600,city,днпропетровськийколеджспортуднпропетровськаобл...,2020
2703,"Комунальний заклад ""Дніпропетровський фаховий ...",спортивний ліцей,04544524,UA12020010010816623,1210136600,city,днпропетровськийколеджспортуднпропетровськаобл...,"2022, 2023"

In [90]:
# schools_with_duplicate_years[schools_with_duplicate_years.eoedrpou=='33246632']

In [91]:
# schools_with_duplicate_years.to_csv('./school_data/schools_with_duplicates_2.csv', index = False)

In [123]:
schools_final_fixed.sort_values('eoedrpou')

,eoname,eotypename,eoedrpou,year,KATOTTG,KOATUU,category,id
4738,Загальноосвітні школи Придністров'я,середня загальноосвітня школа,00000000,2016,UA51100270010196805,5110136900,city,загальноосвтншколиприднстров
20402,Загальноосвітні школи Придністров'я,середня загальноосвітня школа,00000000,2017,UA51100270010196805,5110136900,city,загальноосвтншколиприднстров
92871,Фаховий коледж зварювання та електроніки імені...,заклад фахової передвищої освіти,00129314,2025,UA12020010010512802,1210136900,city,коледжзварюванятаелектронкименопатон
20734,Дніпровський технікум зварювання та електронік...,вищий навчальний заклад I-II рівнів акредитації,00129314,2018,UA12020010010512802,1210136900,city,днпровськийтехнкумзварюванятаелектронкименопатон
70286,Фаховий коледж зварювання та електроніки імені...,заклад фахової передвищої освіти,00129314,2022,UA12020010010512802,1210136900,city,коледжзварюванятаелектронкименопатон
...,...,...,...,...,...,...,...,...
44695,Черепівська загальноосвітня школа I-III ступен...,середня загальноосвітня школа,83126070,2020,UA59020030430042003,5920988801,village,черепвськазагальноосвтняшкола3ступчерепвська
41090,Черепівська загальноосвітня школа I-III ступен...,середня загальноосвітня школа,83126070,2019,UA59020030430042003,5920988801,village,черепвськазагальноосвтняшкола3ступчерепвська
29004,Черепівська загальноосвітня школа I-III ступен...,середня загальноосвітня школа,83126070,2018,UA59020030430042003,5920988801,village,черепвськазагальноосвтняшкола3ступчерепвська
15231,Черепівська загальноосвітня школа I-III ступен...,середня загальноосвітня школа,83126070,2017,UA59020030430042003,5920988801,village,черепвськазагальноосвтняшкола3ступчерепвська
9377,Черепівська загальноосвітня школа I-III ступен...,середня загальноосвітня школа,83126070,2016,UA59020030430042003,5920988801,village,черепвськазагальноосвтняшкола3ступчерепвська

In [93]:
schools_final_fixed.head()

,eoname,eotypename,eoedrpou,year,KATOTTG,KOATUU,category,id
0,"Терпіннівський колегіум ""Джерело"" Мелітопольсь...",колегіум,26373098,2016,UA23080270010078454,2323085101,village,терпнвськийколегумджереломелтопольська
1,Красилівська загальноосвітня школа I-III ступе...,середня загальноосвітня школа,25880114,2016,UA68040210010032567,6822710100,town,красилвськазагальноосвтняшкола3ступ3
2,Чернівецька спеціалізована школа І-ІІІ ступені...,спеціалізована школа,21431046,2016,UA73060610010033137,7310100000,town,чернвецькаспецалзованашкола3ступфзикоматематич...
3,Загальноосвітня школа I-III ступенів № 6 Дружк...,середня загальноосвітня школа,25705061,2016,UA14120030010055241,1411700000,town,загальноосвтняшкола3ступ6дружквська
4,Тернопільська спеціалізована школа І-ІІІ ступе...,спеціалізована школа,14040173,2016,UA61040490010069060,6110100000,town,тернопльськаспецалзованашкола3ступ3зпоглиблени...

In [124]:
schools_final_fixed.to_csv('./school_data/schools_fixed.csv', index = False)

In [128]:
schools_final_fixed.columns

Index(['eoname', 'eotypename', 'eoedrpou', 'year', 'KATOTTG', 'KOATUU',
       'category', 'id'],
      dtype='object')

In [129]:
schools_final_fixed = schools_final_fixed[['eoname', 'eotypename', 'eoedrpou', 'year', 'KATOTTG', 'KOATUU',
       'category']]

In [130]:
schools_final_fixed.to_csv('./matching_data/schools_edrpou.csv', index = False)