# Create `Students` table

In [1]:
import numpy as np
import pandas as pd

from src.dictionaries_translation import *

In [2]:
# load datasets
datasets = {}
years = range(2016, 2026)
for year in years:
    print(f"EIE {year} Loading...")
    if int(year) >= 2019:
        file_name = f'Odata{year}File.csv'
    else:
        file_name = f'OpenData{year}.csv'
    try:           
        dataset = pd.read_csv(f"../../data_loader/{year}/{file_name}", sep=";", encoding='utf-8', dtype = str)
    except:
        dataset = pd.read_csv(f"../../data_loader/{year}/{file_name}", sep=";", encoding='Windows 1251', dtype = str)
    datasets.update({year:dataset})
    print("success")

EIE 2016 Loading...
success
EIE 2017 Loading...
success
EIE 2018 Loading...
success
EIE 2019 Loading...
success
EIE 2020 Loading...
success
EIE 2021 Loading...
success
EIE 2022 Loading...
success
EIE 2023 Loading...
success
EIE 2024 Loading...
success
EIE 2025 Loading...
success

In [3]:
for year, dataset in datasets.items():
    #lowercase all columns and add year as attribute
    dataset.columns = [col.lower() for col in dataset.columns]
    dataset['year'] = year

In [4]:
for year, dataset in datasets.items():
    print(year,":",[col for col in dataset.columns])

2016 : ['outid', 'birth', 'sextypename', 'regname', 'areaname', 'tername', 'regtypename', 'eoname', 'eotypename', 'eoregname', 'eoareaname', 'eotername', 'eoparent', 'ukrtest', 'ukrteststatus', 'ukrball100', 'ukrball12', 'ukrptname', 'ukrptregname', 'ukrptareaname', 'ukrpttername', 'histtest', 'histlang', 'histteststatus', 'histball100', 'histball12', 'histptname', 'histptregname', 'histptareaname', 'histpttername', 'mathtest', 'mathlang', 'mathteststatus', 'mathball100', 'mathball12', 'mathptname', 'mathptregname', 'mathptareaname', 'mathpttername', 'phystest', 'physlang', 'physteststatus', 'physball100', 'physptname', 'physptregname', 'physptareaname', 'physpttername', 'chemtest', 'chemlang', 'chemteststatus', 'chemball100', 'chemptname', 'chemptregname', 'chemptareaname', 'chempttername', 'biotest', 'biolang', 'bioteststatus', 'bioball100', 'bioptname', 'bioptregname', 'bioptareaname', 'biopttername', 'geotest', 'geolang', 'geoteststatus', 'geoball100', 'geoptname', 'geoptregname', 'geoptareaname', 'geopttername', 'engtest', 'engteststatus', 'engball100', 'engptname', 'engptregname', 'engptareaname', 'engpttername', 'frtest', 'frteststatus', 'frball100', 'frptname', 'frptregname', 'frptareaname', 'frpttername', 'deutest', 'deuteststatus', 'deuball100', 'deuptname', 'deuptregname', 'deuptareaname', 'deupttername', 'sptest', 'spteststatus', 'spball100', 'spptname', 'spptregname', 'spptareaname', 'sppttername', 'rustest', 'rusteststatus', 'rusball100', 'rusptname', 'rusptregname', 'rusptareaname', 'ruspttername', 'year']
2017 : ['outid', 'stid', 'birth', 'sextypename', 'regname', 'areaname', 'tername', 'regtypename', 'tertypename', 'classprofilename', 'classlangname', 'eoname', 'eotypename', 'eoregname', 'eoareaname', 'eotername', 'eoparent', 'ukrtest', 'ukrteststatus', 'ukrball100', 'ukrball12', 'ukrptname', 'ukrptregname', 'ukrptareaname', 'ukrpttername', 'histtest', 'histlang', 'histteststatus', 'histball100', 'histball12', 'histptname', 'histptregname', 'histptareaname', 'histpttername', 'mathtest', 'mathlang', 'mathteststatus', 'mathball100', 'mathball12', 'mathptname', 'mathptregname', 'mathptareaname', 'mathpttername', 'phystest', 'physlang', 'physteststatus', 'physball100', 'physball12', 'physptname', 'physptregname', 'physptareaname', 'physpttername', 'chemtest', 'chemlang', 'chemteststatus', 'chemball100', 'chemball12', 'chemptname', 'chemptregname', 'chemptareaname', 'chempttername', 'biotest', 'biolang', 'bioteststatus', 'bioball100', 'bioball12', 'bioptname', 'bioptregname', 'bioptareaname', 'biopttername', 'geotest', 'geolang', 'geoteststatus', 'geoball100', 'geoball12', 'geoptname', 'geoptregname', 'geoptareaname', 'geopttername', 'engtest', 'engteststatus', 'engball100', 'engball12', 'engptname', 'engptregname', 'engptareaname', 'engpttername', 'fratest', 'frateststatus', 'fraball100', 'fraball12', 'fraptname', 'fraptregname', 'fraptareaname', 'frapttername', 'deutest', 'deuteststatus', 'deuball100', 'deuball12', 'deuptname', 'deuptregname', 'deuptareaname', 'deupttername', 'spatest', 'spateststatus', 'spaball100', 'spaball12', 'spaptname', 'spaptregname', 'spaptareaname', 'spapttername', 'rustest', 'rusteststatus', 'rusball100', 'rusball12', 'rusptname', 'rusptregname', 'rusptareaname', 'ruspttername', 'year']
2018 : ['outid', 'birth', 'sextypename', 'regname', 'areaname', 'tername', 'regtypename', 'tertypename', 'classprofilename', 'classlangname', 'eoname', 'eotypename', 'eoregname', 'eoareaname', 'eotername', 'eoparent', 'ukrtest', 'ukrteststatus', 'ukrball100', 'ukrball12', 'ukrball', 'ukrptname', 'ukrptregname', 'ukrptareaname', 'ukrpttername', 'histtest', 'histlang', 'histteststatus', 'histball100', 'histball12', 'histball', 'histptname', 'histptregname', 'histptareaname', 'histpttername', 'mathtest', 'mathlang', 'mathteststatus', 'mathball100', 'mathball12', 'mathball', 'mathptname', 'mathptregname', 'mathptareaname', 'mathpttername', 'phystest', 'physlang', 'physteststatus', 'physball100', 'physball12', 'physball', 'physptname', 'physptregname', 'physptareaname', 'physpttername', 'chemtest', 'chemlang', 'chemteststatus', 'chemball100', 'chemball12', 'chemball', 'chemptname', 'chemptregname', 'chemptareaname', 'chempttername', 'biotest', 'biolang', 'bioteststatus', 'bioball100', 'bioball12', 'bioball', 'bioptname', 'bioptregname', 'bioptareaname', 'biopttername', 'geotest', 'geolang', 'geoteststatus', 'geoball100', 'geoball12', 'geoball', 'geoptname', 'geoptregname', 'geoptareaname', 'geopttername', 'engtest', 'engteststatus', 'engball100', 'engball12', 'engdpalevel', 'engball', 'engptname', 'engptregname', 'engptareaname', 'engpttername', 'fratest', 'frateststatus', 'fraball100', 'fraball12', 'fradpalevel', 'fraball', 'fraptname', 'fraptregname', 'fraptareaname', 'frapttername', 'deutest', 'deuteststatus', 'deuball100', 'deuball12', 'deudpalevel', 'deuball', 'deuptname', 'deuptregname', 'deuptareaname', 'deupttername', 'spatest', 'spateststatus', 'spaball100', 'spaball12', 'spadpalevel', 'spaball', 'spaptname', 'spaptregname', 'spaptareaname', 'spapttername', 'year']
2019 : ['outid', 'birth', 'sextypename', 'regname', 'areaname', 'tername', 'regtypename', 'tertypename', 'classprofilename', 'classlangname', 'eoname', 'eotypename', 'eoregname', 'eoareaname', 'eotername', 'eoparent', 'ukrtest', 'ukrteststatus', 'ukrball100', 'ukrball12', 'ukrball', 'ukradaptscale', 'ukrptname', 'ukrptregname', 'ukrptareaname', 'ukrpttername', 'histtest', 'histlang', 'histteststatus', 'histball100', 'histball12', 'histball', 'histptname', 'histptregname', 'histptareaname', 'histpttername', 'mathtest', 'mathlang', 'mathteststatus', 'mathball100', 'mathball12', 'mathball', 'mathptname', 'mathptregname', 'mathptareaname', 'mathpttername', 'phystest', 'physlang', 'physteststatus', 'physball100', 'physball12', 'physball', 'physptname', 'physptregname', 'physptareaname', 'physpttername', 'chemtest', 'chemlang', 'chemteststatus', 'chemball100', 'chemball12', 'chemball', 'chemptname', 'chemptregname', 'chemptareaname', 'chempttername', 'biotest', 'biolang', 'bioteststatus', 'bioball100', 'bioball12', 'bioball', 'bioptname', 'bioptregname', 'bioptareaname', 'biopttername', 'geotest', 'geolang', 'geoteststatus', 'geoball100', 'geoball12', 'geoball', 'geoptname', 'geoptregname', 'geoptareaname', 'geopttername', 'engtest', 'engteststatus', 'engball100', 'engball12', 'engdpalevel', 'engball', 'engptname', 'engptregname', 'engptareaname', 'engpttername', 'fratest', 'frateststatus', 'fraball100', 'fraball12', 'fradpalevel', 'fraball', 'fraptname', 'fraptregname', 'fraptareaname', 'frapttername', 'deutest', 'deuteststatus', 'deuball100', 'deuball12', 'deudpalevel', 'deuball', 'deuptname', 'deuptregname', 'deuptareaname', 'deupttername', 'spatest', 'spateststatus', 'spaball100', 'spaball12', 'spadpalevel', 'spaball', 'spaptname', 'spaptregname', 'spaptareaname', 'spapttername', 'year']
2020 : ['outid', 'birth', 'sextypename', 'regname', 'areaname', 'tername', 'regtypename', 'tertypename', 'classprofilename', 'classlangname', 'eoname', 'eotypename', 'eoregname', 'eoareaname', 'eotername', 'eoparent', 'ukrtest', 'ukrteststatus', 'ukrball100', 'ukrball12', 'ukrball', 'ukradaptscale', 'ukrptname', 'ukrptregname', 'ukrptareaname', 'ukrpttername', 'histtest', 'histlang', 'histteststatus', 'histball100', 'histball12', 'histball', 'histptname', 'histptregname', 'histptareaname', 'histpttername', 'mathtest', 'mathlang', 'mathteststatus', 'mathball100', 'mathball12', 'mathball', 'mathptname', 'mathptregname', 'mathptareaname', 'mathpttername', 'phystest', 'physlang', 'physteststatus', 'physball100', 'physball12', 'physball', 'physptname', 'physptregname', 'physptareaname', 'physpttername', 'chemtest', 'chemlang', 'chemteststatus', 'chemball100', 'chemball12', 'chemball', 'chemptname', 'chemptregname', 'chemptareaname', 'chempttername', 'biotest', 'biolang', 'bioteststatus', 'bioball100', 'bioball12', 'bioball', 'bioptname', 'bioptregname', 'bioptareaname', 'biopttername', 'geotest', 'geolang', 'geoteststatus', 'geoball100', 'geoball12', 'geoball', 'geoptname', 'geoptregname', 'geoptareaname', 'geopttername', 'engtest', 'engteststatus', 'engball100', 'engball12', 'engdpalevel', 'engball', 'engptname', 'engptregname', 'engptareaname', 'engpttername', 'fratest', 'frateststatus', 'fraball100', 'fraball12', 'fradpalevel', 'fraball', 'fraptname', 'fraptregname', 'fraptareaname', 'frapttername', 'deutest', 'deuteststatus', 'deuball100', 'deuball12', 'deudpalevel', 'deuball', 'deuptname', 'deuptregname', 'deuptareaname', 'deupttername', 'spatest', 'spateststatus', 'spaball100', 'spaball12', 'spadpalevel', 'spaball', 'spaptname', 'spaptregname', 'spaptareaname', 'spapttername', 'year']
2021 : ['outid', 'birth', 'sextypename', 'regname', 'areaname', 'tername', 'regtypename', 'tertypename', 'classprofilename', 'classlangname', 'eoname', 'eotypename', 'eoregname', 'eoareaname', 'eotername', 'eoparent', 'umltest', 'umlteststatus', 'umlball100', 'umlball12', 'umlball', 'umladaptscale', 'umlptname', 'umlptregname', 'umlptareaname', 'umlpttername', 'ukrtest', 'ukrsubtest', 'ukrteststatus', 'ukrball100', 'ukrball12', 'ukrball', 'ukradaptscale', 'ukrptname', 'ukrptregname', 'ukrptareaname', 'ukrpttername', 'histtest', 'histlang', 'histteststatus', 'histball100', 'histball12', 'histball', 'histptname', 'histptregname', 'histptareaname', 'histpttername', 'mathtest', 'mathlang', 'mathteststatus', 'mathball100', 'mathball12', 'mathdpalevel', 'mathball', 'mathptname', 'mathptregname', 'mathptareaname', 'mathpttername', 'mathsttest', 'mathstlang', 'mathstteststatus', 'mathstball12', 'mathstball', 'mathstptname', 'mathstptregname', 'mathstptareaname', 'mathstpttername', 'phystest', 'physlang', 'physteststatus', 'physball100', 'physball12', 'physball', 'physptname', 'physptregname', 'physptareaname', 'physpttername', 'chemtest', 'chemlang', 'chemteststatus', 'chemball100', 'chemball12', 'chemball', 'chemptname', 'chemptregname', 'chemptareaname', 'chempttername', 'biotest', 'biolang', 'bioteststatus', 'bioball100', 'bioball12', 'bioball', 'bioptname', 'bioptregname', 'bioptareaname', 'biopttername', 'geotest', 'geolang', 'geoteststatus', 'geoball100', 'geoball12', 'geoball', 'geoptname', 'geoptregname', 'geoptareaname', 'geopttername', 'engtest', 'engteststatus', 'engball100', 'engball12', 'engdpalevel', 'engball', 'engptname', 'engptregname', 'engptareaname', 'engpttername', 'fratest', 'frateststatus', 'fraball100', 'fraball12', 'fradpalevel', 'fraball', 'fraptname', 'fraptregname', 'fraptareaname', 'frapttername', 'deutest', 'deuteststatus', 'deuball100', 'deuball12', 'deudpalevel', 'deuball', 'deuptname', 'deuptregname', 'deuptareaname', 'deupttername', 'spatest', 'spateststatus', 'spaball100', 'spaball12', 'spadpalevel', 'spaball', 'spaptname', 'spaptregname', 'spaptareaname', 'spapttername', 'year']
2022 : ['outid', 'birth', 'sextypename', 'regname', 'areaname', 'tername', 'regtypename', 'tertypename', 'eoname', 'eotypename', 'eoregname', 'eoareaname', 'eotername', 'eoparent', 'test', 'testdate', 'teststatus', 'block1', 'block1ball100', 'block1ball', 'block2', 'block2ball100', 'block2ball', 'block3', 'block3ball100', 'block3ball', 'ptregname', 'ptareaname', 'pttername', 'year']
2023 : ['outid', 'birth', 'sextypename', 'regname', 'areaname', 'tername', 'regtypename', 'tertypename', 'eoname', 'eotypename', 'eoregname', 'eoareaname', 'eotername', 'eoparent', 'test', 'testdate', 'ukrblock', 'ukrblockstatus', 'ukrblockball100', 'ukrblockball', 'histblock', 'histblockstatus', 'histblockball100', 'histblockball', 'mathblock', 'mathblockstatus', 'mathblockball100', 'mathblockball', 'physblock', 'physblockstatus', 'physblockball100', 'physblockball', 'chemblock', 'chemblockstatus', 'chemblockball100', 'chemblockball', 'bioblock', 'bioblockstatus', 'bioblockball100', 'bioblockball', 'engblock', 'engblockstatus', 'engblockball100', 'engblockball', 'frablock', 'frablockstatus', 'frablockball100', 'frablockball', 'deublock', 'deublockstatus', 'deublockball100', 'deublockball', 'spablock', 'spablockstatus', 'spablockball100', 'spablockball', 'ptregname', 'ptareaname', 'pttername', 'year']
2024 : ['outid', 'birth', 'sextypename', 'regname', 'areaname', 'tername', 'regtypename', 'tertypename', 'eoname', 'eotypename', 'eoregname', 'eoareaname', 'eotername', 'eoparent', 'test', 'testdate', 'ukrblock', 'ukrblockstatus', 'ukrblockball100', 'ukrblockball', 'histblock', 'histblocklang', 'histblockstatus', 'histblockball100', 'histblockball', 'mathblock', 'mathblocklang', 'mathblockstatus', 'mathblockball100', 'mathblockball', 'physblock', 'physblocklang', 'physblockstatus', 'physblockball100', 'physblockball', 'chemblock', 'chemblocklang', 'chemblockstatus', 'chemblockball100', 'chemblockball', 'bioblock', 'bioblocklang', 'bioblockstatus', 'bioblockball100', 'bioblockball', 'geoblock', 'geoblocklang', 'geoblockstatus', 'geoblockball100', 'geoblockball', 'engblock', 'engblockstatus', 'engblockball100', 'engblockball', 'frablock', 'frablockstatus', 'frablockball100', 'frablockball', 'deublock', 'deublockstatus', 'deublockball100', 'deublockball', 'spablock', 'spablockstatus', 'spablockball100', 'spablockball', 'ukrlitblock', 'ukrlitblockstatus', 'ukrlitblockball100', 'ukrlitblockball', 'ptregname', 'ptareaname', 'pttername', 'year']
2025 : ['outid', 'birth', 'sextypename', 'regname', 'areaname', 'tername', 'regtypename', 'tertypename', 'eoname', 'eotypename', 'eoregname', 'eoareaname', 'eotername', 'eoparent', 'eoedrpou', 'eoedeboid', 'test', 'testdate', 'ukrblock', 'ukrblockstatus', 'ukrblockball100', 'ukrblockball', 'histblock', 'histblocklang', 'histblockstatus', 'histblockball100', 'histblockball', 'mathblock', 'mathblocklang', 'mathblockstatus', 'mathblockball100', 'mathblockball', 'physblock', 'physblocklang', 'physblockstatus', 'physblockball100', 'physblockball', 'chemblock', 'chemblocklang', 'chemblockstatus', 'chemblockball100', 'chemblockball', 'bioblock', 'bioblocklang', 'bioblockstatus', 'bioblockball100', 'bioblockball', 'geoblock', 'geoblocklang', 'geoblockstatus', 'geoblockball100', 'geoblockball', 'engblock', 'engblockstatus', 'engblockball100', 'engblockball', 'frablock', 'frablockstatus', 'frablockball100', 'frablockball', 'deublock', 'deublockstatus', 'deublockball100', 'deublockball', 'spablock', 'spablockstatus', 'spablockball100', 'spablockball', 'ukrlitblock', 'ukrlitblockstatus', 'ukrlitblockball100', 'ukrlitblockball', 'ptregname', 'ptareaname', 'pttername', 'year']

In [5]:
for year, dataset in datasets.items():
    print(year)
    print('Dataset Length: ', len(dataset),'  Outid unique values: ', len(dataset['outid'].unique()))

2016
Dataset Length:  268003   Outid unique values:  268003
2017
Dataset Length:  240889   Outid unique values:  240889
2018
Dataset Length:  335687   Outid unique values:  335687
2019
Dataset Length:  353813   Outid unique values:  353813
2020
Dataset Length:  379299   Outid unique values:  379299
2021
Dataset Length:  389323   Outid unique values:  389323
2022
Dataset Length:  234104   Outid unique values:  234104
2023
Dataset Length:  288935   Outid unique values:  288935
2024
Dataset Length:  312508   Outid unique values:  312508
2025
Dataset Length:  317091   Outid unique values:  317091

In [6]:
# check if outid is unique for all years
outid = []
for year, dataset in datasets.items():
    outid.append(dataset['outid'].unique())
outid = np.concatenate(outid)
print('Outid unique values: ', len(np.unique(outid)))
# all datasets length
print('All datasets length: ', sum([len(dataset) for dataset in datasets.values()]))

Outid unique values:  3119652
All datasets length:  3119652

In [7]:
cols = set()
for year, dataset in datasets.items():
    cols.update(col for col in dataset.columns if 'math' not in col and 'bio' not in col and 'block' not in col and 'chem' not in col and 'deu' not in col and 'eng' not in col and 'fra' not in col and 'fr' not in col and 'geo' not in col and 'hist' not in col and 'hist' not in col and 'phys' not in col and 'pt' not in col and 'rus' not in col and 'spa' not in col and 'ukr' not in col and 'uml' not in col)

cols

{'areaname',
 'birth',
 'classlangname',
 'classprofilename',
 'eoareaname',
 'eoedeboid',
 'eoedrpou',
 'eoname',
 'eoparent',
 'eoregname',
 'eotername',
 'eotypename',
 'outid',
 'regname',
 'regtypename',
 'sextypename',
 'spball100',
 'stid',
 'tername',
 'tertypename',
 'test',
 'testdate',
 'teststatus',
 'year'}

In [8]:
# student related columns
student_columns = ['outid', 'birth', 'sextypename', 'regname', 'areaname', 'tername', 'regtypename',
                   'classprofilename', 'classlangname', 'eoname', 'eotypename','eoregname', 'eoareaname', 'eotername', 'year']

In [9]:
students_df = pd.DataFrame(columns=student_columns)

In [10]:
for year, dataset in datasets.items():
    for col in student_columns:
        if col not in dataset.columns:
            print(f"{col} not in {year} dataset")
            dataset[col] = None
    students_df = pd.concat([students_df, pd.DataFrame(dataset.loc[:, student_columns])], ignore_index=True)

students_df

classprofilename not in 2016 dataset
classlangname not in 2016 dataset
classprofilename not in 2022 dataset
classlangname not in 2022 dataset
classprofilename not in 2023 dataset
classlangname not in 2023 dataset
classprofilename not in 2024 dataset
classlangname not in 2024 dataset
classprofilename not in 2025 dataset
classlangname not in 2025 dataset

,outid,birth,sextypename,regname,areaname,tername,regtypename,classprofilename,classlangname,eoname,eotypename,eoregname,eoareaname,eotername,year
0,a99c6c63-aa70-4aec-ba42-370f7261e857,1998,чоловіча,Запорізька область,Мелітопольський район,с.Терпіння,Випускник загальноосвітнього навчального закла...,None,None,"Терпіннівський колегіум ""Джерело"" Мелітопольсь...",колегіум,Запорізька область,Мелітопольський район,с.Терпіння,2016
1,c3136421-569e-422e-ae8f-41c4c931fd70,1998,жіноча,Хмельницька область,Красилівський район,м.Красилів,Випускник загальноосвітнього навчального закла...,None,None,Красилівська загальноосвітня школа I-III ступе...,середня загальноосвітня школа,Хмельницька область,Красилівський район,м.Красилів,2016
2,fbd0e280-4b77-4f34-942d-00bc850c2992,1995,жіноча,Дніпропетровська область,Петропавлівський район,с.Дмитрівка,Випускник минулих років,None,None,NaN,NaN,NaN,NaN,NaN,2016
3,30de395e-7a74-452a-8370-6856d240fbfb,1999,чоловіча,Чернівецька область,м.Чернівці,Шевченківський район міста,Випускник загальноосвітнього навчального закла...,None,None,Чернівецька спеціалізована школа І-ІІІ ступені...,спеціалізована школа,Чернівецька область,м.Чернівці,Шевченківський район міста,2016
4,52a40c74-374e-4744-bd6f-938ab7a4a641,1997,чоловіча,Миколаївська область,Врадіївський район,с.Кумарі,"Учень (слухач, студент) професійно-технічного,...",None,None,NaN,NaN,NaN,NaN,NaN,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3119647,9e703a35-81af-47bc-b4a9-ff5c468c3756,2008,жіноча,м.Київ,м.Київ,Голосіївський район міста,Випускник поточного року,None,None,Ліцей № 59 міста Києва,ліцей,м.Київ,м.Київ,Голосіївський район міста,2025
3119648,9e67ab46-0359-4ae7-9996-ff970ac16a6c,2007,чоловіча,Полтавська область,Кременчуцький район,м.Горішні Плавні,Випускник поточного року,None,None,"Відокремлений структурний підрозділ ""Політехні...",заклад фахової передвищої освіти,Полтавська область,Кременчуцький район,м.Горішні Плавні,2025
3119649,9e8606ee-f67b-4b37-b01a-ffa775e99884,2002,жіноча,Закарпатська область,Берегівський район,м.Берегове,Випускник минулих років,None,None,NaN,NaN,NaN,NaN,NaN,2025
3119650,9e77b512-e760-4796-9e7d-ffa8998f2e1a,2008,чоловіча,Одеська область,Березівський район,с-ще Радісне,Випускник поточного року,None,None,Радісненський ліцей Знам'янської сільської ради,середня загальноосвітня школа,Одеська область,Березівський район,с-ще Радісне,2025
3119651,9e86d68a-a9f3-4932-a693-fff4bd2650f9,2008,чоловіча,Закарпатська область,Хустський район,с-ще Міжгір'я,Випускник поточного року,None,None,"Комунальний заклад ""Міжгірський медичний фахов...",заклад фахової передвищої освіти,Закарпатська область,Хустський район,с-ще Міжгір'я,2025

In EIE 2016 and both NMT tests(2022-2025) - we do not have 'classprofilename', 'classlangname' columns. So we fill them with 'None' values.

In [11]:
students_df.drop_duplicates(inplace=True)

students_df.dropna(subset=students_df.columns.difference(['year']), 
                      how = 'all', inplace=True)
students_df.reset_index(drop=True, inplace=True)
students_df

,outid,birth,sextypename,regname,areaname,tername,regtypename,classprofilename,classlangname,eoname,eotypename,eoregname,eoareaname,eotername,year
0,a99c6c63-aa70-4aec-ba42-370f7261e857,1998,чоловіча,Запорізька область,Мелітопольський район,с.Терпіння,Випускник загальноосвітнього навчального закла...,None,None,"Терпіннівський колегіум ""Джерело"" Мелітопольсь...",колегіум,Запорізька область,Мелітопольський район,с.Терпіння,2016
1,c3136421-569e-422e-ae8f-41c4c931fd70,1998,жіноча,Хмельницька область,Красилівський район,м.Красилів,Випускник загальноосвітнього навчального закла...,None,None,Красилівська загальноосвітня школа I-III ступе...,середня загальноосвітня школа,Хмельницька область,Красилівський район,м.Красилів,2016
2,fbd0e280-4b77-4f34-942d-00bc850c2992,1995,жіноча,Дніпропетровська область,Петропавлівський район,с.Дмитрівка,Випускник минулих років,None,None,NaN,NaN,NaN,NaN,NaN,2016
3,30de395e-7a74-452a-8370-6856d240fbfb,1999,чоловіча,Чернівецька область,м.Чернівці,Шевченківський район міста,Випускник загальноосвітнього навчального закла...,None,None,Чернівецька спеціалізована школа І-ІІІ ступені...,спеціалізована школа,Чернівецька область,м.Чернівці,Шевченківський район міста,2016
4,52a40c74-374e-4744-bd6f-938ab7a4a641,1997,чоловіча,Миколаївська область,Врадіївський район,с.Кумарі,"Учень (слухач, студент) професійно-технічного,...",None,None,NaN,NaN,NaN,NaN,NaN,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3119647,9e703a35-81af-47bc-b4a9-ff5c468c3756,2008,жіноча,м.Київ,м.Київ,Голосіївський район міста,Випускник поточного року,None,None,Ліцей № 59 міста Києва,ліцей,м.Київ,м.Київ,Голосіївський район міста,2025
3119648,9e67ab46-0359-4ae7-9996-ff970ac16a6c,2007,чоловіча,Полтавська область,Кременчуцький район,м.Горішні Плавні,Випускник поточного року,None,None,"Відокремлений структурний підрозділ ""Політехні...",заклад фахової передвищої освіти,Полтавська область,Кременчуцький район,м.Горішні Плавні,2025
3119649,9e8606ee-f67b-4b37-b01a-ffa775e99884,2002,жіноча,Закарпатська область,Берегівський район,м.Берегове,Випускник минулих років,None,None,NaN,NaN,NaN,NaN,NaN,2025
3119650,9e77b512-e760-4796-9e7d-ffa8998f2e1a,2008,чоловіча,Одеська область,Березівський район,с-ще Радісне,Випускник поточного року,None,None,Радісненський ліцей Знам'янської сільської ради,середня загальноосвітня школа,Одеська область,Березівський район,с-ще Радісне,2025
3119651,9e86d68a-a9f3-4932-a693-fff4bd2650f9,2008,чоловіча,Закарпатська область,Хустський район,с-ще Міжгір'я,Випускник поточного року,None,None,"Комунальний заклад ""Міжгірський медичний фахов...",заклад фахової передвищої освіти,Закарпатська область,Хустський район,с-ще Міжгір'я,2025

In [12]:
# check whether there are duplicates by outid
students_df[students_df.duplicated(subset=['outid'], keep=False)]

Empty DataFrame
Columns: [outid, birth, sextypename, regname, areaname, tername, regtypename, classprofilename, classlangname, eoname, eotypename, eoregname, eoareaname, eotername, year]
Index: []

## Added location column id

In [13]:
# load location dictionary
locations = pd.read_csv('./matching_data/locations.csv', encoding='utf-8', dtype=str)
locations

,regname,areaname,tername,KOATUU,KATOTTG,category,region_name
0,Запорізька область,Мелітопольський район,с.Терпіння,2323085101,UA23080270010078454,village,Zaporizka
1,Хмельницька область,Красилівський район,м.Красилів,6822710100,UA68040210010032567,town,Khmelnytska
2,Дніпропетровська область,Петропавлівський район,с.Дмитрівка,1223881501,UA12140170040016918,village,Dnipropetrovska
3,Чернівецька область,м.Чернівці,Шевченківський район міста,7310100000,UA73060610010033137,town,Chernivetska
4,Миколаївська область,Врадіївський район,с.Кумарі,4822383001,UA48080050190079797,village,Mykolaivska
...,...,...,...,...,...,...,...
30028,Одеська область,м.Південне,м.Південне,5111700000,UA51100410010044384,town,Odeska
30029,Нідерланди,м.Гаага,м.Гаага,0018030000,OC18030000000000000,abroad,Netherlands
30030,США,м.Воррен,м.Воррен,0026010000,OC26010000000000000,abroad,United States of America
30031,Польща,м.Домброва-Гурнича,м.Домброва-Гурнича,0021050000,OC21050000000000000,abroad,Poland
30032,Туреччина,м.Стамбул,м.Стамбул,0027030000,OC27030000000000000,abroad,Turkey

In [14]:
# check whether there are duplicates
locations[locations.duplicated(subset=['regname', 'areaname', 'tername'], keep=False)]

Empty DataFrame
Columns: [regname, areaname, tername, KOATUU, KATOTTG, category, region_name]
Index: []

In [15]:
# add location codifier
students_loc_df = students_df.merge(locations[['regname', 'areaname', 'tername', 'KOATUU', 'KATOTTG']], on=['regname', 'areaname', 'tername'], how='left')

students_loc_df

,outid,birth,sextypename,regname,areaname,tername,regtypename,classprofilename,classlangname,eoname,eotypename,eoregname,eoareaname,eotername,year,KOATUU,KATOTTG
0,a99c6c63-aa70-4aec-ba42-370f7261e857,1998,чоловіча,Запорізька область,Мелітопольський район,с.Терпіння,Випускник загальноосвітнього навчального закла...,None,None,"Терпіннівський колегіум ""Джерело"" Мелітопольсь...",колегіум,Запорізька область,Мелітопольський район,с.Терпіння,2016,2323085101,UA23080270010078454
1,c3136421-569e-422e-ae8f-41c4c931fd70,1998,жіноча,Хмельницька область,Красилівський район,м.Красилів,Випускник загальноосвітнього навчального закла...,None,None,Красилівська загальноосвітня школа I-III ступе...,середня загальноосвітня школа,Хмельницька область,Красилівський район,м.Красилів,2016,6822710100,UA68040210010032567
2,fbd0e280-4b77-4f34-942d-00bc850c2992,1995,жіноча,Дніпропетровська область,Петропавлівський район,с.Дмитрівка,Випускник минулих років,None,None,NaN,NaN,NaN,NaN,NaN,2016,1223881501,UA12140170040016918
3,30de395e-7a74-452a-8370-6856d240fbfb,1999,чоловіча,Чернівецька область,м.Чернівці,Шевченківський район міста,Випускник загальноосвітнього навчального закла...,None,None,Чернівецька спеціалізована школа І-ІІІ ступені...,спеціалізована школа,Чернівецька область,м.Чернівці,Шевченківський район міста,2016,7310100000,UA73060610010033137
4,52a40c74-374e-4744-bd6f-938ab7a4a641,1997,чоловіча,Миколаївська область,Врадіївський район,с.Кумарі,"Учень (слухач, студент) професійно-технічного,...",None,None,NaN,NaN,NaN,NaN,NaN,2016,4822383001,UA48080050190079797
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3119647,9e703a35-81af-47bc-b4a9-ff5c468c3756,2008,жіноча,м.Київ,м.Київ,Голосіївський район міста,Випускник поточного року,None,None,Ліцей № 59 міста Києва,ліцей,м.Київ,м.Київ,Голосіївський район міста,2025,8036100000,UA80000000000126643
3119648,9e67ab46-0359-4ae7-9996-ff970ac16a6c,2007,чоловіча,Полтавська область,Кременчуцький район,м.Горішні Плавні,Випускник поточного року,None,None,"Відокремлений структурний підрозділ ""Політехні...",заклад фахової передвищої освіти,Полтавська область,Кременчуцький район,м.Горішні Плавні,2025,5310200000,UA53020030010087471
3119649,9e8606ee-f67b-4b37-b01a-ffa775e99884,2002,жіноча,Закарпатська область,Берегівський район,м.Берегове,Випускник минулих років,None,None,NaN,NaN,NaN,NaN,NaN,2025,2110200000,UA21020030010083215
3119650,9e77b512-e760-4796-9e7d-ffa8998f2e1a,2008,чоловіча,Одеська область,Березівський район,с-ще Радісне,Випускник поточного року,None,None,Радісненський ліцей Знам'янської сільської ради,середня загальноосвітня школа,Одеська область,Березівський район,с-ще Радісне,2025,5121855600,UA51020070020067764
3119651,9e86d68a-a9f3-4932-a693-fff4bd2650f9,2008,чоловіча,Закарпатська область,Хустський район,с-ще Міжгір'я,Випускник поточного року,None,None,"Комунальний заклад ""Міжгірський медичний фахов...",заклад фахової передвищої освіти,Закарпатська область,Хустський район,с-ще Міжгір'я,2025,2122455100,UA21120190010094897

In [16]:
students_loc_df[students_loc_df.KOATUU.isna()]

,outid,birth,sextypename,regname,areaname,tername,regtypename,classprofilename,classlangname,eoname,eotypename,eoregname,eoareaname,eotername,year,KOATUU,KATOTTG
144704,3b07c9d4-067c-47fa-8cf4-8e2097ade009,1999,чоловіча,Дніпропетровська область,Дніпропетровська область,Петропавлівський район,"Учень (слухач, студент) професійно-технічного,...",None,None,NaN,NaN,NaN,NaN,NaN,2016,NaN,NaN

In [17]:
# it is problem row, so we will drop it
students_loc_df.dropna(subset=['KOATUU'], inplace=True)

In [18]:
# drop names
students_loc_df = students_loc_df[['outid',  'birth', 'sextypename', 'regtypename', 'classprofilename', 'classlangname', 
                                   'KOATUU', 'KATOTTG',  'eoname', 'eotypename', 'eoregname', 'eoareaname', 'eotername', 'year']].copy()
students_loc_df

,outid,birth,sextypename,regtypename,classprofilename,classlangname,KOATUU,KATOTTG,eoname,eotypename,eoregname,eoareaname,eotername,year
0,a99c6c63-aa70-4aec-ba42-370f7261e857,1998,чоловіча,Випускник загальноосвітнього навчального закла...,None,None,2323085101,UA23080270010078454,"Терпіннівський колегіум ""Джерело"" Мелітопольсь...",колегіум,Запорізька область,Мелітопольський район,с.Терпіння,2016
1,c3136421-569e-422e-ae8f-41c4c931fd70,1998,жіноча,Випускник загальноосвітнього навчального закла...,None,None,6822710100,UA68040210010032567,Красилівська загальноосвітня школа I-III ступе...,середня загальноосвітня школа,Хмельницька область,Красилівський район,м.Красилів,2016
2,fbd0e280-4b77-4f34-942d-00bc850c2992,1995,жіноча,Випускник минулих років,None,None,1223881501,UA12140170040016918,NaN,NaN,NaN,NaN,NaN,2016
3,30de395e-7a74-452a-8370-6856d240fbfb,1999,чоловіча,Випускник загальноосвітнього навчального закла...,None,None,7310100000,UA73060610010033137,Чернівецька спеціалізована школа І-ІІІ ступені...,спеціалізована школа,Чернівецька область,м.Чернівці,Шевченківський район міста,2016
4,52a40c74-374e-4744-bd6f-938ab7a4a641,1997,чоловіча,"Учень (слухач, студент) професійно-технічного,...",None,None,4822383001,UA48080050190079797,NaN,NaN,NaN,NaN,NaN,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3119647,9e703a35-81af-47bc-b4a9-ff5c468c3756,2008,жіноча,Випускник поточного року,None,None,8036100000,UA80000000000126643,Ліцей № 59 міста Києва,ліцей,м.Київ,м.Київ,Голосіївський район міста,2025
3119648,9e67ab46-0359-4ae7-9996-ff970ac16a6c,2007,чоловіча,Випускник поточного року,None,None,5310200000,UA53020030010087471,"Відокремлений структурний підрозділ ""Політехні...",заклад фахової передвищої освіти,Полтавська область,Кременчуцький район,м.Горішні Плавні,2025
3119649,9e8606ee-f67b-4b37-b01a-ffa775e99884,2002,жіноча,Випускник минулих років,None,None,2110200000,UA21020030010083215,NaN,NaN,NaN,NaN,NaN,2025
3119650,9e77b512-e760-4796-9e7d-ffa8998f2e1a,2008,чоловіча,Випускник поточного року,None,None,5121855600,UA51020070020067764,Радісненський ліцей Знам'янської сільської ради,середня загальноосвітня школа,Одеська область,Березівський район,с-ще Радісне,2025
3119651,9e86d68a-a9f3-4932-a693-fff4bd2650f9,2008,чоловіча,Випускник поточного року,None,None,2122455100,UA21120190010094897,"Комунальний заклад ""Міжгірський медичний фахов...",заклад фахової передвищої освіти,Закарпатська область,Хустський район,с-ще Міжгір'я,2025

In [19]:
students_loc_df[students_loc_df.eoname.notna()]

,outid,birth,sextypename,regtypename,classprofilename,classlangname,KOATUU,KATOTTG,eoname,eotypename,eoregname,eoareaname,eotername,year
0,a99c6c63-aa70-4aec-ba42-370f7261e857,1998,чоловіча,Випускник загальноосвітнього навчального закла...,None,None,2323085101,UA23080270010078454,"Терпіннівський колегіум ""Джерело"" Мелітопольсь...",колегіум,Запорізька область,Мелітопольський район,с.Терпіння,2016
1,c3136421-569e-422e-ae8f-41c4c931fd70,1998,жіноча,Випускник загальноосвітнього навчального закла...,None,None,6822710100,UA68040210010032567,Красилівська загальноосвітня школа I-III ступе...,середня загальноосвітня школа,Хмельницька область,Красилівський район,м.Красилів,2016
3,30de395e-7a74-452a-8370-6856d240fbfb,1999,чоловіча,Випускник загальноосвітнього навчального закла...,None,None,7310100000,UA73060610010033137,Чернівецька спеціалізована школа І-ІІІ ступені...,спеціалізована школа,Чернівецька область,м.Чернівці,Шевченківський район міста,2016
5,852ca6ab-7fbd-40ad-ae51-39dc94edc9e1,1999,жіноча,Випускник загальноосвітнього навчального закла...,None,None,1411700000,UA14120030010055241,Загальноосвітня школа I-III ступенів № 6 Дружк...,середня загальноосвітня школа,Донецька область,Донецька область,м.Дружківка,2016
6,bc9b70ca-c091-440f-b1de-f04b308f3a54,1999,чоловіча,Випускник загальноосвітнього навчального закла...,None,None,6110100000,UA61040490010069060,Тернопільська спеціалізована школа І-ІІІ ступе...,спеціалізована школа,Тернопільська область,Тернопільська область,м.Тернопіль,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3119646,9e5e362f-2b5d-4aa1-b3e9-ff49a50fdc6c,2007,жіноча,Випускник поточного року,None,None,4423810100,UA44120070010080343,"КОМУНАЛЬНА УСТАНОВА ""ПОПАСНЯНСЬКИЙ ЛІЦЕЙ №1 ІМ...",ліцей,Луганська область,Сіверськодонецький район,м.Попасна,2025
3119647,9e703a35-81af-47bc-b4a9-ff5c468c3756,2008,жіноча,Випускник поточного року,None,None,8036100000,UA80000000000126643,Ліцей № 59 міста Києва,ліцей,м.Київ,м.Київ,Голосіївський район міста,2025
3119648,9e67ab46-0359-4ae7-9996-ff970ac16a6c,2007,чоловіча,Випускник поточного року,None,None,5310200000,UA53020030010087471,"Відокремлений структурний підрозділ ""Політехні...",заклад фахової передвищої освіти,Полтавська область,Кременчуцький район,м.Горішні Плавні,2025
3119650,9e77b512-e760-4796-9e7d-ffa8998f2e1a,2008,чоловіча,Випускник поточного року,None,None,5121855600,UA51020070020067764,Радісненський ліцей Знам'янської сільської ради,середня загальноосвітня школа,Одеська область,Березівський район,с-ще Радісне,2025
3119651,9e86d68a-a9f3-4932-a693-fff4bd2650f9,2008,чоловіча,Випускник поточного року,None,None,2122455100,UA21120190010094897,"Комунальний заклад ""Міжгірський медичний фахов...",заклад фахової передвищої освіти,Закарпатська область,Хустський район,с-ще Міжгір'я,2025

## Added school column id

**Note:** not all participants have school id, because if they graduated from schools before we will not have this information.

In [20]:
# separate dataset to with schools and without
students_loc_df_with_schools = students_loc_df[students_loc_df.eoname.notna()].copy()
students_loc_df_without_schools = students_loc_df[students_loc_df.eoname.isna()].copy()

print('With schools: ', len(students_loc_df_with_schools), '\nWithout schools: ', len(students_loc_df_without_schools))

With schools:  2592926
Without schools:  526725

#### School KOATUU codes

In [21]:
location_school = locations.rename(columns={'KOATUU':'KOATUU_school', 'KATOTTG':'KATOTTG_school', 'regname':'eoregname', 'areaname':'eoareaname', 'tername':'eotername'})
location_school.head()

,eoregname,eoareaname,eotername,KOATUU_school,KATOTTG_school,category,region_name
0,Запорізька область,Мелітопольський район,с.Терпіння,2323085101,UA23080270010078454,village,Zaporizka
1,Хмельницька область,Красилівський район,м.Красилів,6822710100,UA68040210010032567,town,Khmelnytska
2,Дніпропетровська область,Петропавлівський район,с.Дмитрівка,1223881501,UA12140170040016918,village,Dnipropetrovska
3,Чернівецька область,м.Чернівці,Шевченківський район міста,7310100000,UA73060610010033137,town,Chernivetska
4,Миколаївська область,Врадіївський район,с.Кумарі,4822383001,UA48080050190079797,village,Mykolaivska

In [22]:
# check whether there are duplicates
location_school[location_school.duplicated(subset=['eoregname', 'eoareaname', 'eotername'], keep=False)]

Empty DataFrame
Columns: [eoregname, eoareaname, eotername, KOATUU_school, KATOTTG_school, category, region_name]
Index: []

In [73]:
students_loc_df_with_schools_loc = students_loc_df_with_schools.merge(
    location_school[['eoregname', 'eoareaname', 'eotername', 'KOATUU_school', 'KATOTTG_school']], 
    on=['eoregname', 'eoareaname', 'eotername'], 
    how='left'
)
students_loc_df_with_schools_loc

,outid,birth,sextypename,regtypename,classprofilename,classlangname,KOATUU,KATOTTG,eoname,eotypename,eoregname,eoareaname,eotername,year,KOATUU_school,KATOTTG_school
0,a99c6c63-aa70-4aec-ba42-370f7261e857,1998,чоловіча,Випускник загальноосвітнього навчального закла...,None,None,2323085101,UA23080270010078454,"Терпіннівський колегіум ""Джерело"" Мелітопольсь...",колегіум,Запорізька область,Мелітопольський район,с.Терпіння,2016,2323085101,UA23080270010078454
1,c3136421-569e-422e-ae8f-41c4c931fd70,1998,жіноча,Випускник загальноосвітнього навчального закла...,None,None,6822710100,UA68040210010032567,Красилівська загальноосвітня школа I-III ступе...,середня загальноосвітня школа,Хмельницька область,Красилівський район,м.Красилів,2016,6822710100,UA68040210010032567
2,30de395e-7a74-452a-8370-6856d240fbfb,1999,чоловіча,Випускник загальноосвітнього навчального закла...,None,None,7310100000,UA73060610010033137,Чернівецька спеціалізована школа І-ІІІ ступені...,спеціалізована школа,Чернівецька область,м.Чернівці,Шевченківський район міста,2016,7310100000,UA73060610010033137
3,852ca6ab-7fbd-40ad-ae51-39dc94edc9e1,1999,жіноча,Випускник загальноосвітнього навчального закла...,None,None,1411700000,UA14120030010055241,Загальноосвітня школа I-III ступенів № 6 Дружк...,середня загальноосвітня школа,Донецька область,Донецька область,м.Дружківка,2016,1411700000,UA14120030010055241
4,bc9b70ca-c091-440f-b1de-f04b308f3a54,1999,чоловіча,Випускник загальноосвітнього навчального закла...,None,None,6110100000,UA61040490010069060,Тернопільська спеціалізована школа І-ІІІ ступе...,спеціалізована школа,Тернопільська область,Тернопільська область,м.Тернопіль,2016,6110100000,UA61040490010069060
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2592921,9e5e362f-2b5d-4aa1-b3e9-ff49a50fdc6c,2007,жіноча,Випускник поточного року,None,None,4423810100,UA44120070010080343,"КОМУНАЛЬНА УСТАНОВА ""ПОПАСНЯНСЬКИЙ ЛІЦЕЙ №1 ІМ...",ліцей,Луганська область,Сіверськодонецький район,м.Попасна,2025,4423810100,UA44120070010080343
2592922,9e703a35-81af-47bc-b4a9-ff5c468c3756,2008,жіноча,Випускник поточного року,None,None,8036100000,UA80000000000126643,Ліцей № 59 міста Києва,ліцей,м.Київ,м.Київ,Голосіївський район міста,2025,8036100000,UA80000000000126643
2592923,9e67ab46-0359-4ae7-9996-ff970ac16a6c,2007,чоловіча,Випускник поточного року,None,None,5310200000,UA53020030010087471,"Відокремлений структурний підрозділ ""Політехні...",заклад фахової передвищої освіти,Полтавська область,Кременчуцький район,м.Горішні Плавні,2025,5310200000,UA53020030010087471
2592924,9e77b512-e760-4796-9e7d-ffa8998f2e1a,2008,чоловіча,Випускник поточного року,None,None,5121855600,UA51020070020067764,Радісненський ліцей Знам'янської сільської ради,середня загальноосвітня школа,Одеська область,Березівський район,с-ще Радісне,2025,5121855600,UA51020070020067764
2592925,9e86d68a-a9f3-4932-a693-fff4bd2650f9,2008,чоловіча,Випускник поточного року,None,None,2122455100,UA21120190010094897,"Комунальний заклад ""Міжгірський медичний фахов...",заклад фахової передвищої освіти,Закарпатська область,Хустський район,с-ще Міжгір'я,2025,2122455100,UA21120190010094897

In [74]:
students_loc_df_with_schools_loc[students_loc_df_with_schools_loc.KATOTTG_school.isna()]

,outid,birth,sextypename,regtypename,classprofilename,classlangname,KOATUU,KATOTTG,eoname,eotypename,eoregname,eoareaname,eotername,year,KOATUU_school,KATOTTG_school
28999,39e01292-ae14-4ee5-a27f-a55fd2c72952,1999,жіноча,Випускник загальноосвітнього навчального закла...,None,None,4624883201,UA46120110270041867,"Лучицький навчально-виховний комплекс ""Загальн...",навчально-виховний комплекс,Львівська область,Львівська область,Сокальський район,2016,NaN,NaN
99255,106e21b4-285d-4e9d-bc09-844c89ba1fd7,1999,чоловіча,Випускник загальноосвітнього навчального закла...,None,None,4624883201,UA46120110270041867,"Лучицький навчально-виховний комплекс ""Загальн...",навчально-виховний комплекс,Львівська область,Львівська область,Сокальський район,2016,NaN,NaN
100232,e84a0dca-f2c0-44c9-8dcc-99302b687da2,1998,чоловіча,Випускник загальноосвітнього навчального закла...,None,None,4624883203,UA46120110580099609,"Лучицький навчально-виховний комплекс ""Загальн...",навчально-виховний комплекс,Львівська область,Львівська область,Сокальський район,2016,NaN,NaN
123586,b2248dcf-06d2-4686-a4f3-f1e26c2cc855,1998,жіноча,Випускник загальноосвітнього навчального закла...,None,None,4624880201,UA46120110030014377,"Лучицький навчально-виховний комплекс ""Загальн...",навчально-виховний комплекс,Львівська область,Львівська область,Сокальський район,2016,NaN,NaN
161138,f57b22c9-cbef-42fd-8729-bda122857e71,1998,чоловіча,Випускник загальноосвітнього навчального закла...,None,None,4624883203,UA46120110580099609,"Лучицький навчально-виховний комплекс ""Загальн...",навчально-виховний комплекс,Львівська область,Львівська область,Сокальський район,2016,NaN,NaN
183789,9508aabb-33a9-4e18-8666-16def1c5e8de,1999,жіноча,Випускник загальноосвітнього навчального закла...,None,None,4624883203,UA46120110580099609,"Лучицький навчально-виховний комплекс ""Загальн...",навчально-виховний комплекс,Львівська область,Львівська область,Сокальський район,2016,NaN,NaN
188801,80be0e6b-2ae1-4cf3-89cb-e5cc903f1cc5,1999,жіноча,Випускник загальноосвітнього навчального закла...,None,None,4624880202,UA46120110250037736,"Лучицький навчально-виховний комплекс ""Загальн...",навчально-виховний комплекс,Львівська область,Львівська область,Сокальський район,2016,NaN,NaN
198778,5b5e05a3-76cd-4160-8a2f-7513bdbfe5dc,1999,чоловіча,Випускник загальноосвітнього навчального закла...,None,None,4624883203,UA46120110580099609,"Лучицький навчально-виховний комплекс ""Загальн...",навчально-виховний комплекс,Львівська область,Львівська область,Сокальський район,2016,NaN,NaN

In [75]:
# set the corresponding KOATUU
to_set = students_loc_df_with_schools_loc[students_loc_df_with_schools_loc.KATOTTG_school.isna()].outid.unique()
for id in to_set:
    students_loc_df_with_schools_loc.loc[students_loc_df_with_schools_loc.outid == id, 'KOATUU_school'] = '4624883201'
    students_loc_df_with_schools_loc.loc[students_loc_df_with_schools_loc.outid == id, 'KATOTTG_school'] = 'UA46120110270041867'

In [76]:
schools_df = pd.read_csv('./matching_data/schools_edrpou.csv', encoding='utf-8', dtype=str)
schools_df

,eoname,eotypename,eoedrpou,year,KATOTTG,KOATUU,category
0,"Терпіннівський колегіум ""Джерело"" Мелітопольсь...",колегіум,26373098,2016,UA23080270010078454,2323085101,village
1,Красилівська загальноосвітня школа I-III ступе...,середня загальноосвітня школа,25880114,2016,UA68040210010032567,6822710100,town
2,Чернівецька спеціалізована школа І-ІІІ ступені...,спеціалізована школа,21431046,2016,UA73060610010033137,7310100000,town
3,Загальноосвітня школа I-III ступенів № 6 Дружк...,середня загальноосвітня школа,25705061,2016,UA14120030010055241,1411700000,town
4,Тернопільська спеціалізована школа І-ІІІ ступе...,спеціалізована школа,14040173,2016,UA61040490010069060,6110100000,town
...,...,...,...,...,...,...,...
99895,"Ходорівське відділення ВСП ""Технічний фаховий ...",заклад фахової передвищої освіти,05393837a,2025,UA46100270010046817,4621510500,town
99896,"ТОВАРИСТВО З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ ""ПРИВА...",гімназія,42372041,2025,UA80000000000210193,8036300000,city
99897,"Гаївська філія ""Початкова школа-заклад дошкіль...",початкова школа,25038104б,2025,UA51140150050060575,5123981101,village
99898,Вільшанська філія Романівського ліцею №2 Роман...,гімназія,45498834,2025,UA18040470090069061,1821481001,village
99899,Одеська державна академія будівництва та архіт...,вищий навчальний заклад III-IV рівнів акредитації,02071033,2025,UA51100270010320268,5110137500,city

In [77]:
schools_df[schools_df.duplicated(subset=['eoname', 'eotypename', 'year', 'KATOTTG'], keep=False)]

Empty DataFrame
Columns: [eoname, eotypename, eoedrpou, year, KATOTTG, KOATUU, category]
Index: []

In [78]:
schools_df.columns

Index(['eoname', 'eotypename', 'eoedrpou', 'year', 'KATOTTG', 'KOATUU',
       'category'],
      dtype='object')

In [79]:
schools_df = schools_df[['eoname', 'eotypename', 'eoedrpou', 'year', 'KATOTTG']]

In [80]:
schools_df = schools_df.rename(columns={'KATOTTG':'KATOTTG_school'})

In [81]:
students_loc_df_with_schools_loc['year'] = students_loc_df_with_schools_loc.year.astype(int)
schools_df['year'] = schools_df.year.astype(int)

In [82]:
# add edrpou to students
students_loc_df_with_schools_loc = students_loc_df_with_schools_loc.merge(
    schools_df, 
    on=['eoname', 'eotypename', 'KATOTTG_school', 'year'], 
    how='left'
)

students_loc_df_with_schools_loc

,outid,birth,sextypename,regtypename,classprofilename,classlangname,KOATUU,KATOTTG,eoname,eotypename,eoregname,eoareaname,eotername,year,KOATUU_school,KATOTTG_school,eoedrpou
0,a99c6c63-aa70-4aec-ba42-370f7261e857,1998,чоловіча,Випускник загальноосвітнього навчального закла...,None,None,2323085101,UA23080270010078454,"Терпіннівський колегіум ""Джерело"" Мелітопольсь...",колегіум,Запорізька область,Мелітопольський район,с.Терпіння,2016,2323085101,UA23080270010078454,26373098
1,c3136421-569e-422e-ae8f-41c4c931fd70,1998,жіноча,Випускник загальноосвітнього навчального закла...,None,None,6822710100,UA68040210010032567,Красилівська загальноосвітня школа I-III ступе...,середня загальноосвітня школа,Хмельницька область,Красилівський район,м.Красилів,2016,6822710100,UA68040210010032567,25880114
2,30de395e-7a74-452a-8370-6856d240fbfb,1999,чоловіча,Випускник загальноосвітнього навчального закла...,None,None,7310100000,UA73060610010033137,Чернівецька спеціалізована школа І-ІІІ ступені...,спеціалізована школа,Чернівецька область,м.Чернівці,Шевченківський район міста,2016,7310100000,UA73060610010033137,21431046
3,852ca6ab-7fbd-40ad-ae51-39dc94edc9e1,1999,жіноча,Випускник загальноосвітнього навчального закла...,None,None,1411700000,UA14120030010055241,Загальноосвітня школа I-III ступенів № 6 Дружк...,середня загальноосвітня школа,Донецька область,Донецька область,м.Дружківка,2016,1411700000,UA14120030010055241,25705061
4,bc9b70ca-c091-440f-b1de-f04b308f3a54,1999,чоловіча,Випускник загальноосвітнього навчального закла...,None,None,6110100000,UA61040490010069060,Тернопільська спеціалізована школа І-ІІІ ступе...,спеціалізована школа,Тернопільська область,Тернопільська область,м.Тернопіль,2016,6110100000,UA61040490010069060,14040173
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2592921,9e5e362f-2b5d-4aa1-b3e9-ff49a50fdc6c,2007,жіноча,Випускник поточного року,None,None,4423810100,UA44120070010080343,"КОМУНАЛЬНА УСТАНОВА ""ПОПАСНЯНСЬКИЙ ЛІЦЕЙ №1 ІМ...",ліцей,Луганська область,Сіверськодонецький район,м.Попасна,2025,4423810100,UA44120070010080343,33225015
2592922,9e703a35-81af-47bc-b4a9-ff5c468c3756,2008,жіноча,Випускник поточного року,None,None,8036100000,UA80000000000126643,Ліцей № 59 міста Києва,ліцей,м.Київ,м.Київ,Голосіївський район міста,2025,8036100000,UA80000000000126643,22879323
2592923,9e67ab46-0359-4ae7-9996-ff970ac16a6c,2007,чоловіча,Випускник поточного року,None,None,5310200000,UA53020030010087471,"Відокремлений структурний підрозділ ""Політехні...",заклад фахової передвищої освіти,Полтавська область,Кременчуцький район,м.Горішні Плавні,2025,5310200000,UA53020030010087471,39248242
2592924,9e77b512-e760-4796-9e7d-ffa8998f2e1a,2008,чоловіча,Випускник поточного року,None,None,5121855600,UA51020070020067764,Радісненський ліцей Знам'янської сільської ради,середня загальноосвітня школа,Одеська область,Березівський район,с-ще Радісне,2025,5121855600,UA51020070020067764,22502305
2592925,9e86d68a-a9f3-4932-a693-fff4bd2650f9,2008,чоловіча,Випускник поточного року,None,None,2122455100,UA21120190010094897,"Комунальний заклад ""Міжгірський медичний фахов...",заклад фахової передвищої освіти,Закарпатська область,Хустський район,с-ще Міжгір'я,2025,2122455100,UA21120190010094897,02010729

In [83]:
students_loc_df_with_schools_loc[students_loc_df_with_schools_loc.eoedrpou.isna()]

,outid,birth,sextypename,regtypename,classprofilename,classlangname,KOATUU,KATOTTG,eoname,eotypename,eoregname,eoareaname,eotername,year,KOATUU_school,KATOTTG_school,eoedrpou
26431,56fdae62-9aa5-463b-9069-250a38567ba1,1999,жіноча,Випускник загальноосвітнього навчального закла...,None,None,5122583401,UA51120090080083006,"Лабушненський навчально-виховний комплекс ""Заг...",навчально-виховний комплекс,Одеська область,Кодимський район,с.Лабушне,2016,5122583401,UA51120090080083006,NaN
45900,143963a7-fbde-4230-aacd-1cf84d3e6666,1999,жіноча,Випускник загальноосвітнього навчального закла...,None,None,5122583401,UA51120090080083006,"Лабушненський навчально-виховний комплекс ""Заг...",навчально-виховний комплекс,Одеська область,Кодимський район,с.Лабушне,2016,5122583401,UA51120090080083006,NaN
57842,bb8aa4b9-0205-4a34-ae19-31691976ef6e,1998,чоловіча,Випускник загальноосвітнього навчального закла...,None,None,5122583401,UA51120090080083006,"Лабушненський навчально-виховний комплекс ""Заг...",навчально-виховний комплекс,Одеська область,Кодимський район,с.Лабушне,2016,5122583401,UA51120090080083006,NaN
79490,1bcc646b-6b3a-4018-a9e3-9888ff9363dc,2000,жіноча,Випускник загальноосвітнього навчального закла...,None,None,5122582601,UA51120090060088330,"Івашківський навчально-виховний комплекс ""Заг...",навчально-виховний комплекс,Одеська область,Кодимський район,с.Івашків,2016,5122582601,UA51120090060088330,NaN
82582,636c691c-9d7a-4e3d-ad94-da77ec44f543,1998,жіноча,Випускник загальноосвітнього навчального закла...,None,None,5122582601,UA51120090060088330,"Івашківський навчально-виховний комплекс ""Заг...",навчально-виховний комплекс,Одеська область,Кодимський район,с.Івашків,2016,5122582601,UA51120090060088330,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2583627,9e67e0a1-6420-4055-875f-e6a170ab3e22,2007,чоловіча,Випускник поточного року,None,None,5322610100,UA53060190010016735,Лохвицька гімназія №1 Лохвицької міської ради ...,середня загальноосвітня школа,Полтавська область,Миргородський район,м.Лохвиця,2025,5322610100,UA53060190010016735,NaN
2583698,9e660891-77eb-451a-a6e3-7c426099542a,2008,чоловіча,Випускник поточного року,None,None,4810136300,UA48060150010139573,"Комунальний заклад фахової передвищої освіти ""...",навчально-виховний комплекс,Миколаївська область,м.Миколаїв,Заводський район міста,2025,4810136300,UA48060150010139573,NaN
2585533,9e9275b7-6bf3-4ae2-a7f4-f7c653efe746,2007,жіноча,Випускник поточного року,None,None,4610136600,UA46060250010121390,Комунальний заклад вищої освіти Львівської обл...,вищий навчальний заклад III-IV рівнів акредитації,Львівська область,м.Львів,Галицький район міста,2025,4610136600,UA46060250010121390,NaN
2587424,9e67ea50-6e35-48b7-b290-a4d65bcd6d12,2008,жіноча,Випускник поточного року,None,None,5322610100,UA53060190010016735,Лохвицька гімназія №1 Лохвицької міської ради ...,середня загальноосвітня школа,Полтавська область,Миргородський район,м.Лохвиця,2025,5322610100,UA53060190010016735,NaN
2587843,9e684ff4-d551-4c5a-b9e8-ac464e8bed6d,2008,жіноча,Випускник поточного року,None,None,4610136600,UA46060250010121390,Комунальний заклад вищої освіти Львівської обл...,вищий навчальний заклад III-IV рівнів акредитації,Львівська область,м.Львів,Галицький район міста,2025,4610136600,UA46060250010121390,NaN

In [84]:
students_loc_df_with_schools_loc[students_loc_df_with_schools_loc.eoedrpou.isna()].eoname.unique()

array(['Лабушненський навчально-виховний комплекс "Загальноосвітня школа I-III ступенів - дошкільний навчальний заклад" Кодимської районної ради Одеської області\r\n',
       ' Івашківський навчально-виховний комплекс "Загальноосвітня школа I-III ступенів - дошкільний навчальний заклад" Кодимської районної ради Одеської області\r\n',
       'Олександрівський навчально-виховний комплекс "загальноосвітня школа І-ІІІ ступенів - ДНЗ" Любашівського району\r\n',
       'Олександрівський навчально-виховний комплекс "загальноосвітня школа І-ІІІ ступенів - ДНЗ" Любашівського району',
       'Лабушненський навчально-виховний комплекс "Загальноосвітня школа I-III ступенів - дошкільний навчальний заклад" Кодимської районної ради Одеської області',
       'Івашківський навчально-виховний комплекс "Загальноосвітня школа I-III ступенів - дошкільний навчальний заклад" Кодимської районної ради Одеської області',
       'ДОНЕЦЬКЕ ВИЩЕ УЧИЛИЩЕ ОЛІМПІЙСЬКОГО РЕЗЕРВУ ІМ.С.БУБКИ',
       'Данилівський заклад загальної середньої освіти І-ІІІ ступенів Хустської міської ради Закарпатської області',
       'Відокремлений структурний підрозділ "Олімпійський фаховий коледж імені Івана Піддубного Національного університету фізичного виховання і спорту України"',
       'Лохвицька гімназія №1 Лохвицької міської ради Полтавської області',
       'Ставищенський ліцей №1 Ставищенської селищної ради Білоцерківського району Київської області',
       'Комунальний заклад фахової передвищої освіти "Миколаївський фаховий коледж фізичної культури" Миколаївської обласної ради',
       'Комунальний заклад вищої освіти Львівської обласної ради "Львівська медична академія імені Андрея Крупинського"'],
      dtype=object)

In [ ]:
students_loc_df_with_schools_loc[students_loc_df_with_schools_loc.duplicated(subset=['outid','EDRPOU'], keep=False)]

Empty DataFrame
Columns: [outid, birth, sextypename, regtypename, classprofilename, classlangname, eoname, KOATUU_2020, KATOTTG_2023, eoregname, eoareaname, eotername, year, KOATUU_2020_school, KATOTTG_2023_school, EDRPOU]
Index: []

In [ ]:
students_loc_df_with_schools_loc = students_loc_df_with_schools_loc[['outid', 'birth', 'sextypename', 'classprofilename', 'regtypename',
                                                             'classlangname', 'KOATUU_2020', 'KATOTTG_2023', 'EDRPOU', 'year']].reset_index(drop=True)
print('With schools: ', len(students_loc_df_with_schools_loc))
students_loc_df_with_schools_loc.head()

With schools:  2122303

,outid,birth,sextypename,classprofilename,regtypename,classlangname,KOATUU_2020,KATOTTG_2023,EDRPOU,year
0,a99c6c63-aa70-4aec-ba42-370f7261e857,1998,чоловіча,None,Випускник загальноосвітнього навчального закла...,None,2323085101,UA23080270010078454,26373098,2016
1,c3136421-569e-422e-ae8f-41c4c931fd70,1998,жіноча,None,Випускник загальноосвітнього навчального закла...,None,6822710100,UA68040210010032567,25880114,2016
2,30de395e-7a74-452a-8370-6856d240fbfb,1999,чоловіча,None,Випускник загальноосвітнього навчального закла...,None,7310100000,UA73060610010033137,21431046,2016
3,852ca6ab-7fbd-40ad-ae51-39dc94edc9e1,1999,жіноча,None,Випускник загальноосвітнього навчального закла...,None,1411700000,UA14120030010055241,25705061,2016
4,bc9b70ca-c091-440f-b1de-f04b308f3a54,1999,чоловіча,None,Випускник загальноосвітнього навчального закла...,None,6110100000,UA61040490010069060,14040173,2016

In [ ]:
students_loc_df_with_schools_loc[students_loc_df_with_schools_loc.EDRPOU.isna()]

Empty DataFrame
Columns: [outid, birth, sextypename, classprofilename, regtypename, classlangname, KOATUU_2020, KATOTTG_2023, EDRPOU, year]
Index: []

In [ ]:
students_loc_df_without_schools = students_loc_df_without_schools[['outid', 'birth', 'sextypename', 'classprofilename', 'regtypename',
                                                             'classlangname', 'KOATUU_2020', 'KATOTTG_2023', 'year']].reset_index(drop=True)
students_loc_df_without_schools['EDRPOU'] = None
print('Without schools: ', len(students_loc_df_without_schools))
students_loc_df_without_schools.head()

Without schools:  367749

,outid,birth,sextypename,classprofilename,regtypename,classlangname,KOATUU_2020,KATOTTG_2023,year,EDRPOU
0,fbd0e280-4b77-4f34-942d-00bc850c2992,1995,жіноча,None,Випускник минулих років,None,1223881501,UA12140170040016918,2016,None
1,52a40c74-374e-4744-bd6f-938ab7a4a641,1997,чоловіча,None,"Учень (слухач, студент) професійно-технічного,...",None,4822383001,UA48080050190079797,2016,None
2,debd6e87-f3a1-483c-bb02-10b56d78ea0d,1995,чоловіча,None,Випускник минулих років,None,1211600000,UA12080050010010114,2016,None
3,6934408b-ff44-495c-9151-8c8c6313a0fa,1995,жіноча,None,Випускник минулих років,None,1210136900,UA12020010010512802,2016,None
4,2b2a1159-caed-48b4-9828-ce2307ff90fa,1997,чоловіча,None,Випускник минулих років,None,1210137800,UA12020010010757287,2016,None

In [ ]:
# merge datasets
students_loc_df = pd.concat([students_loc_df_with_schools_loc, students_loc_df_without_schools], ignore_index=True)
print('All students: ', len(students_loc_df))
students_loc_df.head()

All students:  2490052

,outid,birth,sextypename,classprofilename,regtypename,classlangname,KOATUU_2020,KATOTTG_2023,EDRPOU,year
0,a99c6c63-aa70-4aec-ba42-370f7261e857,1998,чоловіча,None,Випускник загальноосвітнього навчального закла...,None,2323085101,UA23080270010078454,26373098,2016
1,c3136421-569e-422e-ae8f-41c4c931fd70,1998,жіноча,None,Випускник загальноосвітнього навчального закла...,None,6822710100,UA68040210010032567,25880114,2016
2,30de395e-7a74-452a-8370-6856d240fbfb,1999,чоловіча,None,Випускник загальноосвітнього навчального закла...,None,7310100000,UA73060610010033137,21431046,2016
3,852ca6ab-7fbd-40ad-ae51-39dc94edc9e1,1999,жіноча,None,Випускник загальноосвітнього навчального закла...,None,1411700000,UA14120030010055241,25705061,2016
4,bc9b70ca-c091-440f-b1de-f04b308f3a54,1999,чоловіча,None,Випускник загальноосвітнього навчального закла...,None,6110100000,UA61040490010069060,14040173,2016

# Translation

In [ ]:
students_loc_df["sextypename"].replace(sex_type_dict,  inplace=True)
students_loc_df["classprofilename"].replace(class_profile_dict,  inplace=True)
students_loc_df["classlangname"].replace(lang_dict,  inplace=True)

In [ ]:
students_loc_df.rename(columns={"EDRPOU": "EDRPOU_school"}, inplace=True)

In [ ]:
students_loc_df[students_loc_df.year == 2023].regtypename.unique()

array(['Випускник закладу загальної середньої освіти 2023 року',
       'Установа виконання покарань', 'Випускник минулих років'],
      dtype=object)

In [ ]:
translation_map = {
  'Випускник загальноосвітнього навчального закладу 2016 року': 'A graduate of an Ukrainian school of the current year',
  'Випускник загальноосвітнього навчального закладу 2017 року': 'A graduate of an Ukrainian school of the current year',
  'Випускник закладу загальної середньої освіти 2018 року': 'A graduate of an Ukrainian school of the current year',
  'Випускник закладу загальної середньої освіти 2019 року': 'A graduate of an Ukrainian school of the current year',
  'випускник закладу загальної середньої освіти 2020 року': 'A graduate of an Ukrainian school of the current year',
  'Випускник загальноосвітнього навчального закладу 2021 року': 'A graduate of an Ukrainian school of the current year',
  'Випускник закладу загальної середньої освіти 2022 року': 'A graduate of an Ukrainian school of the current year',
  'Випускник закладу загальної середньої освіти 2023 року': 'A graduate of an Ukrainian school of the current year',
  'Учень (слухач, студент) професійно-технічного, вищого навчального закладу':'A student of a higher/vocational pre-higher education institution',
  'Учень (слухач) закладу професійної (професійно-технічної) освіти':'A graduate of a vocational pre-higher education institution',
  'Установа виконання покарань': "The institution of punishment",
  'Випускник минулих років': "A graduate of previous years",
  'Випускник, який здобуде в 2016 році повну загальну середню освіту в навчальному закладі іншої держави':'A graduate of a foreign school',
  'Випускник, який здобуде в 2017 році повну загальну середню освіту в навчальному закладі іншої держави':'A graduate of a foreign school',
  'Випускник, який здобуде в 2018 році повну загальну середню освіту в навчальному закладі іншої держави':'A graduate of a foreign school',
  'Випускник, який здобуде в 2019 році повну загальну середню освіту в закордонному закладі освіти':'A graduate of a foreign school',
  'Випускник, який здобуде в 2020 році повну загальну середню освіту в закордонному закладі освіти':'A graduate of a foreign school',
  'Випускник, який здобуде в 2021 році повну загальну середню освіту в навчальному закладі іншої держави':'A graduate of a foreign school',
  'Випускник, який здобуде в 2022 році повну загальну середню освіту в закордонному закладі освіти':'A graduate of a foreign school',
  'Студент закладу вищої освіти':'A student of a higher education institution',
  'Студент закладу вищої/фахової передвищої освіти':'A student of a higher/vocational pre-higher education institution'
}

students_loc_df.loc[:, 'regtypename'] = students_loc_df['regtypename'].map(translation_map)
students_loc_df.head()

,outid,birth,sextypename,classprofilename,regtypename,classlangname,KOATUU_2020,KATOTTG_2023,EDRPOU_school,year
0,a99c6c63-aa70-4aec-ba42-370f7261e857,1998,Male,None,A graduate of an Ukrainian school of the curre...,None,2323085101,UA23080270010078454,26373098,2016
1,c3136421-569e-422e-ae8f-41c4c931fd70,1998,Female,None,A graduate of an Ukrainian school of the curre...,None,6822710100,UA68040210010032567,25880114,2016
2,30de395e-7a74-452a-8370-6856d240fbfb,1999,Male,None,A graduate of an Ukrainian school of the curre...,None,7310100000,UA73060610010033137,21431046,2016
3,852ca6ab-7fbd-40ad-ae51-39dc94edc9e1,1999,Female,None,A graduate of an Ukrainian school of the curre...,None,1411700000,UA14120030010055241,25705061,2016
4,bc9b70ca-c091-440f-b1de-f04b308f3a54,1999,Male,None,A graduate of an Ukrainian school of the curre...,None,6110100000,UA61040490010069060,14040173,2016

In [ ]:
students_loc_df.regtypename.unique()

array(['A graduate of an Ukrainian school of the current year',
       'The institution of punishment', 'A graduate of previous years',
       'A graduate of a foreign school',
       'A graduate of a vocational pre-higher education institution',
       'A student of a higher education institution',
       'A student of a higher/vocational pre-higher education institution'],
      dtype=object)

In [ ]:
# update all nan values to None
students_loc_df = students_loc_df.where(pd.notnull(students_loc_df), '')

In [ ]:
set(schools_df.EDRPOU) - set(students_loc_df.EDRPOU_school)

set()

In [ ]:
set(students_loc_df.EDRPOU_school) - set(schools_df.EDRPOU)

{''}

## Save table to csv file

In [ ]:
students_loc_df= students_loc_df.drop(columns=['KOATUU_2020'])
students_loc_df

,outid,birth,sextypename,classprofilename,regtypename,classlangname,KATOTTG_2023,EDRPOU_school,year
0,a99c6c63-aa70-4aec-ba42-370f7261e857,1998,Male,,A graduate of an Ukrainian school of the curre...,,UA23080270010078454,26373098,2016
1,c3136421-569e-422e-ae8f-41c4c931fd70,1998,Female,,A graduate of an Ukrainian school of the curre...,,UA68040210010032567,25880114,2016
2,30de395e-7a74-452a-8370-6856d240fbfb,1999,Male,,A graduate of an Ukrainian school of the curre...,,UA73060610010033137,21431046,2016
3,852ca6ab-7fbd-40ad-ae51-39dc94edc9e1,1999,Female,,A graduate of an Ukrainian school of the curre...,,UA14120030010055241,25705061,2016
4,bc9b70ca-c091-440f-b1de-f04b308f3a54,1999,Male,,A graduate of an Ukrainian school of the curre...,,UA61040490010069060,14040173,2016
...,...,...,...,...,...,...,...,...,...
2490047,98f773cf-4b79-425b-a415-2eb5dd097199,2003,Male,,A graduate of previous years,,UA59020070010054283,,2023
2490048,98dc27ec-1801-4741-b8f7-3a2ca8b6e772,1996,Female,,A graduate of previous years,,UA32100010010059200,,2023
2490049,995cc588-5c44-45bd-8f0c-3f70ff1e746e,2004,Female,,A graduate of previous years,,UA56080170010061049,,2023
2490050,98fc3ab5-1d6c-44ec-8e5e-3fd5e1dd3d24,2005,Female,,A graduate of previous years,,UA51100270010320268,,2023
2490051,98de6ea2-28f3-4951-990a-9a3ff45449de,2004,Male,,A graduate of previous years,,UA07060190010068509,,2023

In [ ]:
students_loc_df[students_loc_df.KATOTTG_2023.isna()]

Empty DataFrame
Columns: [outid, birth, sextypename, classprofilename, regtypename, classlangname, KATOTTG_2023, EDRPOU_school, year]
Index: []

In [ ]:
# save dataframe
students_loc_df.to_csv("./final_tables/students.csv", index=False)

# Fix the issue with status of the paricipant

In [ ]:
students_loc_df = pd.read_csv("./final_tables/students.csv", encoding='utf-8', dtype=str)

In [ ]:
schools = pd.read_csv('./final_tables/schools_edrpou.csv', encoding='utf-8', dtype=str)
schools.rename(columns = {'EDRPOU':'EDRPOU_school'}, inplace=True)
schools

,KATOTTG_2023,EDRPOU_school,year,eotypename
0,UA05020030010063857,04601943,2023,заклад фахової передвищої освіти
1,UA05020030010063857,00419667,2022,заклад фахової передвищої освіти
2,UA05020030010063857,03065891,2018,вище професійне училище
3,UA05020030010063857,03065891,2019,вище професійне училище
4,UA05020030010063857,03065891,2020,вище професійне училище
...,...,...,...,...
82508,UA80000000001078669,26125905,2017,середня загальноосвітня школа
82509,UA80000000001078669,26125940,2020,середня загальноосвітня школа
82510,UA80000000001078669,26125940,2021,середня загальноосвітня школа
82511,UA80000000001078669,26125940,2022,середня загальноосвітня школа
82512,UA80000000001078669,26125940,2023,середня загальноосвітня школа

In [ ]:
students_status = students_loc_df.merge(schools[['EDRPOU_school', 'year', 'eotypename']], on = ['EDRPOU_school', 'year'], how = 'left')
students_status

,outid,birth,sextypename,classprofilename,regtypename,classlangname,KATOTTG_2023,EDRPOU_school,year,eotypename
0,a99c6c63-aa70-4aec-ba42-370f7261e857,1998,Male,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA23080270010078454,26373098,2016,колегіум
1,c3136421-569e-422e-ae8f-41c4c931fd70,1998,Female,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA68040210010032567,25880114,2016,середня загальноосвітня школа
2,30de395e-7a74-452a-8370-6856d240fbfb,1999,Male,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA73060610010033137,21431046,2016,спеціалізована школа
3,852ca6ab-7fbd-40ad-ae51-39dc94edc9e1,1999,Female,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA14120030010055241,25705061,2016,середня загальноосвітня школа
4,bc9b70ca-c091-440f-b1de-f04b308f3a54,1999,Male,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA61040490010069060,14040173,2016,спеціалізована школа
...,...,...,...,...,...,...,...,...,...,...
2490047,98f773cf-4b79-425b-a415-2eb5dd097199,2003,Male,NaN,A graduate of previous years,NaN,UA59020070010054283,NaN,2023,NaN
2490048,98dc27ec-1801-4741-b8f7-3a2ca8b6e772,1996,Female,NaN,A graduate of previous years,NaN,UA32100010010059200,NaN,2023,NaN
2490049,995cc588-5c44-45bd-8f0c-3f70ff1e746e,2004,Female,NaN,A graduate of previous years,NaN,UA56080170010061049,NaN,2023,NaN
2490050,98fc3ab5-1d6c-44ec-8e5e-3fd5e1dd3d24,2005,Female,NaN,A graduate of previous years,NaN,UA51100270010320268,NaN,2023,NaN
2490051,98de6ea2-28f3-4951-990a-9a3ff45449de,2004,Male,NaN,A graduate of previous years,NaN,UA07060190010068509,NaN,2023,NaN

In [ ]:
students_status.regtypename.unique()

array(['A graduate of an Ukrainian school of the current year',
       'The institution of punishment', 'A graduate of previous years',
       'A graduate of a foreign school',
       'A graduate of a vocational pre-higher education institution',
       'A student of a higher education institution',
       'A student of a higher/vocational pre-higher education institution'],
      dtype=object)

In [ ]:
students_status.eotypename.unique()

array(['колегіум', 'середня загальноосвітня школа',
       'спеціалізована школа', 'навчально-виховний комплекс',
       'вечірня (змінна) школа', 'ліцей',
       'середня загальноосвітня школа-інтернат', 'гімназія',
       'спеціалізована школа-інтернат', 'загальноосвітня санаторна школа',
       'Пенітенціарна установа',
       'спеціальна загальноосвітня школа-інтернат',
       'спеціальна загальноосвітня школа',
       'школа соціальної реабілітації',
       'вищий навчальний заклад I-II рівнів акредитації',
       "навчально-виховне об'єднання",
       'професійний ліцей відповідного профілю',
       'вище професійне училище',
       'професійно-технічне училище відповідного профілю',
       'центр професійно-технічної освіти',
       'заклад фахової передвищої освіти/ліцей',
       'вище художнє професійно-технічне училище',
       'центр професійної освіти', 'заклад вищої освіти',
       'заклад фахової передвищої освіти', 'коледж',
       'центр підготовки і перепідготовки робітничих кадрів',
       'навчально-реабілітаційний центр',
       'заклад професійної (професійно-технічної) освіти',
       'колегіум/колеж', 'мистецький ліцей', 'науковий ліцей',
       'ліцей із посиленою військово-фізичною підготовкою',
       'спортивний ліцей', 'спеціальна школа',
       'військовий (військово-морський, військово-спортивний) ліцей',
       'початкова школа', nan], dtype=object)

In [ ]:
right_status = {'колегіум':'A graduate of an Ukrainian school of the current year',
                'середня загальноосвітня школа':'A graduate of an Ukrainian school of the current year',
                'спеціалізована школа':'A graduate of an Ukrainian school of the current year',
                'навчально-виховний комплекс':'A graduate of an Ukrainian school of the current year',
                'вечірня (змінна) школа':'A graduate of an Ukrainian school of the current year', 
                'ліцей':'A graduate of an Ukrainian school of the current year',
                'середня загальноосвітня школа-інтернат':'A graduate of an Ukrainian school of the current year', 
                'гімназія':'A graduate of an Ukrainian school of the current year',
                'спеціалізована школа-інтернат':'A graduate of an Ukrainian school of the current year',
                'загальноосвітня санаторна школа':'A graduate of an Ukrainian school of the current year',
                'Пенітенціарна установа':'The institution of punishment',
                'спеціальна загальноосвітня школа-інтернат':'A graduate of an Ukrainian school of the current year',
                'спеціальна загальноосвітня школа':'A graduate of an Ukrainian school of the current year',
                'школа соціальної реабілітації':'A graduate of an Ukrainian school of the current year',
                'вищий навчальний заклад I-II рівнів акредитації':'A graduate of a vocational pre-higher education institution',
                "навчально-виховне об'єднання":'A graduate of an Ukrainian school of the current year',
                'професійний ліцей відповідного профілю':'A graduate of a vocational pre-higher education institution',
                'вище професійне училище':'A graduate of a vocational pre-higher education institution',
                'професійно-технічне училище відповідного профілю':'A graduate of a vocational pre-higher education institution',
                'центр професійно-технічної освіти':'A graduate of a vocational pre-higher education institution',
                'заклад фахової передвищої освіти/ліцей':'A graduate of a vocational pre-higher education institution',
                'вище художнє професійно-технічне училище':'A graduate of a vocational pre-higher education institution',
                'центр професійної освіти':'A graduate of a vocational pre-higher education institution',
                'заклад вищої освіти':'A graduate of a vocational pre-higher education institution',
                'заклад фахової передвищої освіти':'A graduate of a vocational pre-higher education institution',
                'коледж':'A graduate of a vocational pre-higher education institution',
                'центр підготовки і перепідготовки робітничих кадрів':'A graduate of a vocational pre-higher education institution',
                'навчально-реабілітаційний центр':'A graduate of a vocational pre-higher education institution',
                'заклад професійної (професійно-технічної) освіти':'A graduate of a vocational pre-higher education institution',
                'колегіум/колеж':'A graduate of an Ukrainian school of the current year',
                'мистецький ліцей':'A graduate of an Ukrainian school of the current year',
                'науковий ліцей':'A graduate of an Ukrainian school of the current year',
                'ліцей із посиленою військово-фізичною підготовкою':'A graduate of an Ukrainian school of the current year',
                'спортивний ліцей':'A graduate of an Ukrainian school of the current year',
                'спеціальна школа':'A graduate of an Ukrainian school of the current year',
                'військовий (військово-морський, військово-спортивний) ліцей':'A graduate of an Ukrainian school of the current year',
                'початкова школа':'A graduate of an Ukrainian school of the current year'}

students_status['status'] = students_status['eotypename']
for type, status in right_status.items():
    students_status.loc[students_status.eotypename==type, 'status'] = status

In [ ]:
students_status[(students_status.regtypename == 'A student of a higher/vocational pre-higher education institution')&(students_status.eotypename.isin(['заклад фахової передвищої освіти', 'заклад фахової передвищої освіти/ліцей']))].status.unique()

array(['A graduate of a vocational pre-higher education institution'],
      dtype=object)

In [ ]:
students_status.loc[(students_status.regtypename == 'A student of a higher/vocational pre-higher education institution')&(students_status.eotypename.isin(['заклад фахової передвищої освіти', 'заклад фахової передвищої освіти/ліцей'])), 'status']='A graduate of a vocational pre-higher education institution'

In [ ]:
students_status.loc[(students_status.regtypename == 'A graduate of previous years')&(students_status.status.isna()), 'status']='A graduate of previous years'
students_status.loc[(students_status.regtypename == 'A graduate of a foreign school')&(students_status.status.isna()), 'status']='A graduate of a foreign school'
students_status.loc[(students_status.regtypename == 'A graduate of a vocational pre-higher education institution')&(students_status.status.isna()), 'status']='A graduate of a vocational pre-higher education institution'
students_status.loc[(students_status.regtypename == 'A student of a higher/vocational pre-higher education institution')&(students_status.status.isna()&(students_status.year=='2022')), 'status']='A student of a higher education institution'
students_status.loc[(students_status.regtypename == 'A student of a higher education institution')&(students_status.status.isna()), 'status']='A student of a higher education institution'
students_status.loc[(students_status.year=='2023')&(students_status.status=='A graduate of an Ukrainian school of the current year')&(students_status.EDRPOU_school.isna())&(students_status.KATOTTG_2023.str.startswith('OC')), 'status'] = 'A graduate of a foreign school'
# there were no division in 2016 and 2017 for higher and prehigher
students_status.loc[(students_status.regtypename == 'A student of a higher/vocational pre-higher education institution')&(students_status.status.isna())&(students_status.year.isin(['2016', '2017'])), 'status']='A student of a higher/vocational pre-higher education institution'
students_status.loc[(students_status.regtypename == 'A graduate of an Ukrainian school of the current year')&(students_status.status.isna()), 'status']='A graduate of an Ukrainian school of the current year'

students_status.loc[(students_status.status == 'A graduate of a vocational pre-higher education institution')&(students_status.year.isin(['2016', '2017'])), 'status']='A student of a higher/vocational pre-higher education institution'

In [ ]:
students_status[(students_status.year =='2022')&(students_status.regtypename=='A student of a higher/vocational pre-higher education institution')].eotypename.unique()

array(['заклад фахової передвищої освіти', 'заклад вищої освіти',
       'заклад фахової передвищої освіти/ліцей', nan], dtype=object)

In [ ]:
students_status[students_status.status.isna()][['regtypename', 'year']].value_counts()

Series([], Name: count, dtype: int64)

In [ ]:
students_status[(students_status.year=='2023')&(students_status.status=='A graduate of an Ukrainian school of the current year')&(students_status.EDRPOU_school.isna())]

,outid,birth,sextypename,classprofilename,regtypename,classlangname,KATOTTG_2023,EDRPOU_school,year,eotypename,status
2436013,98edc1aa-0764-427f-98b7-4ddb16888c30,2006,Male,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA05120170010081140,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2437952,98ffa4b3-9ad3-4eb6-9209-33836de39a62,2006,Female,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA51100270010320268,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2438177,98f45cba-5942-4705-b5e1-376518eeef9a,2004,Male,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA80000000001078669,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2438817,98da4916-419b-4583-88a9-15e0fcda2263,2006,Female,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA12020010010512802,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2439009,9962c1ce-fe9d-4419-b335-530d73e963ad,2005,Female,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA46060250010457177,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2439352,990a4ff7-d5b8-4176-9b9a-0966af609cce,2006,Female,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA80000000000336424,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2439717,98d820ce-e277-466b-b7e0-e4da6ad478d5,2006,Male,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA63120270010216514,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2440600,98ebe2b5-2a2b-4c92-bfbf-b7c442f02969,2005,Female,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA63140030550055665,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2444211,991431c3-2343-4add-a1ec-1675204e2ed7,2005,Female,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA46060250010457177,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2444312,98da4c73-4ce9-43e3-b65d-f298e6828ebf,2003,Female,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA26060130010099427,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2444461,98d78ac9-36ac-4e3b-b285-24ab138b5819,2004,Female,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA46020030010069501,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2445208,98f030eb-1926-4d51-9f24-ca10d2f11f5d,2001,Female,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA80000000000210193,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2446249,99570b87-397d-42de-a455-5c04f2e8e7ea,2004,Female,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA46020030010069501,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2447114,9914cd37-8912-41e1-b809-b214eb26837d,2006,Female,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA48080130010068596,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2447986,995a460c-7270-4ec6-97a0-7ddffe0f67c0,2005,Female,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA80000000000719633,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2450479,9902be0c-76cf-4f4f-961e-51e08660dcf1,2006,Female,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA61060430010047348,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2452045,991048e8-d28d-49ca-a977-c217702148c5,2005,Female,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA21100230010016545,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2452064,9901fd9b-b914-42b3-966e-f38ea232412c,2006,Male,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA68040210010032567,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2452874,9960290e-2e61-4efa-80ff-85080fff358e,2004,Female,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA59080270010287243,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2453917,99107d1b-abb3-4edc-bcdf-d3127e120880,2004,Female,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA46060250010457177,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2454355,98df8c89-8cfa-47d2-b885-842423148893,2004,Female,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA63120270010948820,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2454869,98d843ce-2ef0-4830-93c2-afb6102fa735,2004,Female,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA80000000000551439,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2455325,99100232-ae10-4a33-ae0f-f6fdb842104b,2006,Male,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA51080030010072039,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2455509,9958f3e9-a8ca-439a-a4b8-3e5870bdc991,2005,Female,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA51100270010320268,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2457330,98f87cf4-4760-48e5-aa2a-782f68d8e1c6,2006,Male,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA12100070010038698,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2459204,991385ba-d644-4eea-9808-8fd2f584058c,2006,Male,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA32060050010081797,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2459778,98f3ef24-2ab4-46bf-8748-a850474bc384,2006,Female,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA80000000000126643,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2460079,99564457-050f-4e39-9402-04f96cc10417,2006,Male,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA35040210010286392,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2461551,99083912-d1da-411e-a9f4-b9889b5f67f9,2002,Female,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA32020010010081183,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2462041,99635167-3b89-405c-b724-a78756bf092e,2004,Female,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA80000000001078669,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2462093,99062778-07cc-4951-bd22-749858e24ca9,2004,Female,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA32080070010087821,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2462225,98d7d6ec-2eeb-4d77-91f0-bbdec0e1904d,2005,Female,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA32140030010045925,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2462407,98d982eb-1ade-44ab-ba1c-ce7234290d23,2006,Male,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA07080170010083384,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2463615,99144f27-c2d9-4086-99fd-154972190443,2006,Male,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA74020030010065172,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2464064,98fa7e81-b9c8-4ff6-81c6-f6f87848d421,2005,Female,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA46060250010457177,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2466139,990193fd-64e3-44b6-bfb0-d8c338c6d342,2002,Male,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA63120270010315719,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2466665,98e45a1b-6e0e-475a-aa49-20b992a972d4,2006,Female,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA80000000001078669,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2466730,9910015d-1e36-4a96-a208-6357c59ee021,2004,Female,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA46040010010077682,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2467044,98db4719-08a6-43dd-b14c-d4e36cb07942,2005,Female,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA12020010010639502,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2467650,99100150-82ee-4691-8819-ec35c096dca5,2004,Female,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA46040010010077682,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2468364,991177b7-01b7-4b2f-9184-85108a4614d2,2006,Female,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA51100270010320268,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2468621,98dc350e-0db0-4f2d-8aff-e4ba3665650a,2006,Female,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA63120270010216514,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2469060,98fdad8e-9e23-42df-bf60-5da84e0cc92f,2005,Female,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA80000000000980793,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2473394,98dd80cc-29c0-463b-9ac5-b3d9d223c079,2003,Female,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA74080130010045104,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2473459,98fc482d-d7b3-46b7-a159-925e36344a6d,2005,Male,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA59100170010017917,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2474152,98e62278-8d0e-407d-a703-44afcb1068fb,2005,Male,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA63140170010036104,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2478050,9901fe5d-cb81-471f-b120-91ff0c0b8d7b,2004,Female,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA53020110010112104,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2479468,98de3b2c-9978-453b-b7f9-a1fc84c9f292,2005,Female,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA80000000000624772,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2480579,990482e5-6f94-4d98-8f9f-ccf709d05f03,2006,Female,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA61040490010069060,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2480925,990657c6-988b-4669-8442-5feb1fa27830,2006,Male,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA80000000001078669,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2486661,98faa86a-6afa-4407-bd23-2ddb9a8e0f06,2006,Female,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA63120270010565081,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2488307,98e92844-3b94-46ac-ad16-7bba08e9a07f,2006,Female,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA12060170010378670,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2489484,98e989a2-c50e-4c12-87c6-dd32d451764d,2006,Male,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA51060030010048411,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...
2489848,990fe792-e53f-414a-99e3-4d5a7ed837c2,2005,Male,NaN,A graduate of an Ukrainian school of the curre...,NaN,UA80000000000875983,NaN,2023,NaN,A graduate of an Ukrainian school of the curre...

In [ ]:
students_status[students_status['regtypename'] != students_status['status']]

,outid,birth,sextypename,classprofilename,regtypename,classlangname,KATOTTG_2023,EDRPOU_school,year,status
34139,11d80970-bc9c-490a-bf21-20774a68bb06,1993,Male,NaN,The institution of punishment,NaN,UA35040210010286392,34548369,2016,A graduate of an Ukrainian school of the curre...
37541,2419c6cb-0f7a-48fc-b8b1-0152ec48638b,1989,Male,NaN,A graduate of previous years,NaN,UA56060470010041018,08564400,2016,The institution of punishment
48058,6a7f9f62-fc39-4aeb-95fe-885abb97e49e,1982,Male,NaN,The institution of punishment,NaN,UA35040210010286392,34548369,2016,A graduate of an Ukrainian school of the curre...
73983,3977dd25-51f7-4d49-a98c-f4633796a932,1999,Male,NaN,A graduate of a foreign school,NaN,UA51100270010076757,35265180,2016,A graduate of an Ukrainian school of the curre...
75654,3ef90708-344a-4399-9512-b178d98b35be,1998,Male,NaN,A graduate of a foreign school,NaN,UA51100270010076757,35265180,2016,A graduate of an Ukrainian school of the curre...
...,...,...,...,...,...,...,...,...,...,...
2482576,98f2ad4a-9f93-4471-8083-790582828dbf,2006,Female,NaN,A graduate of an Ukrainian school of the curre...,NaN,OC03030000000000000,NaN,2023,A graduate of a foreign school
2484821,98ea6c9a-ca7c-4f8e-973d-66a5c8f87fc1,2004,Female,NaN,A graduate of an Ukrainian school of the curre...,NaN,OC03020000000000000,NaN,2023,A graduate of a foreign school
2485724,98e185b2-a555-46a2-92ea-574a28ff1a35,2004,Male,NaN,A graduate of an Ukrainian school of the curre...,NaN,OC24010000000000000,NaN,2023,A graduate of a foreign school
2487889,9910c2c3-424e-4021-9e19-570f223829f4,2005,Female,NaN,A graduate of an Ukrainian school of the curre...,NaN,OC13030000000000000,NaN,2023,A graduate of a foreign school
2488639,99119c25-7141-4e4f-9a2c-04e18fbf4f23,2003,Female,NaN,A graduate of an Ukrainian school of the curre...,NaN,OC21020000000000000,NaN,2023,A graduate of a foreign school

In [ ]:
students_status.groupby(by=['year','status']).count()

                                                          outid   birth  \
year status
2016 A graduate of a foreign school                          59      59
     A graduate of an Ukrainian school of the curren...  200736  200736
     A graduate of previous years                         48505   48505
     A student of a higher/vocational pre-higher edu...   18325   18325
     The institution of punishment                          377     377
2017 A graduate of a foreign school                          62      62
     A graduate of an Ukrainian school of the curren...  192772  192772
     A graduate of previous years                         34424   34424
     A student of a higher/vocational pre-higher edu...   13631   13631
2018 A graduate of a foreign school                          32      32
     A graduate of a vocational pre-higher education...  119466  119466
     A graduate of an Ukrainian school of the curren...  185342  185342
     A graduate of previous years                         29307   29307
     A student of a higher education institution           1540    1540
2019 A graduate of a foreign school                          33      33
     A graduate of a vocational pre-higher education...  132448  132448
     A graduate of an Ukrainian school of the curren...  187632  187632
     A graduate of previous years                         33103   33103
     A student of a higher education institution            597     597
2020 A graduate of a foreign school                          45      45
     A graduate of a vocational pre-higher education...  125465  125465
     A graduate of an Ukrainian school of the curren...  211157  211157
     A graduate of previous years                         42419   42419
     A student of a higher education institution            213     213
2021 A graduate of a foreign school                          36      36
     A graduate of a vocational pre-higher education...  118373  118373
     A graduate of an Ukrainian school of the curren...  219608  219608
     A graduate of previous years                         51009   51009
     A student of a higher education institution            297     297
2022 A graduate of a foreign school                          89      89
     A graduate of a vocational pre-higher education...   30521   30521
     A graduate of an Ukrainian school of the curren...  166238  166238
     A graduate of previous years                         36129   36129
     A student of a higher education institution           1101    1101
     The institution of punishment                           26      26
2023 A graduate of a foreign school                          70      70
     A graduate of a vocational pre-higher education...   53756   53756
     A graduate of an Ukrainian school of the curren...  180744  180744
     A graduate of previous years                         54331   54331
     The institution of punishment                           34      34

                                                         sextypename  \
year status
2016 A graduate of a foreign school                               59
     A graduate of an Ukrainian school of the curren...       200736
     A graduate of previous years                              48505
     A student of a higher/vocational pre-higher edu...        18325
     The institution of punishment                               377
2017 A graduate of a foreign school                               62
     A graduate of an Ukrainian school of the curren...       192772
     A graduate of previous years                              34424
     A student of a higher/vocational pre-higher edu...        13631
2018 A graduate of a foreign school                               32
     A graduate of a vocational pre-higher education...       119466
     A graduate of an Ukrainian school of the curren...       185342
     A graduate of previous years                              29307
     A student of a higher education institution                1540
2019 A graduate of a foreign school                               33
     A graduate of a vocational pre-higher education...       132448
     A graduate of an Ukrainian school of the curren...       187632
     A graduate of previous years                              33103
     A student of a higher education institution                 597
2020 A graduate of a foreign school                               45
     A graduate of a vocational pre-higher education...       125465
     A graduate of an Ukrainian school of the curren...       211157
     A graduate of previous years                              42419
     A student of a higher education institution                 213
2021 A graduate of a foreign school                               36
     A graduate of a vocational pre-higher education...       118373
     A graduate of an Ukrainian school of the curren...       219608
     A graduate of previous years                              51009
     A student of a higher education institution                 297
2022 A graduate of a foreign school                               89
     A graduate of a vocational pre-higher education...        30521
     A graduate of an Ukrainian school of the curren...       166238
     A graduate of previous years                              36129
     A student of a higher education institution                1101
     The institution of punishment                                26
2023 A graduate of a foreign school                               70
     A graduate of a vocational pre-higher education...        53756
     A graduate of an Ukrainian school of the curren...       180744
     A graduate of previous years                              54331
     The institution of punishment                                34

                                                         classprofilename  \
year status
2016 A graduate of a foreign school                                     0
     A graduate of an Ukrainian school of the curren...                 0
     A graduate of previous years                                       0
     A student of a higher/vocational pre-higher edu...                 0
     The institution of punishment                                      0
2017 A graduate of a foreign school                                     0
     A graduate of an Ukrainian school of the curren...            192772
     A graduate of previous years                                       0
     A student of a higher/vocational pre-higher edu...                13
2018 A graduate of a foreign school                                     0
     A graduate of a vocational pre-higher education...                31
     A graduate of an Ukrainian school of the curren...            185342
     A graduate of previous years                                       0
     A student of a higher education institution                        0
2019 A graduate of a foreign school                                     0
     A graduate of a vocational pre-higher education...            132056
     A graduate of an Ukrainian school of the curren...            187632
     A graduate of previous years                                       0
     A student of a higher education institution                        0
2020 A graduate of a foreign school                                     0
     A graduate of a vocational pre-higher education...            125326
     A graduate of an Ukrainian school of the curren...            211157
     A graduate of previous years                                       0
     A student of a higher education institution                        0
2021 A graduate of a foreign school                                     0
     A graduate of a vocational pre-higher education...            118133
     A graduate of an Ukrainian school of the curren...            219608
     A graduate of previous years                                       0
     A student of a higher education institution                        0
2022 A graduate of a foreign school                                     0
     A graduate of a vocational pre-higher education...                 0
     A graduate of an Ukrainian school of the curren...                 0
     A graduate of previous years                                       0
     A student of a higher education institution                        0
     The institution of punishment                                      0
2023 A graduate of a foreign school                                     0
     A graduate of a vocational pre-higher education...                 0
     A graduate of an Ukrainian school of the curren...                 0
     A graduate of previous years                                       0
     The institution of punishment                                      0

                                                         regtypename  \
year status
2016 A graduate of a foreign school                               59
     A graduate of an Ukrainian school of the curren...       200736
     A graduate of previous years                              48505
     A student of a higher/vocational pre-higher edu...        18325
     The institution of punishment                               377
2017 A graduate of a foreign school                               62
     A graduate of an Ukrainian school of the curren...       192772
     A graduate of previous years                              34424
     A student of a higher/vocational pre-higher edu...        13631
2018 A graduate of a foreign school                               32
     A graduate of a vocational pre-higher education...       119466
     A graduate of an Ukrainian school of the curren...       185342
     A graduate of previous years                              29307
     A student of a higher education institution                1540
2019 A graduate of a foreign school                               33
     A graduate of a vocational pre-higher education...       132448
     A graduate of an Ukrainian school of the curren...       187632
     A graduate of previous years                              33103
     A student of a higher education institution                 597
2020 A graduate of a foreign school                               45
     A graduate of a vocational pre-higher education...       125465
     A graduate of an Ukrainian school of the curren...       211157
     A graduate of previous years                              42419
     A student of a higher education institution                 213
2021 A graduate of a foreign school                               36
     A graduate of a vocational pre-higher education...       118373
     A graduate of an Ukrainian school of the curren...       219608
     A graduate of previous years                              51009
     A student of a higher education institution                 297
2022 A graduate of a foreign school                               89
     A graduate of a vocational pre-higher education...        30521
     A graduate of an Ukrainian school of the curren...       166238
     A graduate of previous years                              36129
     A student of a higher education institution                1101
     The institution of punishment                                26
2023 A graduate of a foreign school                               70
     A graduate of a vocational pre-higher education...        53756
     A graduate of an Ukrainian school of the curren...       180744
     A graduate of previous years                              54331
     The institution of punishment                                34

                                                         classlangname  \
year status
2016 A graduate of a foreign school                                  0
     A graduate of an Ukrainian school of the curren...              0
     A graduate of previous years                                    0
     A student of a higher/vocational pre-higher edu...              0
     The institution of punishment                                   0
2017 A graduate of a foreign school                                  0
     A graduate of an Ukrainian school of the curren...         192772
     A graduate of previous years                                    0
     A student of a higher/vocational pre-higher edu...             13
2018 A graduate of a foreign school                                  0
     A graduate of a vocational pre-higher education...             31
     A graduate of an Ukrainian school of the curren...         185342
     A graduate of previous years                                    0
     A student of a higher education institution                     0
2019 A graduate of a foreign school                                  0
     A graduate of a vocational pre-higher education...         132056
     A graduate of an Ukrainian school of the curren...         187632
     A graduate of previous years                                    0
     A student of a higher education institution                     0
2020 A graduate of a foreign school                                  0
     A graduate of a vocational pre-higher education...         125326
     A graduate of an Ukrainian school of the curren...         211157
     A graduate of previous years                                    0
     A student of a higher education institution                     0
2021 A graduate of a foreign school                                  0
     A graduate of a vocational pre-higher education...         118133
     A graduate of an Ukrainian school of the curren...         219608
     A graduate of previous years                                    0
     A student of a higher education institution                     0
2022 A graduate of a foreign school                                  0
     A graduate of a vocational pre-higher education...              0
     A graduate of an Ukrainian school of the curren...              0
     A graduate of previous years                                    0
     A student of a higher education institution                     0
     The institution of punishment                                   0
2023 A graduate of a foreign school                                  0
     A graduate of a vocational pre-higher education...              0
     A graduate of an Ukrainian school of the curren...              0
     A graduate of previous years                                    0
     The institution of punishment                                   0

                                                         KATOTTG_2023  \
year status
2016 A graduate of a foreign school                                59
     A graduate of an Ukrainian school of the curren...        200736
     A graduate of previous years                               48505
     A student of a higher/vocational pre-higher edu...         18325
     The institution of punishment                                377
2017 A graduate of a foreign school                                62
     A graduate of an Ukrainian school of the curren...        192772
     A graduate of previous years                               34424
     A student of a higher/vocational pre-higher edu...         13631
2018 A graduate of a foreign school                                32
     A graduate of a vocational pre-higher education...        119466
     A graduate of an Ukrainian school of the curren...        185342
     A graduate of previous years                               29307
     A student of a higher education institution                 1540
2019 A graduate of a foreign school                                33
     A graduate of a vocational pre-higher education...        132448
     A graduate of an Ukrainian school of the curren...        187632
     A graduate of previous years                               33103
     A student of a higher education institution                  597
2020 A graduate of a foreign school                                45
     A graduate of a vocational pre-higher education...        125465
     A graduate of an Ukrainian school of the curren...        211157
     A graduate of previous years                               42419
     A student of a higher education institution                  213
2021 A graduate of a foreign school                                36
     A graduate of a vocational pre-higher education...        118373
     A graduate of an Ukrainian school of the curren...        219608
     A graduate of previous years                               51009
     A student of a higher education institution                  297
2022 A graduate of a foreign school                                89
     A graduate of a vocational pre-higher education...         30521
     A graduate of an Ukrainian school of the curren...        166238
     A graduate of previous years                               36129
     A student of a higher education institution                 1101
     The institution of punishment                                 26
2023 A graduate of a foreign school                                70
     A graduate of a vocational pre-higher education...         53756
     A graduate of an Ukrainian school of the curren...        180744
     A graduate of previous years                               54331
     The institution of punishment                                 34

                                                         EDRPOU_school  \
year status
2016 A graduate of a foreign school                                  0
     A graduate of an Ukrainian school of the curren...         200736
     A graduate of previous years                                    0
     A student of a higher/vocational pre-higher edu...              1
     The institution of punishment                                 377
2017 A graduate of a foreign school                                  0
     A graduate of an Ukrainian school of the curren...         192772
     A graduate of previous years                                    0
     A student of a higher/vocational pre-higher edu...             13
2018 A graduate of a foreign school                                  0
     A graduate of a vocational pre-higher education...         118238
     A graduate of an Ukrainian school of the curren...         185342
     A graduate of previous years                                    0
     A student of a higher education institution                     0
2019 A graduate of a foreign school                                  0
     A graduate of a vocational pre-higher education...         132056
     A graduate of an Ukrainian school of the curren...         187632
     A graduate of previous years                                    0
     A student of a higher education institution                     0
2020 A graduate of a foreign school                                  0
     A graduate of a vocational pre-higher education...         125326
     A graduate of an Ukrainian school of the curren...         211157
     A graduate of previous years                                    0
     A student of a higher education institution                     0
2021 A graduate of a foreign school                                  0
     A graduate of a vocational pre-higher education...         118133
     A graduate of an Ukrainian school of the curren...         219608
     A graduate of previous years                                    0
     A student of a higher education institution                     0
2022 A graduate of a foreign school                                  0
     A graduate of a vocational pre-higher education...          30168
     A graduate of an Ukrainian school of the curren...         166238
     A graduate of previous years                                    0

In [ ]:
students_status.drop(columns=['eotypename'], inplace=True)

In [ ]:
# save dataframe
students_status.to_csv("./final_tables/students.csv", index=False)