In [1]:
import numpy as np
import pandas as pd

In [5]:
# load datasets
datasets = {}
for year in range(2016, 2026):
    print(f"EIE {year} Loading...")
    if int(year) >= 2019:
        file_name = f'Odata{year}File.csv'
    else:
        file_name = f'OpenData{year}.csv'
    try:           
        dataset = pd.read_csv(f"../../data_loader/{year}/{file_name}", sep=";", encoding='utf-8', dtype = str)
    except UnicodeDecodeError :
        dataset = pd.read_csv(f"../../data_loader/{year}/{file_name}", sep=";", encoding='Windows 1251', dtype = str)
    datasets.update({year: dataset})
    print("success")

EIE 2016 Loading...
success
EIE 2017 Loading...
success
EIE 2018 Loading...
success
EIE 2019 Loading...
success
EIE 2020 Loading...
success
EIE 2021 Loading...
success
EIE 2022 Loading...
success
EIE 2023 Loading...
success
EIE 2024 Loading...
success
EIE 2025 Loading...
success

In [6]:
for year, dataset in datasets.items():
    #lowercase all columns and add year as attribute
    dataset.columns = [col.lower() for col in dataset.columns]

# EIE

In [7]:
nmt_start_year = 2022 # all years before that had EIE
eie_subjects = set()
for year, dataset in datasets.items():
    subjects = [col for col in dataset.columns if col.endswith('test')]
    if year < nmt_start_year:
        eie_subjects.update(subjects)
    print(year, subjects)

2016 ['ukrtest', 'histtest', 'mathtest', 'phystest', 'chemtest', 'biotest', 'geotest', 'engtest', 'frtest', 'deutest', 'sptest', 'rustest']
2017 ['ukrtest', 'histtest', 'mathtest', 'phystest', 'chemtest', 'biotest', 'geotest', 'engtest', 'fratest', 'deutest', 'spatest', 'rustest']
2018 ['ukrtest', 'histtest', 'mathtest', 'phystest', 'chemtest', 'biotest', 'geotest', 'engtest', 'fratest', 'deutest', 'spatest']
2019 ['ukrtest', 'histtest', 'mathtest', 'phystest', 'chemtest', 'biotest', 'geotest', 'engtest', 'fratest', 'deutest', 'spatest']
2020 ['ukrtest', 'histtest', 'mathtest', 'phystest', 'chemtest', 'biotest', 'geotest', 'engtest', 'fratest', 'deutest', 'spatest']
2021 ['umltest', 'ukrtest', 'ukrsubtest', 'histtest', 'mathtest', 'mathsttest', 'phystest', 'chemtest', 'biotest', 'geotest', 'engtest', 'fratest', 'deutest', 'spatest']
2022 ['test']
2023 ['test']
2024 ['test']
2025 ['test']

In [8]:
eie_subjects

{'biotest',
 'chemtest',
 'deutest',
 'engtest',
 'fratest',
 'frtest',
 'geotest',
 'histtest',
 'mathsttest',
 'mathtest',
 'phystest',
 'rustest',
 'spatest',
 'sptest',
 'ukrsubtest',
 'ukrtest',
 'umltest'}

In [9]:
eie_subjects.remove('frtest')
eie_subjects.remove('sptest')
eie_subjects

{'biotest',
 'chemtest',
 'deutest',
 'engtest',
 'fratest',
 'geotest',
 'histtest',
 'mathsttest',
 'mathtest',
 'phystest',
 'rustest',
 'spatest',
 'ukrsubtest',
 'ukrtest',
 'umltest'}

In [10]:
eie_df = pd.DataFrame(data={"test_type": ["EIE"] * len(eie_subjects), "test_subject": list(eie_subjects)})
eie_df

   test_type test_subject
0        EIE     chemtest
1        EIE      deutest
2        EIE      biotest
3        EIE      rustest
4        EIE      fratest
5        EIE     phystest
6        EIE      spatest
7        EIE      geotest
8        EIE      engtest
9        EIE   mathsttest
10       EIE     histtest
11       EIE     mathtest
12       EIE      ukrtest
13       EIE      umltest
14       EIE   ukrsubtest

# NMT

In [25]:
for year in range(2022, 2026):
    print('test', year, datasets[year]['test'].unique())
    print(*[(col, datasets[year][col].unique()) for col in datasets[year].columns if 'block' in col and 'ball' not in col  and 'status' not in col and 'lang' not in col])
    # print('ukrtest', 2022, datasets[2022]['block1'].unique(), 2023, datasets[2023]['ukrblock'].unique())
    # print('histtest', 2022, datasets[2022]['block2'].unique(), 2023, datasets[2023]['histblock'].unique())
    # print('mathtest', 2022, datasets[2022]['block3'].unique(), 2023, datasets[2023]['mathblock'].unique())

test 2022 ['НМТ ']
('block1', array(['Українська мова'], dtype=object)) ('block2', array(['Історія України'], dtype=object)) ('block3', array(['Математика'], dtype=object))
test 2023 ['НМТ']
('ukrblock', array(['Українська мова'], dtype=object)) ('histblock', array([nan, 'Історія України'], dtype=object)) ('mathblock', array(['Математика'], dtype=object)) ('physblock', array([nan, 'Фізика'], dtype=object)) ('chemblock', array([nan, 'Хімія'], dtype=object)) ('bioblock', array([nan, 'Біологія'], dtype=object)) ('engblock', array(['Англійська мова', nan], dtype=object)) ('frablock', array([nan, 'Французька мова'], dtype=object)) ('deublock', array([nan, 'Німецька мова'], dtype=object)) ('spablock', array([nan, 'Іспанська мова'], dtype=object))
test 2024 ['НМТ']
('ukrblock', array(['Українська мова'], dtype=object)) ('histblock', array(['Історія України'], dtype=object)) ('mathblock', array(['Математика'], dtype=object)) ('physblock', array([nan, 'Фізика'], dtype=object)) ('chemblock', array([nan, 'Хімія'], dtype=object)) ('bioblock', array(['Біологія', nan], dtype=object)) ('geoblock', array([nan, 'Географія'], dtype=object)) ('engblock', array([nan, 'Англійська мова'], dtype=object)) ('frablock', array([nan, 'Французька мова'], dtype=object)) ('deublock', array([nan, 'Німецька мова'], dtype=object)) ('spablock', array([nan, 'Іспанська мова'], dtype=object)) ('ukrlitblock', array([nan, 'Українська література'], dtype=object))
test 2025 ['НМТ']
('ukrblock', array(['Українська мова'], dtype=object)) ('histblock', array(['Історія України'], dtype=object)) ('mathblock', array(['Математика'], dtype=object)) ('physblock', array([nan, 'Фізика'], dtype=object)) ('chemblock', array([nan, 'Хімія'], dtype=object)) ('bioblock', array([nan, 'Біологія'], dtype=object)) ('geoblock', array(['Географія', nan], dtype=object)) ('engblock', array([nan, 'Англійська мова'], dtype=object)) ('frablock', array([nan, 'Французька мова'], dtype=object)) ('deublock', array([nan, 'Німецька мова'], dtype=object)) ('spablock', array([nan, 'Іспанська мова'], dtype=object)) ('ukrlitblock', array([nan, 'Українська література'], dtype=object))

In [27]:
subjects = {col for col in datasets[year].columns if col.endswith('block') for year in range(2023, 2026)}
print(sorted(subjects))

['bioblock', 'chemblock', 'deublock', 'engblock', 'frablock', 'geoblock', 'histblock', 'mathblock', 'physblock', 'spablock', 'ukrblock', 'ukrlitblock']

In [28]:
nmt_subjects = [col.replace('block', 'test') for col in subjects]
nmt_subjects

['engtest',
 'fratest',
 'ukrlittest',
 'spatest',
 'geotest',
 'histtest',
 'biotest',
 'deutest',
 'chemtest',
 'ukrtest',
 'mathtest',
 'phystest']

In [29]:
nmt_df = pd.DataFrame(data={"test_type": ["NMT"] * len(nmt_subjects), "test_subject": nmt_subjects})
nmt_df

   test_type test_subject
0        NMT      engtest
1        NMT      fratest
2        NMT   ukrlittest
3        NMT      spatest
4        NMT      geotest
5        NMT     histtest
6        NMT      biotest
7        NMT      deutest
8        NMT     chemtest
9        NMT      ukrtest
10       NMT     mathtest
11       NMT     phystest

In [30]:
subjects_df = pd.concat([eie_df,nmt_df], ignore_index=True)
subjects_df

   test_type test_subject
0        EIE     chemtest
1        EIE      deutest
2        EIE      biotest
3        EIE      rustest
4        EIE      fratest
5        EIE     phystest
6        EIE      spatest
7        EIE      geotest
8        EIE      engtest
9        EIE   mathsttest
10       EIE     histtest
11       EIE     mathtest
12       EIE      ukrtest
13       EIE      umltest
14       EIE   ukrsubtest
15       NMT      engtest
16       NMT      fratest
17       NMT   ukrlittest
18       NMT      spatest
19       NMT      geotest
20       NMT     histtest
21       NMT      biotest
22       NMT      deutest
23       NMT     chemtest
24       NMT      ukrtest
25       NMT     mathtest
26       NMT     phystest

In [31]:
subjects_df.to_csv("./final_tables/subjects.csv", index=False)